(() =>{
   let db = {
      "PVE Update": `Последнее обновление: 28/06/2024`,
      "PVP Update": `Последнее обновление: 27/06/2024`,
      // PVE Skill 01
      "PVE Skill 01": {
         "name": 'Malefic',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1c53f900e5226e09621196190c506da91d3703bb.png',
         "job_icon": 'AST',
         "level": '1',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 150.',
      },
      // PVE Skill 02
      "PVE Skill 02": {
         "name": 'Benefic',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ec1096796458eca5c96eea7720465aa642bd73e1.png',
         "job_icon": 'AST',
         "level": '2',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Восстанавливает HP цели.<br/>Сила лечения: 500<br/>Дополнительный эффект: 15% шанс, что следующий Benefic II будет иметь критический эффект при исцелении<br/>Продолжительность: 15 сек.',
      },
      // PVE Skill 03
      "PVE Skill 03": {
         "name": 'Combust',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7e161244d4e8b8909f2b0804f096fdec8228ef4d.png',
         "job_icon": 'AST',
         "level": '4',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Периодический нестихийный урон.<br/>Сила атаки: 50<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 04
      "PVE Skill 04": {
         "name": 'Lightspeed',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/8e5b0f4ba2437c7ed0dba22471388c128372c767.png',
         "job_icon": 'AST',
         "level": '6',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '90 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Снижает время применения заклинаний на 2.5 секунды.<br/>Продолжительность: 15 сек.',
      },
      // PVE Skill 05
      "PVE Skill 05": {
         "name": 'Helios',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/78affa4069a26e38833b6dc5826c2e3abf05917d.png',
         "job_icon": 'AST',
         "level": '10',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '700 MP',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '15y',
         "content": 'Восстанавливает HP персонажа и всех ближайших сопартийцев.<br/>Сила лечения: 400',
      },
      // PVE Skill 06
      "PVE Skill 06": {
         "name": 'Ascend',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/89ac1eda0deb042fbdb3618d88511262a4d0f5c5.png',
         "job_icon": 'AST',
         "level": '12',
         "classification": 'Заклинание',
         "cast": '8 сек.',
         "recast": '2.5 сек.',
         "cost": '2400 MP',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Воскрешает цель, накладывая эффект слабости (weakeness).',
      },
      // PVE Skill 07
      "PVE Skill 07": {
         "name": 'Essential Dignity',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/6e6f7c02d300a61d010d596d0e2fe80a12f8e03b.png',
         "job_icon": 'AST',
         "level": '15',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '40 сек.',
         "cost": '-',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Восстанавливает HP цели.<br/>Сила лечения: 400<br/>Сила лечения увеличивается до 900 по мере уменьшения HP цели и достигает максимального значения, когда у цели остается 30% HP или меньше.<br/>Максимум зарядов: 3',
      },
      // PVE Skill 08
      "PVE Skill 08": {
         "name": 'Benefic II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/eeb9a90c14711ee0450ce0c96d4b6b00f73f733e.png',
         "job_icon": 'AST',
         "level": '26',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '700 MP',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Восстанавливает HP цели.<br/>Сила лечения: 800',
      },
      // PVE Skill 09 NEW
      "PVE Skill 09": {
         "name": 'Astral Draw',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ca9495b5dd2708d088f8180b433b812580622dcb.png',
         "job_icon": 'AST',
         "level": '30',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Вытягивает из гадальной колоды персонажа карты the Balance, the Arrow, the Spire и the Lord of Crowns.<br/>Дополнительный эффект: восстанавливает 20% MP персонажа<br/>При использовании, Play I меняется на меняется на The Balance, Play II меняется на The Arrow, Play III меняется на The Spire, Minor Arcana меняется на Lord of Crowns и Astral Draw меняется на Umbral Draw.<br/>Имеет общее время восстановления с умением Umbral Draw.',
      },
      // PVE Skill 10 NEW
      "PVE Skill 10": {
         "name": 'Umbral Draw',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/3a5badd54650309c03a120ea6906ad51276e8c6e.png',
         "job_icon": 'AST',
         "level": '30',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Вытягивает из гадальной колоды персонажа карты the Spear, the Bole, the Ewer и the Lady of Crowns.<br/>Дополнительный эффект: восстанавливает 20% MP персонажа<br/>При использовании Play I меняется на The Spear, Play II меняется на The Bole, Play III меняется на The Ewer, Minor Arcana меняется на Lady of Crowns и Umbral Draw меняется на Astral Draw.<br/>Имеет общее время восстановления с умением Astral Draw.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Astral Draw меняется на Umbral Draw при соблюдении требований к выполнению.',
      },
      // PVE Skill 11 NEW
      "PVE Skill 11": {
         "name": 'Play I',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/aa32f90984104b56be403963081f119244df50a8.png',
         "job_icon": 'AST',
         "level": '30',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Разыгрывает нарисованный арканум (arcanum) после использования Astral Draw или Umbral Draw.<br/>Эффект Astral Draw: Умение меняется на The Balance.<br/>Эффект Umbral Draw: Умение меняется на The Spear.',
      },
      // PVE Skill 12 NEW
      "PVE Skill 12": {
         "name": 'Play II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1d7b124a1b665b5be6db3759a2f5060eef40b89d.png',
         "job_icon": 'AST',
         "level": '30',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Разыгрывает нарисованный арканум (arcanum) после использования Astral Draw или Umbral Draw.<br/>Эффект Astral Draw: Умение меняется на The Arrow.<br/>Эффект Umbral Draw: Умение меняется на The Bole.',
      },
      // PVE Skill 13 NEW
      "PVE Skill 13": {
         "name": 'Play III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/59c09c6f090fb75d16bb4f906793b951fd58b4cf.png',
         "job_icon": 'AST',
         "level": '30',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Разыгрывает нарисованный арканум (arcanum) после использования Astral Draw или Umbral Draw.<br/>Эффект Astral Draw: Умение меняется на The Spire.<br/>Эффект Umbral Draw: Умение меняется на The Ewer.',
      },
      // PVE Skill 14
      "PVE Skill 14": {
         "name": 'Aspected Benefic',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/9abd9dc20f6f0864806e050841e5ae74172d3d93.png',
         "job_icon": 'AST',
         "level": '34',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Восстанавливает HP цели.<br/>Сила лечения: 250<br/>Дополнительный эффект: эффект периодического лечения (regen)<br/>Сила лечения: 250<br/>Продолжительность: 15 сек.',
      },
      // PVE Skill 15
      "PVE Skill 15": {
         "name": 'Aspected Helios',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ee92429fd70cd18d445735da357c023336da994d.png',
         "job_icon": 'AST',
         "level": '42',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '800 MP',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '15y',
         "content": 'Восстанавливает HP персонажа и всех ближайших сопартийцев.<br/>Сила лечения: 250<br/>Дополнительный эффект: эффект периодического лечения (regen)<br/>Сила лечения: 150<br/>Продолжительность: 15 сек.',
      },
      // PVE Skill 16
      "PVE Skill 16": {
         "name": 'Gravity',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/f625f3a645c/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/42e3c5d1cccb388c35ee3d6907a6e6109ba4b852.png',
         "job_icon": 'AST',
         "level": '45',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 120 по цели и всем окружающим противникам.',
      },
      // PVE Skill 17
      "PVE Skill 17": {
         "name": 'Combust II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/447dd0b8ed8d759beeaa8b8aa7f8f1ec2cbec7b4.png',
         "job_icon": 'AST',
         "level": '46',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Периодический нестихийный урон.<br/>Сила атаки: 60<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 18
      "PVE Skill 18": {
         "name": 'Synastry',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/67a7f1c0d57/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/883284b0f5ce828b73992bdaf990124383c77efd.png',
         "job_icon": 'AST',
         "level": '50',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "cost": '-',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Создает эфирную связь с выбранным сопартийцем. Каждое применение одиночного лечебного заклинания на персонажа или сопартийца восстанавливает 40% HP от оригинального эффекта заклинания связанному сопартийцу.<br/>Продолжительность: 20 сек.',
      },
      // PVE Skill 19
      "PVE Skill 19": {
         "name": 'Divination',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/24e1ea2b4dce9d16ae60f33ab860190a67a3a506.png',
         "job_icon": 'AST',
         "level": '50',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '30y',
         "content": 'Увеличивает урон персонажа и всех ближайших сопартийцев на 6%.<br/>Продолжительность: 15 сек.<br/>Дополнительный эффект: накладывает эффект Divining<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 20
      "PVE Skill 20": {
         "name": 'Malefic II',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/220108abf60/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e9cbc9998cc2491689d203da71716e9cee15c615.png',
         "job_icon": 'AST',
         "level": '54',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 160.',
      },
      // PVE Skill 21
      "PVE Skill 21": {
         "name": 'Collective Unconscious',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/293a143ad09/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/6ffe2bab0c77721314aee02e2f3f14f61351e2a4.png',
         "job_icon": 'AST',
         "level": '58',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '30y',
         "content": 'Создает защитную область вокруг заклинателя.<br/>Продолжительность: 18 сек.<br/>Дополнительный эффект: снижает получаемый урон на 10% персонажем и всеми ближайшими сопартийцам в радиусе 30 ялмов и накладывает Wheel of Fortune на персонажа и на сопартийцев в радиусе 8 ялмов<br/>Продолжительность: 5 сек.<br/>Эффект Wheel of Fortune: эффект периодического лечения (regen)<br/>Сила лечения: 100<br/>Продолжительность: 15 сек.<br/>Эффекты будут непрерывно накладываться на персонажа и всех сопартийцев, находящихся в пределах области. Эффект Collective Unconscious прерывается при использовании любого другого умения, либо при перемещении (включая повороты на месте).<br/>Прерывает авто атаки при использовании умения.',
      },
      // PVE Skill 22
      "PVE Skill 22": {
         "name": 'Celestial Opposition',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/88888ade6e4/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f2ca2bba463ed6f55295fb64f6a497e130b05cf4.png',
         "job_icon": 'AST',
         "level": '60',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '15y',
         "content": 'Восстанавливает HP персонажа и всех ближайших сопартийцев.<br/>Сила лечения: 200<br/>Дополнительный эффект: эффект периодического лечения (regen)<br/>Сила лечения: 100<br/>Продолжительность: 15 сек.',
      },
      // PVE Skill 23
      "PVE Skill 23": {
         "name": 'Earthly Star',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/522e3417c4930cf5834e64c75e763e999dc284c8.png',
         "job_icon": 'AST',
         "level": '62',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "cost": '-',
         "range": '30y',
         "radius_img": 'R2',
         "radius": '20y',
         "content": 'Создает в указанной зоне Earthly Star и накладывает эффект Earthly Dominance.<br/>Продолжительность: 10 сек.<br/>Использование Stellar Detonation, под действием Earthly Dominance, создает Stellar Burst, наносящий нестихийный урон с силой атаки 205 по всем окружающим противникам. Также восстанавливает HP персонажу и всем окружающим сопартийцам.<br/>Сила лечения: 540<br/>Через 10 сек. эффект Earthly Dominance сменяется эффектом Giant Dominance.<br/>Продолжительность: 10 сек.<br/>Ожидание 10 сек. или использование Stellar Detonation, будучи под эффектом Giant Dominance, создает Stellar Explosion наносящий нестихийный урон с силой атаки 310 по всем окружающим противникам. Также восстанавливает HP персонажу и всем окружающим сопартицам.<br/>Сила лечения: 720',
      },
      // PVE Skill 24
      "PVE Skill 24": {
         "name": 'Stellar Detonation',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f69c65b6871458427cf794c2467d50e1ae6b7949.png',
         "job_icon": 'AST',
         "level": '62',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '3 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '20y',
         "content": 'Находясь под действием Earthly Dominance создает на месте Earthly Star звёздную вспышку, наносящую нестихийный урон с силой 100 всем противникам поблизости.<br/>Дополнительный эффект: восстанавливает HP персонажа и всех ближайших сопартийцев<br/>Сила лечения: 540<br/>Находясь под действием Earthly Dominance создает на месте Earthly Star звездный взрыв, наносящий нестихийный урон с силой 150 всем противникам поблизости.<br/>Дополнительный эффект: восстанавливает HP персонажа и всех ближайших сопартийцев<br/>Сила лечения: 720',
      },
      // PVE Skill 25
      "PVE Skill 25": {
         "name": 'Malefic III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4383eddfb0a234ec105f3bdfcc162aa2ff8b37d8.png',
         "job_icon": 'AST',
         "level": '64',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 190.',
      },
      // PVE Skill 26
      "PVE Skill 26": {
         "name": 'Minor Arcana',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5f9cec813674a23520286ff23759e752db5499bd.png',
         "job_icon": 'AST',
         "level": '70',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Разыгрывает нарисованный арканум (arcanum) после использования Astral Draw или Umbral Draw<br/>Эффект Astral Draw: Умение меняется на Lord of Crowns<br/>Эффект Umbral Draw: Умение меняется на Lady of Crowns',
      },
      // PVE Skill 27
      "PVE Skill 27": {
         "name": 'Combust III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/0f73da17cc2ccea0a36787347d34738d6a97673a.png',
         "job_icon": 'AST',
         "level": '72',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Периодический нестихийный урон.<br/>Сила атаки: 70<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 28
      "PVE Skill 28": {
         "name": 'Malefic IV',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/0a063c1dba4b21b9f27440a05d707da109b00d15.png',
         "job_icon": 'AST',
         "level": '72',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 230.',
      },
      // PVE Skill 29
      "PVE Skill 29": {
         "name": 'Celestial Intersection',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2a71645e6880d0bb4b46332fd64cd0756dd3b08f.png',
         "job_icon": 'AST',
         "level": '74',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '30 сек.',
         "cost": '-',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Восстанавливает HP персонажу или выбранному сопартийцу.<br/>Сила лечения: 200<br/>Дополнительный эффект: создает магический барьер, который предотвращает получение урона, равного 200% от количества восстановленных HP<br/>Продолжительность: 30 сек.<br/>Максимум стаков: 2',
      },
      // PVE Skill 30
      "PVE Skill 30": {
         "name": 'Horoscope',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c806bf7d70b7343de2de42f47a2bbaa59e8b324e.png',
         "job_icon": 'AST',
         "level": '76',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '20y',
         "content": 'Предсказывает судьбу для персонажа и всех окружающих сопартийцев, накладывая на них эффект Horoscope.<br/>Продолжительность: 10 сек.<br/>Эффект улучшается до Horoscope Helios после получения эффекта Helios или Helios Conjunction.<br/>Продолжительность: 30 сек.<br/>Восстанавливает HP сопартийцам с данными эффектами при повторном предсказании судьбы или окончании времени действия эффекта.<br/>Сила лечения Horoscope: 200<br/>Сила лечения Horoscope Helios: 400',
      },
      // PVE Skill 31
      "PVE Skill 31": {
         "name": 'Horoscope',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/224ca9088106c40e33179fa3fdfcd742104d1891.png',
         "job_icon": 'AST',
         "level": '76',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '20y',
         "content": 'Восстанавливает HP персонажа и всех окружающих сопартийцев.<br/>Сила лечения определяется эффектом Horoscope на сопартийцах. Эффект спадает после использования.<br/>Сила с Horoscope: 200<br/>Сила с Horoscope Helios: 400',
      },
      // PVE Skill 32
      "PVE Skill 32": {
         "name": 'Neutral Sect',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/8ccf71b513276dce09f58889b5bb8878371b8519.png',
         "job_icon": 'AST',
         "level": '80',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Увеличивает силу магии лечения на 20%.<br/>Продолжительность: 20 сек.<br/>Дополнительный эффект: после использования Aspected Benefic и Helios Conjunction, который предотвращает получение урона<br/>Эффект Aspected Benefic: обнуляет урон, равный 250% от количества восстановленных HP<br/>Эффект Aspected Helios: обнуляет урон, равный 125% от количества восстановленных HP<br/>Продолжительность: 30 сек.<br/>Дополнительный эффект: накладывает эффект Suntouched<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 33
      "PVE Skill 33": {
         "name": 'Fall Malefic',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/6f0ba481b923ff8cea8bc37b5c25f9192e494beb.png',
         "job_icon": 'AST',
         "level": '82',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 270.',
      },
      // PVE Skill 34
      "PVE Skill 34": {
         "name": 'Gravity II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/56748917749affb1f286aba23c3a54cc0e5d0156.png',
         "job_icon": 'AST',
         "level": '82',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 130 по цели и всем окружающим противникам.',
      },
      // PVE Skill 35
      "PVE Skill 35": {
         "name": 'Exaltation',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c4bf5c769353b2ee48cba7af8c64a86f1bb11e7d.png',
         "job_icon": 'AST',
         "level": '86',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "cost": '-',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Снижает урон, наносимый персонажу или выбранному сопартийцу, на 10%.<br/>Продолжительность: 8 сек.<br/>Дополнительный эффект: восстанавливает HP по окончании действия эффекта<br/>Сила лечения: 500',
      },
      // PVE Skill 36
      "PVE Skill 36": {
         "name": 'Macrocosmos',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1d39637c8a2ed0b39fc54cac5eb718eabc29bc53.png',
         "job_icon": 'AST',
         "level": '90',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '180 сек.',
         "cost": '600 MP',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '20y',
         "content": 'Наносит нестихийный урон по цели и всем окружающим противникам с силой атаки 250 для первого и на 40% меньше для остальных.<br/>Дополнительный эффект: накладывает эффект Macrocosmos на персонажа и всех ближайших сопартийцев.<br/>Продолжительность: 15 сек<br/>На время действия эффекта 50% получаемого урона накапливается.<br/>Восстанавливает HP, равное силе лечению 200, прибавляя накопленный урон, когда эффект истекает или при использовании Microcosmos.<br/>Восстановленное количество не может превышать максимальное количество HP цели.<br/>На время восстановления не могут повлиять статусные эффекты или атрибуты снаряжения.',
      },
      // PVE Skill 37
      "PVE Skill 37": {
         "name": 'Microcosmos',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/03b8b3a806a33ef16f67e6c5c09e8deb6c59d526.png',
         "job_icon": 'AST',
         "level": '90',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '20y',
         "content": 'Активирует исцеляющий эффект Macrocosmos, восстанавливающий HP, равное силе лечения 200, прибавляя 50% накопленного урона.<br/>Количество восстановленных HP не может превышать максимальное количество HP цели.',
      },
      // PVE Skill 38 NEW
      "PVE Skill 38": {
         "name": 'Oracle',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7c826ef697cd5d5934661e9238dd5ba0ad607e9d.png',
         "job_icon": 'AST',
         "level": '92',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 860 по цели и всем окружающим противникам.<br/>Может быть использовано только во время действия эффекта Divining.',
      },
      // PVE Skill 39 NEW
      "PVE Skill 39": {
         "name": 'Helios Conjunction',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/20768aed61f83aeae04632231cba41ae889e187f.png',
         "job_icon": 'AST',
         "level": '96',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '800 MP',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '15y',
         "content": 'Восстанавливает HP персонажа и всех окружающих сопартийцев.<br/>Сила лечения: 250<br/>Дополнительный эффект: эффект периодического лечения (Regen)<br/>Сила лечения: 175<br/>Продолжительность: 15 сек.',
      },
      // PVE Skill 40 NEW
      "PVE Skill 40": {
         "name": 'Sun Sign',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/9b0527d5ad6cdb263a912b463d4ff12bd13e9fea.png',
         "job_icon": 'AST',
         "level": '100',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '30y',
         "content": 'Снижает урон, наносимый персонажу и ближайшим сопартийцам, на 10%.<br/>Продолжительность: 15 сек.<br/>Может быть использовано только во время действия эффекта Suntouched.',
      },
      // Arcana 01
      "Arcana 01": {
         "name": 'The Balance',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e0c271c023e40dbe891c059a0649384bd8bd9813.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Увеличивает урон, наносимый персонажем или сопартийцем на 6% если целью является персонаж ближнего боя или танк, или на 3% для остальных ролей.<br/>Продолжительность: 15 сек.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Play I меняется на The Balance при соблюдении требований к выполнению.',
      },
      // Arcana 02
      "Arcana 02": {
         "name": 'The Arrow',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5ed37e114bdbc3bb017899ccf292c119dff9fc8c.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Увеличивает восстановление HP при использовании исцеляющих умений персонажа или сопартийца на 10%.<br/>Продолжительность: 15 сек.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Play II меняется на The Arrow при соблюдении требований к выполнению.',
      },
      // Arcana 03
      "Arcana 03": {
         "name": 'The Spear',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2058f6ea0446529384c53e230d990cec8cb91877.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Увеличивает урон, наносимый персонажем или сопартийцем на 6% если целью является персонаж дальнего боя или целитель, или на 3% для остальных ролей.<br/>Продолжительность: 15 сек.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Play I меняется на The Spear при соблюдении требований к выполнению.',
      },
      // Arcana 04
      "Arcana 04": {
         "name": 'The Bole',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/61c774c41795b2f62b9da4f3c3caf7668abef559.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Снижает урон, получаемый персонажем или сопартицем на 10%.<br/>Продолжительность: 15 сек.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Play II меняется на The Bole при соблюдении требований к выполнению.',
      },
      // Arcana 05
      "Arcana 05": {
         "name": 'The Ewer',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/92c50500729867248fd6e8fc00f7767cffdc2f90.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Накладывает эффект периодического лечения на персонажа или сопартийца.<br/>Сила лечения: 200<br/>Продолжительность: 15 сек.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Play III меняется на The Ewer при соблюдении требований к выполнению.',
      },
      // Arcana 06
      "Arcana 06": {
         "name": 'The Spire',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/423ae76b858935990514ef42b8588d8a782212aa.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Создает вокруг персонажа или выбранного сопартийца барьер, поглощающий урон, эквивалентный силе лечения 400.<br/>Продолжительность: 30 сек.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Play III меняется на The Spire при соблюдении требований к выполнению.',
      },
      // Arcana 07
      "Arcana 07": {
         "name": 'Lord of Crowns',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/723259daf1a4692eba3d085bbd5af39be69b1a93.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '20y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 400 по всем окружающим противникам.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Minor Arcana меняется на Lord of Crowns при соблюдении требований к выполнению.',
      },
      // Arcana 08
      "Arcana 08": {
         "name": 'Lady of Crowns',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d2e17a98f5db304851aa2f5f8c28a2d589af692a.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '20y',
         "content": 'Восстанавливает HP персонажа и всех ближайших сопартийцев.<br/>Сила лечения: 400<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Minor Arcana меняется на Lady of Crowns при соблюдении требований к выполнению.',
      },
      // Trait 01
      "Trait 01": {
         "name": 'Maim and Mend',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/099b8ce7dff9d154a1ae5ac6ba70e7b77530491b.png',
         "job_icon": 'AST',
         "level": '20',
         "content": 'Увеличивает базовый урон умений и восстановления HP на 10%.',
      },
      // Trait 02
      "Trait 02": {
         "name": 'Enhanced Benefic',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7753c5b2adf795e504d26c97452f03dbd9ad4ae6.png',
         "job_icon": 'AST',
         "level": '36',
         "content": 'Дает 15% шанс, что следующий Benefic II будет иметь критический эффект при исцелении.<br/>Продолжительность: 15 сек.',
      },
      // Trait 03
      "Trait 03": {
         "name": 'Maim and Mend II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ea011d893abd8a39efff14c7da1e9cac613b33da.png',
         "job_icon": 'AST',
         "level": '40',
         "content": 'Увеличивает базовый урон умений и восстановления HP на 30%.',
      },
      // Trait 04
      "Trait 04": {
         "name": 'Combust Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f89557c8a060b5202436b06ce55c414930a87824.png',
         "job_icon": 'AST',
         "level": '46',
         "content": 'Улучшает умения Combust до Combust II.',
      },
      // Trait 05
      "Trait 05": {
         "name": 'Malefic Mastery',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/220108abf60/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/096c90be485edbee28599286d9aa506904bfedc1.png',
         "job_icon": 'AST',
         "level": '54',
         "content": 'Улучшает умение Malefic до Malefic II.',
      },
      // Trait 06
      "Trait 06": {
         "name": 'Malefic Mastery II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f519d617a33b436f8bfae128cafb433fa5b4de01.png',
         "job_icon": 'AST',
         "level": '64',
         "content": 'Улучшает умение Malefic II до Malefic III.',
      },
      // Trait 07
      "Trait 07": {
         "name": 'Hyper Lightspeed',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/97aa38c611b5b28a96f41040e8369f9d662c0398.png',
         "job_icon": 'AST',
         "level": '68',
         "content": 'Уменьшает время восстановления умения Lightspeed до 90 сек.',
      },
      // Trait 08 NEW
      "Trait 08": {
         "name": 'Minor Arcana Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b6a9c01931066dd4d28235ea22c332cb20b7a4a1.png',
         "job_icon": 'AST',
         "level": '70',
         "content": 'Lord of Crowns может быть нарисована при использовании Astral Draw, а Lady of Crowns - при использовании Umbral Draw.',
      },
      // Trait 09
      "Trait 09": {
         "name": 'Combust Mastery II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/fa5c279e7998444bf41ef52dd540e514040310ba.png',
         "job_icon": 'AST',
         "level": '72',
         "content": 'Улучшает умение Combust II до Combust III.',
      },
      // Trait 10
      "Trait 10": {
         "name": 'Malefic Mastery III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/79a6019f3f36d87224dcb1621917ede36f53a0eb.png',
         "job_icon": 'AST',
         "level": '72',
         "content": 'Улучшает умение Malefic III до Malefic IV.',
      },
      // Trait 11
      "Trait 11": {
         "name": 'Enhanced Essential Dignity',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5e5dc4bdd1316f0b6e37f3e7aef349e7504a0713.png',
         "job_icon": 'AST',
         "level": '78',
         "content": 'Позволяет накапливать заряды для последовательного использования Essential Dignity.<br/>Максимум зарядов: 2',
      },
      // Trait 12
      "Trait 12": {
         "name": 'Malefic Mastery IV',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/263e46f4c7940ee1681d0f15582ac7a32af7fc6a.png',
         "job_icon": 'AST',
         "level": '82',
         "content": 'Улучшает умение Malefic IV до Fall Malefic.',
      },
      // Trait 13
      "Trait 13": {
         "name": 'Gravity Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e458835a8f922a7e95c1ca5e325e3498007798b6.png',
         "job_icon": 'AST',
         "level": '82',
         "content": 'Улучшает умение Gravity до Gravity II.',
      },
      // Trait 14
      "Trait 14": {
         "name": 'Enhanced Healing Magic',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a24e5cd23307348ea0119062908b5153b2b84ca2.png',
         "job_icon": 'AST',
         "level": '85',
         "content": 'Увеличивает силу исцеляющих умений Benefic до 500, Helios до 400, Benefic II до 800, Aspected Benefic до 250, эффект периодического лечения Aspected Benefic (regen) до 250, Aspected Helios до 250 и эффект периодического лечения Aspected Helios (regen) до 150.',
      },
      // Trait 15
      "Trait 15": {
         "name": 'Enhanced Celestial Intersection',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f43bd4d97118a07e9521573ace0ca9f5cebfb4a5.png',
         "job_icon": 'AST',
         "level": '88',
         "content": 'Позволяет накапливать заряды для последовательного использования Celestial Intersection.<br/>Максимум зарядов: 2',
      },
      // Trait 16 NEW
      "Trait 16": {
         "name": 'Enhanced Divination',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7c830c636c71c4ad906fb4cf3f5a5d2ce684f34f.png',
         "job_icon": 'AST',
         "level": '92',
         "content": 'Накладывает эффект Divining после использования Divination.<br/>Продолжительность: 30 сек.',
      },
      // Trait 17 NEW
      "Trait 17": {
         "name": 'Magick Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/faebcc03aa187f6f45319b41b7336431d1722fc4.png',
         "job_icon": 'AST',
         "level": '94',
         "content": 'Увеличивает силу атаки Combust III, наносящего урон с течением времени, до 70 и Fall Malefic до 270.',
      },
      // Trait 18 NEW
      "Trait 18": {
         "name": 'Aspected Helios Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2cba14df39809f3229349749785e64eb391bed15.png',
         "job_icon": 'AST',
         "level": '96',
         "content": 'Улучшает умение Aspected Helios до Helios Conjunction.',
      },
      // Trait 19 NEW
      "Trait 19": {
         "name": 'Enhanced Essential Dignity II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2836e6ebf3b7d82144fbc5a8ea04c58aa7dff5da.png',
         "job_icon": 'AST',
         "level": '98',
         "content": 'Добавляет третий заряд для умения Essential Dignity.',
      },
      // Trait 20 NEW
      "Trait 20": {
         "name": 'Enhanced Neutral Sect',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/874220e311422fcc32177900e58af6b005976cb2.png',
         "job_icon": 'AST',
         "level": '100',
         "content": 'Накладывает эффект Suntouched после использования Neutral Sect.<br/>Продолжительность: 30 сек.',
      },
      // PVP Skill 01
      "PVP Skill 01": {
         "name": 'Fall Malefic',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7e78194d327e6a89ecb90f3eae608c085346e1f4.png',
         "classification": 'Заклинание',
         "cast": '1.44 сек.',
         "recast": '2.4 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 5,000.',
      },
      // PVP Skill 02
      "PVP Skill 02": {
         "name": 'Aspected Benefic',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4d933fcf783650927195ec4b1814e9609eeddc58.png',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Восстанавливает HP цели.<br/>Сила лечения: 5,000<br/>Сила увеличивается до 10,000 по мере уменьшения HP цели, достигая максимального значения, когда у цели 50% HP или меньше<br/>Дополнительный эффект: накладывает на цель эффект Diurnal Benefic<br/>Эффект Diurnal Benefic: постепенно восстанавливает HP<br/>Сила лечения: 2,000<br/>Продолжительность: 15 сек.<br/>Максимум зарядов: 2<br/>Это умение не имеет общего времени восстановления с другими умениями.',
      },
      // PVP Skill 03
      "PVP Skill 03": {
         "name": 'Gravity II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/65bf868f9e1117ac27da24bca3b88022fca4eb89.png',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 8,000 по цели и всем окружающим противникам.<br/>Дополнительный эффект: накладывает на первую цель эффект +75% тяжесть (heavy)<br/>Продолжительность: 5 сек.<br/>Это умение не имеет общего времени восстановления с другими умениями.',
      },
      // PVP Skill 04
      "PVP Skill 04": {
         "name": 'Double Cast',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/9ba6e1a43826a71c5520b5f322440ca88b85b809.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Повторяет ранее использованное заклинание.<br/>Максимум зарядов: 2<br/>Может быть использовано только после заклинания.',
      },
      // PVP Skill 05
      "PVP Skill 05": {
         "name": 'Draw',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/02611d732461020324f552966a57ec5444dfc387.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Вытягивает the Balance, the Bole или the Arrow из гадальной колоды.<br/>Продолжительность: 15 сек.',
      },
      // PVP Skill 06
      "PVP Skill 06": {
         "name": 'Macrocosmos',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/bbddf9b46af564ac6f2c1ca17e11f44782b8ce21.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '30 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '20y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 12,000 по всем окружающим противникам<br/>Дополнительный эффект: накладывает Macrocosmos на персонажа и всех ближайших сопартийцев<br/>Продолжительность: 10 сек.<br/>При использовании умение меняется на Microcosmos.<br/>На время действия эффекта накапливается 25% получаемого урона.<br/>Восстанавливает HP, равное силе лечения 4000, плюс суммарный урон по истечении срока действия эффекта или после использования Microcosmos.',
      },
      // PVP Skill 07
      "PVP Skill 07": {
         "name": 'Fall Malefic',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7e78194d327e6a89ecb90f3eae608c085346e1f4.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 5,000.<br/>Дополнительный эффект: сокращает время восстановления умения Double Cast на 10 сек.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 08
      "PVP Skill 08": {
         "name": 'Aspected Benefic',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4d933fcf783650927195ec4b1814e9609eeddc58.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Восстанавливает HP цели.<br/>Сила лечения: 5,000<br/>Сила увеличивается до 10,000 по мере уменьшения HP цели, достигая максимального значения, когда у цели 50% HP или меньше.<br/>Дополнительный эффект: накладывает эффект Nocturnal Benefic на цель<br/>Эффект Nocturnal Benefic: создает магический барьер, который обнуляет урон, эквивалентный силе лечения 5,000<br/>Продолжительность: 15 сек.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 09
      "PVP Skill 09": {
         "name": 'Gravity II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/65bf868f9e1117ac27da24bca3b88022fca4eb89.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 8,000 по цели и всем окружающим противникам.<br/>Дополнительный эффект: накладывает на первую цель эффект bind (связывание)<br/>DПродолжительность: 3 сек.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 10
      "PVP Skill 10": {
         "name": 'The Balance',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/643c4801f72755b50d18395bbb46772b714611ac.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '30y',
         "radius_img": 'R2',
         "radius": '20y',
         "content": 'Увеличивает урон, наносимый целью и ближайшими сопартийцами на 10%.<br/>Продолжительность: 15 сек.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 11
      "PVP Skill 11": {
         "name": 'The Bole',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/9b6044f7563aeb1f0a1563df58e91f2fcab7c7b9.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '30y',
         "radius_img": 'R2',
         "radius": '20y',
         "content": 'Уменьшает получаемый урон целью и ближайшими сопартийцами на 10%.<br/>Продолжительность: 15 сек.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 12
      "PVP Skill 12": {
         "name": 'The Arrow',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/85a1d6205ebc89fc139d8fde7966e578fcdc4c2f.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '30y',
         "radius_img": 'R2',
         "radius": '20y',
         "content": 'Уменьшает время применения и время восстановления боевых навыков и заклинаний целью и ближайшими сопартийцами на 10%, а также увеличивает скорость передвижения на 25%.<br/>Продолжительность: 15 сек.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 13
      "PVP Skill 13": {
         "name": 'Microcosmos',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/727601c35b12c8cf610a619bffea557c4eae6140.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '20y',
         "content": 'Активирует исцеляющий эффект Macrocosmos, восстанавливающий HP, равное силе лечения 4000, прибавляя 25% накопленного урона.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 14
      "PVP Skill 14": {
         "name": 'Celestial River',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/184ffb6c90cb6ab81b25f68ba19510ee469ce306.png',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '15y',
         "content": 'Уменьшает урон, наносимый ближайшими противниками на 30%. Эффект снижается на 10% каждые 5 секунд.<br/>Продолжительность: 15 сек.<br/>Дополнительный эффект: увеличивает урон, наносимый персонажем и ближайшими сопартийцами на 30%. Эффект снижается на 10% каждые 5 сек.<br/>Продолжительность: 15 сек.<br/>Может быть использовано только тогда, когда шкала лимит брейка (limit gauge) заполнена.<br/>Время зарядки шкалы: 105 сек.',
      },
   };
   FILL_DB_VALUES(db);
   FILL_DB_SKILLS(db);
   FILL_DB_SKILLS_PASSIVE(db);
   FILL_DB_SKILLS_PVP(db);
   FILL_DB_SKILLS_MENU(db);
})();