(() =>{
   let db = {
      "PVE Update": `Последнее обновление: 27/06/2024`,
      "PVP Update": `Последнее обновление: 27/06/2024`,
      // PVE Skill 01
      "PVE Skill 01": {
         "name": 'Blizzard',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/dab74d4a196c546228d67c91db4bde70c32c45df.png',
         "job_icon": 'THM',
         "level": '1',
         "classification": 'Заклинание',
         "cast": '2.5 сек.',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон льдом с силой атаки 180.<br/>Дополнительный эффект: накладывает эффект Umbral Ice или снимает эффект Astral Fire<br/>Продолжительность: 15 сек.',
      },
      // PVE Skill 02
      "PVE Skill 02": {
         "name": 'Fire',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/0f0b18de207de52d394b2ca8cb990a38e96587e0.png',
         "job_icon": 'THM',
         "level": '2',
         "classification": 'Заклинание',
         "cast": '2.5 сек.',
         "recast": '2.5 сек.',
         "cost": '800 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон огнем с силой атаки 180.<br/>Дополнительный эффект: накладывает эффект Astral Fire или снимает эффект Umbral Ice<br/>Продолжительность: 15 сек.<br/>Дополнительный эффект: шанс 40%, что следующее применение заклинания Fire III будет бесплатным (не потребует MP) и будет использоваться мгновенно<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 03
      "PVE Skill 03": {
         "name": 'Transpose',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/11343c230e7ebd41588ca8f684cb99ee13809398.png',
         "job_icon": 'THM',
         "level": '4',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '5 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Заменяет эффект Astral Fire на одиночный Umbral Ice или эффект Umbral Ice на одиночный Astral Fire.',
      },
      // PVE Skill 04
      "PVE Skill 04": {
         "name": 'Thunder',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/db30f0fa05ce4f541f839c5b2c57cfe0e9fb77f8.png',
         "job_icon": 'THM',
         "level": '6',
         "classification": 'Заклинание',
         "cast": '2.5 сек.',
         "recast": '2.5 сек.',
         "cost": '200 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон молнией с силой атаки 120.<br/>Дополнительный эффект: периодический урон с молнией<br/>Сила атаки: 40<br/>Продолжительность: 24 сек.<br/>Может быть использовано только под действием эффекта Thunderhead, которое дается при получении Astral Fire или Umbral Ice из нестихийного состояния или при переключении между эффектами.<br/>Продолжительность эффекта Thunderhead: 30 сек.<br/>На одну цель может быть наложено только одно заклинание Thunder, наносящее периодический урон.',
      },
      // PVE Skill 05
      "PVE Skill 05": {
         "name": 'Blizzard II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/af68a6b262379df65a5b4bd0408fafbfd3feb450.png',
         "job_icon": 'THM',
         "level": '12',
         "classification": 'Заклинание',
         "cast": '3 сек.',
         "recast": '2.5 сек.',
         "cost": '800 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон льдом с силой атаки 80 по цели и ближайшим противникам.<br/>Дополнительный эффект: накладывает эффект Umbral Ice III или снимает эффект Astral Fire<br/>Продолжительность: 15 сек.',
      },
      // PVE Skill 06
      "PVE Skill 06": {
         "name": 'Scathe',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/82cdaaebcce/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/9b763aecc46c5559bbbccadfe866fe42d56a9597.png',
         "job_icon": 'THM',
         "level": '15',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '800 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'дар, наносящий нестихийный урон с силой атаки 100.<br/>Дополнительный эффект: 20% шанс, что сила заклинания будет удвоена.',
      },
      // PVE Skill 07
      "PVE Skill 07": {
         "name": 'Fire II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/8876f1b3cf116acf7138253e0193396c75698651.png',
         "job_icon": 'THM',
         "level": '18',
         "classification": 'Заклинание',
         "cast": '3 сек.',
         "recast": '2.5 сек.',
         "cost": '1500 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон огнем с силой атаки 80 по цели и ближайшим противникам.<br/>Дополнительный эффект: накладывает эффект Astral Fire III или снимает эффект Umbral Ice<br/>Продолжительность: 15 сек.',
      },
      // PVE Skill 08
      "PVE Skill 08": {
         "name": 'Thunder II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/67205b06f51ddd0e07f16441e38e90d59840f1b6.png',
         "job_icon": 'THM',
         "level": '26',
         "classification": 'Заклинание',
         "cast": '2.5 сек.',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон молнией с силой атаки 60 по цели и ближайшим противникам.<br/>Дополнительный эффект: периодический урон молнией<br/>Сила атаки: 30<br/>Продолжительность: 18 сек.<br/>Может быть использовано только под действием эффекта Thunderhead, которое дается при получении Astral Fire или Umbral Ice из нестихийного состояния или при переключении между эффектами.<br/>Продолжительность эффекта Thunderhead: 30 сек.<br/>На одну цель может быть наложено только одно заклинание Thunder, наносящее периодический урон.',
      },
      // PVE Skill 09
      "PVE Skill 09": {
         "name": 'Manaward',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/efb4d31dbd3/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/75ed92265dc2dcc6fa1e0b8f22a01258799f222d.png',
         "job_icon": 'THM',
         "level": '30',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Создает барьер, предотвращающий получение урона до 30% от максимального HP.<br/>Продолжительность: 20 сек.',
      },
      // PVE Skill 10
      "PVE Skill 10": {
         "name": 'Manafont',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/eec832efc26/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/46be5d9b06e228473154bc91d303ba989308a1cb.png',
         "job_icon": 'BLM',
         "level": '30',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Полностью восстанавливает MP.<br/>Дополнительный эффект: накладывает эффект Astral Fire III<br/>Продолжительность: 15 сек.<br/>Дополнительный эффект: накладывает эффект Thunderhead<br/>Продолжительность: 30 сек.<br/>Дополнительный эффект: накладывает 3 Umbral Hearts<br/>Бонус Umbral Hearts: предотвращает увеличение стоимости Astral Fire MP для заклинаний Fire<br/>Дополнительный эффект: накладывает эффект Paradox<br/>Возможно использовать только под действием эффекта Astral Fire.',
      },
      // PVE Skill 11
      "PVE Skill 11": {
         "name": 'Fire III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/3ff8dcabba57f6a697d5a86fc7490884b74eddff.png',
         "job_icon": 'THM',
         "level": '35',
         "classification": 'Заклинание',
         "cast": '3.5 сек.',
         "recast": '2.5 сек.',
         "cost": '2000 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон огнем с силой атаки 280.<br/>Дополнительный эффект: накладывает эффект Astral Fire III и снимает эффект Umbral Ice<br/>Продолжительность: 15 сек.',
      },
      // PVE Skill 12
      "PVE Skill 12": {
         "name": 'Blizzard III',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/cc550942448/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/6dbb819d3f64b93d6f6ffa23a73101c79592ae2f.png',
         "job_icon": 'BLM',
         "level": '35',
         "classification": 'Заклинание',
         "cast": '3.5 сек.',
         "recast": '2.5 сек.',
         "cost": '800 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон льдом с силой атаки 280.<br/>Дополнительный эффект: накладывает эффект Umbral Ice III и снимает эффект Astral Fire<br/>Продолжительность: 15 сек.',
      },
      // PVE Skill 13
      "PVE Skill 13": {
         "name": 'Freeze',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/bf524c2622f/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2190c4a6ebb204b010020af62a99b1829185aa21.png',
         "job_icon": 'BLM',
         "level": '40',
         "classification": 'Заклинание',
         "cast": '2.8 сек.',
         "recast": '2.5 сек.',
         "cost": '1000 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон льдом с силой атаки 120 по цели и ближайшим противникам.<br/>Дополнительный эффект: накладывает 3 Umbral Hearts<br/>Эффект Umbral Heart: предотвращает увеличение стоимости MP для заклинаний Fire и снижает стоимость MP у заклинания Flare на одну треть<br/>Возможно использовать только под действием эффекта Umbral Ice.',
      },
      // PVE Skill 14
      "PVE Skill 14": {
         "name": 'Thunder III',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/e023bb97879/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2efb022c0715f802a88e1edef4924c075e92a53d.png',
         "job_icon": 'BLM',
         "level": '45',
         "classification": 'Заклинание',
         "cast": '2.5 сек.',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон молнией с силой атаки 160.<br/>Дополнительный эффект: периодический урон молнией<br/>Сила: 45<br/>Продолжительность: 27 сек.<br/>Может быть использовано только под действием эффекта Thunderhead, которое дается при получении Astral Fire или Umbral Ice из нестихийного состояния или при переключении между эффектами.<br/>Продолжительность эффекта Thunderhead: 30 сек.<br/>На одну цель может быть наложено только одно заклинание Thunder, наносящее периодический урон.',
      },
      // PVE Skill 15
      "PVE Skill 15": {
         "name": 'Aetherial Manipulation',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a8c94264a1522d4e1f80e9dcac7864eb6170d722.png',
         "job_icon": 'THM',
         "level": '50',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Мгновенное перемещение к сопартийцу.<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.',
      },
      // PVE Skill 16
      "PVE Skill 16": {
         "name": 'Flare',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/cecfdb58804/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a2d60b093374b2c896487aba2e32eb8bd32eee7c.png',
         "job_icon": 'BLM',
         "level": '50',
         "classification": 'Заклинание',
         "cast": '4 сек.',
         "recast": '2.5 сек.',
         "cost": 'Все MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон по цели и всем ближайшим противникам с силой атаки 240 для первого противника и на 40% меньше для всех остальных.<br/>Дополнительный эффект: накладывает эффект Astral Fire III<br/>Продолжительность: 15 сек.<br/>Дополнительный эффект: дает 3 стака Astral Soul<br/>Эффект заканчивается, когда истекает действие Astral Fire.<br/>Возможно использовать только под действием эффекта Astral Fire.',
      },
      // PVE Skill 17
      "PVE Skill 17": {
         "name": 'Ley Lines',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/cede0d25c63/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2c84ee7f590f1563a8eda87c8ac5d89081365a92.png',
         "job_icon": 'BLM',
         "level": '52',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '3y',
         "content": 'оздает круг силы вокруг персонажа, нахождение в котором снижает время применения и время восстановления заклинаний, а также задержку между авто атаками на 15%.<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 18
      "PVE Skill 18": {
         "name": 'Blizzard IV',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/c4360e9d473/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/43e1468c5bc711966fdbb2790cd60aa6527461bf.png',
         "job_icon": 'BLM',
         "level": '58',
         "classification": 'Заклинание',
         "cast": '2.5 сек.',
         "recast": '2.5 сек.',
         "cost": '800 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон льдом с силой атаки 310.<br/>Дополнительный эффект: накладывает 3 Umbral Hearts<br/>Бонус Umbral Heart: предотвращает увеличение стоимости MP для заклинаний Astral Fire и снижает стоимость MP у заклинания Flare на одну треть<br/>Возможно использовать только под действием эффекта Umbral Ice.',
      },
      // PVE Skill 19
      "PVE Skill 19": {
         "name": 'Fire IV',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/2e548618321/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1a353ade6d0e1ff5828cca6b4bbc11c9f52618bb.png',
         "job_icon": 'BLM',
         "level": '60',
         "classification": 'Заклинание',
         "cast": '2.8 сек.',
         "recast": '2.5 сек.',
         "cost": '800 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон огнем с силой атаки 310.<br/>Дополнительный эффект: активирует Astral Soul<br/>Эффект заканчивается, когда истекает действие Astral Fire.<br/>Заклинание может использоваться только под эффектом Astral Fire.',
      },
      // PVE Skill 20
      "PVE Skill 20": {
         "name": 'Between the Lines',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7c05d4b844c5a3f1e85e6f4b19214715f7d609e2.png',
         "job_icon": 'BLM',
         "level": '62',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '3 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Мгновенное перемещение в Ley Lines, созданные персонажем.<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.',
      },
      // PVE Skill 21
      "PVE Skill 21": {
         "name": 'Thunder IV',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/de62d077a3306797d48ee62f183e82c474b2b768.png',
         "job_icon": 'BLM',
         "level": '64',
         "classification": 'Заклинание',
         "cast": '2.5 сек.',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон молнией с силой атаки 80 по цели и ближайшим противникам.<br/>Дополнительный эффект: периодический урон молнией<br/>Сила атаки: 35<br/>Продолжительность: 21 сек.<br/>Может быть использовано только под действием эффекта Thunderhead, которое дается при получении Astral Fire или Umbral Ice из нестихийного состояния или при переключении между эффектами.<br/>Продолжительность эффекта Thunderhead: 30 сек.<br/>На одну цель может быть наложено только одно заклинание Thunder, наносящее периодический урон.',
      },
      // PVE Skill 22
      "PVE Skill 22": {
         "name": 'Triplecast',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d5bb89a25bf7ce54c03b6fb2898927bd06653219.png',
         "job_icon": 'BLM',
         "level": '66',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Следующие три заклинания будут использованы мгновенно.<br/>Продолжительность: 15 сек.<br/>Максимум зарядов: 2',
      },
      // PVE Skill 23
      "PVE Skill 23": {
         "name": 'Foul',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/c1f2ce42b9d/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4a87efd9bcba0589fb9e9a86b1f9dcd38157c1ee.png',
         "job_icon": 'BLM',
         "level": '70',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'дар, наносящий нестихийный урон по цели и всем противникам с силой атаки 600 для первого и на 60% меньше для всех остальных.<br/>Стоимость: 1 Polyglot',
      },
      // PVE Skill 24
      "PVE Skill 24": {
         "name": 'Despair',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/73a81c740f02599d7ec5d451d659b1fe4409123a.png',
         "job_icon": 'BLM',
         "level": '72',
         "classification": 'Заклинание',
         "cast": '3 сек.',
         "recast": '2.5 сек.',
         "cost": 'Все MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон огнем с силой атаки 340.<br/>Дополнительный эффект: накладывает эффект Astral Fire III<br/>Продолжительность: 15 сек.<br/>Возможно использовать только под действием эффекта Astral Fire.',
      },
      // PVE Skill 25
      "PVE Skill 25": {
         "name": 'Umbral Soul',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5c3311c8d38df2d4617c0a325772cdd229f3c181.png',
         "job_icon": 'BLM',
         "level": '76',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Накладывает эффект Umbral Ice и дает 1 Umbral Heart.<br/>Эффект Umbral Heart: предотвращает увеличение стоимости MP для заклинаний Astral Fire и снижает стоимость MP у заклинания Flare на одну треть<br/>Дополнительный эффект: восстанавливает количество MP, равное количеству стаков Umbral Ice<br/>Umbral Ice I: 2,500 MP<br/>Umbral Ice II: 5,000 MP<br/>Umbral Ice III: 10,000 MP<br/>Возможно использовать только под действием эффекта Umbral Ice.',
      },
      // PVE Skill 26
      "PVE Skill 26": {
         "name": 'Xenoglossy',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/428eac2232a6d9531a9a02e344dc48bb06310c6c.png',
         "job_icon": 'BLM',
         "level": '80',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 880.<br/>Стоимость: 1 Polyglot',
      },
      // PVE Skill 27
      "PVE Skill 27": {
         "name": 'High Fire II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/46a0285209f71ee209c27b8211e9aa798417813c.png',
         "job_icon": 'BLM',
         "level": '82',
         "classification": 'Заклинание',
         "cast": '3 сек.',
         "recast": '2.5 сек.',
         "cost": '1500 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон огнем с силой атаки 100 по цели и ближайшим противникам.<br/>Дополнительный эффект: накладывает эффект Astral Fire III и снимает эффект Umbral Ice<br/>Продолжительность: 15 сек.',
      },
      // PVE Skill 28
      "PVE Skill 28": {
         "name": 'High Blizzard II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f775fdd2f3ef5115cad5ed5a85c81ca2a2cfd735.png',
         "job_icon": 'BLM',
         "level": '82',
         "classification": 'Заклинание',
         "cast": '3 сек.',
         "recast": '2.5 сек.',
         "cost": '800 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон льдом с силой атаки 100 по цели и ближайшим противникам.<br/>Дополнительный эффект: накладывает эффект Umbral Ice III и снимает эффект Astral Fire<br/>Продолжительность: 15 сек.',
      },
      // PVE Skill 29
      "PVE Skill 29": {
         "name": 'Amplifier',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/6f48a9f1b585cf23a21cf9ed3f7a012745928295.png',
         "job_icon": 'BLM',
         "level": '86',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'обавляет Polyglot.<br/>Возможно использовать только под действием эффекта Astral Fire или Umbral Ice.',
      },
      // PVE Skill 30
      "PVE Skill 30": {
         "name": 'Paradox',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7a6d48e67b25969c1ad12f0f42d03b484f8f9f9b.png',
         "job_icon": 'BLM',
         "level": '90',
         "classification": 'Заклинание',
         "cast": '2.5 сек.',
         "recast": '2.5 сек.',
         "cost": '1600 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 500.<br/>Дополнительный эффект: накладывает эффект Astral Fire<br/>Продолжительность: 15 сек.<br/>Дополнительный эффект: накладывает эффект Firestarter<br/>Эффект Firestarter: следующий Fire III будет использован мгновенно и не расходует MP<br/>Продолжительность: 30 сек.<br/>Может использоваться только под действием эффекта Paradox.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Fire меняется на Paradox при соблюдении требований к выполнению.',
      },
      // PVE Skill 31 NEW
      "PVE Skill 31": {
         "name": 'High Thunder',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1babd2b0f9ad34451ac3ac29230b2239db95065b.png',
         "job_icon": 'BLM',
         "level": '92',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон молнией с силой атаки 200.<br/>Дополнительный эффект: периодический урон молнией<br/>Сила атаки: 55<br/>Продолжительность: 30 сек.<br/>Может быть использовано только под действием эффекта Thunderhead, которое дается при получении Astral Fire или Umbral Ice из нестихийного состояния или при переключении между эффектами.<br/>Продолжительность эффекта Thunderhead: 30 сек.<br/>На одну цель может быть наложено только одно заклинание Thunder, наносящее периодический урон.',
      },
      // PVE Skill 32 NEW
      "PVE Skill 32": {
         "name": 'High Thunder II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/51a70145dcf0d8136ff82ce50713529f1cebaf84.png',
         "job_icon": 'BLM',
         "level": '92',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон молнией с силой атаки 100 по цели и ближайшим противникам.<br/>Дополнительный эффект: периодический урон молнией<br/>Сила атаки: 40<br/>Продолжительность: 24 сек.<br/>Может быть использовано только под действием эффекта Thunderhead, которое дается при получении Astral Fire или Umbral Ice из нестихийного состояния или при переключении между эффектами.<br/>Продолжительность эффекта Thunderhead: 30 сек.<br/>На одну цель может быть наложено только одно заклинание Thunder, наносящее периодический урон.',
      },
      // PVE Skill 33 NEW
      "PVE Skill 33": {
         "name": 'Retrace',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/cede0d25c63/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/44666e4299c0eded8c4af12edb67c7c9f718bda5.png',
         "job_icon": 'BLM',
         "level": '96',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '40 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '3y',
         "content": 'Создаёт круг силы заново, перемещая его на новое месте.<br/>Может быть использовано только под действием эффекта Ley Lines.',
      },
      // PVE Skill 34 NEW
      "PVE Skill 34": {
         "name": 'Flare Star',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1bf799ec68187691dceb2adb9dc0ea1259f03dd1.png',
         "job_icon": 'BLM',
         "level": '100',
         "classification": 'Заклинание',
         "cast": '3 сек.',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон огнем по цели и всем ближайшим противникам с силой атаки 400 для первого противника и на 65% меньше для всех остальных.<br/>Возможно использовать только при полной шкале Astral Gauge.',
      },
      // Trait 01
      "Trait 01": {
         "name": 'Aspect Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1f6dc1fc194d45867020cb6f5d28829bc1320a35.png',
         "job_icon": 'THM',
         "level": '1',
         "content": 'Использование персонажем определённых огненных и ледяных заклинаний дает стак Astral Fire and Umbral Ice.<br/>Максимум стаков: 1<br/>Продолжительность: 15 сек.<br/>Пока персонаж находится под действием эффекта Astral Fire, стоимость произнесения заклинаний Fire удваивается, восстановление MP снижается до 0. Сила заклинаний Ice снижается на 10%.<br/>Пока персонаж находится под действием эффекта Umbral Ice, стоимость произнесения заклинаний Ice снижается до 0, при произнесении заклинания Ice восстанавливается 2,500 MP. Сила заклинаний Fire снижается на 10%.',
      },
      // Trait 02
      "Trait 02": {
         "name": 'Maim and Mend',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/688b9e979396925fa8a996968547e39f057ff539.png',
         "job_icon": 'THM',
         "level": '20',
         "content": 'Увеличивает базовый урон умений и восстановления HP на 10%.',
      },
      // Trait 03
      "Trait 03": {
         "name": 'Aspect Mastery II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a82ec92018c475ea79c983d7cd8aee36403769c5.png',
         "job_icon": 'THM',
         "level": '20',
         "content": 'Позволяет накапливать второй стак Astral Fire и Umbral Ice.<br/>Пока персонаж находится под действием эффекта Astral Fire, сила заклинаний Fire увеличивается на 60%, а сила заклинаний Ice снижается на 20%.<br/>Пока персонаж находится под действием эффекта Umbral Ice, при произнесении заклинания Ice восстанавливается 5,000 MP, а сила заклинаний Fire снижается на 20%.',
      },
      // Trait 04
      "Trait 04": {
         "name": 'Aspect Mastery III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/76a7c6ce2f03e8daa6d5639923955353d7ad7cb8.png',
         "job_icon": 'THM',
         "level": '35',
         "content": 'Позволяет накапливать третий Astral Fire и Umbral Ice.<br/>Использование Fire II или Blizzard II дает максимальное количество стаков Astral Fire или Umbral Ice соответственно.<br/>Пока персонаж находится под действием эффекта  Astral Fire III, сила заклинаний огня увеличивается на 60%, а время произнесения заклинаний Ice сокращается вдвое.<br/>Пока персонаж находится под действием эффекта Umbral Ice III, при использовании Ice заклинания восстанавливается 10,000 MP, а время произнесения заклинаний Fire сокращается вдвое.',
      },
      // Trait 05
      "Trait 05": {
         "name": 'Maim and Mend II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f0493aff0cf655167be05890774732eebed2b598.png',
         "job_icon": 'THM',
         "level": '40',
         "content": 'Увеличивает базовый урон умений и восстановления HP на 30%.',
      },
      // Trait 06
      "Trait 06": {
         "name": 'Firestarter',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/eba9b84751761d8b1a31d917f098c8b1843f8572.png',
         "job_icon": 'THM',
         "level": '42',
         "content": 'ает 40% шанс, что после использования заклинания Fire следующее заклинание Fire III не потребует MP и будет использовано мгновенно.<br/>Продолжительность: 30 сек.',
      },
      // Trait 07
      "Trait 07": {
         "name": 'Thunder Mastery',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/e023bb97879/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d246d935235a66fd245a11325a9e49fb8c41525d.png',
         "job_icon": 'BLM',
         "level": '45',
         "content": 'Улучшает умение Thunder до Thunder III.',
      },
      // Trait 08
      "Trait 08": {
         "name": 'Enochian',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/27332e04866/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/455d53e43676e9604b93ba67180e9050cfd7077f.png',
         "job_icon": 'BLM',
         "level": '56',
         "content": 'Увеличивает наносимый урон на 5% под действием эффекта Astral Fire или Umbral Ice.',
      },
      // Trait 09 NEW
      "Trait 09": {
         "name": 'Umbral Heart',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e6f9a67222832fe27c7a6f3998ed0ab39aaddf1c.png',
         "job_icon": 'BLM',
         "level": '58',
         "content": 'Накладывает 3 Umbral Hearts после произнесения Freeze или использования Manafont.',
      },
      // Trait 10
      "Trait 10": {
         "name": 'Thunder Mastery II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c9bc1640c47083f7df3ba856be93dfa1e59d600f.png',
         "job_icon": 'BLM',
         "level": '64',
         "content": 'Улучшает умение Thunder II до Thunder IV.',
      },
      // Trait 11
      "Trait 11": {
         "name": 'Enhanced Enochian',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/c1f2ce42b9d/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/53a893a774b158e25e4803a4b9ec92b50e6492da.png',
         "job_icon": 'BLM',
         "level": '70',
         "content": 'Накладывает эффект Polyglot при поддержании Enochian в течение 30 секунд. Также усиливает увеличение магического урона Enochian до 10%.',
      },
      // Trait 12
      "Trait 12": {
         "name": 'Enhanced Enochian II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/442db8a1a39e876e2abbc2727fcb816255f701b7.png',
         "job_icon": 'BLM',
         "level": '78',
         "content": 'Усиливает увеличение магического урона Enochian до 15%.',
      },
      // Trait 13
      "Trait 13": {
         "name": 'Enhanced Polyglot',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ecd14c75e33f69d4006d1c80fd44952d60c2c0a2.png',
         "job_icon": 'BLM',
         "level": '80',
         "content": 'Позволяет накапливать второй стак Polyglot.',
      },
      // Trait 14
      "Trait 14": {
         "name": 'Enhanced Foul',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4e8b85566fa51e858b0dfdf86e0f9457e8606880.png',
         "job_icon": 'BLM',
         "level": '80',
         "content": 'Позволяет мгновенно использовать Foul.',
      },
      // Trait 15
      "Trait 15": {
         "name": 'Aspect Mastery IV',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/3ae30d9437eea508883a60853048894f3c8af421.png',
         "job_icon": 'BLM',
         "level": '82',
         "content": 'Улучшает умение Fire II и Blizzard II до High Fire II и High Blizzard II.',
      },
      // Trait 16
      "Trait 16": {
         "name": 'Enhanced Manafont',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/791a538cb15c66db13742a098bfd38f2f8f8ec53.png',
         "job_icon": 'BLM',
         "level": '84',
         "content": 'Сокращает время восстановления Manafont до 100 сек.',
      },
      // Trait 17
      "Trait 17": {
         "name": 'Enhanced Enochian III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/72578b4df3af511dffc110405fba9737cff7d922.png',
         "job_icon": 'BLM',
         "level": '86',
         "content": 'Усиливает увеличение магического урона Enochian до 23%.',
      },
      // Trait 18
      "Trait 18": {
         "name": 'Aspect Mastery V',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c81e19d6212f972df31805fc204e150740067760.png',
         "job_icon": 'BLM',
         "level": '90',
         "content": 'Добавляет маркер Paradox к шкале Elemental Gauge персонажа.<br/>Маркер становится активным после достижения Umbral Ice III, получения 3 Umbral Hearts и затем смены элемента на противоположный. Маркер становится неактивным, когда эффект Astral Fire истекает.<br/>Умения Fire становятся Paradox, когда маркер Paradox становится активным.',
      },
      // Trait 19 NEW
      "Trait 19": {
         "name": 'Thunder Mastery III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/eebc32855d2ca394cf748076ef0b9cacbec2e32f.png',
         "job_icon": 'BLM',
         "level": '92',
         "content": 'Улучшает умение Thunder до High Thunder и Thunder IV до High Thunder IV.',
      },
      // Trait 20 NEW
      "Trait 20": {
         "name": 'Enhanced Ley Lines',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/972846e749d8f5230fd758f2fd861e2120063279.png',
         "job_icon": 'BLM',
         "level": '96',
         "content": 'Расположение Ley Lines может быть сброшено, пока действует эффект.',
      },
      // Trait 21 NEW
      "Trait 21": {
         "name": 'Enhanced Enochian IV',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/56e64c6a8875472651cd1280bcdb3d879c7aabdf.png',
         "job_icon": 'BLM',
         "level": '96',
         "content": 'Повышает урон от магии Enochian до 30%.',
      },
      // Trait 22 NEW
      "Trait 22": {
         "name": 'Enhanced Polyglot II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/cd30af36c468ebc29ca7b8eba0a922a05dc6adf8.png',
         "job_icon": 'BLM',
         "level": '98',
         "content": 'Позволяет накапливать третий стак Polyglot.',
      },
      // Trait 23 NEW
      "Trait 23": {
         "name": 'Enhanced Astral Fire',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/72fc6ff01df8c8581add7a77a3c64f969f854083.png',
         "job_icon": 'BLM',
         "level": '100',
         "content": 'Дает стак Astral Soul при использовании Fire IV или Flare.<br/>Максимум стаков: 6',
      },
      // PVP Skill 01
      "PVP Skill 01": {
         "name": 'Fire',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/bd8aefe983c379ed726996e5030785d492cef722.png',
         "classification": 'Заклинание',
         "cast": '1.44 сек.',
         "recast": '2.4 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон огнем с силой атаки 4,000.<br/>Заклинание используется мгновенно, если если персонаж находится действием Umbral Ice.<br/>Дополнительный эффект: накладывает на цель стак эффекта Astral Warmth, вплоть до 3<br/>Продолжительность: 15 сек.<br/>Эффект не складывается с эффектом Umbral Freeze<br/>Дополнительный эффект: накладывает эффект Astral Fire II<br/>Продолжительность: 30 сек.<br/>Эффект не складывается с эффектом Umbral Ice.<br/><br/>※Умением меняется на Fire IV под действием эффекта Astral Fire II.',
      },
      // PVP Skill 02
      "PVP Skill 02": {
         "name": 'Blizzard',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/dc24fffcea464a6f5f4ae83c893e89f31ca6a274.png',
         "classification": 'Заклинание',
         "cast": '1.44 сек.',
         "recast": '2.4 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон льдом с силой атаки 4,000.<br/>Заклинание используется мгновенно, если если персонаж находится действием Astral Fire.<br/>Дополнительный эффект: накладывает на цель стак эффекта Umbral Freeze, вплоть до 3<br/>Продолжительность: 15 сек.<br/>Эффект не складывается с эффектом Astral Warmth.<br/>Дополнительный эффект: накладывает эффект Ice II<br/>Продолжительность: 30 сек.<br/>Эффект не складывается с эффектом Astral Fire.<br/><br/>※Умением меняется на Blizzard IV под действием эффекта Umbral Ice II.',
      },
      // PVP Skill 03
      "PVP Skill 03": {
         "name": 'Burst',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f2047323e6e33591811d0303209137f0f841cd81.png',
         "classification": 'Заклинание',
         "cast": '1.92 сек.',
         "recast": '20 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон молнией с силой атаки 16,000 по всем ближайшим противникам.<br/>Дополнительный эффект: создает барьер вокруг персонажа, поглощающий урон, равный силе лечения 16,000.<br/>Продолжительность: 10 сек.<br/>Это умение не имеет общего времени восстановления с другими умениями.',
      },
      // PVP Skill 04
      "PVP Skill 04": {
         "name": 'Paradox',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1fd314a320e0ffcf7b928a1e8edb882a7803a7a9.png',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 8,000.<br/>Дополнительный эффект: увеличивает на цели количество стаков эффекта Astral Warmth или Umbral Freeze до максимума<br/>Продолжительность: 15 сек.<br/>Это умение не имеет общего времени восстановления с другими умениями.',
      },
      // PVP Skill 05
      "PVP Skill 05": {
         "name": 'Night Wing',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/39b84e9b07f19b7d4fd195171668fc71d98d438b.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '30 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Накладывает на цель и всех ближайших противников эффект полу-сон (half-sleep).<br/>Продолжительность: 3 сек.<br/>Эффект Half-asleep: цель погружается в сон (sleep) по истечении действия эффекта<br/>Продолжительность: 3 сек.<br/>Цели, находящиеся под действием эффекта сон (sleep), получают дополнительный урон с силой атаки 8,000, после чего эффект рассеется.',
      },
      // PVP Skill 06
      "PVP Skill 06": {
         "name": 'Aetherial Manipulation',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b7bfe048da3d02b5572be0dfa123d46be0ca3784.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Мгновенное перемещение к сопартийцу или в противнику.<br/>Дополнительный эффект: накладывает эффект Swiftcast<br/>Эффект Swiftcast: следующее заклинание можно использовать мгновенно<br/>Продолжительность: 10 сек.<br/>Максимум зарядов: 2<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.',
      },
      // PVP Skill 07
      "PVP Skill 07": {
         "name": 'Superflare',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/6864c3e2bb745d9715492532ad74a4277ea5b2ab.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '30y',
         "content": 'Удар, наносящий урон по всем ближайшим противникам с силой атаки от 3,000 до 9,000, в зависимости от количество стаков эффекта Astral Warmth или Umbral Freeze на них.<br/>Дополнительный эффект: противники, находящиеся под действием эффекта Astral Warmth, получают Burns, наносящий периодический урон огнем<br/>Сила атаки: 3,000<br/>Продолжительность: 6 сек.<br/>Длительность увеличивается на 3 сек. за каждый дополнительный стак Astral Warmth, вплоть до 12 сек.<br/>Дополнительный эффект: противники, находящиеся под действием эффекта Umbral Freeze, получают негативный статус, соответствующее количеству накопленных стаков<br/>1 стак: тяжесть (heavy)<br/>2 стака: связывание (bind)<br/>3 стака: глубокая заморозка (deep freeze)<br/>Продолжительность: 2 сек.<br/>Максимум зарядов: 2',
      },
      // PVP Skill 08
      "PVP Skill 08": {
         "name": 'Fire IV',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c19670b228b7a32f1555a892ad6c6f6cf5a299eb.png',
         "classification": 'Заклинание',
         "cast": '1.44 сек.',
         "recast": '2.4 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон огнем с силой атаки 6,000.<br/>Дополнительный эффект: накладывает на цель стак эффекта Astral Warmth, вплоть до 3<br/>Продолжительность: 15 сек.<br/>Эффект не складывается с эффектом Umbral Freeze.<br/>Дополнительный эффект: накладывает эффект Astral Fire III<br/>Продолжительность: 30 сек.<br/>Эффект не складывается с эффектом Umbral Ice.<br/>Можно использовать только под действием эффекта Astral Fire II.<br/><br/>※Умение меняется на Flare под действием эффекта Astral Fire III.<br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 09
      "PVP Skill 09": {
         "name": 'Flare',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e741977a1edf3dd9346fda665513f44e2f3657f4.png',
         "classification": 'Заклинание',
         "cast": '1.44 сек.',
         "recast": '2.4 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон огнем с силой атаки 12,000 по цели и 8,000 по всем ближайшим противникам.<br/>Дополнительный эффект: накладывает на цель стак эффекта Astral Warmth, вплоть до 3<br/>Продолжительность: 15 сек.<br/>Эффект не складывается с эффектом Umbral Freeze<br/>Можно использовать только под действием эффекта Astral Fire III.<br/>Эффект Astral Fire III прекращается после использования.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 10
      "PVP Skill 10": {
         "name": 'Blizzard IV',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/07ed8d0a26c2565eb1b299106a1cf65e947f1c6f.png',
         "classification": 'Заклинание',
         "cast": '1.44 сек.',
         "recast": '2.4 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон льдом с силой атаки 6,000.<br/>Дополнительный эффект: накладывает на цель стак эффекта Umbral Freeze, вплоть до 3<br/>Продолжительность: 15 сек.<br/>Эффект не складывается с эффектом Astral Warmth.<br/>Дополнительный эффект: накладывает эффект Umbral Ice III<br/>Продолжительность: 30 сек.<br/>Эффект не складывается с эффектом Astral Fire.<br/>Можно использовать только под действием эффекта Umbral Ice II.<br/><br/>※Умение меняется на Freeze под действием эффекта Umbral Ice II.<br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 11
      "PVP Skill 11": {
         "name": 'Freeze',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/aafe3a863f3f3f97139afda8225384ef31a5dd96.png',
         "classification": 'Заклинание',
         "cast": '1.44 сек.',
         "recast": '2.4 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон льдом с силой атаки 12,000 по цели и 8,000 по всем ближайшим противникам.<br/>Дополнительный эффект: накладывает на цель стак эффекта Umbral Freeze, вплоть до 3<br/>Продолжительность: 15 сек.<br/>Эффект не складывается с эффектом Astral Warmth.<br/>Можно использовать только под действием эффекта Umbral Ice III.<br/>Эффект Umbral Ice III прекращается после использования.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 12
      "PVP Skill 12": {
         "name": 'Foul',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c69c9a5fc01ef8c831af84aff7d3d7c5cba0d1f0.png',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.4 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 16,000 по цели и всем ближайшим противникам.<br/>Можно использовать только под действием эффекта Polyglot.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 13
      "PVP Skill 13": {
         "name": 'Soul Resonance',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b834e18e2f5e1eb8dcdde2e1360761650e6296a3.png',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Накладывает 6 стаков Soul Resonance, улучшая умения Fire до Flare и Blizzard до Freeze.<br/>Продолжительность: 30 сек.<br/>Дополнительный эффект: накладывает эффекты Polyglot и Apocatastasis<br/>Эффект Polyglot: умение меняется на Foul<br/>Продолжительность: 60 сек.<br/>Эффект Apocatastasis: снижает получаемый урон на 10%<br/>Продолжительность: 15 сек.<br/>Дополнительный эффект: уменьшает время повторного применения Superflare на 15 сек.<br/>Может быть использовано только тогда, когда шкала лимит брейка (limit gauge) заполнена.<br/>Время зарядки шкалы:  60 сек.',
      },
   };
   FILL_DB_VALUES(db);
   FILL_DB_SKILLS(db);
   FILL_DB_SKILLS_PASSIVE(db);
   FILL_DB_SKILLS_PVP(db);
   FILL_DB_SKILLS_MENU(db);
})();