FILL_DB_VALUES(
   {
      "CRP Update": `Последнее обновление: 02/10/2023`,
      "Basic Synthesis": ``,
      "Basic Touch": ``,
      "Master's Mend": ``,
      "Hasty Touch": ``,
      "Rapid Synthesis": ``,
      "Observe": ``,
      "Tricks of the Trade": ``,
      "Waste Not": ``,
      "Veneration": ``,
      "Standard Touch": ``,
      "Great Strides": ``,
      "Innovation": ``,
      "Final Appraisal": ``,
      "Waste Not II": ``,
      "Byregot's Blessing": ``,
      "Precise Touch": ``,
      "Muscle Memory": ``,
      "Careful Synthesis": ``,
      "Manipulation": ``,
      "Prudent Touch": ``,
      "Focused Synthesis": ``,
      "Focused Touch": ``,
      "Reflect": ``,
      "Preparatory Touch": ``,
      "Groundwork": ``,
      "Delicate Synthesis": ``,
      "Intensive Synthesis": ``,
      "Trained Eye": ``,
      "Advanced Touch": ``,
      "Prudent Synthesis": ``,
      "Trained Finesse": ``,
      "Careful Observation": ``,
      "Heart and Soul": ``,
      "Inner Quiet": ``,
      "Practice Makes Perfect": ``,
      "Basic Synthesis Mastery": ``,
      "Quality Assurance": ``,
      "Rapid Synthesis Mastery": ``,
      "Careful Synthesis Mastery": ``,
      "Groundwork Mastery": ``,
   }
);