(() =>{
   let db = {
      "PVE Update": `Последнее обновление: 27/06/2024`,
      "PVP Update": `Последнее обновление: 27/06/2024`,
      // PVE Skill 01
      "PVE Skill 01": {
         "name": 'Cascade',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/6843786e4a944ff2e315004f38416b9098b62988.png',
         "job_icon": 'DNC',
         "level": '1',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 220.<br/>Дополнительный эффект: 50% шанс при использовании получить эффект Silken Symmetry<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 02
      "PVE Skill 02": {
         "name": 'Fountain',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/25291ed46a237d93b8ada8db02fdeb34f5706c6e.png',
         "job_icon": 'DNC',
         "level": '2',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 120.<br/>Комбо умение: Cascade<br/>Сила в комбо: 280<br/>Комбо бонус: 50% шанс при использовании получить эффект Silken Flow<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 03
      "PVE Skill 03": {
         "name": 'Windmill',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2b56bd032544ac3119cf459288984ea195837486.png',
         "job_icon": 'DNC',
         "level": '15',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 100 по всем ближайшим противникам.<br/>Дополнительный эффект: 50% шанс при использовании получить эффект Silken Symmetry<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 04
      "PVE Skill 04": {
         "name": 'Standard Step',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/601122ac0085d666731203ba91b41a5099457eca.png',
         "job_icon": 'DNC',
         "level": '15',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '30 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Начинает танец, накладывая на персонажа эффект Standard Step.<br/>Продолжительность: 15 сек.<br/>Умение сменяется на Standard Finish во время танца.<br/>Только умения Standard Finish, En Avant, Curing Waltz, Shield Samba, step умения, ролевые умения, ускорение (sprint) и лимит брейк (limit Break) могут использоваться во время танца.<br/>После использования этого умения время восстановления будет применено ко всем остальным боевым навыкам и магическим умениям.',
      },
      // PVE Skill 05
      "PVE Skill 05": {
         "name": 'Standard Finish',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/3be799f98318288057e0c0957fce44d32d8f2974.png',
         "job_icon": 'DNC',
         "level": '15',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '15y',
         "content": 'Удар, наносящий урон по всем ближайшим противникам. Сила атаки умения варьируется в зависимости от количества успешно сделанных steps, нанося полный урон первому противнику, и на 75% меньше остальным.<br/>0 Steps: 360<br/>1 Step: 540<br/>2 Steps: 850<br/>Бонус Step: накладывает эффект Standard Finish и Esprit на персонажа и выбранного сопартийца, который выбран как Dance Partner<br/>Бонус урона от Standard Finish зависит от количества успешно исполненных steps.<br/>1 Step: 2%<br/>2 Steps: 5%<br/>Продолжительность: 60 сек.<br/>Дополнительный эффект: накладывает эффект Last Dance Ready<br/>Продолжительность: 30 сек.<br/>Может использоваться только во время Dancing.<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями.<br/>После использования этого умения время восстановления будет применено ко всем остальным боевым навыкам и магическим умениям.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Standard Step меняется на Standard Finish при соблюдении требований к выполнению.',
      },
      // PVE Skill 06
      "PVE Skill 06": {
         "name": 'Reverse Cascade',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a03ec89f3860e636fa459b5ac4212031aea5c8f7.png',
         "job_icon": 'DNC',
         "level": '20',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 280.<br/>Дополнительный эффект: 50% шанс при использовании получить эффект Fourfold Feather<br/>Может использоваться только под эффектами Silken Symmetry или Flourishing Symmetry.',
      },
      // PVE Skill 07
      "PVE Skill 07": {
         "name": 'Bladeshower',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/65c0208ef7c6b132558c6aab0a15832fec601e5b.png',
         "job_icon": 'DNC',
         "level": '25',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 100 по всем ближайшим противникам.<br/>Комбо умение: Windmill<br/>Сила в комбо: 140<br/>Комбо бонус: 50% шанс при использовании получить эффект Silken Flow<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 08
      "PVE Skill 08": {
         "name": 'Fan Dance',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/62a211c886bd5b46f47b11419f3b55fb628f6535.png',
         "job_icon": 'DNC',
         "level": '30',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 150.<br/>Дополнительный эффект: 50% шанс при использовании получить эффект Threefold Fan Dance<br/>Продолжительность: 30 сек.<br/>Может быть использовано только при наличии Fourfold Feathers.',
      },
      // PVE Skill 09
      "PVE Skill 09": {
         "name": 'Rising Windmill',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e233509e4d32c5f7aef385766026a3e161d2d142.png',
         "job_icon": 'DNC',
         "level": '35',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 140 по всем ближайшим противникам.<br/>Дополнительный эффект: 50% шанс при использовании получить эффект Fourfold Feather<br/>Может использоваться только под эффектами Silken Symmetry или Flourishing Symmetry.',
      },
      // PVE Skill 10
      "PVE Skill 10": {
         "name": 'Fountainfall',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e4e0f0c2d152720e33f1759219de09ab52051a21.png',
         "job_icon": 'DNC',
         "level": '40',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 340.<br/>Дополнительный эффект: 50% шанс при использовании получить эффект Fourfold Feather<br/>Может использоваться только под эффектами Silken Symmetry или Flourishing Flow.',
      },
      // PVE Skill 11
      "PVE Skill 11": {
         "name": 'Bloodshower',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/75fa1885b19b76db73429a0661588d544e5bc974.png',
         "job_icon": 'DNC',
         "level": '45',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 180 по всем ближайшим противникам.<br/>Дополнительный эффект: 50% шанс при использовании получить эффект Fourfold Feather<br/>Может использоваться только под эффектами Silken Symmetry или Flourishing Flow.',
      },
      // PVE Skill 12
      "PVE Skill 12": {
         "name": 'Fan Dance II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/835016d35e3f62a1ce42a3519e70714b25d91969.png',
         "job_icon": 'DNC',
         "level": '50',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 100 по всем ближайшим противникам.<br/>Дополнительный эффект: 50% шанс при использовании получить эффект Threefold Fan Dance<br/>Продолжительность: 30 сек.<br/>Может быть использовано только при наличии Fourfold Feathers.',
      },
      // PVE Skill 13
      "PVE Skill 13": {
         "name": 'En Avant',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b855b43c6fa93b143a93b339527a31950f6cdc47.png',
         "job_icon": 'DNC',
         "level": '50',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '30 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Рывок на 10 ялмов вперед.<br/>Максимум зарядов: 3<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.',
      },
      // PVE Skill 14
      "PVE Skill 14": {
         "name": 'Curing Waltz',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/30a793f0a1bae7d643449bd69b63722b8bbf1b3a.png',
         "job_icon": 'DNC',
         "level": '52',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '3y',
         "content": 'Восстанавливает HP персонажа и ближайших сопартийцев.<br/>Сила лечения: 300<br/>Дополнительный эффект: сопартиец, отмеченный как Dance Partner, также будет лечить себя и ближайших сопартийцев',
      },
      // PVE Skill 15
      "PVE Skill 15": {
         "name": 'Shield Samba',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f9692ff39ee50c5901429aaca48c066b8952732a.png',
         "job_icon": 'DNC',
         "level": '56',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '90 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '30y',
         "content": 'Снижает урон получаемый персонажем и сопартийцами на 15%.<br/>Продолжительность: 15 сек.<br/>Эффект не суммируется с умение Troubadour барда или Tactician машиниста.',
      },
      // PVE Skill 16
      "PVE Skill 16": {
         "name": 'Closed Position',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/6bdcca52407a9435fe5a8578742995382e38f097.png',
         "job_icon": 'DNC',
         "level": '60',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '30 сек.',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Накладывает на персонажа Closed Position и назначает выбранного сопартийца Dance Partner, позволяя разделять с ним эффекты Standard Finish, Curing Waltz, Devilment и Tillana.<br/>Эффект спадает при повторном использовании.',
      },
      // PVE Skill 17
      "PVE Skill 17": {
         "name": 'Ending',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e32ebe0fb7a3a32ca14bdae331a0a05253f77f8e.png',
         "job_icon": 'DNC',
         "level": '60',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Заканчивает танец с выбранным партнером.',
      },
      // PVE Skill 18
      "PVE Skill 18": {
         "name": 'Devilment',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5dbf1b6a363454e48f1a32f92fe5c5cb6d8d229b.png',
         "job_icon": 'DNC',
         "level": '62',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Увеличивает шансы критического (critical) и прямого (direct) урона на 20%.<br/>Продолжительность: 20 сек.<br/>Дополнительный эффект: сопартиец, отмеченный как Dance Partner, также получит эффект Devilment<br/>Дополнительный эффект: накладывает Flourishing Starfall<br/>Продолжительность: 20 сек.',
      },
      // PVE Skill 19
      "PVE Skill 19": {
         "name": 'Fan Dance III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d786bf59396fce45e0e1bdf96cb1196b48b4a98a.png',
         "job_icon": 'DNC',
         "level": '66',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон по цели и всем ближайшим противникам с силой атаки 220 для первого и на 50% меньше для всех остальных.<br/>Может использоваться только под эффектом Threefold Fan Dance.',
      },
      // PVE Skill 20
      "PVE Skill 20": {
         "name": 'Technical Step',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/cab5f473230/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2b0f0944de8d90ce1e9413cc3294bde99b7e1d7a.png',
         "job_icon": 'DNC',
         "level": '70',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Начинает танец, накладывая на персонажа эффект Technical Step.<br/>Продолжительность: 15 сек.<br/>Умение сменяется на Technical Finish во время танца.<br/>Только умения Technical Step, En Avant, Curing Waltz, Shield Samba, step умения, ролевые умения, ускорение (sprint), and лимит брейк (Limit Break) могут использоваться во время танца.<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями. После использования этого умения время восстановления будет применено ко всем остальным боевым навыкам и магическим умениям.',
      },
      // PVE Skill 21
      "PVE Skill 21": {
         "name": 'Technical Finish',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4fa04453ce7de1db88f05bd6f931d489961cc6b1.png',
         "job_icon": 'DNC',
         "level": '70',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '15y',
         "content": 'Удар, наносящий урон по всем ближайшим противникам в радиусе 15 ялмов. Сила атаки умения варьируется в зависимости от количества успешно сделанных steps, нанося полный урон первому противнику, и на 75% меньше остальным.<br/>0 Steps: 350<br/>1 Step: 540<br/>2 Steps: 720<br/>3 Steps: 900<br/>4 Steps: 1,300<br/>Бонус Step: накладывает эффект Technical Finish и Esprit на персонажа и ближайших сопартийцев в радиусе 30 ялмов<br/>Бонус урона от Technical Finish зависит от количества успешно выполненных steps.<br/>1 Step: 1%<br/>2 Steps: 2%<br/>3 Steps: 3%<br/>4 Steps: 5%<br/>Продолжительность: 20 сек.<br/>Дополнительный эффект: накладывает эффект Flourishing Finish<br/>Продолжительность: 30 сек.<br/>Дополнительный эффект: накладывает эффект Dance of the Dawn Ready<br/>Продолжительность: 30 сек.<br/>Может использоваться только во время Dancing.<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями.<br/>После использования этого умения время восстановления будет применено ко всем остальным боевым навыкам и магическим умениям.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Technical Step меняется на Technical Finish при соблюдении требований к выполнению.',
      },
      // PVE Skill 22
      "PVE Skill 22": {
         "name": 'Flourish',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ae6211655f643d512199cf8596bed5c379a53063.png',
         "job_icon": 'DNC',
         "level": '72',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Накладывает эффекты Flourishing Symmetry, Flourishing Flow, Threefold Fan Dance, Fourfold Fan Dance и Finishing Move Ready.<br/>Продолжительность: 30 сек.<br/>Может быть использовано только в бою.',
      },
      // PVE Skill 23
      "PVE Skill 23": {
         "name": 'Saber Dance',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/88cfba4c4fe50b5ad841ac5d34679ab96fd5ff13.png',
         "job_icon": 'DNC',
         "level": '76',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон по цели и всем противникам с силой атаки 520 для первого противника и на 50% меньше для всех остальных.<br/>Стоимость: 50 Esprit Gauge',
      },
      // PVE Skill 24
      "PVE Skill 24": {
         "name": 'Improvisation',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/837e2a8d2f6c135ea8aaa20630487d15967465c8.png',
         "job_icon": 'DNC',
         "level": '80',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '8y',
         "content": 'Танец под собственный ритм, накладывающий эффект Rising Rhythm на персонажа.<br/>Стаки накладываются каждые 3 секунды, вплоть до 4.<br/>Дополнительный эффект: накладывает периодическое лечение на персонажа и ближайших сопартийцев<br/>Сила лечения: 100<br/>Продолжительность: 15 сек.<br/>Эффект спадет при использовании умений или перемещении персонажа (включая разворот в другие стороны).<br/>Прерывает авто атаки при использовании умения.',
      },
      // PVE Skill 25
      "PVE Skill 25": {
         "name": 'Improvised Finish',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c32da2126ef617153a8aa7401324d80bdb564ae2.png',
         "job_icon": 'DNC',
         "level": '80',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '8y',
         "content": 'Создает барьер вокруг персонажа и ближайших сопартийцев. Поглощаемый урон увеличивается в зависимости от стаков Rising Rhythm.<br/>0 стаков: 5% от максимального HP<br/>1 стак: 6% от максимального HP<br/>2 стака: 7% от максимального HP<br/>3 стека: 8% от максимального HP<br/>4 стака: 10% от максимального HP<br/>Продолжительность: 30 сек.<br/>Может быть выполнено только при использовании Improvisation.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Improvisation меняется на Improvised Finish при соблюдении требований к выполнению.',
      },
      // PVE Skill 26
      "PVE Skill 26": {
         "name": 'Tillana',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/013e279b45dd499fdedb71be99ba844a65150da8.png',
         "job_icon": 'DNC',
         "level": '82',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '15y',
         "content": 'Удар, наносящий урон по всем ближайшим противникам с силой атаки 600 для первого и на 50% меньше для всех остальных.<br/>Дополнительный эффект: накладывает Standard Finish и Esprit на персонажа и выбранного сопартийца, который выбран как Dance Partner<br/>Эффект Standard Finish: увеличивает наносимый урон на 5%<br/>Продолжительность: 60 сек.<br/>Может быть выполнено только под действием эффекта Flourishing Finish.<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями. После использования этого умения время восстановления будет применено ко всем остальным боевым навыкам и магическим умениям.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Technical Finish меняется на Improvised Tillana при соблюдении требований к выполнению.',
      },
      // PVE Skill 27
      "PVE Skill 27": {
         "name": 'Fan Dance IV',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/0ff359ea16721e9cf04e2af49dbcad4bc2f23bf7.png',
         "job_icon": 'DNC',
         "level": '86',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '15y',
         "radius_img": 'R4',
         "radius": '15y',
         "content": 'Удар, наносящий урон по всем противникам в конусе перед персонажем с силой атаки 300 для первого и на 50% меньше для всех остальных.<br/>Может использоваться только под действием эффекта Fourfold Fan Dance.',
      },
      // PVE Skill 28
      "PVE Skill 28": {
         "name": 'Starfall Dance',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/027a3d59d160a17f7568069fe25324c61bc4ee13.png',
         "job_icon": 'DNC',
         "level": '90',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '25y',
         "radius_img": 'R6',
         "radius": '25y',
         "content": 'Удар, наносящий критический (critical) прямой (direct) урон по всем противникам по прямой линии перед персонажем с силой атаки 600 для первого противника и на 75% меньше для всех остальных.<br/>Наносимый урон увеличивается под действием эффектов, повышающих вероятность критического (critical) и прямого (direct) урона.<br/>Может использоваться только под действием эффекта Flourishing Starfall.',
      },
      // PVE Skill 29 NEW
      "PVE Skill 29": {
         "name": 'Last Dance',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4928175718cd6dcb3f4e39eccea94c7c2fd6f595.png',
         "job_icon": 'DNC',
         "level": '92',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон по цели и всем ближайшим противникам с силой атаки 520 для первого и на 50% меньше для всех остальных.<br/>Может использоваться только под эффектом Last Dance Ready.',
      },
      // PVE Skill 30 NEW
      "PVE Skill 30": {
         "name": 'Finishing Move',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/8b85962f58aaef35ad086a228b5fb12584fc6e0d.png',
         "job_icon": 'DNC',
         "level": '96',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '30 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '15y',
         "content": 'Удар, наносящий урон по всем ближайшим противникам с силой атаки 820 для первого и на 75% меньше для всех остальных.<br/>Дополнительный эффект: накладывает эффект Standard Finish и Esprit на персонажа и выбранного сопартийца, который выбран как Dance Partner<br/>Эффект Standard Finish: увеличивает наносимый урон на 5%<br/>Продолжительность: 60 сек.<br/>Дополнительный эффект: накладывает эффект Last Dance Ready<br/>Продолжительность: 30 сек.<br/>Может быть выполнено только под действием эффекта Finishing Move Ready.<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями. После использования этого умения время восстановления будет применено ко всем остальным боевым навыкам и магическим умениям.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Standard Step меняется на Finishing Move при соблюдении требований к выполнению.',
      },
      // PVE Skill 31 NEW
      "PVE Skill 31": {
         "name": 'Dance of the Dawn',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a4c8408be6396477a003a90a573bc23c141b54a6.png',
         "job_icon": 'DNC',
         "level": '100',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон по цели и всем ближайшим противникам с силой атаки 1,000 для первого и на 50% меньше для всех остальных.<br/>Стоимость Esprit Gauge: 50<br/>Может использоваться только под эффектом Dance of the Dawn Ready.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Saber Dance меняется на Dance of the Dawn при соблюдении требований к выполнению.',
      },
      // Step Actions 01
      "Step Actions 01": {
         "name": 'Emboite',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d953ffb6694914914ec78257c3f0b1f7039d57e6.png',
         "job_icon": 'DNC',
         "level": '15',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Исполняет Emboite.<br/>При последовательном использовании с другими step умениями, сила атаки Standard Finish и Technical Finish увеличится.<br/>Может использоваться только во время Dancing.<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями. После использования этого умения время восстановления будет применено ко всем остальным боевым навыкам и магическим умениям.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Cascade и Windmill меняется на Emboite при соблюдении требований к выполнению.',
      },
      // Step Actions 02
      "Step Actions 02": {
         "name": 'Entrechat',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e3b6714319b3125e5fbab101fe2944821c2e23c6.png',
         "job_icon": 'DNC',
         "level": '15',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Исполняет Entrechat.<br/>При последовательном использовании с другими step умениями, сила атаки Standard Finish и Technical Finish увеличится.<br/>Может использоваться только во время Dancing.<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями. После использования этого умения время восстановления будет применено ко всем остальным боевым навыкам и магическим умениям.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Fountain и Bladeshower меняется на Entrechat при соблюдении требований к выполнению.',
      },
      // Step Actions 03
      "Step Actions 03": {
         "name": 'Jete',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e80edc2d0bbfa228d89dabef2e14dc81d234a343.png',
         "job_icon": 'DNC',
         "level": '15',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Исполняет Jete.<br/>При последовательном использовании с другими step умениями, сила атаки Standard Finish и Technical Finish увеличится.<br/>Может использоваться только во время Dancing.<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями. После использования этого умения время восстановления будет применено ко всем остальным боевым навыкам и магическим умениям.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Reverse Cascade и Rising Windmill меняется на Jete при соблюдении требований к выполнению.',
      },
      // Step Actions 04
      "Step Actions 04": {
         "name": 'Pirouette',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/8ca01b65d44ad053609372bdb5f7c3dc621ce218.png',
         "job_icon": 'DNC',
         "level": '15',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Исполняет Pirouette.<br/>При последовательном использовании с другими step умениями, сила атаки Standard Finish и Technical Finish увеличится.<br/>Может использоваться только во время Dancing.<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями. После использования этого умения время восстановления будет применено ко всем остальным боевым навыкам и магическим умениям.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Fountainfall и Bloodshower меняется на Pirouette при соблюдении требований к выполнению.',
      },
      // Trait 01
      "Trait 01": {
         "name": 'Fourfold Fantasy',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2dc0608544b9e3c17af5a660aa0f444117b70830.png',
         "job_icon": 'DNC',
         "level": '30',
         "content": 'Накладывает Fourfold Feather после использования определенных умений.<br/>Максимум стаков: 4',
      },
      // Trait 02
      "Trait 02": {
         "name": 'Increased Action Damage',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ba2c0a977d0288d7367454315e83b824134f5a17.png',
         "job_icon": 'DNC',
         "level": '50',
         "content": 'Увеличивает базовый урон умений на 10%.',
      },
      // Trait 03
      "Trait 03": {
         "name": 'Increased Action Damage II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c0784d72b68ee37b055564c375803d05068bc548.png',
         "job_icon": 'DNC',
         "level": '60',
         "content": 'Увеличивает базовый урон умений на 20%.',
      },
      // Trait 04
      "Trait 04": {
         "name": 'Enhanced En Avant',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7ebcb675b09761d30eaf97b73bb1d99a87a5a55e.png',
         "job_icon": 'DNC',
         "level": '68',
         "content": 'Позволяет накапливать заряды для последовательного использования En Avant.<br/>Максимум зарядов: 2',
      },
      // Trait 05
      "Trait 05": {
         "name": 'Esprit',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e33f0e11c737999656fad322e77fcfe4585d077e.png',
         "job_icon": 'DNC',
         "level": '76',
         "content": 'Накладывает Esprit на персонажа и ближайших сопартийцев после успешного использования Standard Finish или Technical Finish. <br/>Эффект Esprit: при успешном использовании Cascade, Reverse Cascade, Fountain, Fountainfall, Windmill, Rising Windmill, Bladeshower ил Bloodshower шкала Esprit Gauge восполняется на 5.<br/>Шкала Esprit Gauge будет восполняться на 10, когда ваши сопартийцы под эффектом Esprit будут успешно использовать боевые навыки или заклинания.<br/>Шанс срабатывания эффекта для сопартийцев зависит от их профессии.',
      },
      // Trait 06
      "Trait 06": {
         "name": 'Enhanced En Avant II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/68df331c6193bcc50048021dc3cf811d4959893d.png',
         "job_icon": 'DNC',
         "level": '78',
         "content": 'Позволяет накапливать третий заряд En Avant.',
      },
      // Trait 07
      "Trait 07": {
         "name": 'Enhanced Technical Finish',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7ba1f0f663c32b481f06ebb833e26be063d6ebf0.png',
         "job_icon": 'DNC',
         "level": '82',
         "content": 'Накладывает эффект Flourishing Finish после использования Technical Finish.<br/>Продолжительность: 30 сек.<br/>Technical Finish заменяется на Tillana под действием эффекта.',
      },
      // Trait 08
      "Trait 08": {
         "name": 'Enhanced Esprit',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/24c75407f6abb4b9038f781ff9638ad0c0f966ef.png',
         "job_icon": 'DNC',
         "level": '84',
         "content": 'Восполняет шкалу Esprit Gauge на 10 при успешном использовании Reverse Cascade, Fountainfall, Rising Windmill или Bloodshower.',
      },
      // Trait 09
      "Trait 09": {
         "name": 'Enhanced Flourish',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/bcb3f5f1bc3c616a6c14ca1c0276c358d73f14d5.png',
         "job_icon": 'DNC',
         "level": '86',
         "content": 'Накладывает Fourfold Fan Dance после использования Flourish.<br/>Продолжительность: 30 сек.',
      },
      // Trait 10
      "Trait 10": {
         "name": 'Enhanced Shield Samba',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e20ca0fddbcde430a07709e4b7ba314d9fac4519.png',
         "job_icon": 'DNC',
         "level": '88',
         "content": 'Сокращает время восстановления Shield Samba до 90 сек.',
      },
      // Trait 11
      "Trait 11": {
         "name": 'Enhanced Devilment',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/10e6b71bfc8ca885dcc031770d2dbfce750fa115.png',
         "job_icon": 'DNC',
         "level": '90',
         "content": 'Накладывает эффект Flourishing Starfall после использования Devilment.<br/>Продолжительность: 20 сек.',
      },
      // Trait 12 NEW
      "Trait 12": {
         "name": 'Enhanced Standard Finish',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/61f7797649fc9a916295e3bf5e7cff0d77da5954.png',
         "job_icon": 'DNC',
         "level": '92',
         "content": 'Накладывает эффект Last Dance Ready после использования Standard Finish.<br/>Продолжительность: 30 сек.',
      },
      // Trait 13 NEW
      "Trait 13": {
         "name": 'Dynamic Dancer',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4c948f409f459cc6cc4983962f78d071f06ef5b8.png',
         "job_icon": 'DNC',
         "level": '94',
         "content": 'Увеличивает силу атаки Cascade до 220, Fountain до 120, Reverse Cascade до 280, Fountainfall до 340, Double Standard Finish до 850, Quadruple Technical Finish до 1,300 и Saber Dance до 520.',
      },
      // Trait 14 NEW
      "Trait 14": {
         "name": 'Enhanced Flourish II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/755e03aa52e57a1f2e5b6796e74a6ce0be288e1d.png',
         "job_icon": 'DNC',
         "level": '96',
         "content": 'Накладывает эффект Finishing Move Ready после использования Flourish.<br/>Продолжительность: 30 сек.<br/>Standard Step меняется на Finishing Move под действием эффекта Finishing Move Ready.',
      },
      // Trait 15 NEW
      "Trait 15": {
         "name": 'Enhanced Shield Samba II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/198ae66af1422a784316aebe385e4a4e69d5694b.png',
         "job_icon": 'DNC',
         "level": '98',
         "content": 'Увеличивает эффективность снижения урона Shield Samba до 15%.',
      },
      // Trait 16 NEW
      "Trait 16": {
         "name": 'Enhanced Technical Finish II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4331a113b8c8cf86ebf54913cf3998201c719ae6.png',
         "job_icon": 'DNC',
         "level": '100',
         "content": 'Накладывает эффект Dance of the Dawn Ready после использования Technical Finish.<br/>Продолжительность: 30 сек.<br/>Saber Dance меняется на Dance of the Dawn под действием эффекта Dance of the Dawn Ready и шкала Esprit Gauge равна 50 или выше.',
      },
      // PVP Skill 01
      "PVP Skill 01": {
         "name": 'Cascade',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/0438e84e65435d300b345c5de777c34e20847983.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.2 сек.',
         "range": '15y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Дальний удар, наносящий урон с силой атаки 3,000.<br/><br/>※Умение меняется на Reverse Cascade под действием эффекта En Avant.<br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 02
      "PVP Skill 02": {
         "name": 'Fountain',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b89b3e26b00ad1f3f2e34bfe58bf3f6ef6ae6cd9.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.2 сек.',
         "range": '15y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Дальний удар, наносящий урон с силой атаки 5,000.<br/>Комбо умение: Cascade или Reverse Cascade<br/><br/>※Умение меняется на Fountainfall под действием эффекта En Avant.<br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 03
      "PVP Skill 03": {
         "name": 'Starfall Dance',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/8619c1a93719a934576b062297009ae6af83ec46.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '25y',
         "radius_img": 'R6',
         "radius": '25y',
         "content": 'Удар, наносящий урон по всем противникам по прямой линии перед персонажем с силой атаки 10,000.<br/>Дополнительный эффект: уменьшает время применения и восстановления боевых навыков, заклинаний для персонажа и сопартийца, выбранного Dance Partner на 10%<br/>Продолжительность: 10 сек.<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями.',
      },
      // PVP Skill 04
      "PVP Skill 04": {
         "name": 'Honing Dance',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/cecaa07a349b4c21c5645a3b3527e6bddfcdd76e.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Проводит серию ударов чакрамами по ближайшим противникам, нанося периодический урон с силой атаки 4,000 и снижая получаемый урон на 25% до окончания действия эффекта.<br/>Продолжительность: 3 сек.<br/>Использует Honing Ovation по истечении срока действия эффекта.<br/>Дополнительный эффект: накладывает стак Acclaim, вплоть до 4<br/>Эффект Acclaim: увеличивает урон и силу эффекта Honing Ovation<br/>Продолжительность: 5 сек.<br/>Может быть использовано во время движения.<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями.<br/><br/>※При использовании умение меняется на Honing Ovation.',
      },
      // PVP Skill 05
      "PVP Skill 05": {
         "name": 'Fan Dance',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e703a26adff2f9c1061ca1b8a05ba0da5a1ccc69.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '15y',
         "radius_img": 'R4',
         "radius": '15y',
         "content": 'Удар, наносящий урон по всем противникам в конусе перед персонажем с силой атаки 5,000.<br/>Дополнительный эффект: снижает урон, получаемый персонажем и сопартийцем, выбранным Dance Partner на 10%<br/>Продолжительность: 10 сек.',
      },
      // PVP Skill 06
      "PVP Skill 06": {
         "name": 'Curing Waltz',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/29bc9e646f24cf83364965086b2278361f6d1515.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '3y',
         "content": 'Восстанавливает HP персонажа и ближайших сопартийцев.<br/>Сила лечения: 10,000<br/>Дополнительный эффект: сопартиец, отмеченный как Dance Partner, также будет лечить себя и ближайших сопартийцев.',
      },
      // PVP Skill 07
      "PVP Skill 07": {
         "name": 'En Avant',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ba6a5ba3fa6a69c17a7971e18387a3485322b087.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Рывок на 10 ялмов вперед.<br/>Дополнительный эффект: накладывает эффект En Avant<br/>Продолжительность: 10 сек<br/>Максимум зарядов: 4<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.',
      },
      // PVP Skill 08
      "PVP Skill 08": {
         "name": 'Closed Position',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/3f8ab05d4c5ad09461eac1d129eb4df7c03278ee.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Накладывает на персонажа Closed Position и назначает выбранного сопартийца Dance Partner, позволяя разделять с ним эффекты Saber Dance, Starfall Dance, Fan Dance и Curing Waltz.<br/>Эффект спадает при повторном использовании.',
      },
      // PVP Skill 09
      "PVP Skill 09": {
         "name": 'Reverse Cascade',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/aa56ad7f967a949f7c941f76bfca65d77831c5fc.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.2 сек.',
         "range": '15y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Дальний удар, наносящий урон с силой атаки 6,000.<br/>Дополнительный эффект: накладывает эффект Bladecatcher<br/>Если на персонажа уже действует эффект Bladecatcher, он меняется на Flourishing Saber Dance.<br/>Продолжительность: 15 сек.<br/>Может быть использовано только под действием эффекта En Avant.<br/><br/>※Fountain Combo меняется на Saber Dance под действием эффекта Flourishing Saber Dance.<br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 10
      "PVP Skill 10": {
         "name": 'Fountainfall',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b8b5608b6f10d1e782447e3b9a9e87b2022f6886.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.2 сек.',
         "range": '15y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Дальний удар, наносящий урон с силой атаки 8,000.<br/>Комбо умение: Cascade или Reverse Cascade<br/>Дополнительный эффект: накладывает эффект Bladecatcher<br/>Если на персонажа уже действует эффект Bladecatcher, он меняется на Flourishing Saber Dance.<br/>Продолжительность: 15 сек.<br/>Может быть использовано только под действием эффекта En Avant.<br/><br/>※Fountain Combo меняется на Saber Dance под действием эффекта Flourishing Saber Dance.<br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 11
      "PVP Skill 11": {
         "name": 'Saber Dance',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/0a5e6ed048ddc25735cbe4ece188628329790146.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.2 сек.',
         "range": '15y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 10,000 по цели и всем ближайшим противникам.<br/>Сила атаки увеличивается на 50%, если персонаж атакуете только одну цель.<br/>Дополнительный эффект: увеличивает урон, наносимый персонажем и сопартийцем, выбранный Dance Partner на 10%<br/>Продолжительность: 10 сек.<br/>Может быть использовано только под действием эффекта Flourishing Saber Dance.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 12
      "PVP Skill 12": {
         "name": 'Honing Ovation',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/6f694039fa153206117e9a789a78cd6443f93fc4.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.2 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '15y',
         "content": 'Наносит урон ближайшим противникам и создает магический барьер вокруг ближайших сопартийцев.<br/>Сила атаки и барьера зависит от количества стаков Acclaim, накопленных на момент использования.<br/>Сила атаки и барьера удваивается, если цель находится в пределах 5 ялмов.<br/>0 стаков: 2,000 силы атаки и барьер, равный силе лечения 1,000<br/>1 стак: 3,000 силы атаки и барьер, равный силе лечения 2,000<br/>2 стака: 4,000 силы атаки и барьер, равный силе лечения 3,000<br/>3 стака: 5,000 силы атаки и барьер, равный силе лечения 4,000 <br/>4 стака: 6,000 силы атаки и барьер, равный силе лечения 5,000<br/>Продолжительность: 10 сек.<br/>Эффект Honing Dance истекает после использования.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 13
      "PVP Skill 13": {
         "name": 'Contradance',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/8389226ba5e7eab65952af115123a4db1357a03c.png',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '15y',
         "content": 'Очаровывает ближайших врагов.<br/>Продолжительность: 2 сек.<br/>Урон, нанесенный очарованным врагам, продлевает длительность эффекта на 2 сек. Этот эффект можно продлить только один раз.<br/>Может быть использовано только тогда, когда шкала лимит брейка (limit gauge) заполнена.<br/>Время зарядки шкалы: 90 сек.',
      },
   };
   FILL_DB_VALUES(db);
   FILL_DB_SKILLS(db);
   FILL_DB_SKILLS_PASSIVE(db);
   FILL_DB_SKILLS_PVP(db);
   FILL_DB_SKILLS_MENU(db);
})();