(() =>{
   let db = {
      "PVE Update": `Последнее обновление: 27/06/2024`,
      "PVP Update": `Последнее обновление: 27/06/2024`,
      // PVE Skill 01
      "PVE Skill 01": {
         "name": 'Split Shot',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/8060c2f198141fb9c4d4202e298c212c15a82e88.png',
         "job_icon": 'MCH',
         "level": '1',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 140.<br/>Дополнительный эффект: восполняет Heat Gauge на 5',
      },
      // PVE Skill 02
      "PVE Skill 02": {
         "name": 'Slug Shot',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/63bb059658f193d08de8cd45e4a95e7bed0418b8.png',
         "job_icon": 'MCH',
         "level": '2',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 100.<br/>Комбо умение: Split Shot или Heated Split Shot<br/>Сила в комбо: 210<br/>Комбо бонус: восполняет Heat Gauge на 5',
      },
      // PVE Skill 03
      "PVE Skill 03": {
         "name": 'Hot Shot',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b297b6034baa7347d3a53a12910b102914ce3c3e.png',
         "job_icon": 'MCH',
         "level": '4',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '40 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 240.<br/>Дополнительный эффект: восполняет Battery Gauge на 20<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями.',
      },
      // PVE Skill 04
      "PVE Skill 04": {
         "name": 'Reassemble',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/55906cd43fffdf7bcc09790b1b02b19edc6b2e8e.png',
         "job_icon": 'MCH',
         "level": '10',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '55 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Следующий боевой навык гарантированно получит эффект критического (critical) прямого (direct) удара.<br/>Продолжительность: 5 сек.<br/>Наносимый урон увеличивается под действием эффектов, повышающего вероятность критического (critical) или прямого (direct) урона.<br/>Это умение не влияет на периодический урон.<br/>Максимум зарядов: 2',
      },
      // PVE Skill 05
      "PVE Skill 05": {
         "name": 'Gauss Round',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e6959a3306b601fc9e5987712f6d9ea247a7a566.png',
         "job_icon": 'MCH',
         "level": '15',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '30 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 130.<br/>Максимум зарядов: 3',
      },
      // PVE Skill 06
      "PVE Skill 06": {
         "name": 'Spread Shot',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7c4e991ed4e6b585ceb2dda1c03dec0278ff28f0.png',
         "job_icon": 'MCH',
         "level": '18',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '12y',
         "radius_img": 'R4',
         "radius": '12y',
         "content": 'Удар, наносящий урон с силой атаки 140 по всем противникам в конусе перед персонажем.<br/>Дополнительный эффект: восполняет Heat Gauge на 5',
      },
      // PVE Skill 07
      "PVE Skill 07": {
         "name": 'Clean Shot',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d6d762f987ab51e9840cbf5229251838b16078b5.png',
         "job_icon": 'MCH',
         "level": '26',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 100.<br/>Комбо умение: Slug Shot или Heated Slug Shot<br/>Сила в комбо: 270<br/>Комбо бонус: восполняет Heat Gauge на 5<br/>Комбо бонус: восполняет Battery Gauge на 10',
      },
      // PVE Skill 08
      "PVE Skill 08": {
         "name": 'Hypercharge',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/e67ae514847/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/273150b6ebb3357688de07d86ec37a02da8e9348.png',
         "job_icon": 'MCH',
         "level": '30',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Накладывает 5 стаков Overheated, каждый из которых позволяет использовать Blazing Shot или Auto Crossbow.<br/>Продолжительность: 10 сек.<br/>Эффект Overheated: увеличивает силу атаки боевых навыков по одной цели на 20<br/>Стоимость Heat Gauge: 50<br/>Эффект Overheated распространяется только на умения машиниста.',
      },
      // PVE Skill 09
      "PVE Skill 09": {
         "name": 'Heat Blast',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/618ec7eb4bb/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/009d06297b1776f1404cdf4de9c5bd8b17a447e6.png',
         "job_icon": 'MCH',
         "level": '35',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 200.<br/>Дополнительный эффект: снижает время восстановления Gauss Round и Richochet на 15 сек.<br/>Может использоваться только под эффектом Overheated.<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями. После использования этого умения время восстановления будет применено ко всем остальным боевым навыкам и магическим умениям.',
      },
      // PVE Skill 10
      "PVE Skill 10": {
         "name": 'Rook Autoturret',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/6ef1ac08680/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5b7c9667f3dca5facbc020d4ab7743c7f9d4e6d9.png',
         "job_icon": 'MCH',
         "level": '40',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '6 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Развертывает боевую турель, которая будет наносить атаки по одиночной цели, используя Volley Fire с силой атаки 35.<br/>Сила атаки увеличивается пропорционально расходу шкалы Battery Gauge и достигает 75 при максимальном значении.<br/>Стоимость Battery Gauge: 50<br/>Продолжительность: 9 сек.<br/>Расходует Battery Gauge в процессе использования.<br/>Отключается, если истечет время умения или после запуска Rook Overdrive.<br/>Имеет общее время восстановления с умением Rook Overdrive.',
      },
      // PVE Skill 11
      "PVE Skill 11": {
         "name": 'Rook Overdrive',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d02c5a123e15d77891887c24dce2f6f21d92852d.png',
         "job_icon": 'MCH',
         "level": '40',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Отправляет команду вашей боевой турели (Rook Autoturret) использовать Rook Overload.<br/>Сила атаки Rook Overload: 160<br/>Сила атаки увеличивается пропорционально расходу шкалы Battery Gauge и достигает 320 при максимальном значении.<br/>Отключается после использования умения.<br/>Если умение не было использовано, пока турель активна, оно сработает автоматически непосредственно перед отключением.<br/>Имеет общее время восстановления с умением Rook Autoturret.',
      },
      // PVE Skill 12
      "PVE Skill 12": {
         "name": 'Rook Overload',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/0458a11999934b3eb6d4088c941329698c898722.png',
         "job_icon": 'MCH',
         "level": '40',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '-',
         "range": '40y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 160.<br/>Сила атаки увеличивается пропорционально расходу шкалы Battery Gauge и достигает 320 при максимальном значении.<br/>Отключается после использования умения. Если умение не было использовано, пока турель активна, оно сработает автоматически непосредственно перед отключением.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 13
      "PVE Skill 13": {
         "name": 'Wildfire',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/6d73e45fbbfb35ad0a4f8b4a73753e6a06a37651.png',
         "job_icon": 'MCH',
         "level": '45',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Окутывает цель медленно горящим огнем, накладывая эффект Wildfire. Умение заменяется на Detonator на время действия эффекта.<br/>Наносит урон по истечении времени или после использования умения Detonator.<br/>Сила атаки умения увеличивается на 240 за каждый боевой навык персонажа, который будет успешно применен на цель до окончания эффекта.<br/>Может накапливаться до 6 раз.<br/>Продолжительность: 10 сек.',
      },
      // PVE Skill 14
      "PVE Skill 14": {
         "name": 'Detonator',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d342968f8a04290200386a016f586a0b175e3d3b.png',
         "job_icon": 'MCH',
         "level": '45',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Заканчивает действие эффекта Wildfire, нанося урон цели.<br/>Можно использовать только под действием эффекта Wildfire.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Wildfire меняется на Detonator при соблюдении требований к выполнению.',
      },
      // PVE Skill 15
      "PVE Skill 15": {
         "name": 'Ricochet',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/8009173f2c1/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5556960a2e8ce389c2117d13c6d182f41943c3c9.png',
         "job_icon": 'MCH',
         "level": '50',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '30 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон по всем ближайшим противникам с силой атаки 130 для первого и на 50% меньше для всех остальных.<br/>Максимум зарядов: 3',
      },
      // PVE Skill 16
      "PVE Skill 16": {
         "name": 'Auto Crossbow',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/dec97d20aae/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/8c8ae8bf5d1dbcae1bf932cfed578e4fda8d80f3.png',
         "job_icon": 'MCH',
         "level": '52',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "range": '12y',
         "radius_img": 'R4',
         "radius": '12y',
         "content": 'Удар, наносящий урон с силой атаки 160 по всем противникам в конусе перед персонажем.<br/>Может использоваться только под эффектом Overheated.<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями. После использования этого умения время восстановления будет применено ко всем остальным боевым навыкам и магическим умениям.',
      },
      // PVE Skill 17
      "PVE Skill 17": {
         "name": 'Heated Split Shot',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/708447cc2e7/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c7fb786ed29dd5618309e36b58105dd329f255fa.png',
         "job_icon": 'MCH',
         "level": '54',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 220.<br/>Дополнительный эффект: восполняет Heat Gauge на 5',
      },
      // PVE Skill 18
      "PVE Skill 18": {
         "name": 'Tactician',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/fac8668168e/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/eb334bf6f4cfd728e234e09c1cc1521c37d9d73e.png',
         "job_icon": 'MCH',
         "level": '56',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '90 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '30y',
         "content": 'Снижает урон получаемый персонажем и сопартийцами на 15%.<br/>Продолжительность: 15 сек.<br/>Эффект не суммируется с умение Troubadour барда или Shield Samba дансера.',
      },
      // PVE Skill 19
      "PVE Skill 19": {
         "name": 'Drill',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/1f28f88b934/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c8bd9fe712521ac377c3359846437a640c0516b7.png',
         "job_icon": 'MCH',
         "level": '58',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 660.<br/>Максимум зарядов: 2<br/>Имеет общее время восстановления с умением Bioblaster.',
      },
      // PVE Skill 20
      "PVE Skill 20": {
         "name": 'Heated Slug Shot',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/74fe228d7b6/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7f91784177366a8b4dd069a15915b41601231f83.png',
         "job_icon": 'MCH',
         "level": '60',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 140.<br/>Комбо умение: Heated Split Shot<br/>Сила в комбо: 320<br/>Комбо бонус: восполняет Heat Gauge на 5',
      },
      // PVE Skill 21
      "PVE Skill 21": {
         "name": 'Dismantle',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/94eaa7aadfa4d857c00551af690f42bb5d7a4a94.png',
         "job_icon": 'MCH',
         "level": '62',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Снижает наносимый целью урон на 10%.<br/>Продолжительность: 10 сек.',
      },
      // PVE Skill 22
      "PVE Skill 22": {
         "name": 'Heated Clean Shot',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/3c8cababe00b6d512baada3b68a32cb866758a17.png',
         "job_icon": 'MCH',
         "level": '64',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 140.<br/>Комбо умение: Heated Slug Shot<br/>Сила в комбо: 400<br/>Комбо бонус: восполняет Heat Gauge на 5<br/>Комбо бонус: восполняет Battery Gauge на 10',
      },
      // PVE Skill 23
      "PVE Skill 23": {
         "name": 'Barrel Stabilizer',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1688057a6b4150542d3c41e9e5202cf5aa14b5b7.png',
         "job_icon": 'MCH',
         "level": '66',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Накладывает эффект Hypercharged.<br/>Продолжительность: 30 сек.<br/>Дополнительный эффект: накладывает эффект Full Metal Machinist<br/>Продолжительность: 30 сек.<br/>Может быть использовано только в бою.',
      },
      // PVE Skill 24 NEW
      "PVE Skill 24": {
         "name": 'Blazing Shot',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c70341dbb174a9c43c76249ae4b7c40aefbbf40a.png',
         "job_icon": 'MCH',
         "level": '68',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 220.<br/>Дополнительный эффект: уменьшает время повторного применения Double Check и Checkmate на 15 сек.<br/>Может быть выполнено только при перегреве огнестрельного оружия.<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями.<br/>После использования этого умения время восстановления будет применено ко всем остальным боевым навыкам и магическим умениям.',
      },
      // PVE Skill 25
      "PVE Skill 25": {
         "name": 'Flamethrower',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/07e9b7dbdb8/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/37f5418d1629e6ebc93161622a271d14aa82464e.png',
         "job_icon": 'MCH',
         "level": '70',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "range": '0y',
         "radius_img": 'R4',
         "radius": '8y',
         "content": 'Наносит периодический урон по всем противникам в конусе перед персонажем.<br/>Сила атаки: 80<br/>Продолжительность: 10 сек.<br/>Умение прервется при использовании умений или перемещении персонажа (включая разворот в другие стороны).<br/>Прерывает авто атаки при использовании умения.<br/>Запускает время восстановления боевых навыков после использования. Не может использоваться во время восстановления боевых навыков.',
      },
      // PVE Skill 26
      "PVE Skill 26": {
         "name": 'Bioblaster',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/193879ae7c68f4e144e385a018c69e3626dfa569.png',
         "job_icon": 'MCH',
         "level": '72',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '12y',
         "radius_img": 'R4',
         "radius": '12y',
         "content": 'Удар, наносящий урон с силой атаки 50 по всем противникам в конусе перед персонажем.<br/>Дополнительный эффект: периодический урон<br/>Сила атаки: 50<br/>Продолжительность: 15 сек.<br/>Максимум зарядов: 2<br/>Имеет общее время восстановления с умением Drill.',
      },
      // PVE Skill 27
      "PVE Skill 27": {
         "name": 'Air Anchor',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/85abf6ce8fa5c7b7bda98e11f37df0e8c024015e.png',
         "job_icon": 'MCH',
         "level": '76',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '40 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 600.<br/>Дополнительный эффект: восполняет шкалу Battery Gauge на 20<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями.',
      },
      // PVE Skill 28
      "PVE Skill 28": {
         "name": 'Automaton Queen',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e27f4ccdaad09197dbb5c06734c52bd2e4b4af06.png',
         "job_icon": 'MCH',
         "level": '80',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '6 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Призывает Automaton Queen, которая сражается на стороне персонажа.<br/>Сила атаки увеличивается пропорционально расходу шкалы Battery Gauge, превышает требуемую стоимость на момент развертывания.<br/>Стоимость Battery Gauge: 50<br/>Продолжительность: 12 сек.<br/>Расходует Battery Gauge в процессе использования.<br/>Отключается, если истечет время действия, или после запуска Queen Overdrive.<br/>Имеет общее время восстановления с умением Queen Overdrive.',
      },
      // PVE Skill 29
      "PVE Skill 29": {
         "name": 'Queen Overdrive',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1424989e6ca3765da1c9c323ebcf72d0c9ba1536.png',
         "job_icon": 'MCH',
         "level": '80',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Приказывает вашей Automaton Queen использовать Pile Bunker.<br/>Сила атаки Pile Bunker: 340<br/>Сила атаки увеличивается пропорционально расходу шкалы Battery Gauge и достигает 680 при максимальном значении.<br/>Automaton Queen отключается после использования умения. Если умение не было использовано, пока Automaton Queen активна, оно сработает автоматически непосредственно перед отключением.<br/>Имеет общее время восстановления с умением Automaton Queen.',
      },
      // PVE Skill 30
      "PVE Skill 30": {
         "name": 'Arm Punch',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/813737b1502285e729d93645fe816e75350bb1c9.png',
         "job_icon": 'MCH',
         "level": '80',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 120.<br/>Сила атаки увеличивается пропорционально расходу шкалы Battery Gauge и достигает 240 при максимальном значении.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 31
      "PVE Skill 31": {
         "name": 'Roller Dash',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2f01267b74b97a5447bd88cf5a953e532313255a.png',
         "job_icon": 'MCH',
         "level": '80',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '3 сек.',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Рывок к цели и удар, наносящий урон с силой атаки 240.<br/>Сила атаки увеличивается пропорционально расходу шкалы Battery Gauge и достигает 480 при максимальном значении.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 32
      "PVE Skill 32": {
         "name": 'Pile Bunker',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5e8ab4cb384f66e2f6a041ab70923ac104fdab80.png',
         "job_icon": 'MCH',
         "level": '80',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '-',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 340.<br/>Сила атаки увеличивается пропорционально расходу шкалы Battery Gauge и достигает 680 при максимальном значении.<br/>Если умение не было использовано, пока Automaton Queen активна, оно сработает автоматически непосредственно перед отключением.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 33
      "PVE Skill 33": {
         "name": 'Scattergun',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/8cde8fc67f1387b83328aa85cbe044d21a5bc9b0.png',
         "job_icon": 'MCH',
         "level": '82',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '12y',
         "radius_img": 'R4',
         "radius": '12y',
         "content": 'Удар, наносящий урон с силой атаки 160 по всем противникам в конусе перед персонажем.<br/>Дополнительный эффект: восполняет Heat Gauge на 10',
      },
      // PVE Skill 34
      "PVE Skill 34": {
         "name": 'Crowned Collider',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e7dfcf4eb7f3e2cea526372e8edd8732348bc035.png',
         "job_icon": 'MCH',
         "level": '86',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '-',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 390.<br/>Сила атаки увеличивается пропорционально расходу шкалы Battery Gauge и достигает 780 при максимальном значении.<br/>Automaton Queen отключается после использования умения. Если умение не было использовано, пока Automaton Queen активна, оно сработает автоматически непосредственно перед отключением.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 35
      "PVE Skill 35": {
         "name": 'Chain Saw',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2f788128862828a0a36c66d4dcd6f521f8391d04.png',
         "job_icon": 'MCH',
         "level": '90',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "range": '25y',
         "radius_img": 'R6',
         "radius": '25y',
         "content": 'Удар, наносящий урон по всем противникам по прямой линии перед персонажем с силой атаки 600 для первого противника и на 65% меньше для всех остальных.<br/>Дополнительный эффект: восполняет Battery Gauge на 20<br/>Дополнительный эффект: накладывает эффект Excavator Ready<br/>Продолжительность: 30 сек.<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями. ',
      },
      // PVE Skill 36 NEW
      "PVE Skill 36": {
         "name": 'Double Check',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5de8d4517d7e5179cc341ecb2d0bb63e0d716492.png',
         "job_icon": 'MCH',
         "level": '92',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '30 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон по цели и по всем окружающим противникам с силой атаки 160 для первого противника и на 50% меньше для всех остальных.<br/>Максимум зарядов: 3',
      },
      // PVE Skill 37 NEW
      "PVE Skill 37": {
         "name": 'Checkmate',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f44e0b84bfe54b08662b521becbb338225ea90c9.png',
         "job_icon": 'MCH',
         "level": '92',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '30 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон по цели и по всем окружающим противникам с силой атаки 160 для первого противника и на 50% меньше для всех остальных.<br/>Максимум зарядов: 3',
      },
      // PVE Skill 38 NEW
      "PVE Skill 38": {
         "name": 'Excavator',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/6e221fc321a6d40ecac7a908c5b8c144c8c693a3.png',
         "job_icon": 'MCH',
         "level": '96',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон по цели и по всем окружающим противникам с силой атаки 600 для первого противника и на 65% меньше для всех остальных.<br/>Дополнительный эффект: восполняет Battery Gauge на 20<br/>Можно использовать только под действием эффекта Excavator Ready.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Chain Saw меняется на Excavator при соблюдении требований к выполнению.',
      },
      // PVE Skill 39 NEW
      "PVE Skill 39": {
         "name": 'Full Metal Field',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/9c5bb54095373de5764bcfee0205f998f57b986b.png',
         "job_icon": 'MCH',
         "level": '100',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон по цели и по всем окружающим противникам с силой атаки 700 для первого противника и на 50% меньше для всех остальных.<br/>Наносимый урон увеличивается под действием эффектов, повышающего вероятность критического (critical) и прямого (direct) урона.<br/>Можно использовать только под действием эффекта Full Metal Machinist.',
      },
      // Trait 01
      "Trait 01": {
         "name": 'Increased Action Damage',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7a4446670bbb1ae60b4026125c28469c0c32802f.png',
         "job_icon": 'MCH',
         "level": '20',
         "content": 'Увеличивает базовый урон умений и урон турелей на 10%.',
      },
      // Trait 02
      "Trait 02": {
         "name": 'Increased Action Damage II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e58ddf4e9b28be5305924b0a016be89f3e6f5c09.png',
         "job_icon": 'MCH',
         "level": '40',
         "content": 'Увеличивает базовый урон умений и урон турелей на 20%.',
      },
      // Trait 03
      "Trait 03": {
         "name": 'Split Shot Mastery',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/708447cc2e7/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/17e2bfa91c00357867f74f213d54acbdb3eccf9c.png',
         "job_icon": 'MCH',
         "level": '54',
         "content": 'Улучшает умение Split Shot до Heated Split Shot.',
      },
      // Trait 04
      "Trait 04": {
         "name": 'Slug Shot Mastery',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/74fe228d7b6/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/fcfac995467f1b40637328ca1fb2e0f96d3d93fa.png',
         "job_icon": 'MCH',
         "level": '60',
         "content": 'Улучшает умение Slug Shot до Heated Slug Shot.',
      },
      // Trait 05
      "Trait 05": {
         "name": 'Clean Shot Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/22ad0318de7c24159dee74596a7bfe78c1947d3a.png',
         "job_icon": 'MCH',
         "level": '64',
         "content": 'Улучшает умение Clean Shot до Heated Clean Shot.',
      },
      // Trait 06 NEW
      "Trait 06": {
         "name": 'Heat Blast Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/9cccaf0b8870d8d58435d49c1d4af6b97747cb05.png',
         "job_icon": 'MCH',
         "level": '68',
         "content": 'Улучшает умение Heat Blast до Blazing Shot.',
      },
      // Trait 07
      "Trait 07": {
         "name": 'Charged Action Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7c9a0badfb53894c632d694c869e031bceebef88.png',
         "job_icon": 'MCH',
         "level": '74',
         "content": 'Позволяет накапливать 3 заряда Gauss Round и Ricochet.',
      },
      // Trait 08
      "Trait 08": {
         "name": 'Hot Shot Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7973381f2d9c49f26b5b72f9cc370b402359d2a8.png',
         "job_icon": 'MCH',
         "level": '76',
         "content": 'Улучшает умение Hot Shot до Air Anchor.',
      },
      // Trait 09
      "Trait 09": {
         "name": 'Enhanced Wildfire',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ee45320e4da5dfac149b4d204d8b6d300cdc9623.png',
         "job_icon": 'MCH',
         "level": '78',
         "content": 'Увеличивает силу Wildfire за каждый использованный боевой навык до 240.',
      },
      // Trait 10
      "Trait 10": {
         "name": 'Promotion',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7f48e481afe9adde72358481f334754d9bd65016.png',
         "job_icon": 'MCH',
         "level": '80',
         "content": 'Улучшает Rook Autoturret и Rook Overdrive до Automaton Queen и Queen Overdrive.',
      },
      // Trait 11
      "Trait 11": {
         "name": 'Spread Shot Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/733c87787a7829705ddb6e45ecc77afa3a69706f.png',
         "job_icon": 'MCH',
         "level": '82',
         "content": 'Улучшает умение Spread Shot до Scattergun.',
      },
      // Trait 12
      "Trait 12": {
         "name": 'Enhanced Reassemble',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7ea5f5c63a2624cd7f20dc650d5714969117d531.png',
         "job_icon": 'MCH',
         "level": '84',
         "content": 'Позволяет накапливать заряды для последовательного использования Reassemble.<br/>Максимум зарядов: 2',
      },
      // Trait 13
      "Trait 13": {
         "name": "Marksman's Mastery",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/bc58b07072e258883e9e584c4e45355d092da661.png',
         "job_icon": 'MCH',
         "level": '84',
         "content": 'Увеличивает силу атаки Heated Split Shot до 200, Heated Slug Shot до 120 и Heated Clean Shot до 120.',
      },
      // Trait 14
      "Trait 14": {
         "name": "Queen's Gambit",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/bfe38af9b9aebf5a2febaafa0ed4c0867da59a2e.png',
         "job_icon": 'MCH',
         "level": '86',
         "content": 'Automaton Queen, после использования Pile Bunker, также использует Crowned Collider.',
      },
      // Trait 15
      "Trait 15": {
         "name": 'Enhanced Tactician',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/83abb5edaa137fdb0a1665598fbba3d0de804520.png',
         "job_icon": 'MCH',
         "level": '88',
         "content": 'Сокращает время восстановления Tactician до 90 сек.',
      },
      // Trait 16 NEW
      "Trait 16": {
         "name": 'Double-barrel Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d27efc5e828ecabff4d0b45ee10c6e731cc71847.png',
         "job_icon": 'MCH',
         "level": '92',
         "content": 'Улучшает умение Gauss Round до Double Check и Ricochet до Checkmate.',
      },
      // Trait 17 NEW
      "Trait 17": {
         "name": 'Enhanced Multiweapon',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ae9cf4acdbd365202307fbaedd38340a7d0fa94f.png',
         "job_icon": 'MCH',
         "level": '94',
         "content": 'Позволяет накапливать заряды для последовательного использования Drill и Bioblaster.<br/>Максимум зарядов: 2',
      },
      // Trait 18 NEW
      "Trait 18": {
         "name": "Marksman's Mastery II",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b60557edca3b093463f0f0c0c04dc3895855e9f8.png',
         "job_icon": 'MCH',
         "level": '94',
         "content": 'Увеличивает силу атаки Auto Crossbow до 160, Heated Split Shot до 220, Heated Slug Shot до 140, Heated Clean Shot до 140 и Scattergun до 160.',
      },
      // Trait 19 NEW
      "Trait 19": {
         "name": 'Enhanced Multiweapon II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/28f091ab4b400b52cb77f45488cd87386ba45998.png',
         "job_icon": 'MCH',
         "level": '96',
         "content": 'Накладывает эффект Excavator Ready после использования Chain Saw.<br/>Продолжительность: 30 сек.<br/>Chain Saw меняется на Excavator под действием эффекта Excavator Ready.',
      },
      // Trait 20 NEW
      "Trait 20": {
         "name": 'Enhanced Tactician II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a3ae0598316b6300ddb35a842fd49f138d837b8e.png',
         "job_icon": 'MCH',
         "level": '98',
         "content": 'Увеличивает эффективность снижения урона Tactician до 15%.',
      },
      // Trait 21 NEW
      "Trait 21": {
         "name": 'Enhanced Barrel Stabilizer',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1afa87e85f90db56234d7365432dfd5bde9a4b31.png',
         "job_icon": 'MCH',
         "level": '100',
         "content": 'Накладывает эффект Full Metal Machinist после использования Barrel Stabilizer.<br/>Продолжительность: 30 сек.',
      },
      // PVP Skill 01
      "PVP Skill 01": {
         "name": 'Blast Charge',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e15fdee2a9a849495d10440d6d5f007a66f636e0.png',
         "classification": 'Боевой навык',
         "cast": '1.44 сек.',
         "recast": '2.4 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Дальний удар, наносящий урон с силой атаки 4,000.<br/>Дополнительный эффект: накладывает стак Heat, вплоть до 5<br/>Продолжительность: 15 сек.<br/>При максимальном количестве стаков накладывает Overheated и увеличивает скорость передвижения на 25%.<br/>Продолжительность: 5 сек.<br/>Для используется требуется время применения, однако во время применения можно перемещаться.<br/><br/>※Умение меняется на Heat Blast под действием эффекта Overheated.',
      },
      // PVP Skill 02
      "PVP Skill 02": {
         "name": 'Scattergun',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a97a3334f7e3c5afaa91eb2ab84c953f9e1402a7.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '12y',
         "radius_img": 'R4',
         "radius": '12y',
         "content": 'Удар, наносящий урон с силой атаки 6,000 по всем противникам в конусе перед персонажем. Наносит двойной удар, если поражает только одну цель.<br/>Дополнительный эффект: отбрасывает цель на 10 ялмов назад<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями.',
      },
      // PVP Skill 03
      "PVP Skill 03": {
         "name": 'Drill',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1843c5eb1876f021be1a9cf6359c316781916627.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Дальний удар, наносящий урон с силой атаки 10,000.<br/>Сила атаки увеличивается до 20,000, пока персонаж находитесь под действием эффекта Analysis.<br/>Игнорирует эффект Guard при нанесении урона.<br/>Дополнительный эффект: накладывает эффект Bioblaster Primed<br/>Максимум зарядов: 2<br/>Можно использовать только под действием Drill Primed.<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями.<br/><br/>※Умение меняется на Bioblaster под действием эффекта Bioblaster Primed.',
      },
      // PVP Skill 04
      "PVP Skill 04": {
         "name": 'Wildfire',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/95728389d41fbd0e5d09f80b2c0d10df41441cd9.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Окутывает цель медленно горящим огнем, накладывая эффект Wildfire. Наносит урон цели и всем противникам в радиусе 5 ялмов по истечении времени.<br/>Продолжительность: 7 сек.<br/>Сила атаки увеличивается на 4,000 за каждое атакующее умение персонажа, которое он совершаете до окончания действия эффекта.<br/>Если персонаж нанесет 3 атакующих умения по цели, то медленно горящая цель немедленно взорвется.',
      },
      // PVP Skill 05
      "PVP Skill 05": {
         "name": 'Bishop Autoturret',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5b81ea0d7793a71e83ebe7472ce3f860a51a842a.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '30 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Развертывает боевую турель, которая будет наносить авто атаки по противникам с силой атаки 6,000.<br/>Продолжительность: 10 сек.<br/>Дополнительный эффект: увеличивает получаемый целью урон на 10%<br/>Продолжительность: 7 сек.<br/>Дополнительный эффект: создает барьер, поглощающий урон, равный силе лечения 6,000<br/>Продолжительность: 7 сек.',
      },
      // PVP Skill 06
      "PVP Skill 06": {
         "name": 'Analysis',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/38dc9d35007c7cdc38d10d63379748401fed9939.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Накладывает эффект, дающий дополнительные эффекты умениям Drill, Bioblaster, Air Anchor и Chain Saw при использовании этих боевых навыков.<br/>Продолжительность: 10 сек.<br/>Дополнительный эффект Drill: сила атаки увеличена до 200%<br/>Дополнительный эффект Bioblaster: удваивает силу атаки и накладывает цель тяжесть (heavy) +75%<br/>Дополнительный эффект Air Anchor: сила атаки увеличена на 50%, а эффект связывания (bind) становится оглушением (stun)<br/>Дополнительный эффект Chain Saw: сила атаки увеличена на 50%<br/>Максимум зарядов: 2',
      },
      // PVP Skill 07
      "PVP Skill 07": {
         "name": 'Heat Blast',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/84a05c1b20f3981ddf99a23880ea9a2063fe87b2.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Дальний удар, наносящий урон с силой атаки 6,000.<br/>Может быть использовано только под действием эффекта Overheated.<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 08
      "PVP Skill 08": {
         "name": 'Bioblaster',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/70783248b63c783d9df10fbe8f420ec6954d9eab.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "range": '12y',
         "radius_img": 'R4',
         "radius": '12y',
         "content": 'Удар, наносящий урон с силой атаки 4,000 по всем противникам в конусе перед персонажем.<br/>Дополнительный эффект: удваивает силу атаки и накладывает на цель тяжесть (heavy) +75% при наличии эффекта Analysis<br/>Продолжительность: 5 сек.<br/>Дополнительный эффект: периодический урон<br/>Potency: 4,000<br/>Продолжительность: 12 сек.<br/>Удвоение силы атаки не распространяется на эффект периодического урона.<br/>Дополнительный эффект: накладывает эффект Air Anchor Primed<br/>Maximum Charges: 2<br/>Может быть использовано только под действием эффекта Bioblaster Primed.<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями.<br/><br/>※Умение меняется на Air Anchor под действием эффекта Air Anchor Primed.<br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 09
      "PVP Skill 09": {
         "name": 'Air Anchor',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/120150f155ff0887d5b979ef25e82df2232e2afe.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Дальний удар, наносящий урон с силой атаки 8,000.<br/>Дополнительный эффект: связывание (bind)<br/>Продолжительность: 3 сек.<br/>Дополнительные эффекты: сила атаки увеличивается на 50%, а эффект связывания (bind) становится оглушением (stun) при наличии эффекта Analysis<br/>Продолжительность: 3 сек.<br/>Дополнительный эффект: накладывает эффект Chain Saw Primed<br/>Максимум зарядов: 2<br/>Может быть использовано только под действием эффекта Air Anchor Primed.<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями.<br/><br/>※Умение меняется на Chain Saw под действием эффекта Chain Saw Primed.<br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 10
      "PVP Skill 10": {
         "name": 'Chain Saw',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/acbc270d0d2e6192541800dcc280c80a7eae3bba.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "range": '25y',
         "radius_img": 'R6',
         "radius": '25y',
         "content": 'Удар, наносящий урон по всем противникам по прямой линии перед персонажем с силой атаки 8,000.<br/>Сила атаки увеличивается на 50%, если HP цели ниже 50%.<br/>Дополнительный эффект: сила атаки увеличивается на 50% при наличии эффекта Analysis<br/>Дополнительный эффект: накладывает эффект Drill Primed<br/>Максимум зарядов: 2<br/>Может быть использовано только под действием эффекта Chain Saw Primed.<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями.<br/><br/>※Умение меняется на Drill под действием эффекта Drill Primed.<br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 11
      "PVP Skill 11": {
         "name": 'Aether Mortar',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e630bb066bbc76a8e961d011612bbdcdaf9509d2.png',
         "classification": 'Способность',
         "cast": '1 сек.',
         "recast": '1 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 6,000 по всем ближайшим противникам.<br/>Дополнительный эффект: увеличивает получаемый целью урон на 10%<br/>Продолжительность: 7 сек.<br/>Дополнительный эффект: создает барьер, поглощающий урон, равный силе лечения 6,000<br/>Продолжительность: 7 сек.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 12
      "PVP Skill 12": {
         "name": "Marksman's Spite",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b641fb27f646df1959aa4754f6389d54fd20b9d5.png',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "range": '50y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Дальний удар, наносящий урон с силой атаки 36,000.<br/>Может быть использовано только тогда, когда шкала лимит брейка (limit gauge) заполнена.<br/>Время зарядки шкалы: 90 сек.',
      },
   };
   FILL_DB_VALUES(db);
   FILL_DB_SKILLS(db);
   FILL_DB_SKILLS_PASSIVE(db);
   FILL_DB_SKILLS_PVP(db);
   FILL_DB_SKILLS_MENU(db);
})();