(() =>{
   let db = {
      "PVE Update": `Последнее обновление: 10/02/2023`,
      "PVP Update": `Последнее обновление: 01/16/2024`,
      // PVE Skill 01
      "PVE Skill 01": {
         "name": 'Bootshine',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/042e3be3ea0a054e9fa9cb7db61dd0a14a3622f7.png',
         "job_icon": 'PGL',
         "level": '1',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 210.<br/>Сила атаки Leaden Fist: 310<br/>Бонус Opo-opo формы: гарантирует нанесение критического (critical) удара<br/>Наносимый урон увеличивается под действием эффектов, повышающих вероятность критического (critical) урона.<br/>Дополнительный эффект: изменяет форму на raptor<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 02
      "PVE Skill 02": {
         "name": 'True Strike',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/af7b18aed7033e61d761f6103f46160923ce4dba.png',
         "job_icon": 'PGL',
         "level": '4',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '3 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 300.<br/>Может быть использовано только в форме raptor.<br/>Дополнительный эффект: изменяет форму на coeurl<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 03
      "PVE Skill 03": {
         "name": 'Snap Punch',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a0723660e32d9a35961de3002386736a3f97f9aa.png',
         "job_icon": 'PGL',
         "level": '6',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар в бок, наносящий урон с силой атаки 250, при выполнении удара в бок цели 310.<br/>Может быть использовано только в форме coeurl.<br/>Дополнительный эффект: изменяет форму на opo-opo<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 04
      "PVE Skill 04": {
         "name": 'Meditation',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/86b9816c4f8/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c9043d24d8c1d97eb7858c7d6bac820e1a3b5999.png',
         "job_icon": 'PGL',
         "level": '15',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Открывает чакру на шкале Chakra Gauge. Одновременно может быть открыто до пяти чакр.<br/>Открывает все пять чакр при использовании вне боя.<br/>Это умение имеет общее время восстановления с другими боевыми навыками.<br/>И наоборот, использование боевого навыка имеет общее время восстановления с этим умением.<br/><br/>※Умение меняется на The Forbidden Chakra, когда открыты все пять чакр.',
      },
      // PVE Skill 05
      "PVE Skill 05": {
         "name": 'Steel Peak',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/bf14821955a0b22662b2ad2f939f5d25e28ddfbe.png',
         "job_icon": 'PGL',
         "level": '15',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 180.<br/>Может быть использовано только в бою и под эффектом Fifth Chakra. Все пять чакр закрываются при использовании.<br/>Имеет общее время восстановления с умением Howling Fist.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 06
      "PVE Skill 06": {
         "name": 'Twin Snakes',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/30f4acde19a2b7da96a18abfb609bf41f1d140dd.png',
         "job_icon": 'PGL',
         "level": '18',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 280.<br/>Может быть использовано только в форме raptor.<br/>Дополнительный эффект: накладывает эффект Disciplined Fist<br/>Эффект Disciplined Fist: увеличивает наносимый урон на 15%<br/>Продолжительность: 15 сек.<br/>Дополнительный эффект: изменяет форму на coeurl<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 07
      "PVE Skill 07": {
         "name": 'Arm of the Destroyer',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/44aeab1317ba946482cfcb3db020495c82b2adaf.png',
         "job_icon": 'PGL',
         "level": '26',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 100 по всем противникам.<br/>Сила атаки Opo-opo Form: 110<br/>Дополнительный эффект: изменяет форму на raptor<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 08
      "PVE Skill 08": {
         "name": 'Demolish',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/a9f57cdec57/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/478fe9db14cb870f97bd5c97e94d6c330a52e625.png',
         "job_icon": 'PGL',
         "level": '30',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 70, при выполнении удара в спину цели 130.<br/>Может быть использовано только в форме coeurl.<br/>Дополнительный эффект: периодический урон<br/>Сила атаки: 70<br/>Продолжительность: 18 сек<br/>Дополнительный эффект: изменяет форму на opo-opo<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 09
      "PVE Skill 09": {
         "name": 'Rockbreaker',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/4480af45c8c/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/6f757660279f936fff7f7b46f415c50ffa8ab08a.png',
         "job_icon": 'MNK',
         "level": '30',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 130 по всем окружающим противникам.<br/>Может быть использовано только в форме coeurl.<br/>Дополнительный эффект: изменяет форму на opo-opo<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 10
      "PVE Skill 10": {
         "name": 'Thunderclap',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/fc024563e92/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/3cd306065005282605a77162e9158092ba2a75b1.png',
         "job_icon": 'MNK',
         "level": '35',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '30 сек.',
         "range": '20y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Рывок к выбранному противнику или сопартийцу.<br/>Максимум стаков: 3<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.',
      },
      // PVE Skill 11
      "PVE Skill 11": {
         "name": 'Howling Fist',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/2c6c07794c6/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b5e5c9978cca1e84dd3dfd44bf37acb9aa875c13.png',
         "job_icon": 'MNK',
         "level": '40',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '10y',
         "radius_img": 'R6',
         "radius": '10y',
         "content": 'Удар, наносящий урон с силой атаки 100 по всем противникам по прямой линии перед персонажем.<br/>Может быть использовано только в бою и под эффектом Fifth Chakra. Все пять чакр закрываются при использовании.<br/>Имеет общее время восстановления с умением The Forbidden Chakra.',
      },
      // PVE Skill 12
      "PVE Skill 12": {
         "name": 'Mantra',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/87f8bb6f1bcc8aa169c04e15c7d526d9d6e3dc55.png',
         "job_icon": 'PGL',
         "level": '42',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '90 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '30y',
         "content": 'Увеличивает количество HP, восстанавливаемое исцеляющими умениями на 10% для персонажа и ближайших сопартийцев.<br/>Продолжительность: 15 сек.',
      },
      // PVE Skill 13
      "PVE Skill 13": {
         "name": 'Four-point Fury',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/ef40194d56f/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2e982c5bcdf7073f54f478d072d76eb8fc7ebd73.png',
         "job_icon": 'MNK',
         "level": '45',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 120 по всем окружающим противникам.<br/>Может быть использовано только в форме raptor.<br/>Дополнительный эффект: накладывает эффект Disciplined Fist<br/>Эффект Disciplined Fist: увеличивает наносимый урон на 15%<br/>Продолжительность: 15 сек.<br/>Дополнительный эффект: изменяет форму на coeurl<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 14
      "PVE Skill 14": {
         "name": 'Dragon Kick',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b28fd0b73c9131439b9d376ea443532892876681.png',
         "job_icon": 'PGL',
         "level": '50',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 320.<br/>Бонус Opo-opo Form: накладывает Leaden Fist<br/>Продолжительность: 30 сек.<br/>Дополнительный эффект: изменяет форму на raptor<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 15
      "PVE Skill 15": {
         "name": 'Perfect Balance',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/c297c0c3578/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/08bf418da9242f2ad395422bd474f9f4b8819b29.png',
         "job_icon": 'MNK',
         "level": '50',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '40 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Накладывает 3 стака Perfect Balance, каждый из которых позволяет использовать боевой навык, требующий определенной формы, не находясь в этой форме.<br/>Продолжительность: 20 сек.<br/>Дополнительный эффект: дает Opo-opo Chakra, Coeurl Chakra или Raptor Chakra в зависимости от формы, требуемой для использования умения<br/>Максимум зарядов: 2<br/>Может быть использован только в бою, когда на персонажа не наложен эффект Beast Chakra.',
      },
      // PVE Skill 16
      "PVE Skill 16": {
         "name": 'Form Shift',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/0c3856b6bc3/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f48ad79820696829faea1b43c94a9e70a1b84ce9.png',
         "job_icon": 'MNK',
         "level": '52',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Накладывает на персонажа эффект Formless Fist, позволяя использовать боевой навык, требующий определенной формы, не находясь в этой форме.<br/>Продолжительность: 30 сек.<br/>Любые дополнительные эффекты, связанные с использованным умением, также будут применены.',
      },
      // PVE Skill 17
      "PVE Skill 17": {
         "name": 'The Forbidden Chakra',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/401f59c6a53/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/cbe79f033c767f053b625ec72de22bee654722b8.png',
         "job_icon": 'MNK',
         "level": '54',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 340.<br/>Может быть использован только в бою и под эффектом Fifth Chakra. Все пять чакр закрываются при использовании.<br/>Имеет общее время восстановления с умением Enlightenment.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 18
      "PVE Skill 18": {
         "name": 'Masterful Blitz',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/718bc0561cb/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/00cd52fc4dd2849210bea04ee05cd62a921f1cfb.png',
         "job_icon": 'MNK',
         "level": '60',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Поражает противника техникой, заряженной силой Beast Chakra.<br/>Используемая техника зависит от количества открытых типов Beast Chakra.<br/>Один тип Beast Chakra: Elixir Field<br/>Два типа Beast Chakra: Celestial Revolution<br/>Три типа Beast Chakra: Rising Phoenix<br/>Три Beast Chakra и обе Nadi: Phantom Rush',
      },
      // PVE Skill 19
      "PVE Skill 19": {
         "name": 'Elixir Field',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c3b8c8cd51562f2117d6ee72ee44c6cb7a9ed497.png',
         "job_icon": 'MNK',
         "level": '60',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон по всем окружающим противникам с силой атаки 600 для первого и на 70% меньше для остальных.<br/>Дополнительный эффект: открывает Lunar Nadi<br/>Дополнительный эффект: накладывает Formless Fist, позволяя использовать боевой навык, требующий определенной формы, не находясь в этой форме<br/>Продолжительность: 30 сек.<br/>Любые дополнительные эффекты, связанные с использованным умением, также будут применены.<br/>Может быть использовано только под действием трех одинаковых Beast Chakra.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 20
      "PVE Skill 20": {
         "name": 'Flint Strike',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4a4c381e589645018bad71d48508a65e340035ca.png',
         "job_icon": 'MNK',
         "level": '60',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон по всем окружающим противникам с силой атаки 600 для первого и на 70% меньше для остальных. <br/>Дополнительный эффект: открывает Solar Nadi<br/>Дополнительный эффект: накладывает Formless Fist, позволяя использовать боевой навык, требующий определенной формы, не находясь в этой форме<br/>Продолжительность: 30 сек.<br/>Любые дополнительные эффекты, связанные с использованным умением, также будут применены.<br/>Может быть использовано только под действием трех разных Beast Chakra.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 21
      "PVE Skill 21": {
         "name": 'Celestial Revolution',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c9d2b58e28943b3309db19b112d998246d1b79b2.png',
         "job_icon": 'MNK',
         "level": '60',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 450.<br/>Дополнительный эффект: открывает Lunar Nadi<br/>Если Lunar Nadi уже открыта, вместо нее открывается Solar Nadi<br/>Дополнительный эффект: накладывает Formless Fist, позволяя использовать боевой навык, требующий определенной формы, не находясь в этой форме<br/>Продолжительность: 30 сек.<br/>Любые дополнительные эффекты, связанные с использованным умением, также будут применены.<br/>Может быть использовано только под действием трех Beast Chakra.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 22
      "PVE Skill 22": {
         "name": 'Tornado Kick',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e5c7d0867c9b53f33bd8b319379946e7b9c27ba1.png',
         "job_icon": 'MNK',
         "level": '60',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '3y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон по цели и всем окружающим противникам с силой атаки 850 для первого и на 50% меньше для остальных.<br/>Дополнительный эффект: накладывает Formless Fist, позволяя использовать боевой навык, требующий определенной формы, не находясь в этой форме<br/>Продолжительность: 30 сек.<br/>Любые дополнительные эффекты, связанные с использованным умением, также будут применены.<br/>Может быть использовано только под действием эффекта Lunar Nadi и Solar Nadi, а также трех Beast Chakra.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 23
      "PVE Skill 23": {
         "name": 'Riddle of Earth',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/84e3e679f5393f9a83e3b8204aad5192ecc483d1.png',
         "job_icon": 'MNK',
         "level": '64',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Снижает получаемый урон на 20%.<br/>Продолжительность: 10 сек.<br/>Дополнительный эффект: накладывает Earth's Reply при получении урона<br/>Эффект Earth's Reply: постепенно восстанавливает HP<br/>Сила лечения: 100<br/>Продолжительность: 10 сек.",
      },
      // PVE Skill 24
      "PVE Skill 24": {
         "name": 'Riddle of Fire',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1bc71b7e13b0634a6242026cd6ae29e018add98a.png',
         "job_icon": 'MNK',
         "level": '68',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Увеличивает наносимый урон на 15%.<br/>Продолжительность: 20 сек.',
      },
      // PVE Skill 25
      "PVE Skill 25": {
         "name": 'Brotherhood',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/c85116d60e5/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a744e79fae56358a44e1d1f253a8be12d0ebaf8f.png',
         "job_icon": 'MNK',
         "level": '70',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '30y',
         "content": 'Накладывает эффект Brotherhood и Meditative Brotherhood на персонажа и всех окружающих сопартийцев.<br/>Эффект Brotherhood: увеличивает наносимый урон на 5%<br/>Эффект Meditative Brotherhood: с вероятностью 20% открывается чакру, когда сопартийцы под этим эффектом успешно проводят боевой навык или произносят заклинание<br/>С вероятностью 100% окрывает чакру, если персонаж успешно проводит боевой навык или произносит заклинание, находясь под эффектом Meditative Brotherhood.<br/>Продолжительность: 15 сек.',
      },
      // PVE Skill 26
      "PVE Skill 26": {
         "name": 'Riddle of Wind',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/793d43f2460d5b36044a6926484d73bf8670190f.png',
         "job_icon": 'MNK',
         "level": '72',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '90 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Снижает задержку между авто атаками на 50%.<br/>Продолжительность: 15 сек.',
      },
      // PVE Skill 27
      "PVE Skill 27": {
         "name": 'Enlightenment',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f258ec9d84566ca80f061e58a8ba3993a7b735a3.png',
         "job_icon": 'MNK',
         "level": '74',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '10y',
         "radius_img": 'R6',
         "radius": '10y',
         "content": 'Удар, наносящий урон с силой атаки 170 по всем противникам по прямой линии перед персонажем.<br/>Может быть использован только в бою и под эффектом Fifth Chakra. Все пять чакр закрываются при использовании.<br/>Имеет общее время восстановления с умением The Forbidden Chakra.',
      },
      // PVE Skill 28
      "PVE Skill 28": {
         "name": 'Anatman',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/eecc1b38ea1de839b3b275cd6d9cd10cdc8dab13.png',
         "job_icon": 'MNK',
         "level": '78',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Увеличивает время эффекта Disciplined Fist и активной формы персонажа до максимума и останавливает их истечение.<br/>Продолжительность: 30 сек.<br/>Прерывает авто атаки при использовании умения. Эффект спадет при использовании умений или перемещении персонажа (включая разворот в другие стороны).<br/>При использовании срабатывает восстановление боевых умений. Не может быть использовано во время восстановления боевых навыков.',
      },
      // PVE Skill 29
      "PVE Skill 29": {
         "name": 'Six-sided Star',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/eaa1b242a96d4dd9511d690e7d7aa1e1ea985e5a.png',
         "job_icon": 'MNK',
         "level": '80',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '4 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 550.<br/>Дополнительный эффект: увеличивает скорость передвижения<br/>Продолжительность: 5 сек.<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями. После использования время повторного применения этого умения будет применено ко всем боевым навыкам и магическим умениям.',
      },
      // PVE Skill 30
      "PVE Skill 30": {
         "name": 'Shadow of the Destroyer',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5166f89f6382d21ffd65cb45b3537c507f7d55de.png',
         "job_icon": 'MNK',
         "level": '82',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 110 по всем окружающим противникам.<br/>Бонус формы Opo-opo: гарантирует критическое попадание<br/>Наносимый урон увеличивается под действием эффектов, повышающих вероятность критического (critical) урона.<br/>Дополнительный эффект: меняет форму на raptor<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 31
      "PVE Skill 31": {
         "name": 'Rising Phoenix',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2ab98b9212f6d5a8d56cf74d904b3f15eda79d52.png',
         "job_icon": 'MNK',
         "level": '86',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий физический урон огнем по всем окружающим противникам с силой атаки 700 для первого и на 70% меньше для остальных.<br/>Дополнительный эффект: открывает Solar Nadi<br/>Дополнительный эффект: накладывает Formless Fist позволяя использовать боевой навык, требующий определенной формы, не находясь в этой форме<br/>Продолжительность: 30 сек.<br/>Любые дополнительные эффекты, связанные с использованным умением, также будут применены.<br/>Может быть использовано только под эффектом трех разных Beast Chakra.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 32
      "PVE Skill 32": {
         "name": 'Phantom Rush',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/47555f213252da857e3c68acb669cdb7f2c3d78d.png',
         "job_icon": 'MNK',
         "level": '90',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '3y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон по цели и всем окружающим противникам с силой атаки 1,150 для первого и на 50% меньше для остальных.<br/>Дополнительный эффект: накладывает Formless Fist позволяя использовать боевой навык, требующий определенной формы, не находясь в этой форме<br/>Продолжительность: 30 сек.<br/>Любые дополнительные эффекты, связанные с использованным умением, также будут применены.<br/>Может быть использовано только под действим эффектов Lunar Nadi и Solar Nadi, а также трех Beast Chakra.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // Trait 01
      "Trait 01": {
         "name": 'Greased Lightning',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1c068309f8a71e83a87f15b96f6c2d6abc543a83.png',
         "job_icon": 'PGL',
         "level": '1',
         "content": 'Уменьшает время длительности применения и время восстановления боевых навыков и заклинаний, а также промежуток между авто атаками на 5%.',
      },
      // Trait 02
      "Trait 02": {
         "name": 'Enhanced Greased Lightning',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/0ec2b9d599b31df85a165ae15d9d28c7ffed0d7b.png',
         "job_icon": 'PGL',
         "level": '20',
         "content": 'Уменьшает время длительности применения и время восстановления боевых навыков и заклинаний, а также промежуток между авто атаками на 10%.',
      },
      // Trait 03
      "Trait 03": {
         "name": 'Deep Meditation',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e4c442dfc2030eb7e7bc365b251acd77b79d058a.png',
         "job_icon": 'MNK',
         "level": '38',
         "content": 'Дает 80% шанс того, что чакра откроется при нанесении боевым умением критического урона.',
      },
      // Trait 04
      "Trait 04": {
         "name": 'Enhanced Greased Lightning II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e25c3c9c590fc63a386fb3492cb998aff23c19b8.png',
         "job_icon": 'MNK',
         "level": '40',
         "content": 'Уменьшает время длительности применения и время восстановления боевых навыков и заклинаний, а также промежуток между авто атаками на 15%.',
      },
      // Trait 05
      "Trait 05": {
         "name": 'Steel Peak Mastery',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/401f59c6a53/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e0030e047f082e09274b12e49adaf06ff088a3fd.png',
         "job_icon": 'MNK',
         "level": '54',
         "content": 'Улучшает умение Steel Peak до The Forbidden Chakra.',
      },
      // Trait 06
      "Trait 06": {
         "name": 'Enhanced Perfect Balance',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/718bc0561cb/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/3c4b7d740d86fbb56c459884cd3c52fe30a55d6d.png',
         "job_icon": 'MNK',
         "level": '60',
         "content": 'Когда персонаж находится под эффектом Perfect Balance, он получает Beast Chakra в соответствии с формой, которая обычно требуется для использования боевых навыков.<br/>Боевые навыки, требующие формы opo-opo, дают Opo-opo Chakra.<br/>Боевые навыки, требующие формы coeurl, дают Coeurl Chakra.<br/>Боевые навыки, требующие формы raptor, дают Raptor Chakra.',
      },
      // Trait 07
      "Trait 07": {
         "name": 'Deep Meditation II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/8a5b1c57a2e11d0e8f30df9848db1dafbeecf906.png',
         "job_icon": 'MNK',
         "level": '74',
         "content": 'Гарантирует, что чакра откроется при нанесении боевым умением критического урона.',
      },
      // Trait 08
      "Trait 08": {
         "name": 'Howling Fist Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b1e3b7ae734c31fced05be1a0b2fd15f03c1a245.png',
         "job_icon": 'MNK',
         "level": '74',
         "content": 'Улучшает умение Howling Fist до Enlightenment.',
      },
      // Trait 09
      "Trait 09": {
         "name": 'Enhanced Greased Lightning III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/85b59350c1cf08e9396d8f7f69156998efeee7ae.png',
         "job_icon": 'MNK',
         "level": '76',
         "content": 'Уменьшает время длительности применения и время восстановления боевых навыков и заклинаний, а также промежуток между авто атаками на 20%. А также увеличивает эффект Disciplined Fist до 15%.',
      },
      // Trait 10
      "Trait 10": {
         "name": 'Arm of the Destroyer Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/60a9a7542216180a206ebba580f89899b2978ec0.png',
         "job_icon": 'MNK',
         "level": '82',
         "content": 'Улучшает умение Arm of the Destroyer до Shadow of the Destroyer.',
      },
      // Trait 11
      "Trait 11": {
         "name": 'Enhanced Thunderclap',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a4e3cef1786273e7635c04b66cd8b2fb7459f983.png',
         "job_icon": 'MNK',
         "level": '84',
         "content": 'Позволяет использовать третий заряд Thunderclap.',
      },
      // Trait 12
      "Trait 12": {
         "name": 'Melee Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/6acea5ac3fd49cd172fac240c194a5847b080ccf.png',
         "job_icon": 'MNK',
         "level": '84',
         "content": 'Увеличивает силу атаки умений Bootshine до 210, True Strike до 300, Snap Punch до 250, Twin Snakes до 280, Demolish до 70, Dragon Kick до 320, The Forbidden Chakra до 340 и Six-sided Star до 550.',
      },
      // Trait 13
      "Trait 13": {
         "name": 'Flint Strike Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e00c6d101ec7bf712cb9c46a499ff69266044b9f.png',
         "job_icon": 'MNK',
         "level": '86',
         "content": 'Улучшает умение Flint Strike до Rising Phoenix.',
      },
      // Trait 14
      "Trait 14": {
         "name": 'Enhanced Brotherhood',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/25a9150b179ba0d9d53fefa92df4032e4d82e02b.png',
         "job_icon": 'MNK',
         "level": '88',
         "content": 'Гарантирует открытие чакры, когда персонаж находится под эффектом Meditative Brotherhood при использовании боевого навыка или заклинания.',
      },
      // Trait 15
      "Trait 15": {
         "name": 'Tornado Kick Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/0ea4fdc3ccaf0005e85c113865dbcfb0cf51a354.png',
         "job_icon": 'MNK',
         "level": '90',
         "content": 'Улучшает умение Tornado Kick до Phantom Rush.',
      },
      // PVP Skill 01
      "PVP Skill 01": {
         "name": 'Bootshine',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a308885df8d02be9db7168e1a6499fd874c3693d.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 3,000.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 02
      "PVP Skill 02": {
         "name": 'True Strike',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c2b81787340e6f18744ba26619a422f84093499c.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 4,000.<br/>Комбо умение: Bootshine<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 03
      "PVP Skill 03": {
         "name": 'Snap Punch',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5216fce6eb0e1f98a22673993403c01005144e3e.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 6,000.<br/>Комбо умение:True Strike<br/>Дополнительный эффект: увеличивает продолжительность Wind Resonance на 5 сек., вплоть до 15 сек.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 04
      "PVP Skill 04": {
         "name": 'Dragon Kick',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5ec9494d0971929187228a39aaff90a2b3d6a634.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 3,000.<br/>Комбо умение: Snap Punch<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 05
      "PVP Skill 05": {
         "name": 'Twin Snakes',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/527f4b68d64733c38d667f81c5e1f9d4875127ac.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 4,000.<br/>Комбо умение: Dragon Kick<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 06
      "PVP Skill 06": {
         "name": 'Demolish',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/67078f08b4af6bacf409e67e4afca97ade589d1d.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 6,000.<br/>Комбо умение: Twin Snakes<br/>Дополнительный эффект: увеличивает продолжительность Wind Resonance на 5 сек., вплоть до 15 сек.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 07
      "PVP Skill 07": {
         "name": 'Phantom Rush',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/fc732ca2151a2ae7012961e98e696865ad1e1d04.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '6y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 12,000 по цели и всем окружающим противникам.<br/>Комбо умение: Demolish<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 08
      "PVP Skill 08": {
         "name": 'Six-sided Star',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4092af75879715af0b2b3ed04d26c4ebaee5aa1e.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 4,000.<br/>Дополнительный эффект: оглушение (stun)<br/>Продолжительность: 2 сек.<br/>Дополнительный эффект: увеличивает скорость передвижения на 25%<br/>Продолжительность: 5 сек.',
      },
      // PVP Skill 09
      "PVP Skill 09": {
         "name": 'Enlightenment',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/826cec4e0ac932a29b38e6c8d19c1246615fdfca.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '10y',
         "radius_img": 'R6',
         "radius": '10y',
         "content": 'Удар, наносящий урон с силой атаки 8,000 по всем противникам по прямой линии перед персонажем.<br/>Дополнительный эффект: отталкивает первую цель на 15 ялмов<br/>Также поражает первую цель эффектом Pressure Point, если она успешно оттолкнута.<br/>Эффект  Pressure Point: следующий боевой навык или Meteodrive, использованный по цели, нанесет дополнительный урон с силой атаки 8,000 <br/>Продолжительность: 3 сек.<br/>Эффект Pressure Point заканчивает свое действие после нанесения дополнительного урона.<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями.',
      },
      // PVP Skill 10
      "PVP Skill 10": {
         "name": 'Rising Phoenix',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f1d0fb89b8edd7248064be9fd13aa927b40aadd2.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 3,000 по всем окружающим противникам.<br/>Дополнительный эффект: накладывает эффект Fire Resonance<br/>Эффект Fire Resonance: увеличивает урон, наносимый следующим боевым умением на 50%<br/>Продолжительность: 10 сек.<br/>Максимум зарядов: 2',
      },
      // PVP Skill 11
      "PVP Skill 11": {
         "name": 'Riddle of Earth',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/64a9bd6d68ae80af1ea8daa2410bd032d39b97be.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '25 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Накладывает эффекты Earth Resonance, меняя Riddle of Earth на Earth's Reply и позволяя накапливать урон каждый раз, когда персонажа поражает противник.<br/>Продолжительность: 8 сек.<br/>Использование Earth's Reply наносит физический урон всем ближайшим противникам и восстанавливает HP персонажа.<br/>Сила урона: 2,000 плюс 25% от накопленного урона<br/>Сила лечения: 4,000 плюс 50 % от накопленного урона.",
      },
      // PVP Skill 12
      "PVP Skill 12": {
         "name": 'Thunderclap',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a54ed85ea1e9f400712c049ca5f8f6d503bd2ab6.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "range": '20y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Рывок к месту выбранного противника или сопартийца.<br/>Дополнительный эффект: накладывает эффект Wind Resonance<br/>Эффект Wind Resonance: уменьшает время восстановления боевых навыков на 10%<br/>Продолжительность: 10 сек.<br/>Если на персонаже уже действует эффект Wind Resonance, его продолжительность увеличивается на 10 сек., вплоть 15 сек.<br/>Дополнительный эффект: создает вокруг выбранного сопартийца барьер, равный силе лечения 6,000<br/>Если выбранная целью был выбран противник, барьер создается вокруг персонажа.<br/>Продолжительность: 5 сек.<br/>Максимум зарядов: 3<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.',
      },
      // PVP Skill 13
      "PVP Skill 13": {
         "name": "Earth's Reply",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c5310e97e21000736821f990996a09f2d0bba1e6.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий физический урон всем ближайшим противникам и восстанавливает HP персонажа.<br/>Сила урона: 2,000 плюс 25% от полученного урона<br/>Сила лечения: 4,000 плюс 50 % от полученного урона<br/>Может быть использовано только под действием эффекта Earth Resonance.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 14
      "PVP Skill 14": {
         "name": 'Meteodrive',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/db4da14c2bf5aabe9de5c2cc782225c7fb13b9a8.png',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "range": '20y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Рывок, наносящий удар с силой атаки 12,000.<br/>Дополнительный эффект: снимает с цели Guard<br/>Дополнительный эффект: накладывает на цель эффект Meteodrive, лишая ее возможности двигаться<br/>Продолжительность: 3 сек.<br/>Если у цели не активен Guard, наносит дополнительный урон с силой атаки 12,000.<br/>Не действует на неигровых персонажей или игроков, находящихся в роботах.<br/>CМожет быть использовано только тогда, когда шкала лимит брейка (limit gauge) заполнена.<br/>Время зарядки шкалы: 75 сек.<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.',
      },
   };
   FILL_DB_VALUES(db);
   FILL_DB_SKILLS(db);
   FILL_DB_SKILLS_PASSIVE(db);
   FILL_DB_SKILLS_PVP(db);
   FILL_DB_SKILLS_MENU(db);
})();