(() =>{
   let db = {
      "PVE Update": `Последнее обновление: 27/06/2024`,
      "PVP Update": `Последнее обновление: 27/06/2024`,
      // PVE Skill 01
      "PVE Skill 01": {
         "name": 'Spinning Edge',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/657b568d32fd379339d365704c75ee7ca7e0cbd9.png',
         "job_icon": 'ROG',
         "level": '1',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.12 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 220.<br/>Дополнительный эффект: восполняет шкалу Ninki Gauge на 5',
      },
      // PVE Skill 02
      "PVE Skill 02": {
         "name": 'Shade Shift',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/533a4a3e924aaf268ee89a9c58845941bb73bad1.png',
         "job_icon": 'ROG',
         "level": '2',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Создает тени, которые поглощают получаемый урон в размере 20% от максимального HP.<br/>Продолжительность: 20 сек.',
      },
      // PVE Skill 03
      "PVE Skill 03": {
         "name": 'Gust Slash',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/3b3414364511f0fa913d25a989b88668c6152a90.png',
         "job_icon": 'ROG',
         "level": '4',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.12 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 160.<br/>Комбо умение: Spinning Edge<br/>Сила в комбо: 320<br/>Комбо бонус: восполняет шкалу Ninki Gauge на 5',
      },
      // PVE Skill 04
      "PVE Skill 04": {
         "name": 'Hide',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2dc011be7f8180f6559af70db7dc93c4b0229d95.png',
         "job_icon": 'ROG',
         "level": '10',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Персонаж сливается с окружающим миром, чтобы большинство противников не смогли его обнаружить, снижая скорость передвижения на 50%. Не действует на врагов на 10 уровней выше, а также на некоторых противников с особым зрением.<br/>Дополнительный эффект: восстанавливает 2 заряда всех мудр<br/>Эффект Doton заканчивается после использования Hide.<br/>Не может быть использовано во время боя.<br/>Эффект заканчивается при использовании любого умения, кроме ускорения (sprint) или при повторном использовании Hide.',
      },
      // PVE Skill 05
      "PVE Skill 05": {
         "name": 'Throwing Dagger',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/9bb819456d7/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e874766b966c4e6a786b58a35d76d3c0bd25b973.png',
         "job_icon": 'ROG',
         "level": '15',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.12 сек.',
         "range": '20y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Дальний удар, наносящий урон с силой атаки 120.<br/>Дополнительный эффект: восполняет шкалу Ninki Gauge на 5',
      },
      // PVE Skill 06
      "PVE Skill 06": {
         "name": 'Mug',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/3551bcd013b/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/61a5e5150f8d24fa8d9d5dfbefceb5ec53fe4045.png',
         "job_icon": 'ROG',
         "level": '15',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 150.<br/>Дополнительный эффект: увеличивает получаемый целью урон на 5%<br/>Продолжительность: 20 сек.<br/>Дополнительный эффект: увеличивает шанс выпадения дополнительных предметов из цели (в открытом мире), если Mug нанесен до или в качестве завершающего удара<br/>Дополнительный эффект: восполняет шкалу Ninki Gauge на 40',
      },
      // PVE Skill 07
      "PVE Skill 07": {
         "name": 'Trick Attack',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/fb4232c3fd76ce4d889759ec7ef7bffb15b78ede.png',
         "job_icon": 'ROG',
         "level": '18',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 300, при выполнении удара в спину цели 400.<br/>Дополнительный эффект: увеличивает наносимый персонажем урон по цели на 10%<br/>Продолжительность: 15 сек.<br/>Может быть использовано только под действием эффекта Hidden.',
      },
      // PVE Skill 08
      "PVE Skill 08": {
         "name": 'Aeolian Edge',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e68ade763da71adb1e8401db79a08e1df6f4d9e1.png',
         "job_icon": 'ROG',
         "level": '26',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.12 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 140, при выполнении удара в спину цели 200.<br/>Комбо умение: Gust Slash<br/>Сила в комбо: 380<br/>Сила в комбо в спину цели: 440<br/>Комбо бонус: восполняет шкалу Ninki Gauge на 15',
      },
      // PVE Skill 09
      "PVE Skill 09": {
         "name": 'Ten',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/fb587e6e821/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/55c66e798d7404567ec69a023335542cef7cd916.png',
         "job_icon": 'NIN',
         "level": '30',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Собирает жестами рук ритуальную мудру, обозначающую "небо".<br/>Продолжительность: 6 сек.<br/>Максимум зарядов: 2<br/>При использовании активируется время восстановления боевых навыков, мудр и Ninjutsu.<br/>И наоборот, использование боевых навыков приводит к активации времени восстановления этого умения.',
      },
      // PVE Skill 10
      "PVE Skill 10": {
         "name": 'Ninjutsu',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b1362c998dbfc19dfd13223d2ae275be7f4db7cc.png',
         "job_icon": 'NIN',
         "level": '30',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Собирает специальное ниндзюцу, соответсвующее с комбинацией мудр, созданной непосредственно перед этим.<br/>Если до объединения мудр и выполнения ниндзюцу будет использовано любое другое умение, Ninjutsu будет провалено.<br/>При использовании Ninjutsu активируется время восстановления боевых навыков, мудр и Ninjutsu.<br/>И наоборот, использование боевых навыков приводит к активации времени восстановления этого умения.<br/>Восстанавливает 2 заряда всех мудр при использовании Hide вне боя.',
      },
      // PVE Skill 11
      "PVE Skill 11": {
         "name": 'Chi',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/d1c274636ba/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1836df5cdf1d1f78ae7b2f65462661f2fa6a79d8.png',
         "job_icon": 'NIN',
         "level": '35',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Собирает жестами рук ритуальную мудру, обозначающую "земля".<br/>Продолжительность: 6 сек.<br/>Максимум зарядов: 2<br/>При использовании активируется время восстановления боевых навыков, мудр и Ninjutsu.<br/>И наоборот, использование боевых навыков приводит к активации времени восстановления этого умения.',
      },
      // PVE Skill 12
      "PVE Skill 12": {
         "name": 'Death Blossom',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d40b78dd5c99076b25086882f27de295f8a609af.png',
         "job_icon": 'ROG',
         "level": '38',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.12 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 100 по всем окружающим противникам.<br/>Дополнительный эффект: восполняет шкалу Ninki Gauge на 5',
      },
      // PVE Skill 13
      "PVE Skill 13": {
         "name": 'Assassinate',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/99d0c3688cb4d3fafd0df210199783bcadc74cc2.png',
         "job_icon": 'NIN',
         "level": '40',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 200.',
      },
      // PVE Skill 14
      "PVE Skill 14": {
         "name": 'Shukuchi',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/1f28eecd53c/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ea2717bad5b805b35bb32731d78113692104a30d.png',
         "job_icon": 'NIN',
         "level": '40',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "range": '20y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Быстро перемещается в указанное место.<br/>Максимум заряд: 2<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.',
      },
      // PVE Skill 15
      "PVE Skill 15": {
         "name": 'Jin',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/2c937a7e1f7/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2183f2672edde169e6276764503ec11ae06b4c1e.png',
         "job_icon": 'NIN',
         "level": '45',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Собирает жестами рук ритуальную мудру, обозначающую "человек".<br/>Продолжительность: 6 сек.<br/>Максимум зарядов: 2<br/>При использовании активируется время восстановления боевых навыков, мудр и Ninjutsu.<br/>И наоборот, использование боевых навыков приводит к активации времени восстановления этого умения.',
      },
      // PVE Skill 16
      "PVE Skill 16": {
         "name": 'Kassatsu',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/2d589d83483/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a12553440d7385aaafc940cac8f14682e3012392.png',
         "job_icon": 'NIN',
         "level": '50',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Позволяет использовать одно ниндзюцу без расхода зарядов мудры.<br/>Дополнительный эффект: увеличивает урон от следующего умения ниндзюцу на 30%<br/>Продолжительность: 15 сек.<br/>Время повторного применения мудры не зависит от использования этого умения.',
      },
      // PVE Skill 17
      "PVE Skill 17": {
         "name": 'Hakke Mujinsatsu',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/74499f0e20d/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/86e59c1bd3dedee2a6b68d3321da04c68a3acb52.png',
         "job_icon": 'NIN',
         "level": '52',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.12 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 100 по всем окружающим противникам.<br/>Комбо умение: Death Blossom<br/>Сила в комбо: 130<br/>Комбо бонус: увеличивает продолжительность Huton на 10 сек., вплоть до 60 сек.<br/>Комбо бонус: восполняет шкалу Ninki Gauge на 5',
      },
      // PVE Skill 18
      "PVE Skill 18": {
         "name": 'Armor Crush',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/7f99763377d/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f8e49f627d8f6e16b91b2192b322812f09c40475.png',
         "job_icon": 'NIN',
         "level": '54',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.12 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 140, при выполнении удара в спину цели 200.<br/>Комбо умение: Gust Slash<br/>Combo Potency: 360<br/>Сила в комбо в спину цели: 420<br/>Комбо бонус: увеличивает продолжительность Huton на 30 сек., вплоть до 60 сек.<br/>Комбо бонус: восполняет шкалу Ninki Gauge на 15',
      },
      // PVE Skill 19
      "PVE Skill 19": {
         "name": 'Dream Within a Dream',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/51342498a4d/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f2e750bda00af60c3a06480f512753c8b6d5951b.png',
         "job_icon": 'NIN',
         "level": '56',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Тройной удар, каждый из которых наносит урон с силой атаки 150.',
      },
      // PVE Skill 20
      "PVE Skill 20": {
         "name": 'Hellfrog Medium',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c802df3d7abd5e50889d1cc5e97cf64eb1610afa.png',
         "job_icon": 'NIN',
         "level": '62',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '6y',
         "content": 'Удар, наносящий урон с силой атаки 160 по цели и всем окружающим противникам.<br/>Стоимость: 50 Ninki Gauge<br/>Имеет общее время восстановления с умением Bhavacakra.',
      },
      // PVE Skill 21
      "PVE Skill 21": {
         "name": 'Dokumori',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/751e11fc60c05f5ac427b522211ae510ef845f6c.png',
         "job_icon": 'NIN',
         "level": '66',
         "classification": 'Ability',
         "cast": 'Instant',
         "recast": '120 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": ' ',
      },
      // PVE Skill 22
      "PVE Skill 22": {
         "name": 'Bhavacakra',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7fa8283b30b9ac35aada60984cbfaf01d3268c95.png',
         "job_icon": 'NIN',
         "level": '68',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 350.<br/>Бонус Meisui: сила атаки увеличивается до 500, когда персонаж находится под эффектом Meisui<br/>Стоимость: 50 Ninki Gauge<br/>Имеет общее время восстановления с умением Hellfrog Medium.',
      },
      // PVE Skill 23
      "PVE Skill 23": {
         "name": 'Ten Chi Jin',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/a5518b30cd3/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/9c0c72efe9ba9c13d3765b1b7dd863c68eeaf4ba.png',
         "job_icon": 'NIN',
         "level": '70',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Временно превращает каждую из трех мудр в умение ниндзюцу. Использование одного из этих умений преобразует остальные мудры в различные умения ниндзюцу, пока не будут использованы все три или не истечет срок действия эффекта Ten Chi Jin.<br/>Продолжительность: 6 сек.<br/>Можно использовать только ниндзюцу, пока активно умение. Одно и то же ниндзюцу не может быть использовано дважды.<br/>Не может быть использовано под действием Kassatsu. Эффект прекращается при перемещении.',
      },
      // PVE Skill 24
      "PVE Skill 24": {
         "name": 'Meisui',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/9c7d1c58eb10c5d105f1ee98a21f84a031d26518.png',
         "job_icon": 'NIN',
         "level": '72',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Рассеивает Suiton, увеличивая шкалу Ninki Gauge на 50.<br/>Дополнительный эффект: увеличивает силу атаки Bhavacakra до 500<br/>Продолжительность: 30 сек.<br/>Может быть использовано только в бою.',
      },
      // PVE Skill 25
      "PVE Skill 25": {
         "name": 'Bunshin',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/0469d406babef3b172ba2a567f748b6ff8e11860.png',
         "job_icon": 'NIN',
         "level": '80',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '90 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Накладывает 5 стаков Bunshin, каждый из которых позволяет тени персонажа атаковать противников каждый раз, когда используется боевой навык. Сила атаки тени зависит от использованной атаки, но не зависит от комбо бонусов.<br/>Сила атаки ближнего боя: 160<br/>Сила атаки дальнего боя: 160<br/>Сила атаки по площади: 80<br/>Ninki Gauge увеличивается на 5 каждый раз, когда тень персонажа наносит атак<br/>Продолжительность: 30 сек.<br/>Дополнительный эффект: накладывает Phantom Kamaitachi Ready<br/>Продолжительность: 45 сек.<br/>Стоимость: 50 Ninki Gauge<br/><br/>※После использования умение меняется на Phantom Kamaitachi.',
      },
      // PVE Skill 26
      "PVE Skill 26": {
         "name": 'Phantom Kamaitachi',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/45a5ef76e62a78c0c0fcf1feeefb4b992ab82346.png',
         "job_icon": 'NIN',
         "level": '82',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.12 сек.',
         "range": '20y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Тень персонажа атакует, нанося урон ветром по цели и всем ближайшим противникам в радиусе 5 ялмов с силой 600 для первого противника и на 50% меньше для всех остальных.<br/>Дополнительный эффект: увеличивает продолжительность Huton на 10 сек., вплоть до 60 сек.<br/>Дополнительный эффект: увеличивает Ninki Gauge на 10<br/>Можно использовать только под действием эффекта Phantom Kamaitachi Ready.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 27
      "PVE Skill 27": {
         "name": 'Hollow Nozuchi',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/54d329bd6de61295054388e35afdd610561884ca.png',
         "job_icon": 'NIN',
         "level": '86',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '-',
         "range": '100y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Все противники, стоящие на проклятой земле Doton, получают дополнительный урон землей с силой атаки 50.<br/>Требует использования Katon, Goka Mekkyaku, Phantom Kamaitachi или Hakke Mujinsatsu в качестве комбо умения.<br/>Эффект может быть использован только при активном Doton.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 28
      "PVE Skill 28": {
         "name": 'Forked Raiju',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/9ab20d782e03641292336da9b2453f426435a3b0.png',
         "job_icon": 'NIN',
         "level": '90',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.12 сек.',
         "range": '20y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Рывок к цели и молниеносный удар, наносящий урон с силой атаки  560.<br/>Дополнительный эффект: увеличивает Ninki Gauge на 5<br/>Можно использовать только под действием эффекта Raiju Ready.<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.',
      },
      // PVE Skill 29
      "PVE Skill 29": {
         "name": 'Fleeting Raiju',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/aaf631010c04fc9685247fe855060f640dff89f7.png',
         "job_icon": 'NIN',
         "level": '90',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.12 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон молнией с силой атаки 560.<br/>Дополнительный эффект: увеличивает Ninki Gauge на 5<br/>Может быть использовано только под действием эффекта Raiju Ready.',
      },
      // PVE Skill 30 NEW
      "PVE Skill 30": {
         "name": "Kunai's Bane",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/70139d7c1c6e323518d56f1bd503a9e8bc94d21b.png',
         "job_icon": 'NIN',
         "level": '92',
         "classification": 'Ability',
         "cast": 'Instant',
         "recast": '60 сек.',
         "range": '3y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": '',
      },
      // PVE Skill 31 NEW
      "PVE Skill 31": {
         "name": 'Deathfrog Medium',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/cb1fc6f802ae442daa8ead243f4f9f49bf9525f4.png',
         "job_icon": 'NIN',
         "level": '96',
         "classification": 'Ability',
         "cast": 'Instant',
         "recast": '1 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '6y',
         "content": '',
      },
      // PVE Skill 32 NEW
      "PVE Skill 32": {
         "name": 'Zesho Meppo',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/55604bbe9cf720982be6e0ef74e9bf002d939935.png',
         "job_icon": 'NIN',
         "level": '96',
         "classification": 'Ability',
         "cast": 'Instant',
         "recast": '1 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": '',
      },
      // PVE Skill 33 NEW
      "PVE Skill 33": {
         "name": 'Tenri Jindo',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7604dd447d3b450e4816e62d5bf4e2f83fafabc4.png',
         "job_icon": 'NIN',
         "level": '100',
         "classification": 'Ability',
         "cast": 'Instant',
         "recast": '1 сек.',
         "range": '20y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": '',
      },
      // Ninjutsu 01
      "Ninjutsu 01": {
         "name": 'Fuma Shuriken',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/be6fdb084ef5ffd556f82bf0f3e0bb0085adf53f.png',
         "job_icon": 'NIN',
         "level": '30',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Дальний удар ниндзюцу, наносящий урон с силой атаки 450.<br/>Комбинация мудр: одна любая Ten, Chi или Jin мудра<br/>При использовании активируется время восстановления боевых навыков, мудр и Ninjutsu.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // Ninjutsu 02
      "Ninjutsu 02": {
         "name": 'Katon',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c13292e99775bf7b834e9bf44eae59cdf977dc8c.png',
         "job_icon": 'NIN',
         "level": '35',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "range": '20y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон огнем с силой атаки 350 по цели и окружающим противникам.<br/>Комбинация мудр: Chi→Ten или Jin→Ten<br/>При использовании активируется время восстановления боевых навыков, мудр и Ninjutsu.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // Ninjutsu 03
      "Ninjutsu 03": {
         "name": 'Raiton',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1c5d9c8d2301016f0d1d7412cc5100a7e41de735.png',
         "job_icon": 'NIN',
         "level": '35',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "range": '20y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон молнией с силой атаки 650.<br/>Дополнительный эффект: накладывает стак Raiju Ready<br/>Продолжительность: 30 сек.<br/>Максимум стаков: 3<br/>Эффект Raiju Ready заканчивается при использовании любого боевого умения ближнего боя.<br/>Комбинация мудр: Ten→Chi или Jin→Chi<br/>При использовании активируется время восстановления боевых навыков, мудр и Ninjutsu.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // Ninjutsu 04
      "Ninjutsu 04": {
         "name": 'Hyoton',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c1f09309f06281706fd1a6f37051a97dc8fdfd4f.png',
         "job_icon": 'NIN',
         "level": '45',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон льдом с силой атаки 350.<br/>Дополнительный эффект: обездвиживает цель (bind)<br/>Продолжительность: 15 сек.<br/>Комбинация мудр: Ten→Jin или Chi→Jin<br/>Прерывает авто атаки при использовании умения.<br/>При использовании активируется время восстановления боевых навыков, мудр и Ninjutsu.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // Ninjutsu 05
      "Ninjutsu 05": {
         "name": 'Huton',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/52e16f75932d2dc542606dccf6b9a8ffdef35b5d.png',
         "job_icon": 'NIN',
         "level": '45',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Уменьшает время восстановления боевых навыков и задержку между авто атаками на 15%.<br/>Продолжительность: 60 сек.<br/>Комбинация мудр: Jin→Chi→Ten или Chi→Jin→Ten<br/>При использовании активируется время восстановления боевых навыков, мудр и Ninjutsu.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // Ninjutsu 06
      "Ninjutsu 06": {
         "name": 'Doton',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c4807f81a654f2b25cca49c1f61e9b3bc7df62d6.png',
         "job_icon": 'NIN',
         "level": '45',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Создает область проклятой земли, наносящую урон с силой атаки 80 всем противникам, входящим в область.<br/>Продолжительность: 18 сек.<br/>Дополнительный эффект: тяжесть (heavy) +40%<br/>Комбинация мудр: Ten→Jin→Chi или Jin→Ten→Chi<br/>При использовании активируется время восстановления боевых навыков, мудр и Ninjutsu.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // Ninjutsu 07
      "Ninjutsu 07": {
         "name": 'Suiton',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/fd706ad1980d3382fd9c64ffec7a0374d549d5cc.png',
         "job_icon": 'NIN',
         "level": '45',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "range": '20y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон водой с силой атаки 500.<br/>Дополнительный эффект: накладывает эффект Suiton<br/>Продолжительность: 20 сек.<br/>Эффект Suiton: позволяет использовать умения, которые требуют нахождения под действием Hidden, не находясь под этим эффектом<br/>Комбинация мудр: Ten→Chi→Jin или Chi→Ten→Jin<br/>Использование активирует время восстановления боевых навыков, мудр и Ninjutsu.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // Ninjutsu 08
      "Ninjutsu 08": {
         "name": 'Goka Mekkyaku',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/289a0bd6679306c587cb3bcf2f90a1ed6bfb1897.png',
         "job_icon": 'NIN',
         "level": '76',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "range": '20y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон огнем с силой атаки 600 по цели и всем окружающим противникам.<br/>Комбинация мудр: Chi→Ten или Jin→Ten<br/>Может использоваться только под действием эффекта Kassatsu.<br/>При использовании активируется время восстановления боевых навыков, мудр и Ninjutsu.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // Ninjutsu 09
      "Ninjutsu 09": {
         "name": 'Hyosho Ranryu',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a700c6a595b5f5ee272b5a3452f680497df8fabe.png',
         "job_icon": 'NIN',
         "level": '76',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон льдом с силой атаки 1,300.<br/>Комбинация мудр: Chi→Jin or Ten→Jin<br/>Может использоваться только под действием эффекта Kassatsu.<br/>При использовании активируется время восстановления боевых навыков, мудр и Ninjutsu.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // Trait 01
      "Trait 01": {
         "name": 'All Fours',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7c99182c1513f1a387f6a0b8d25ec630f3109fb9.png',
         "job_icon": 'ROG',
         "level": '14',
         "content": 'Снижает получаемый при падении урон.',
      },
      // Trait 02
      "Trait 02": {
         "name": 'Fleet of Foot',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a6cdfeaa6ad9084494fd2ad0eaea1e9701386e3c.png',
         "job_icon": 'ROG',
         "level": '20',
         "content": 'Увеличивает скорость передвижения.',
      },
      // Trait 03 NEW
      "Trait 03": {
         "name": 'Increase Attack Speed',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/6d96e09b096b18633938943d197373212d767009.png',
         "job_icon": 'ROG',
         "level": '45',
         "content": ' ',
      },
      // Trait 04
      "Trait 04": {
         "name": 'Adept Assassination',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/51342498a4d/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b87e949a34c52ddeba48178f74445dd578b6d8c9.png',
         "job_icon": 'NIN',
         "level": '56',
         "content": 'Улучшает умение Assassinate до Dream Within a Dream.',
      },
      // Trait 05
      "Trait 05": {
         "name": 'Shukiho',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ed4979c9bfae8fed8e478ff2ce14e88961c7d014.png',
         "job_icon": 'NIN',
         "level": '62',
         "content": 'Восполняет шкалу Ninki Gauge на 5 после успешного использования определенных боевых умений или завершения определенных комбо.',
      },
      // Trait 06
      "Trait 06": {
         "name": 'Enhanced Shukuchi',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/947645f8d561b8bc9d8102189d9c36d7bbf5a5b1.png',
         "job_icon": 'NIN',
         "level": '64',
         "content": 'Сбрасывает время восстановления Shukuchi после использования Katon, Raiton или Hyoton по большинству целей.',
      },
      // Trait 07 NEW
      "Trait 07": {
         "name": 'Mug Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f8789bead06bbb86cf1961b04271a275413ca68e.png',
         "job_icon": 'NIN',
         "level": '66',
         "content": ' ',
      },
      // Trait 08
      "Trait 08": {
         "name": 'Enhanced Shukuchi II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/0360c16afed0561315ba7bc311e7f4e29e061ddc.png',
         "job_icon": 'NIN',
         "level": '74',
         "content": 'Позволяет накапливать заряды для последовательного использования Shukuchi.<br/>Максимум зарядов: 2',
      },
      // Trait 09
      "Trait 09": {
         "name": 'Melee Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/bc58b07072e258883e9e584c4e45355d092da661.png',
         "job_icon": 'NIN',
         "level": '74',
         "content": 'Увеличивает силу атаки Gust Slash до 120, Aeolian Edge до 140 и Armor Crush до 140.',
      },
      // Trait 10
      "Trait 10": {
         "name": 'Enhanced Kassatsu',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d579d27b0f2e059f63390cb5bcc22bac26365149.png',
         "job_icon": 'NIN',
         "level": '76',
         "content": 'Улучшает умения Katon и Hyoton до Goka Mekkyaku и Hyosho Ranryu под действием эффекта Kassatsu.',
      },
      // Trait 11
      "Trait 11": {
         "name": 'Shukiho II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f907e0c1b9b1d0a739cf2438986fcd4a3b51175a.png',
         "job_icon": 'NIN',
         "level": '78',
         "content": 'Восполняет Ninki Gauge на 10 при успешном завершении комбо с Aeolian Edge или Armor Crush.',
      },
      // Trait 12
      "Trait 12": {
         "name": 'Shukiho III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d4af7caeb6ccefc6db10dcc03953e90b24824950.png',
         "job_icon": 'NIN',
         "level": '84',
         "content": 'Восполняет Ninki Gauge на 15 при успешном завершении комбо с Aeolian Edge или Armor Crush.',
      },
      // Trait 13
      "Trait 13": {
         "name": 'Melee Mastery II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/eb2173170fff9f761a656135293703a149717ede.png',
         "job_icon": 'NIN',
         "level": '84',
         "content": 'Увеличивает силу атаки Spinning Edge до 220 и Gust Slash до 160.',
      },
      // Trait 14
      "Trait 14": {
         "name": 'Enhanced Meisui',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c47e82ddc2a4148f8b8dbdcbad6277e8ff1c73e4.png',
         "job_icon": 'NIN',
         "level": '88',
         "content": 'Увеличивает силу атаки Bhavacakra до 500, пока персонаж находится под эффектом Meisui.<br />Продолжительность: 30 сек.',
      },
      // Trait 15
      "Trait 15": {
         "name": 'Enhanced Raiton',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/347d3667b142103093c59bc61db363a7f089ca69.png',
         "job_icon": 'NIN',
         "level": '90',
         "content": 'Накладывает стак Raiju Ready при использовании Raiton.<br/>Максимум стаков: 3<br/>Продолжительность: 30 сек.<br/>Эффект Raiju Ready заканчивается при использовании любого боевого навыка ближнего боя.',
      },
      // Trait 16 NEW
      "Trait 16": {
         "name": 'Trick Attack Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4ab2eab74e5f92060d2d1866451d9ebfe86204a7.png',
         "job_icon": 'NIN',
         "level": '92',
         "content": '',
      },
      // Trait 17 NEW
      "Trait 17": {
         "name": 'Melee Mastery III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/76ee293b5a8fae7dd16716bc05d79216ef2689a9.png',
         "job_icon": 'NIN',
         "level": '94',
         "content": '',
      },
      // Trait 18 NEW
      "Trait 18": {
         "name": 'Enhanced Dokumori',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f5e5d42f5d1ac030ce64650db8a0496edca66cd9.png',
         "job_icon": 'NIN',
         "level": '96',
         "content": '',
      },
      // Trait 19 NEW
      "Trait 19": {
         "name": 'Enhanced Ten Chi Jin',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5c06ede286225c8c52a672be5d631803f4fc4821.png',
         "job_icon": 'NIN',
         "level": '100',
         "content": '',
      },
      // PVP Skill 01
      "PVP Skill 01": {
         "name": 'Spinning Edge',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2c7a551985023f8a7d2e338a014ab29454318b81.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 3,000.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 02
      "PVP Skill 02": {
         "name": 'Gust Slash',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/443f61d91e3c8a64e725b7366c33c267f606c8b1.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 4,000.<br/>Комбо умение: Spinning Edge<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 03
      "PVP Skill 03": {
         "name": 'Aeolian Edge',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/baa12f591901930702230bc6e3e5119c194de1db.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 5,000.<br/>Комбо умение: Gust Slash<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 04
      "PVP Skill 04": {
         "name": 'Fuma Shuriken',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a4295da0185e15eaf0481b14d04e59133c8fc699.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "range": '20y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Дальний удар, наносящий урон с силой атаки 6,000.<br/>Максимум зарядов: 3<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями.<br/><br/>※Умение меняется на Hyosho Ranryu под действием эффекта Three Mudra.',
      },
      // PVP Skill 05
      "PVP Skill 05": {
         "name": 'Mug',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/0b093065502dad176d2b335b15528e1947bf806f.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 2,000.<br/>Дополнительный эффект: увеличивает получаемый целью урон на 10%.<br/>Продолжительность: 10 сек.<br/>Дополнительный эффект: уменьшает время повторного применения Fuma Shuriken на 10 сек.<br/><br/>※Умение меняется на Goka Mekkyaku под действием эффекта Three Mudra.',
      },
      // PVP Skill 06
      "PVP Skill 06": {
         "name": 'Three Mudra',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/df52e05ddb6ca5801114faf60e5ba05442c5cb6f.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Накладывает Three Mudra, позволяющие немедленно использовать любое умение ninjutsu. Однако одно и то же умение ninjutsu не может быть использовано последовательно.<br/>Продолжительность: 10 сек.<br/>Максимум зарядов: 2<br/><br/>※Умение меняется на Meisui под действием эффекта Three Mudra.<br/>※Все умения, кроме Seiton Tenchu, будут изменены на соответствующие умения ниндзюцу, под действием эффекта Three Mudra.',
      },
      // PVP Skill 07
      "PVP Skill 07": {
         "name": 'Bunshin',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/dd5359193e18dec8796cb164c2a31cd7de730e31.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '30 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'На пять атак тень персонажа становится живой и атакует противников каждый раз, когда используется боевой навык.<br/>Сила атаки тени будет равна силе атаки боевыми умениями персонажа, но будет уменьшена вдвое при использовании Fuma Shuriken или Assassinate.<br/>Продолжительность: 20 сек.<br/>Дополнительный эффект: создает тень, поглощающую урон, равный силе лечения 8,000<br/>Продолжительность: 10 сек.<br/><br/>※Умение меняется на Huton под действием эффекта Three Mudra.',
      },
      // PVP Skill 08
      "PVP Skill 08": {
         "name": 'Shukuchi',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/cf1bb42ed0500b95e768ec8fff4aa0f7b3d1c20a.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '20y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Персонаж быстро перемещается в указанное место.<br/>Дополнительный эффект: накладывает эффект Hidden<br/>Эффект Hidden: персонаж сливается с окружающим миром, становясь невидимым для противников и не давая выбрать в качестве цели<br/>Продолжительность: 4 сек.<br/>Эффект заканчивается при использовании любого умения или при получении урона от противника.<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.<br/><br/>※Умение меняется на Doton под действием эффекта Three Mudra.<br/>※Aeolian Edge Combo меняется на Assassinate под действием эффекта Hidden.',
      },
      // PVP Skill 09
      "PVP Skill 09": {
         "name": 'Forked Raiju',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4808fd0960ff552e382c3bc3242c43c4634b3a16.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '20y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Рывок к цели, наносящий урон с силой атаки 4,000.<br/>Дополнительный эффект: stun (оглушение)<br/>Продолжительность: 2 сек.<br/>Дополнительный эффект: накладывает Fleeting Raiju Ready<br/>Продолжительность: 10 сек.<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.<br/><br/>※Aeolian Edge Combo меняется на Fleeting Raiju под действием эффекта Fleeting Raiju Ready.<br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 10
      "PVP Skill 10": {
         "name": 'Fleeting Raiju',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/834c61d21d0517e99776d435f3125c0d856bff96.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '20y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Рывок к цели, наносящий урон с силой атаки 4,000.<br/>Дополнительный эффект: stun (оглушение)<br/>Продолжительность: 2 сек.<br/>Можно использовать только под действием эффекта Fleeting Raiju Ready.<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 11
      "PVP Skill 11": {
         "name": 'Hyosho Ranryu',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7b5b3ecb51c13a72c65bbb7dd48b6d702d546da9.png',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '20y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 16,000.<br/>Может быть использовано только под действием эффекта Three Mudra.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 12
      "PVP Skill 12": {
         "name": 'Goka Mekkyaku',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/8ecdf7edc6dd4e686813cdd58a5edcdf49e0404d.png',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '20y',
         "radius_img": 'R2',
         "radius": '6y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 4,000 по цели и всем окружающим противникам.<br/>Дополнительный эффект: периодический урон<br/>Сила атаки: 4,000<br/>DПродолжительность: 12 сек.<br/>Можно использовать только под действием эффекта Three Mudra.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 13
      "PVP Skill 13": {
         "name": 'Meisui',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/359bc1829d69bdbe859863cd2a782fbacc61de16.png',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Восстанавливает HP персонажу или выбранному сопартийцу.<br/>Сила лечения: 8,000<br/>Дополнительный эффект: накладывает на цель постепенное восстановление HP<br/>Сила лечения: 4,000<br/>Продолжительность: 15 сек.<br/>Можно использовать только под действием эффекта Three Mudra.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 14
      "PVP Skill 14": {
         "name": 'Huton',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/839919eb2756e950cdae46be906b564ce77bd4b6.png',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Накладывает эффект Huton, создавая барьер, поглощающий урон, равный силе лечения 16,000 и увеличивающий скорость передвижения на 25%.<br/>Продолжительность: 10 сек.<br/>Скорость передвижения возвращается к нормальной, когда барьер поглотит весь урон.<br/>Можно использовать только под действием эффекта Three Mudra.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 15
      "PVP Skill 15": {
         "name": 'Doton',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/8c6735eac69b6180ad6b23c92fc467a81701cf4a.png',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Создает под ногами персонажа область оскверненной земли, наносящей урон с силой атаки 3,000 по всем противникам, вошедшим в него.<br/>Продолжительность: 10 сек.<br/>Можно использовать только под действием эффекта Three Mudra.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 16
      "PVP Skill 16": {
         "name": 'Hollow Nozuchi',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d2a67da760022e80b85ba1ccbeeecdf8bddda757.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '-',
         "range": '100y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Все противники, находящиеся в области оскверненной земли Doton, получают дополнительный урон землей с силой атаки 3,000.<br/>Требуется использование боевого навыка, Hyosho Ranryu или Goka Mekkyaku<br/>Дополнительный эффект: тяжесть (heavy) +75%<br/>Продолжительность: 3 сек.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 17
      "PVP Skill 17": {
         "name": 'Assassinate',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/bd62134b59f61995abdfea2f7fee502c5795f9f9.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 12,000.<br/>Можно использовать только под действием эффекта Hidden.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 18
      "PVP Skill 18": {
         "name": 'Seiton Tenchu',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b3cc3f2b23553fa8ce5a4a46fe159c12a2f82aaa.png',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "range": '20y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Рывок к цели, наносящий удар с силой атаки 12,000, уничтожая противника, чье HP ниже 50%.<br/>Дополнительный эффект: накладывает на цель эффект Death Link<br/>Продолжительность: 4 сек.<br/>Убийство противника этим умением или под эффектом Death Link накладывает Unsealed Seiton Tenchu, позволяя повторно использовать умение.<br/>Продолжительность: 8 сек.<br/>Длительность эффекта уменьшается на 1 сек. каждый раз, когда он применяется к цели с минимальной продолжительностью 4 сек.<br/>Не действует на неигровых персонажей или игроков, находящихся в роботах.<br/>Может быть использовано только тогда, когда шкала лимит брейка (limit gauge) заполнена или под действием Unsealed Seiton Tenchu.<br/>Время зарядки шкалы: 105 сек.<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.',
      },
   };
   FILL_DB_VALUES(db);
   FILL_DB_SKILLS(db);
   FILL_DB_SKILLS_PASSIVE(db);
   FILL_DB_SKILLS_PVP(db);
   FILL_DB_SKILLS_MENU(db);
})();