(() =>{
   let db = {
      "PVE Update": `Последнее обновление: 27/06/2024`,
      "PVP Update": `Последнее обновление: 27/06/2024`,
      // PVE Skill 01
      "PVE Skill 01": {
         "name": 'Fast Blade',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/8325a7bb54f039c5bd3cd2af4430dccfd525e0b9.png',
         "job_icon": 'GLA',
         "level": '1',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": "3y",
         "radius_img": 'R1',
         "radius": "0y", 
         "content": 'Удар, наносящий урон с силой атаки 220.',
      },
      // PVE Skill 02
      "PVE Skill 02": {
         "name": 'Fight or Flight',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/87405b9b9f00d9957df252ea0116e4137bc4dbd1.png',
         "job_icon": 'GLA',
         "level": '2',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "cost": '-',
         "range": "0y",
         "radius_img": 'R1',
         "radius": "0y",
         "content": 'Увеличивает наносимый урон на 25%.<br>Продолжительность: 20 сек.<br>Дополнительный эффект: накладывает эффект Goring Blade Ready.<br>Продолжительность: 30 сек.',
      },
      // PVE Skill 03
      "PVE Skill 03": {
         "name": 'Riot Blade',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/bdda04f3b284e3cbf7d07e50d9bffb21b74ce869.png',
         "job_icon": 'GLA',
         "level": '4',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": "3y",
         "radius_img": 'R1',
         "radius": "0y",
         "content": 'Удар, наносящий урон с силой атаки 170.<br>Комбо умение: Fast Blade<br>Сила в комбо: 330<br>Комбо бонус: восстанавливает MP',
      },
      // PVE Skill 04
      "PVE Skill 04": {
         "name": 'Total Eclipse',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/07c42572697cdcf5381955b09ed7c3028be8a0bb.png',
         "job_icon": 'GLA',
         "level": '6',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": "0y",
         "radius_img": 'R2',
         "radius": "5y",
         "content": 'Удар, наносящий урон с силой атаки 100 по всем окружающим противникам.',
      },
      // PVE Skill 05
      "PVE Skill 05": {
         "name": 'Shield Bash',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/49cbc217420d69d69bb1bfcf6fba10358dcd2521.png',
         "job_icon": 'GLA',
         "level": '10',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": "3y",
         "radius_img": 'R1',
         "radius": "0y",
         "content": 'Удар, наносящий урон с силой атаки 100.<br>Дополнительный эффект: оглушение (stun)<br>Продолжительность: 6 сек.',
      },
      // PVE Skill 06
      "PVE Skill 06": {
         "name": 'Iron Will',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1e60c8b0c72bbc52497a163755dc855f5cdf7091.png',
         "job_icon": 'GLA',
         "level": '10',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "cost": '-',
         "range": "0y",
         "radius_img": 'R1',
         "radius": "0y",
         "content": 'Танковая стойка. Значительно повышает генерацию уровня угрозы.<br>Эффект спадает при повторном использовании.',
      },
      // PVE Skill 07
      "PVE Skill 07": {
         "name": 'Release Iron Will',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/0b880866e9d45ac7b9b664dcf536acc46ecb4679.png',
         "job_icon": 'GLA',
         "level": '10',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "cost": '-',
         "range": "0y",
         "radius_img": 'R1',
         "radius": "0y",
         "content": 'Отменяет эффект Iron Will.',
      },
      // PVE Skill 08
      "PVE Skill 08": {
         "name": 'Shield Lob',
         "eorzeadb": "https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/eaf9428dd8f/",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d95d796eae4df45f2419a8c6df1cdf4afc7b0523.png',
         "job_icon": 'GLA',
         "level": '15',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": "20y",
         "radius_img": 'R1',
         "radius": "0y",
         "content": 'Дальний удар, наносящий урон с силой атаки 100.<br>Дополнительный эффект: повышает уровень угрозы.',
      },
      // PVE Skill 09
      "PVE Skill 09": {
         "name": 'Rage of Halone',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b35b9fa5ce7169d660177032734661f18a79ee5b.png',
         "job_icon": 'GLA',
         "level": '26',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": "3y",
         "radius_img": 'R1',
         "radius": "0y",
         "content": 'Удар, наносящий урон с силой атаки 100.<br>Комбо умение: Riot Blade<br>Сила в комбо: 330',
      },
      // PVE Skill 10
      "PVE Skill 10": {
         "name": 'Spirits Within',
         "eorzeadb": "https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/90a79bf83dc/",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d7e7cf097286ae99e6637242596a14832a9edf8f.png',
         "job_icon": 'PLD',
         "level": '30',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '30 сек.',
         "cost": '-',
         "range": "3y",
         "radius_img": 'R1',
         "radius": "0y",
         "content": 'Удар, наносящий урон с силой атаки 270.<br>Дополнительный эффект: восстанавливает MP',
      },
      // PVE Skill 11
      "PVE Skill 11": {
         "name": 'Sheltron',
         "eorzeadb": "https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/8e6b7dd4c72/",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e622516a93fd2298b9fd40e0d2d60c3fc8485c5a.png',
         "job_icon": 'PLD',
         "level": '35',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '5 сек.',
         "cost": '-',
         "range": "0y",
         "radius_img": 'R1',
         "radius": "0y",
         "content": 'Снижает получаемый урон на 15%.<br>Продолжительность: 6 сек.<br>Стоимость: 50 Oath Gauge',
      },
      // PVE Skill 12
      "PVE Skill 12": {
         "name": 'Sentinel',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/913eb4344bb6c8710f250115fa22484b026f08bd.png',
         "job_icon": 'GLA',
         "level": '38',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "cost": '-',
         "range": "0y",
         "radius_img": 'R1',
         "radius": "0y",
         "content": 'Снижает получаемый урон на 30%.<br>Продолжительность: 15 сек.',
      },
      // PVE Skill 13
      "PVE Skill 13": {
         "name": 'Prominence',
         "eorzeadb": "https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/16d122e30f6/",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c0f8a1aa0ba0a20c0d8580e63932678c5c4a8b9b.png',
         "job_icon": 'PLD',
         "level": '40',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": "0y",
         "radius_img": 'R2',
         "radius": "5y",
         "content": 'Удар, наносящий урон с силой атаки 100 по всем окружающим противникам.<br>Комбо умение: Total Eclipse<br>Сила атаки с комбо: 170<br>Комбо бонус: восстанавливает MP<br>Комбо бонус: накладывает эффект Divine Might<br>Эффект Divine Might: позволяет применить Holy Spirit or Holy Circle с повышенной силой атаки. Эффект пропадает после использования<br>Продолжительность: 30 сек.',
      },
      // PVE Skill 14
      "PVE Skill 14": {
         "name": 'Cover',
         "eorzeadb": "https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/de79d3a7ff9/",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/81b581992c0df5ad867ed18ad229f6d6f7fd3eea.png',
         "job_icon": 'PLD',
         "level": '45',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "cost": '-',
         "range": "10y",
         "radius_img": 'R1',
         "radius": "0y",
         "content": 'Забирает весь урон направленный на сопартийца, до тех пор, пока он находится в радиусе 10 ялмов.<br>Не срабатывает на некоторые атаки.<br>Продолжительность: 12 сек.<br>Стоимость: 50 Oath Gauge',
      },
      // PVE Skill 15
      "PVE Skill 15": {
         "name": 'Circle of Scorn',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/af5ddb89ddd5ade6706afe571f45aa6028e1925b.png',
         "job_icon": 'GLA',
         "level": '50',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '30 сек.',
         "cost": '-',
         "range": "0y",
         "radius_img": 'R2',
         "radius": "5y",
         "content": 'Удар, наносящий урон с силой атаки 140 по всем окружающим противникам.<br>Дополнительный эффект: периодический урон<br>Сила периодического урона: 30<br>Продолжительность: 15 сек.',
      },
      // PVE Skill 16
      "PVE Skill 16": {
         "name": 'Hallowed Ground',
         "eorzeadb": "https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/406b25707e6/",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/249bf48c39ec44b9b32f0681ea256850ed6aa8f8.png',
         "job_icon": 'PLD',
         "level": '50',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '420 сек.',
         "cost": '-',
         "range": "0y",
         "radius_img": 'R1',
         "radius": "0y",
         "content": 'Даёт неуязвимость против большинства атак.<br>Продолжительность: 10 сек.',
      },
      // PVE Skill 17
      "PVE Skill 17": {
         "name": 'Bulwark',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b0a3dcb47763055bc61ee9f90ba0ee3b46050197.png',
         "job_icon": 'PLD',
         "level": '52',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '90 сек.',
         "cost": '-',
         "range": "0y",
         "radius_img": 'R1',
         "radius": "0y",
         "content": 'Блокирует входящие атаки.<br>Продолжительность: 10 сек.',
      },
      // PVE Skill 18
      "PVE Skill 18": {
         "name": 'Goring Blade',
         "eorzeadb": "https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/afaf0c9a7c5/",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/eb067afbfb5a4198760b2e28e9c3cf669d9866b8.png',
         "job_icon": 'PLD',
         "level": '54',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": "3y",
         "radius_img": 'R1',
         "radius": "0y",
         "content": 'Удар, наносящий урон с силой атаки 700.<br>Может быть использовано только под действием эффекта Goring Blade Ready.<br>Этот боевой навык не имеет общего время восстановления с другими умениями.',
      },
      // PVE Skill 19
      "PVE Skill 19": {
         "name": 'Divine Veil',
         "eorzeadb": "https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/6948068d18e/",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/495faab61344751872ca0867e2d5e59b04c6940c.png',
         "job_icon": 'PLD',
         "level": '56',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '90 сек.',
         "cost": '-',
         "range": "0y",
         "radius_img": 'R2',
         "radius": "30y",
         "content": 'Создает барьер вокруг персонажа и всех ближийших сопартийцев, который поглощает урон, равный 10% от максимального HP персонажа.<br>Продолжительность: 30 сек.<br>Дополнительный эффект: восстанавливает HP цели<br>Сила лечения: 400',
      },
      // PVE Skill 20
      "PVE Skill 20": {
         "name": 'Clemency',
         "eorzeadb": "https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/7f095beca39/",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/3c20e8bf8f5f130db398ac4ba5df14e403b7666a.png',
         "job_icon": 'PLD',
         "level": '58',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '2000 MP',
         "range": "30y",
         "radius_img": 'R1',
         "radius": "0y",
         "content": 'Восстанавливает HP цели.<br>Сила лечения: 1,000<br>Дополнительный эффект: восстанавливает себе 50% от HP восстановленных цели, если цель является сопартийцем',
      },
      // PVE Skill 21
      "PVE Skill 21": {
         "name": 'Royal Authority',
         "eorzeadb": "https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/d29b8150228/",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/3fe523f08ebd0b93125ae42d5bcf8e18dce08a02.png',
         "job_icon": 'PLD',
         "level": '60',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": "3y",
         "radius_img": 'R1',
         "radius": "0y",
         "content": 'Удар, наносящий урон с силой атаки 180.<br>Комбо умение: Riot Blade<br>Сила в комбо: 440<br>Комбо бонус: накладывает эффект Atonement Ready<br>Продолжительность: 30 сек.<br>Комбо бонус: накладывает эффект Divine Might<br>Эффект Divine Might: позволяет применить Holy Spirit or Holy Circle с повышенной силой атаки. Эффект пропадает после использования<br>Продолжительность: 30 сек.',
      },
      // PVE Skill 22
      "PVE Skill 22": {
         "name": 'Intervention',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/fdb9b8347b33dae63e25debeab15aa75c270f39a.png',
         "job_icon": 'PLD',
         "level": '62',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "cost": '-',
         "range": "30y",
         "radius_img": 'R1',
         "radius": "0y",
         "content": `Снижает урон получаемый выбранным сопартийцем на 10%.<br>Продолжительность: 8 сек.<br>Дополнительный эффект: увеличивает снижаемый урона на дополнительные 10%, если на персонаже наложен эффект от Rampart или Guardian<br>Дополнительный эффект: накладывает на выбранного сопартийца эффект Knight's Resolve<br>Эффект Knight's Resolve: уменьшает получаемый урон на 10%<br>Продолжительность: 4 сек.<br>Дополнительный эффект: накладывает на выбранного сопартийца эффект Knight's Benediction<br>Эффект Knight's Benediction: постепенно восстанавливает HP<br>Сила лечения: 250<br>Продолжительность: 12 сек.<br>Стоимость: 50 Oath Gauge`,
      },
      // PVE Skill 23
      "PVE Skill 23": {
         "name": 'Holy Spirit',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b8ad098c5afaad79a847f3fb79298456c1e9d689.png',
         "job_icon": 'PLD',
         "level": '64',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '1000 MP',
         "range": "25y",
         "radius_img": 'R1',
         "radius": "0y",
         "content": 'Удар, наносящий нестихийный урон с силой атаки 370.<br>Сила атаки под эффектом Divine Might: 470<br>Сила атаки под эффектом Requiescat: 670<br>Эффект Divine Might будет иметь приоритет над эффектом Requiescat при нахождении под действием обоих.<br>Дополнительный эффект: восстанавливает HP персонажа<br>Сила лечения: 400',
      },
      // PVE Skill 24
      "PVE Skill 24": {
         "name": 'Requiescat',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/acbcd4de5a1839e4fd8c96ae05eb4109caed9ca1.png',
         "job_icon": 'PLD',
         "level": '68',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "cost": '-',
         "range": "3y",
         "radius_img": 'R1',
         "radius": "0y",
         "content": 'Удар, наносящий нестихийный урон с силой атаки 320.<br>Дополнительный эффект: накладывает 4 стака эффекта Requiescat<br>Эффект Requiescat: увеличивает силу Holy Spirit, Holy Circle и всех умений комбо Confiteor, а также делает все заклинания мгновенными<br>Дополнительный эффект: накладывает эффект Confiteor Ready. Эффект пропадает после использования<br>Продолжительность: 30 сек.',
      },
      // PVE Skill 25
      "PVE Skill 25": {
         "name": 'Passage of Arms',
         "eorzeadb": "https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/9193a6f1c9c/",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b570dfda793945b3bb8fddef02b1a865b8a04b32.png',
         "job_icon": 'PLD',
         "level": '70',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "cost": '-',
         "range": "0y",
         "radius_img": 'R3',
         "radius": "8y",
         "content": 'Увеличивает шанс блока до 100% и создает область в форме конуса позади персонажа, снижающую нанесенный вашим сопартийцам урон до 85%. Эффект активен только если сопартийцы находятся в области действия умения.<br>Продолжительность: 18 сек.<br>Эффект спадет при использовании умений или перемещении персонажа (включая разворот в другие стороны).<br>Прерывает авто атаки при использовании умения.',
      },
      // PVE Skill 26
      "PVE Skill 26": {
         "name": 'Holy Circle',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/afd455f208e2720a10a1b26e9a231fefac4d5be7.png',
         "job_icon": 'PLD',
         "level": '72',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '1000 MP',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 100 по всем окружающим противникам.<br>Сила атаки под эффектом Divine Might: 200<br>Сила атаки под эффектом Requiescat: 300<br>Эффект Divine Might будет иметь приоритет над эффектом Requiescat, при нахождении под действием обоих<br>Дополнительный эффект: восстанавливает HP персонажа<br>Сила лечения: 400',
      },
      // PVE Skill 27
      "PVE Skill 27": {
         "name": 'Intervene',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c841f5c954aa4e31bd1d82ffd00f863eb944a386.png',
         "job_icon": 'PLD',
         "level": '74',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '30 сек.',
         "cost": '-',
         "range": '20y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Рывок к цели, наносящий урон с силой атаки 150.<br>Максимум зарядов: 2<br>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.',
      },
      // PVE Skill 28
      "PVE Skill 28": {
         "name": 'Atonement',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f59cb1517f2f26c490a87d58366b5bccff372f19.png',
         "job_icon": 'PLD',
         "level": '76',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 440.<br>Дополнительный эффект: восстанавливает MP<br>Накладывает эффект Supplication Ready<br>Продолжительность: 30 сек.<br>Умение может быть выполнено только под действием эффекта Atonement Ready.',
      },
      // PVE Skill 29 NEW
      "PVE Skill 29": {
         "name": 'Supplication',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a13b67a351de7eaf60e51a8662e722785ec3826f.png',
         "job_icon": 'PLD',
         "level": '76',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 460.<br>Дополнительный эффект: восстанавливает MP.<br>Дополнительный эффект: накладывает эффект Sepulcher Ready<br>Продолжительность: 30 сек.<br>Может быть использовано только под действием эффекта Supplication Ready.<br><br>※Это умение нельзя поместить на хотбар.<br>※Atonement меняется на Supplication при соблюдении требований к выполнению.',
      },
      // PVE Skill 30 NEW
      "PVE Skill 30": {
         "name": 'Sepulchre',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/445847900654988d4b1a2950d57f69793a425d00.png',
         "job_icon": 'PLD',
         "level": '76',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 480.<br>Дополнительный эффект: восстанавливает MP<br>Может быть использовано только под действием эффекта Sepulcher Ready.<br><br>※Это умение нельзя поместить на хотбар.<br>※Supplication меняется на Sepulcher при соблюдении требований к выполнению.',
      },
      // PVE Skill 31
      "PVE Skill 31": {
         "name": 'Confiteor',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/362579dcb6dc2b7c9ea6eac6917c7b9c61f7ce1b.png',
         "job_icon": 'PLD',
         "level": '80',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '1000 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон по цели и по всем окружающим противникам с силой атаки 440 для первого и на 50% меньше для всех остальных.<br>Сила атаки Requiescat: 940<br>Дополнительный эффект: восстанавливает HP<br>Сила лечения: 400<br>Может быть использовано только под действием эффекта Confiteor Ready. Эффект спадет после использования.',
      },
      // PVE Skill 32
      "PVE Skill 32": {
         "name": 'Holy Sheltron',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c856abb6dac68e4bfd6cbb98b309360cb6162ced.png',
         "job_icon": 'PLD',
         "level": '82',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '5 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": `Снижает получаемый урон на 15%.<br>Продолжительность: 8 сек.<br>Дополнительный эффект: накладывает эффект Knight's Resolve<br>Эффект Knight's Resolve: уменьшает получаемый урон на 15%<br>Продолжительность: 4 сек.<br>Дополнительный эффект: накладывает эффект Knight's Benediction<br>Эффект Knight's Benediction: постепенное восстанавливает HP<br>Сила лечения: 250<br>Продолжительность: 12 сек.<br>Стоимость: 50 Oath Gauge`,
      },
      // PVE Skill 33
      "PVE Skill 33": {
         "name": 'Expiacion',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5e4beef5d32f45954a62524cdebb8d535de32921.png',
         "job_icon": 'PLD',
         "level": '86',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '30 сек.',
         "cost": '-',
         "range": '3y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон по цели и по всем окружающим противникам с силой атаки 450 для первого и на 60% меньше для всех остальных.<br>Дополнительный эффект: восстанавливает MP',
      },
      // PVE Skill 34
      "PVE Skill 34": {
         "name": 'Blade of Faith',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/004ab8b8fc5c3fe5b362bf7f0e35f9ab9a91918a.png',
         "job_icon": 'PLD',
         "level": '90',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '1000 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон по цели и по всем окружающим противникам с силой 240 для первого и на 50% меньше для всех остальных.<br>Сила атаки под эффектом Requiescat: 740<br>Комбо умение: Confiteor<br>Дополнительный эффект: восстанавливает HP персонажа<br>Сила лечения: 400<br><br>※Это умение нельзя поместить на хотбар.<br>※Confiteor меняется на Blade of Faith при соблюдении требований к выполнению.',
      },
      // PVE Skill 35
      "PVE Skill 35": {
         "name": 'Blade of Truth',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/31fd8e8a1827a2f830335a67cf52abb191d62485.png',
         "job_icon": 'PLD',
         "level": '90',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '1000 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон по цели и по всем окружающим противникам с силой 340 для первого и на 50% меньше для всех остальных.<br>Сила атаки под эффектом Requiescat: 840<br>Комбо умение: Blade of Faith<br>Дополнительный эффект: восстанавливает HP персонажа<br>Сила лечения: 400<br><br>※Это умение нельзя поместить на хотбар.<br>※Blade of Faith меняется на Blade of Truth при соблюдении требований к выполнению.',
      },
      // PVE Skill 36
      "PVE Skill 36": {
         "name": 'Blade of Valor',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/289629a47afee95a9d05e38bcc68a2b7fdd1cacd.png',
         "job_icon": 'PLD',
         "level": '90',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '1000 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон по цели и по всем окружающим противникам с силой 440 для первого и на 50% меньше для всех остальных.<br>Сила атаки под эффектом Requiescat: 940<br>Комбо умение: Blade of Truth<br>Дополнительный эффект: восстанавливает HP персонажа<br>Сила лечения: 400<br>Дополнительный эффект: накладывает эффект Blade of Honor Ready<br>Продолжительность: 30 сек.<br><br>※Это умение нельзя поместить на хотбар.<br>※Blade of Truth меняется на Blade of Valor при соблюдении требований к выполнению.',
      },
      // PVE Skill 37 NEW
      "PVE Skill 37": {
         "name": 'Guardian',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4c5945e5decd30562898378c54cc3308aa210ff1.png',
         "job_icon": 'PLD',
         "level": '92',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Уменьшает получаемый урон на 40%.<br>Продолжительность: 15 сек.<br>Дополнительный эффект: создает барьер, предотвращающий получение урона, эквивалентный исцелению силой 1,000<br>Продолжительность: 15 сек.',
      },
      // PVE Skill 38 NEW
      "PVE Skill 38": {
         "name": 'Imperator',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a888fa731d0d80fd277caa00abbca126be5b0b3c.png',
         "job_icon": 'PLD',
         "level": '96',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон по цели и по всем окружающим противникам с силой 580 для первого и на 50% меньше для всех остальных.<br>Дополнительный эффект: накладывает 4 стака Requiescat<br>Продолжительность: 30 сек.<br>Эффект Requiescat: увеличивает силу Holy Spirit, Holy Circle и всех умений комбо Confiteor, а также делает все заклинания мгновенными<br>Дополнительные эффекты: накладывает эффект Confiteor Ready<br>Продолжительность: 30 сек.',
      },
      // PVE Skill 39 NEW
      "PVE Skill 39": {
         "name": 'Blade of Honor',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/18481cd008426e41c0773107a91b20e2b9d59f7e.png',
         "job_icon": 'PLD',
         "level": '100',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон по цели и по всем окружающим противникам с силой 1,000 для первого и на 50% меньше для всех остальных.<br>Может быть использовано только под действием эффекта Blade of Honor Ready.<br><br>※Это умение нельзя поместить на хотбар.<br>※Imperator меняется на Blade of Honor при соблюдении требований к выполнению.',
      },
      // Trait 01
      "Trait 01": {
         "name": 'Tank Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b6414caac03c831ec90c34e501e444031d44003c.png',
         "job_icon": 'GLA',
         "level": '1',
         "content": 'Снижает получаемый урон на 20%. Также персонаж получает бонус к максимальному количеству HP в зависимости от значения выносливости (vitality) и бонус к урону в зависимости от значения силы (strength).',
      },
      // Trait 02
      "Trait 02": {
         "name": 'Oath Mastery',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/8e6b7dd4c72/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/3ea4bdf5de4ff4d7d14041fd6caa625d68c131cd.png',
         "job_icon": 'PLD',
         "level": '35',
         "content": 'Восполняет ресурс шкалы Oath Gauge на 5 при каждой авто атаке.',
      },
      // Trait 04 NEW обновить цифру с 4 на 3
      "Trait 04": {
         "name": 'Enhanced Fight or Flight',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/afaf0c9a7c5/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/bd891a4170937927986328cf502585a6a20d3f65.png',
         "job_icon": 'PLD',
         "level": '54',
         "content": 'Накладывает эффект Goring Blade Ready при использовании Fight or Flight.<br>Продолжительность: 30 сек.',
      },
      // Trait 03
      "Trait 03": {
         "name": 'Chivalry',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/303132af0562c1741746d382e2e7060032436afa.png',
         "job_icon": 'PLD',
         "level": '58',
         "content": 'Восстанавливает MP при использовании умения Riot Blade или Spirits Within.',
      },
      // Trait 05
      "Trait 05": {
         "name": 'Rage of Halone Mastery',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/d29b8150228/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/8f37467dd4cd7e208aa4d5d2dba1481e5b330438.png',
         "job_icon": 'PLD',
         "level": '60',
         "content": 'Улучшает умение Rage of Halone до Royal Authority.',
      },
      // Trait 06
      "Trait 06": {
         "name": 'Divine Magic Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/12b652e6942ca7d5fcf19e7b2473c1ce8654b0d9.png',
         "job_icon": 'PLD',
         "level": '64',
         "content": 'Сокращает затраты MP для всех заклинаний, а также предотвращает прерывание чтения заклинания после получения урона. Накладывает следующие эффекты после успешного завершения комбо с Royal Authority:<br>Комбо бонус: накладывает эффект Divine Might<br>Эффект Divine Might: позволяет мгновенно применить умение Holy Spirit or Holy Circle с повышенной силой атаки<br>Продолжительность: 30 сек.',
      },
      // Trait 07
      "Trait 07": {
         "name": 'Enhanced Prominence',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/413518284f7ac59252bf26c3da7493fcae6c5b35.png',
         "job_icon": 'PLD',
         "level": '72',
         "content": 'Накладывает следующие эффекты после успешного завершения комбо с Prominence:<br>Комбо бонус: восстанавливает MP<br>Комбо бонус: накладывает эффект Divine Might<br>Эффект Divine Might: позволяет мгновенно применить умение Holy Spirit or Holy Circle с повышенной силой атаки<br>Продолжительность: 30 сек.',
      },
      // Trait 08
      "Trait 08": {
         "name": 'Enhanced Sheltron',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/3d00586a157017225c57713dde5d1d17f8745086.png',
         "job_icon": 'PLD',
         "level": '74',
         "content": 'Увеличивает продолжительность умения Sheltron до 6 сек.',
      },
      // Trait 09
      "Trait 09": {
         "name": 'Sword Oath',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7abcc7ab50300a442c5f0aa68261b9730a2070c0.png',
         "job_icon": 'PLD',
         "level": '76',
         "content": 'Накладывает эффект Atonement Ready после успешного завершения комбо с Royal Authority.<br>Продолжительность: 30 сек.',
      },
      // Trait 10
      "Trait 10": {
         "name": 'Enhanced Requiescat',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/894b41ba20cd94ed36fd681d9729d21ba7e22052.png',
         "job_icon": 'PLD',
         "level": '80',
         "content": 'Накладывает эффект Confiteor Ready после использования Requiescat.<br>Продолжительность: 30 сек.',
      },
      // Trait 11
      "Trait 11": {
         "name": 'Sheltron Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5727377cab202a9ba787318ec8694067e837a8a2.png',
         "job_icon": 'PLD',
         "level": '82',
         "content": 'Улучшает умение Sheltron до Holy Sheltron.',
      },
      // Trait 12
      "Trait 12": {
         "name": 'Enhanced Intervention',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7d8cd4ab4588bc9d68b8436b378563d590dae1e8.png',
         "job_icon": 'PLD',
         "level": '82',
         "content": `Увеличивает продолжительность умения Intervention до 8 секунд.<br>Накладывает эффект Knight's Resolve на выбранного сопартийца, снижая получаемый урон на 10%<br>Продолжительность: 4 сек.<br>Накладывает эффект Knight's Benediction на выбранного сопартийца, постепенно восстанавливающий HP<br>Сила лечения: 250<br>Продолжительность: 12 сек.`,
      },
      // Trait 13
      "Trait 13": {
         "name": 'Divine Magic Mastery II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/3d7131e2d50c6b43898deadb212e3c58fedc2a87.png',
         "job_icon": 'PLD',
         "level": '84',
         "content": 'Добавляет исцеляющий эффект умениям Holy Spirit, Holy Circle и Confiteor.<br>Сила лечения: 400',
      },
      // Trait 14
      "Trait 14": {
         "name": 'Melee Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/bc58b07072e258883e9e584c4e45355d092da661.png',
         "job_icon": 'PLD',
         "level": '84',
         "content": 'Увеличивает силу атаки умениям Fast Blade до 200, Riot Blade до 140, Royal Authority до 140, Holy Spirit до 350, Atonement до 400, Supplication до 420 и Sepulcher до 440.',
      },
      // Trait 15
      "Trait 15": {
         "name": 'Spirits Within Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/8f8d91cf706370a9295a3a9495713a18e9a84e37.png',
         "job_icon": 'PLD',
         "level": '86',
         "content": 'Улучшает умение Spirits Within до Expiacion.',
      },
      // Trait 16
      "Trait 16": {
         "name": 'Enhanced Divine Veil',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7cdd930171cd46b5dae53f059704d0db413a7e82.png',
         "job_icon": 'PLD',
         "level": '88',
         "content": 'Добавляет исцеляющий эффект для умения Divine Veil.<br>Сила лечения: 400',
      },
      // Trait 17 NEW
      "Trait 17": {
         "name": 'Sentinel Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b04967e1f3a9990b5c01ac4b3bb950cbc1bd0392.png',
         "job_icon": 'PLD',
         "level": '92',
         "content": 'Улучшает умение Sentinel до Guardian.',
      },
      // Trait 18 NEW
      "Trait 18": {
         "name": 'Melee Mastery II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b60557edca3b093463f0f0c0c04dc3895855e9f8.png',
         "job_icon": 'PLD',
         "level": '94',
         "content": 'Увеличивает силу атаки умениям Fast Blade до 220, Riot Blade до 170, Royal Authority до 180, Holy Spirit до 370, Atonement до 440, Supplication до 460, Sepulcher до 480, Confiteor до 440, Blade of Faith до 240, Blade of Truth до 340 и Blade of Valor до 440.',
      },
      // Trait 19 NEW
      "Trait 19": {
         "name": 'Requiescat Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/416e440b4f9346f24141890f736f6f2838363de4.png',
         "job_icon": 'PLD',
         "level": '96',
         "content": 'Улучшает умение Requiescat до Imperator.',
      },
      // Trait 20 NEW
      "Trait 20": {
         "name": 'Enhanced Blade of Valor',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/92d476e84bdd9b49ab34c50058430c0dd4c25930.png',
         "job_icon": 'PLD',
         "level": '100',
         "content": 'Накладывает эффект Blade of Honor Ready при использовании Blade of Valor.<br>Продолжительность: 30 сек.<br>Imperator меняется на Blade of Honor, пока находится под действием эффекта Blade of Honor Ready.',
      },
      // PVP Skill 01
      "PVP Skill 01": {
         "name": 'Fast Blade',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b6e3e8407297c7ddfdb89ded7805c1bf3f686763.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.4 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 3,000.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 02
      "PVP Skill 02": {
         "name": 'Riot Blade',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/16fb67b5a63cab9b4b6ac910d446c8ef975add39.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.4 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 4,000.<br/>Комбо умение: Fast Blade<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 03
      "PVP Skill 03": {
         "name": 'Royal Authority',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/fa5810b4d52f18313e35508984d1c36008b6a214.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.4 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 5,000.<br/>Комбо умение: Riot Blade<br/>Дополнительный эффект: дает стак пассивного умения Sword Oath, вплоть до 3<br/>Продолжительность: 10 сек.<br/><br/>※Combo Royal Authority меняется на Atonement под действием эффекта Sword Oath.<br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 04
      "PVP Skill 04": {
         "name": 'Confiteor',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/89abaf2266f70e33e486e6cf5ff338ade9719786.png',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 12,000 по цели и всем противника рядом с ней.<br/>Дополнительный эффект: накладывает на цель эффект Sacred Claim<br/>Sacred Claim эффект: восстановление HP при успешной атаке по целям, находящимся под этим эффектом<br/>Сила лечения: 3,000<br/>Продолжительность: 10 сек.<br/>Это умение не имеет общего время восстановления с другими умениями.',
      },
      // PVP Skill 05
      "PVP Skill 05": {
         "name": 'Shield Bash',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ba245ce78b36cd3064eb986634a224aff58cf31b.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 4,000.<br/>Дополнительный эффект: оглушение (stun).<br/>Продолжительность: 3 сек.<br/>Дополнительный эффект: дает стак пассивного умения Sword Oath, вплоть до 3<br/>Продолжительность: 10 сек.<br/><br/>※Combo Royal Authority меняется на Atonement, пока находится под действием эффекта Sword Oath.',
      },
      // PVP Skill 06
      "PVP Skill 06": {
         "name": 'Intervene',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/dc0a7f454aeb6fa8cf680d223f5b97ba6c768955.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "range": '20y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Рывок к цели, наносящий урон с силой атаки 2,000.<br/>Дополнительный эффект: дает стак пассивного умения Sword Oath, вплоть до 3<br/>Продолжительность: 10 сек.<br/>Максимум зарядов: 2<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.<br/><br/>※Combo Royal Authority меняется на Atonement, пока находится под действием эффекта Sword Oath.',
      },
      // PVP Skill 07
      "PVP Skill 07": {
         "name": 'Guardian',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/058522fdb7c58e87b3ba52f85c1cb70f5c0501e8.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '25 сек.',
         "range": '20y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Рывок в сторону выбранного сопартийца.<br/>Дополнительный эффект: принимает на себя весь урон, предназначенный сопартийцу<br/>Продолжительность: 10 сек.<br/>Может быть использовано только тогда, когда сопартиец находится на расстоянии менее 10 ялмов.<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.<br/>Невозможно использовать на цели, взаимодействующие с объектами.',
      },
      // PVP Skill 08
      "PVP Skill 08": {
         "name": 'Holy Sheltron',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/473ed65d458df3b6e6eaf3404009bac010a592d0.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": `Накладывает на персонажа эффекты Holy Sheltron and Knight's Resolve.<br/>Эффект Holy Sheltron: создает барьер вокруг персонажа, который поглощает урон, равный исцелению силой 8,000<br/>Продолжительность: 4 сек.<br/>Если барьер не разрушен к моменту истечения эффекта, то он наносит стихийный урон всем окружающим противникам с силой атаки, равной 150% от оставшейся прочности барьера.<br/>Эффект Knight's Resolve: снижает получаемый урон на 20%<br/>Продолжительность: 8 сек.<br/>Дополнительный эффект: тяжесть (heavy) +75%<br/>Продолжительность: 5 сек.`,
      },
      // PVP Skill 09
      "PVP Skill 09": {
         "name": 'Atonement',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/35a45eefc453b71019fda6740cfc01c51f3d3a03.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.4 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 8,000.<br/>Дополнительный эффект: восстановление HP<br/>Сила лечения: 4,000<br/>Может быть использовано только под действием эффекта пассивного умения Sword Oath.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 10
      "PVP Skill 10": {
         "name": 'Blade of Faith',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2f944d27fc3705822d461cd9e46ae2c288c80ee8.png',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.4 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 7,000 по цели и всем противникам рядом с ней.<br/>Дополнительный эффект: сила атаки увеличивается на 50%, когда цель находится под действием эффекта Sacred Claim<br/>Дополнительный эффект: накладывает на цель эффект Sacred Claim<br/>Эффект Sacred Claim: восстанавливает HP при успешной атаке по целям, находящихся под этим эффектом<br/>Сила лечения: 3,000<br/>Продолжительность: 10 сек.<br/>Возможно использовать только под действием умения Blade of Faith Ready.<br/><br/>※Умения меняется на Blade of Truth после использования.<br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 11
      "PVP Skill 11": {
         "name": 'Blade of Truth',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/0f4597a0f6f40a77de83b1ce656d81345a5613ef.png',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.4 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 8,000 по цели и всем противникам рядом с ней.<br/>Дополнительный эффект: сила атаки увеличивается на 50%, когда цель находится под действием эффекта Sacred Claim<br/>Комбо умение: Blade of Faith<br/>Дополнительный эффект: накладывает на цель эффект Sacred Claim<br/>Эффект Sacred Claim: восстанавливает HP при успешной атаке по целям, находящихся под этим эффектом<br/>Сила лечения: 3,000<br/>Продолжительность: 10 сек.<br/><br/>※Умения меняется на Blade of Valor после использования.<br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 12
      "PVP Skill 12": {
         "name": 'Blade of Valor',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/115a30be11fa866d366d36b07d8542a0efd667bb.png',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.4 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 9,000 по цели и всем противникам рядом с ней.<br/>Дополнительный эффект: сила атаки увеличивается на 50%, когда цель находится под действием эффекта Sacred Claim<br/>Комбо умение: Blade of Truth<br/>Дополнительный эффект: накладывает на цель эффект Sacred Claim<br/>Эффект Sacred Claim: восстанавливает HP при успешной атаке по целям, находящихся под этим эффектом<br/>Сила лечения: 3,000.<br/>Продолжительность: 10 сек.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 13
      "PVP Skill 13": {
         "name": 'Phalanx',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a94e3555b79c68a9eb7f5ca496bcac7ef7fdcbcf.png',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '15y',
         "content": 'Накладывает эффект Hallowed Ground на себе и эффект Phalanx на ближайших сопартийцев.<br/>Эффект Hallowed Ground: дает персонажу неуязвимость против большинства атак<br/>Продолжительность: 10 сек.<br/>Эффект Phalanx: снижаем получаемый урон на 33%<br/>Продолжительность: 10 сек.<br/>Дополнительный эффект: накладывает эффект Blade of Faith Ready<br/>Продолжительность: 10 сек.<br/>Может быть использовано только тогда, когда шкала лимит брейка (limit gauge) заполнена.<br/>Время зарядки шкалы: 120 сек.<br/><br/>※Умение меняется на Blade of Faith при использовании.',
      },
   };
   FILL_DB_VALUES(db);
   FILL_DB_SKILLS(db);
   FILL_DB_SKILLS_PASSIVE(db);
   FILL_DB_SKILLS_PVP(db);
   FILL_DB_SKILLS_MENU(db);
})();