(() =>{
   let db = {
      "PVE Update": `Последнее обновление: 28/06/2024`,
      "PVP Update": `Последнее обновление: 27/06/2024`,
      // PVE Skill 01
      "PVE Skill 01": {
         "name": 'Slice',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/26fda59956454f1dbca5f260b2763321a2bb761a.png',
         "job_icon": 'RPR',
         "level": '1',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 420.<br/>Дополнительный эффект: восполняет шкалу Soul Gauge на 10',
      },
      // PVE Skill 02
      "PVE Skill 02": {
         "name": 'Waxing Slice',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4bab01eb43df9752e98deef097e9251647ad96df.png',
         "job_icon": 'RPR',
         "level": '5',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 260.<br/>Комбо умение: Slice<br/>Сила в комбо: 500<br/>Дополнительный эффект: восполняет шкалу Soul Gauge на 10',
      },
      // PVE Skill 03
      "PVE Skill 03": {
         "name": 'Shadow of Death',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e3e48cee91c7abf77a15f6c4c9c9630349849205.png',
         "job_icon": 'RPR',
         "level": '10',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Удар, наносящий урон с силой атаки 300.<br/>Дополнительный эффект: накладывает на цель эффект Death's Design, увеличивает наносимый персонажем урон по цели на 10%<br/>Продолжительность: 30 сек.<br/>Увеличивает продолжительность эффекта Death's Design на 30 сек, вплоть до 60 сек.<br/>Дополнительный эффект: восполняет Soul Gauge на 10, если цель убита до конца действия эффекта",
      },
      // PVE Skill 04
      "PVE Skill 04": {
         "name": 'Harpe',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d3ae9c9673da37ea10aa4103b747163250c4a385.png',
         "job_icon": 'RPR',
         "level": '15',
         "classification": 'Заклинание',
         "cast": '1.3 сек.',
         "recast": '2.5 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 300.<br/>Дополнительный эффект: восполняет шкалу Soul Gauge на 10',
      },
      // PVE Skill 05
      "PVE Skill 05": {
         "name": "Hell's Ingress",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2e1c97fd007f90808b2fd40ad86354b9e97447a8.png',
         "job_icon": 'RPR',
         "level": '20',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Быстрый рывок вперед на 15 ялмов.<br/>Дополнительный эффект: накладывает эффект Enhanced Harpe<br/>Эффект Enhanced Harpe: позволяющий использовать Harpe без времени применения и сокращает время повторного применения Hell's Ingress на 5 сек. после использования.<br/>Длительность: 10 сек.<br/>Дополнительный эффект: оставляет за собой на месте рывка Hellsgate и накладывает на персонажа эффект Threshold.<br/>Длительность: 10 сек.<br/>Невозможно использовать, если персонаж находится под эффектами ограничивающими перемещение.<br/>Имеет общее время восстановления с умением Hell's Egress.",
      },
      // PVE Skill 06
      "PVE Skill 06": {
         "name": "Hell's Egress",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/113b87916c7ffdb9a8007615f697f2c189c6646a.png',
         "job_icon": 'RPR',
         "level": '20',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Быстрый рывок назад на 15 ялмов.<br/>Дополнительный эффект: накладывает эффект Enhanced Harpe<br/>Эффект Enhanced Harpe: позволяющий использовать Harpe без времени применения и сокращает время повторного применения Hell's Ingress на 5 сек. после использования.<br/>Длительность: 10 сек.<br/>Дополнительный эффект: оставляет за собой на месте рывка Hellsgate и накладывает на персонажа эффект Threshold<br/>Длительность: 10 сек.<br/>Невозможно использовать, если персонаж находится под эффектами ограничивающими перемещение.<br/>Имеет общее время восстановления с умением Hell's Ingress",
      },
      // PVE Skill 07
      "PVE Skill 07": {
         "name": 'Spinning Scythe',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/dac9dba46aa8ff673cd2e365c9468525db0ba1a2.png',
         "job_icon": 'RPR',
         "level": '25',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 160 по всем ближайшим противникам.<br/>Дополнительный эффект: восполняет шкалу Soul Gauge на 10',
      },
      // PVE Skill 08
      "PVE Skill 08": {
         "name": 'Infernal Slice',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/aa7a7dd464459f24aa2209cddcbf8a3ebb167f0b.png',
         "job_icon": 'RPR',
         "level": '30',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 280.<br/>Комбо умение: Waxing Slice<br/>Сила в комбо: 600<br/>Комбо бонус: восполняет шкалу Soul Gauge на 10',
      },
      // PVE Skill 09
      "PVE Skill 09": {
         "name": 'Whorl of Death',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/31d409f8aaeae041b8150e68764e032fccd7c4c6.png',
         "job_icon": 'RPR',
         "level": '35',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": "Удар, наносящий урон с силой атаки 100 по всем ближайшим противникам.<br/>Дополнительный эффект: накладывает на цель эффект Death's Design,увеличивает наносимый персонажем урон по цели на 10%<br/>Продолжительность: 30 сек.<br/>Увеличивает продолжительность эффекта Death's Design на 30 сек., вплоть до 60 сек.<br/>Дополнительный эффект: восполняет Soul Gauge на 10, если цель убита до конца действия эффекта",
      },
      // PVE Skill 10
      "PVE Skill 10": {
         "name": 'Arcane Crest',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/9977fdbbf70443f9f31f4868cba97138fbec5460.png',
         "job_icon": 'RPR',
         "level": '40',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '30 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Накладывает эффект Crest of Time Borrowed на персонажа, создающий барьер, который поглощает урон в размере 10% от максимального HP.<br/>Продолжительность: 5 сек.<br/>Накладывает Crest of Time Returned на персонажа и ближайших сопартийцев в радиусе 15 ялмов, когда барьер будет поглощён или расходован<br/>Эффект Crest of Time Returned: постепенно восстанавливает HP<br/>Сила лечения: 50<br/>Продолжительность: 15 сек.',
      },
      // PVE Skill 11
      "PVE Skill 11": {
         "name": 'Nightmare Scythe',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/710256a9319251859b53dd3804078cc8e35c2333.png',
         "job_icon": 'RPR',
         "level": '45',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 140 по всем ближайшим противникам.<br/>Комбо умение: Spinning Scythe<br/>Сила в комбо: 200<br/>Комбо бонус: восполняет шкалу Soul Gauge на 10',
      },
      // PVE Skill 12
      "PVE Skill 12": {
         "name": 'Blood Stalk',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f0f3d4c722f5f9b36b25ba72d3774b4b811b699d.png',
         "job_icon": 'RPR',
         "level": '50',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Призывает аватар, наносящего удар с силой атаки 340.<br/>Дополнительный эффект: накладывает эффект Soul Reaver<br/>Продолжительность: 30 сек.<br/>Количество стаков уменьшится до 1, если персонаж уже находится под действием эффекта Soul Reaver.<br/>Эффект не стакается с Executioner.<br/>Стоимость: 50 Soul Gauge <br/>Имеет общее время восстановления со всеми атаками аватара, кроме Gluttony.",
      },
      // PVE Skill 13
      "PVE Skill 13": {
         "name": 'Grim Swathe',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ac34fd282b758c407014a47e3c30e188050307d8.png',
         "job_icon": 'RPR',
         "level": '55',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '8y',
         "radius_img": 'R4',
         "radius": '8y',
         "content": "Призывает аватар, наносящего удар с силой атаки 140 во всем противникам в конусе перед персонажем.<br/>Дополнительный эффект: накладывает эффект Soul Reaver<br/>Продолжительность: 30 сек.<br/>Количество стаков уменьшится до 1, если персонаж уже находится под действием эффекта Soul Reaver.<br/>Эффект не стакается с Executioner.<br/>Стоимость: 50 Soul Gauge<br/>Имеет общее время восстановления со всеми атаками аватара, кроме Gluttony.<br/><br/>※ Умение меняется на Lemure's Slice под действием эффекта Enshrouded.",
      },
      // PVE Skill 14
      "PVE Skill 14": {
         "name": 'Soul Slice',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/089e7135cc2e4e64590c18db17fbab56e0040843.png',
         "job_icon": 'RPR',
         "level": '60',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '30 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 460.<br/>Дополнительный эффект: восполняет шкалу Soul Gauge на 50<br/>Максимум зарядов: 2 <br/>Имеет общее время восстановления с умением Soul Scythe.<br/>На время восстановления не влияют статусные эффекты и атрибуты снаряжения.',
      },
      // PVE Skill 15
      "PVE Skill 15": {
         "name": 'Soul Scythe',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/22ae994a06569700d3f9d51b1b999c951ca171e3.png',
         "job_icon": 'RPR',
         "level": '65',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '30 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 180 по всем ближайшим противникам.<br/>Дополнительный эффект: восполняет шкалу Soul Gauge на 50<br/>Максимум зарядов: 2<br/>Имеет общее время восстановления с умением Soul Slice.<br/>На время восстановления не влияют статусные эффекты и атрибуты снаряжения.',
      },
      // PVE Skill 16
      "PVE Skill 16": {
         "name": 'Gibbet',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f8259f07fef48d2d418535404fdc672bdc852285.png',
         "job_icon": 'RPR',
         "level": '70',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий Удар, наносящий урон с силой атаки 500, при выполнени удара в бок цели 560.<br/>Сила атаки Enhanced Gibbet: 560<br/>Сила атаки Enhanced Gibbet в бок цели: 620<br/>Дополнительный эффект: накладывает Enhanced Gallows<br/>Продолжительность: 60 сек.<br/>Умение Blood Stalk меняется на Unveiled Gallows под действием эффекта Enhanced Gallows.<br/>Дополнительный эффект: восполняет шкалу Shroud Gauge на 10<br/>Можно использовать только под действием эффекта Soul Reaver.<br/><br/>※ Умение меняется на Void Reaping под действием эффекта Enshrouded. с силой атаки 400, при выполнении удара в бок цели 460.<br/>Сила атаки Enhanced Gibbet: 460<br/>Сила атаки Enhanced Gibbet в бок цели: 520<br/>Дополнительный эффект: накладывает Enhanced Gallows<br/>Продолжительность: 60 сек.<br/>Умение Blood Stalk меняется на Unveiled Gallows под действием эффекта Enhanced Gallows.<br/>Дополнительный эффект: восполняет шкалу Shroud Gauge на 10<br/>Можно использовать только под действием эффекта Soul Reaver.<br/><br/>※Умение меняется на Void Reaping под действием эффекта Enshrouded.',
      },
      // PVE Skill 17
      "PVE Skill 17": {
         "name": 'Gallows',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ae681cd40113523630db64f0e3823235db61a364.png',
         "job_icon": 'RPR',
         "level": '70',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с Удар, наносящий урон с силой атаки 500, при выполнени удара сзади цели 560.<br/>Сила атаки Enhanced Gallows: 560<br/>Сила атаки Enhanced Gallows сзади цели: 620<br/>Дополнительный эффект: накладывает Enhanced Gibbet<br/>Продолжительность: 60 сек.<br/>Умение Blood Stalk меняется на Unveiled Gibbet под действием эффекта Enhanced Gibbet.<br/>Дополнительный эффект: восполняет шкалу Shroud Gauge на 10<br/>Можно использовать только под действием эффекта Soul Reaver.<br/><br/>※ Умение меняется на Cross Reaping под действием эффекта Enshrouded.силой атаки 400, при выполнении удара в спину цели 460.<br/>Сила атаки Enhanced Gallows: 460<br/>Сила атаки Enhanced Gallows в спину цели: 520<br/>Дополнительный эффект: накладывает Enhanced Gibbet<br/>Продолжительность: 60 сек.<br/>Умение Blood Stalk меняется на Unveiled Gibbet под действием эффекта Enhanced Gibbet<br/>Дополнительный эффект: восполняет шкалу Shroud Gauge на 10<br/>Можно использовать только под действием эффекта Soul Reaver.<br/><br/>※Умение меняется на Cross Reaping под действием эффекта Enshrouded.',
      },
      // PVE Skill 18
      "PVE Skill 18": {
         "name": 'Guillotine',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b4d685f506367e2bd3228603e7b2c4172567f933.png',
         "job_icon": 'RPR',
         "level": '70',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '8y',
         "radius_img": 'R4',
         "radius": '8y',
         "content": 'Удар, наносящий урон с силой атаки 200 по всем противникам в конусе перед персонажем.<br/>Дополнительный эффект: восполняет шкалу Shroud Gauge на 10<br/>Можно использовать только под действием эффекта Soul Reaver.<br/><br/>※Умение меняется на Grim Reaping под действием эффекта Enshrouded.',
      },
      // PVE Skill 19
      "PVE Skill 19": {
         "name": 'Unveiled Gibbet',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/02ab830b9551480d0b5d62a24012c401a422b0bd.png',
         "job_icon": 'RPR',
         "level": '70',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Призывает аватар, наносящего удар с силой атаки 400.<br/>ДополнительПризывает аватар, наносящего удар с силой атаки 440.<br/>Дополнительный эффект: накладывает эффект Soul Reaver<br/>Продолжительность: 30 сек.<br/>Количество стаков уменьшится до 1, если персонаж уже находится под действием эффекта Soul Reaver.<br/>Эффект не стакается с Executioner.<br/>Стоимость: 50 Soul Gauge<br/>Можно использовать только под действием эффекта Enhanced Gibbet.<br/>Имеет общее время восстановления со всеми атаками аватара, кроме Gluttony.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Blood Stalk меняется на Unveiled Gibbet под действием эффекта Enhanced Gibbet.ный эффект: накладывает эффект Soul Reaver<br/>Продолжительность: 30 сек.<br/>Количество стаков уменьшится до 1, если персонаж уже находится под действием эффекта Soul Reaver.<br/>Стоимость: 50 Soul Gauge <br/>Можно использовать только под действием эффекта Enhanced Gibbet.<br/>Имеет общее время восстановления со всеми атаками аватара, кроме Gluttony.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 20
      "PVE Skill 20": {
         "name": 'Unveiled Gallows',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/017af138fc2458f9cae561ec96f027791d1da803.png',
         "job_icon": 'RPR',
         "level": '70',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Призывает аватар, Призывает аватар, наносящего удар с силой атаки 440.<br/>Дополнительный эффект: накладывает эффект Soul Reaver<br/>Продолжительность: 30 сек.<br/>Количество стаков уменьшится до 1, если персонаж уже находится под действием эффекта Soul Reaver.<br/>Эффект не стакается с Executioner.<br/>Стоимость: 50 Soul Gauge<br/>Можно использовать только под действием эффекта Enhanced Gallows.<br/>Имеет общее время восстановления со всеми атаками аватара, кроме Gluttony.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Blood Stalk меняется на Unveiled Gallows под действием эффекта Enhanced Gallows. удар с силой атаки 400.<br/>Дополнительный эффект: накладывает эффект Soul Reaver<br/>Продолжительность: 30 сек.<br/>Количество стаков уменьшится до 1, если персонаж уже находится под действием эффекта Soul Reaver.<br/>Стоимость: 50 Soul Gauge <br/>Можно использовать только под действием эффекта Enhanced Gallows.<br/>Имеет общее время восстановления со всеми атаками аватара, кроме Gluttony.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 21
      "PVE Skill 21": {
         "name": 'Arcane Circle',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b561271272c45fb8436bfe4dfb590b76c631687b.png',
         "job_icon": 'RPR',
         "level": '72',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '30y',
         "content": 'Увеличивает урон персонажа и ближайших сопартийцев на 3%.<br/>Продолжительность: 20 сек.<br/>Дополнительный эффект: накладывает на персонажа и ближайших сопартийцев эффект Circle of Sacrifice<br/>Продолжительность: 5 сек.<br/>Дополнительный эффект: накладывает на персонажа эффект Bloodsown Circle<br/>Продолжительность: 6 сек.<br/>Эффект Circle of Sacrifice: когда персонаж или сопартийцы, находящиеся под этим эффектом, успешно используют боевой навык или произносят заклинание, рипер получает стак Immortal Sacrifice, вплоть до 8<br/>Продолжительность: 30 сек.<br/>Эффект Bloodsown Circle: позволяет накапливать стаки Immortal Sacrifice от сопартийцев, находящихся под действием эффекта Circle of Sacrifice',
      },
      // PVE Skill 22
      "PVE Skill 22": {
         "name": 'Regress',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/eaeec5829efd0623650ee09d1b3867ef3804c643.png',
         "job_icon": 'RPR',
         "level": '74',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Мгновенно перемещается в оставленные персонажем Hellsgate.<br/>Может быть использовано только под действием Threshold.<br/>Невозможно использовать, если персонаж находится под эффектами ограничивающими перемещение.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Hell's Ingress или Hell's Egress меняется на Regress при соблюдении требований к выполнению.",
      },
      // PVE Skill 23
      "PVE Skill 23": {
         "name": 'Gluttony',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/933867484213377dc45cafd796ff5d934cee8906.png',
         "job_icon": 'RPR',
         "level": '76',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Призывает аватар, наносящего нестихийный урон по цели и всем ближайшим противникам с силой атаки 520 для первого и на 25% меньше для остальным.<br/>Дополнительный эффект: накладывает 2 стака Soul Reaver<br/>Продолжительность: 30 сек.<br/>Эффект не стакается с Soul Reaver.<br/>Стоимость: 50 Soul Gauge',
      },
      // PVE Skill 24
      "PVE Skill 24": {
         "name": 'Enshroud',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/a3c7fb68def/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4e389efd3504b3ed9dcd4f7633ebc9a5bb528971.png',
         "job_icon": 'RPR',
         "level": '80',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Тело персонажа становится сосудом для аватара и персонаж получает максимальное количество стаков Lemure Shroud.<br/>Продолжительность: 30 сек.<br/>Некоторые умения не могут быть использованы, пока персонаж во власти аватара.<br/>Дополнительный эффект: накладывает эффект Oblatio<br/>Продолжительность: 30 сек.<br/>Стоимость: 50 Soul Gauge',
      },
      // PVE Skill 25
      "PVE Skill 25": {
         "name": 'Void Reaping',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d2632208267baca74f7d9c19ee7a9c794034f2f0.png',
         "job_icon": 'RPR',
         "level": '80',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 500.<br/>Сила атаки Enhanced Void Reaping: 560<br/>Дополнительный эффект: накладывает эффект Enhanced Cross Reaping<br/>Продолжительность: 30 сек.<br/>Дополнительный эффект: добавляет стак Void Shroud<br/>Может быть использовано только под действием эффекта Enshrouded.<br/>На время восстановления не влияют статусные эффекты и атрибуты снаряжения.<br/>Стоимость: 1 Lemure Shroud<br/>Этот умение не имеет общего времени восстановления с другими умениями.<br/>После выполнения время повторного восстановления этого умения будет применено ко всем боевым навыкам и магическим умениям.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Gibbet меняется на Void Reaping при соблюдении требований к выполнению.',
      },
      // PVE Skill 26
      "PVE Skill 26": {
         "name": 'Cross Reaping',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a080e4189263d80adcd79deaaac266c93798d202.png',
         "job_icon": 'RPR',
         "level": '80',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 500.<br/>Сила атаки Enhanced Cross Reaping: 560<br/>Дополнительный эффект: накладывает эффект Enhanced Void Reaping<br/>Продолжительность: 30 сек.<br/>Дополнительный эффект: добавляет стак Void Shroud<br/>Можно использовать только под действием эффекта Lemure Shroud.<br/>Стоимость: 1 Lemure Shroud<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями.<br/>После выполнения время повторного восстановления этого умения будет применено ко всем боевым навыкам и магическим умениям.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Gallows меняется на Cross Reaping при соблюдении требований к выполнению.',
      },
      // PVE Skill 27
      "PVE Skill 27": {
         "name": 'Grim Reaping',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/3b57c45ec39fc75788c9603653a77c5b95f04e67.png',
         "job_icon": 'RPR',
         "level": '80',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "range": '8y',
         "radius_img": 'R4',
         "radius": '8y',
         "content": 'Удар, наносящий урон с силой атаки 200 по всем противникам в конусе перед персонажем.<br/>Дополнительный эффект: накладывает эффект Void Shroud<br/>Можно использовать только под действием эффекта Enshrouded.<br/>Стоимость: 1 Lemure Shroud<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями.<br/>После выполнения время повторного применения этого умения будет применено ко всем боевым навыкам и магическим умениям.<br/>※Это умение нельзя поместить на хотбар.<br/>※Guillotine меняется на Grim Reaping при соблюдении требований к выполнению.',
      },
      // PVE Skill 28
      "PVE Skill 28": {
         "name": 'Soulsow',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a59a5def406758cbd282cffdea8bea00a98f5e58.png',
         "job_icon": 'RPR',
         "level": '82',
         "classification": 'Заклинание',
         "cast": '5 сек.',
         "recast": '2.5 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Накладывает эффект Soulsow на персонажа, меняя умение на Harvest Moon.<br/>Применяется мгновенно, если использовано вне боя.',
      },
      // PVE Skill 29
      "PVE Skill 29": {
         "name": 'Harvest Moon',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e5f0a7dabd5ef44d08e8d5920d834f3e734169d9.png',
         "job_icon": 'RPR',
         "level": '82',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон по цели и по всем окружающим противникам с силой атаки 800 для первого противника и на 50% меньше для всех остальных.<br/>Дополнительный эффект: восполняет шкалу Soul Gauge на 10<br/>Может быть использовано только под действием эффекта Soulsow.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Soulsow меняется на Harvest Moon при соблюдении требований к выполнению.',
      },
      // PVE Skill 30
      "PVE Skill 30": {
         "name": "Lemure's Slice",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c9ae486399356401f032b455ea5b13f986236c82.png',
         "job_icon": 'RPR',
         "level": '86',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Удар, наносящий урон с силой атаки 280.<br/>Стоимость: 2 Void Shroud<br/>Имеет общее время восстановления с умением Lemure's Scythe.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Blood Stalk меняется на Lemure's Slice под действием эффекта Enshrouded.",
      },
      // PVE Skill 31
      "PVE Skill 31": {
         "name": "Lemure's Scythe",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/479155b751c2764273ae35c1aab71ed298ad9d18.png',
         "job_icon": 'RPR',
         "level": '86',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '8y',
         "radius_img": 'R4',
         "radius": '8y',
         "content": "Удар, наносящий урон с силой атаки 100 по всем противникам в конусе перед персонажем.<br/>Стоимость: 2 Void Shroud<br/>Имеет общее время восстановления с умением Lemure's Slice.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Grim Swathe меняется на Lemure's Slice под действием эффекта Enshrouded.",
      },
      // PVE Skill 32
      "PVE Skill 32": {
         "name": 'Plentiful Harvest',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/08babf4d2bf7ce046d03f459af8fa4c9921f96cc.png',
         "job_icon": 'RPR',
         "level": '88',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '15y',
         "radius_img": 'R6',
         "radius": '15y',
         "content": 'Удар, наносящий урон по всем противникам по прямой линии с силой атаки 720 для первого противника и на 60% меньше для всех остальных.<br/>Стоимость: 1 стак Immortal Sacrifice<br/>Сила атаки увеличивается вплоть до 1,000, когда стаки Immortal Sacrifice превышают минимальную стоимость.<br/>Дополнительный эффект: накладывает эффект Ideal Host<br/>Продолжительность: 30 сек.<br/>Дополнительный эффект: накладывает эффект Perfectio Occulta<br/>Эффект Perfectio Occulta: накладывает эффект Perfectio Parata после использования Communio.<br/>Продолжительность: 30 сек.<br/>Не может быть использовано под действием эффекта Bloodsown Circle.<br/>При выполнении расходует все стаки Immortal Sacrifice.<br/>Дополнительный эффект: восполняет шкалу Shroud Gauge на 50',
      },
      // PVE Skill 33
      "PVE Skill 33": {
         "name": 'Communio',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/3b0daa7e454abbd2b6ce037b5c77157462fadbf7.png',
         "job_icon": 'RPR',
         "level": '90',
         "classification": 'Заклинание',
         "cast": '1.3 сек.',
         "recast": '2.5 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон по цели и по всем окружающим противникам с силой атаки 1,100 для первого противника и на 60% меньше для всех остальных.<br/>Дополнительный эффект: накладывает эффект Perfectio Parata при использовании, пока активен Perfectio Occulta<br/>Продолжительность: 30 сек.<br/>Эффект Enshrouded завершается после выполнения.<br/>Для использования требуется как минимум один стак Lemure Shroud.',
      },
      // PVE Skill 34 NEW
      "PVE Skill 34": {
         "name": 'Sacrificium',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c30eb0a31733645a16fe4afedf837597addded77.png',
         "job_icon": 'RPR',
         "level": '92',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон по цели и по всем окружающим противникам с силой атаки 530 для первого противника и на 50% меньше для всех остальных.<br/>Можно использовать только под действием эффекта Enshrouded и Oblatio.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Gluttony меняется на Sacrificium при соблюдении требований к выполнению.',
      },
      // PVE Skill 35 NEW
      "PVE Skill 35": {
         "name": "Executioner's Gibbet",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7df5921d09e8a524ef8b7c187a9f0cb1ee181aff.png',
         "job_icon": 'RPR',
         "level": '96',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Удар, наносящий урон с силой атаки 700, при выполнени удара в бок цели 760.<br/>Сила атаки Enhanced Gibbet: 760<br/>Сила атаки Enhanced Gibbet в бок цели: 820<br/>Дополнительный эффект: накладывает Enhanced Gallows<br/>Продолжительность: 60 сек.<br/>Умение Blood Stalk меняется на Unveiled Gallows под действием эффекта Enhanced Gallows.<br/>Дополнительный эффект: восполняет шкалу Shroud Gauge на 10<br/>Можно использовать только под действием эффекта Executioner.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Gibbet меняется на Executioner's Gibbet при соблюдении требований к выполнению.",
      },
      // PVE Skill 36 NEW
      "PVE Skill 36": {
         "name": "Executioner's Gallows",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/0dfc7d7951330304c328135c306fa3d54b1a9cdc.png',
         "job_icon": 'RPR',
         "level": '96',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Удар, наносящий урон с силой атаки 700, при выполнени удара сзади цели 760.<br/>Сила атаки Enhanced Gallows: 760<br/>Сила атаки Enhanced Gallows сзади цели: 820<br/>Дополнительный эффект: накладывает Enhanced Gibbet<br/>Продолжительность: 60 сек.<br/>Умение Blood Stalk меняется на Unveiled Gibbet под действием эффекта Enhanced Gibbet.<br/>Дополнительный эффект: восполняет шкалу Shroud Gauge на 10<br/>Можно использовать только под действием эффекта Executioner.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Gallows меняется на Executioner's Gallows при соблюдении требований к выполнению.",
      },
      // PVE Skill 37 NEW
      "PVE Skill 37": {
         "name": "Executioner's Guillotine",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d732a04e72dd2c5e3c0702749e6310329b611ca8.png',
         "job_icon": 'RPR',
         "level": '96',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '8y',
         "radius_img": 'R4',
         "radius": '8y',
         "content": "Удар, наносящий урон с силой атаки 300 по всем противникам в конусе перед персонажем.<br/>Дополнительный эффект: восполняет шкалу Shroud Gauge на 10<br/>Можно использовать только под действием эффекта Executioner.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Guillotine меняется на Executioner's Guillotine при соблюдении требований к выполнению.",
      },
      // PVE Skill 38 NEW
      "PVE Skill 38": {
         "name": 'Perfectio',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ab9537a1e24665b2b794656e28f58981b95b3c52.png',
         "job_icon": 'RPR',
         "level": '100',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон по цели и по всем окружающим противникам с силой атаки 1,200 для первого противника и на 60% меньше для всех остальных.<br/>Можно использовать только под действием эффекта Perfectio Parata.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Communio меняется на Perfectio при соблюдении требований к выполнению.',
      },
      // Trait 01
      "Trait 01": {
         "name": 'Soul Gauge',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/cdd4dbdaa89dfc284e0be14a8ef05287679e7210.png',
         "job_icon": 'RPR',
         "level": '50',
         "content": "Позволяет восполнять шкалу Soul Gauge при использовании определенных боевых навыков или магических умений или при победе над врагами, находящимися под действием эффекта Death's Design.",
      },
      // Trait 02 NEW
      "Trait 02": {
         "name": 'Melee Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/bc58b07072e258883e9e584c4e45355d092da661.png',
         "job_icon": 'RPR',
         "level": '60',
         "content": 'Увеличивает силу атаки Slice до 300, Waxing Slice до 140, Shadow of Death до 300, Harpe до 300, Spinning Scythe до 140, Infernal Slice до 140, Whorl of Death до 100 и Nightmare Scythe до 120.',
      },
      // Trait 03
      "Trait 03": {
         "name": 'Enhanced Avatar',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/884cf03809d4b64336961dedfcb87d7fa5c065f3.png',
         "job_icon": 'RPR',
         "level": '70',
         "content": 'Накладывает эффект Soul Reaver при успешном использовании Blood Stalk или Grim Swathe.<br/>Продолжительность: 30 сек.<br/>Эффект прекращается при использовании любого боевого навыка или магической атаки.',
      },
      // Trait 04
      "Trait 04": {
         "name": 'Hellsgate',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/197108fc180510d46e15ba85434a517352da9ea3.png',
         "job_icon": 'RPR',
         "level": '74',
         "content": "Использовав умение Hell's Ingress или Hell's Egress, персонаж оставляет за собой Hellsgate и накладывает эффект Threshold на персонажа.<br/>Продолжительность: 10 сек.<br/>Hell's Ingress меняется на Regress после использования Hell's Egress и наоборот.",
      },
      // Trait 05
      "Trait 05": {
         "name": 'Tempered Soul',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c1fcd7a37a619bdd241fafe156ffe6e1c306553d.png',
         "job_icon": 'RPR',
         "level": '78',
         "content": 'Позволяет накапливать заряды для последовательного использования Soul Slice и Soul Scythe.<br/>Максимум зарядов: 2 ',
      },
      // Trait 06
      "Trait 06": {
         "name": 'Shroud Gauge',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/a3c7fb68def/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/aec909a3e2c44d5c726b997c0d1af8da7175218d.png',
         "job_icon": 'RPR',
         "level": '80',
         "content": 'Позволяет восполнять Shroud Gauge при использовании Gibbet, Gallows или Guillotine.',
      },
      // Trait 07
      "Trait 07": {
         "name": 'Enhanced Arcane Crest',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b2f58d09091b830b74082188a84bb17efd365dc2.png',
         "job_icon": 'RPR',
         "level": '84',
         "content": 'Накладывает эффект Crest of Time Returned на персонажа и ближайших сопартийцев, постепенно восстанавливая HP. Этот эффект появляется только тогда, когда барьер Crest of Time Borrowed полностью поглощен.<br/>Сила лечения: 50<br/>Продолжительность: 15 сек.',
      },
      // Trait 08 NEW
      "Trait 08": {
         "name": 'Melee Mastery II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b60557edca3b093463f0f0c0c04dc3895855e9f8.png',
         "job_icon": 'RPR',
         "level": '84',
         "content": 'Увеличивает силу атаки Slice до 320, Waxing Slice до 160 и  Infernal Slice до 180.',
      },
      // Trait 09
      "Trait 09": {
         "name": 'Enhanced Shroud',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ada3c73d86be1fc25e17386dd10e76e170fef077.png',
         "job_icon": 'RPR',
         "level": '86',
         "content": 'Добавляет стак Void Shroud после использования Void Reaping, Cross Reaping или Grim Reaping.',
      },
      // Trait 10
      "Trait 10": {
         "name": 'Enhanced Arcane Circle',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b6f540f8120532425d4aa28831c6f8cdcbfa5db7.png',
         "job_icon": 'RPR',
         "level": '88',
         "content": 'Накладывает эффект Circle of Sacrifice на персонажа и ближайших сопартийцев при использовании умения Arcane Circle.<br/>Продолжительность: 5 сек.<br/>Когда персонаж или сопартийцы под этим эффектом успешно используют боевые навыки или произносят заклинание, персонаж получает стак Immortal Sacrifice, вплоть до 8.<br/>Продолжительность: 30 сек.<br/>Накладывает на персонажа Bloodsown Circle, позволяя получать стаки Immortal Sacrifice от сопартийцев, находящихся под действием эффекта Circle of Sacrifice.<br/>Продолжительность: 6 сек.',
      },
      // Trait 11 NEW
      "Trait 11": {
         "name": 'Enhanced Enshroud',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5091bfb444d4a9ee64f5b364fc58f0c5fb5b0b38.png',
         "job_icon": 'RPR',
         "level": '92',
         "content": 'Накладывает эффект Oblatio после использования Enshroud.<br/>Продолжительность: 30 сек.',
      },
      // Trait 12 NEW
      "Trait 12": {
         "name": 'Melee Mastery III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/76ee293b5a8fae7dd16716bc05d79216ef2689a9.png',
         "job_icon": 'RPR',
         "level": '94',
         "content": "Увеличивает силу атаки Slice до 420, Waxing Slice до 260, Spinning Scythe до 160, Infernal Slice до 280, Nightmare Scythe до 140, Gibbet до 500, Gallows до 500, Unveiled Gibbet до 440, Unveiled Gallows до 440, Void Reaping до 500, Cross Reaping до 500, Harvest Moon до 700 и Lemure's Slice до 280.",
      },
      // Trait 13 NEW
      "Trait 13": {
         "name": 'Enhanced Gluttony',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a31d9112196a1558d38290cc5502d584ce5f05f0.png',
         "job_icon": 'RPR',
         "level": '96',
         "content": "Накладывает эффект Executioner после использования Gluttony.<br/>Продолжительность: 30 сек.<br/>Эффект не стакается с Soul Reaver.<br/>Эффект прекращается при выполнении любого боевого навыка или магической атаки.<br/>Gibbet меняется на Executioner's Gibbet, Gallows меняется на Executioner's Gallows и Guillotine меняется на Executioner's Guillotine под действием эффекта Executioner.",
      },
      // Trait 14 NEW
      "Trait 14": {
         "name": 'Enhanced Plentiful Harvest',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/71ef6d72decb0ba869aa07010008e538299ba064.png',
         "job_icon": 'RPR',
         "level": '100',
         "content": 'Накладывает эффект Perfectio Occulta после использования Plentiful Harvest.<br/>Продолжительность: 30 сек.<br/>Perfectio Occulta меняется на Perfectio Parata после использования Communio.<br/>Эффект Perfectio Parata заканчивается при получении эффекта Lemure Shroud.',
      },
      // PVP Skill 01
      "PVP Skill 01": {
         "name": 'Slice',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b3aba81b36f1d7f627a0f83e38f1b9a6b92434cd.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.4 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 3,000.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 02
      "PVP Skill 02": {
         "name": 'Waxing Slice',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5d626f5a33df738e1e06dfdd8d7094bda770ad64.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.4 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 4,000.<br/>Комбо умение: Slice<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 03
      "PVP Skill 03": {
         "name": 'Infernal Slice',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/dd4a740c4bbf1f6fa18b92187e7039379fbfed30.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.4 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 5,000.<br/>Комбо умение: Waxing Slice<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 04
      "PVP Skill 04": {
         "name": 'Soul Slice',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2f9f04bc14107eb92ebc354091b1274464e9c002.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 8,000.<br/>Дополнительный эффект: накладывает стак Immortal Sacrifice, вплоть до 8<br/>Максимум зарядов: 2<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями.',
      },
      // PVP Skill 05
      "PVP Skill 05": {
         "name": 'Plentiful Harvest',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ab0eae0be0bf452487bd9f9c33ac06ab5ae53efc.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "range": '15y',
         "radius_img": 'R6',
         "radius": '15y',
         "content": 'Удар, наносящий урон по всем противникам по прямой линии с силой атаки 4,000.<br/>Сила атаки увеличивается до 24,000 в зависимости от накопленных стаков Immortal Sacrifice, полученных за использование Soul Slice, убийства противников или получение ассистов.<br/>Дополнительный эффект: постепенно заполняет шкалу лимит брейка<br/>Продолжительность: 15 сек.<br/>Эффект можно активировать только в бою.<br/>При использовании расходует все стаки Immortal Sacrifice.<br/>Может быть использовано только в то время, когда на персонажа не наложен эффект Enshrouded.<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями.',
      },
      // PVP Skill 06
      "PVP Skill 06": {
         "name": 'Grim Swathe',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4b0d41599ef62b2057cf1e0ac5a007eb235baa5f.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '8y',
         "radius_img": 'R4',
         "radius": '8y',
         "content": 'Призывает аватар, наносящего удар с силой атаки 4,000 по всем противникам в конусе перед персонажем.<br/>Дополнительный эффект: накладывает эффект Soul Reaver<br/>Продолжительность: 10 сек.<br/>Дополнительный эффект: тяжесть (heavy) +75%<br/>Продолжительность: 3 сек.<br/><br/>※Infernal Slice Combo меняется на Guillotine при использовании.',
      },
      // PVP Skill 07
      "PVP Skill 07": {
         "name": 'Death Warrant',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4717cd6aa17ee7ea4fb28d37658b738c83d67f34.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Накладывает на цель эффект Death Warrant, накапливающий урон, который персонаж наносит цели.<br/>По истечении действия эффекта цель получает 50% от накопленного урона.<br/>Продолжительность: 7 сек.<br/>Дополнительный эффект: накладывает эффект Soulsow<br/>Продолжительность: 10 сек.<br/><br/>※После использования умение меняется на Harvest Moon.',
      },
      // PVP Skill 08
      "PVP Skill 08": {
         "name": "Hell's Ingress",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2424ad75e462d533b623f1371216bc130c82b109.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Быстрый рывок вперед на 15 ялмов.<br/>Дополнительный эффект: оставляет за собой на месте рывка Hellsgate и накладывает на персонажа эффект Threshold<br/>Продолжительность: 10 сек.<br/>Дополнительный эффект: увеличивает скорость передвижения на 25%<br/>Продолжительность: 5 сек.<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.<br/><br/>※При использовании умение меняется на Regress.',
      },
      // PVP Skill 09
      "PVP Skill 09": {
         "name": 'Arcane Crest',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/076c61a60da76d1c1060275a87218c9ea298974b.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Накладывает эффект Crest of Time Borrowed на персонажа, создавая барьер, предотвращающий получение урона, равного силе лечения 12,000.<br/>Продолжительность: 10 сек.<br/>Дополнительный эффект: увеличивает наносимый урон на 10%<br/>Продолжительность: 10 сек.<br/>Накладывает эффект Crest of Time Returned на персонажа и ближайших сопартийцев в радиусе 15 ялмов, когда барьер полностью поглощен.<br/>Эффект Crest of Time Returned: постепенно восстанавливает HP<br/>Сила лечения: 6,000<br/>Продолжительность: 6 сек.',
      },
      // PVP Skill 10
      "PVP Skill 10": {
         "name": 'Guillotine',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c9b769d7ad4c9f51f1f714df3d66cc4884ae1f97.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.4 сек.',
         "range": '8y',
         "radius_img": 'R4',
         "radius": '8y',
         "content": 'Удар, наносящий урон с силой атаки 8,000 по всем противникам в конусе перед персонажем.<br/>Можно использовать только под действием эффекта Soul Reaver.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 11
      "PVP Skill 11": {
         "name": 'Void Reaping',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a9236a05eda40fadfa57db522498cf8da0c1338f.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 8,000.<br/>Дополнительный эффект: накладывает Ripe for Reaping<br/>Продолжительность: 10 сек.<br/>Может быть использовано только под действием эффекта Enshrouded.<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями.<br/><br/>※Infernal Slice Combo меняется на Cross Reaping под действием эффекта Ripe for Reaping.<br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 12
      "PVP Skill 12": {
         "name": 'Cross Reaping',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/3e622ba1498759d256ccbb7ae712fb848142b8b4.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 8,000.<br/>Может быть использовано только под действием эффектов Enshrouded и Ripe for Reaping.<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 13
      "PVP Skill 13": {
         "name": "Lemure's Slice",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/9506431de0afcffcbfa5d260d2d488afbceb84a7.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '8y',
         "radius_img": 'R4',
         "radius": '8y',
         "content": 'Удар, наносящий урон с силой атаки 4,000 по всем противникам в конусе перед персонажем.<br/>Дополнительный эффект: связывание (bind)<br/>Продолжительность: 3 сек.<br/>Можно использовать только под действием эффекта Enshrouded.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 14
      "PVP Skill 14": {
         "name": 'Harvest Moon',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7c70f9fe69e5c51199086c4345095722bf7a9b5a.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 4,000 по цели и всем ближайшим противникам.<br/>Сила атаки увеличивается до 8,000 по мере уменьшения HP цели и достигает максимального значения, когда у цели остается 50% HP или меньше.<br/>Дополнительный эффект: поглощает 100% нанесенного урона в виде HP<br/>Можно использовать только под действием эффекта Soulsow.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 15
      "PVP Skill 15": {
         "name": 'Regress',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f9dde969872d209ff9752660a9fe5083df829856.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Персонаж мгновенно перемещается в оставленный Hellsgate.<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 16
      "PVP Skill 16": {
         "name": 'Communio',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/fad15db3f8853ecf4d7789fb9d5429e64edb02ba.png',
         "classification": 'Заклинание',
         "cast": '1.44 сек.',
         "recast": '2.4 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 16,000 по цели и всем ближайшим противникам.<br/>Требуется как минимум один стак эффекта Enshrouded.<br/>При использовании расходует все стаки эффекта Enshrouded.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 17
      "PVP Skill 17": {
         "name": 'Tenebrae Lemurum',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a2c6adec36c8eeace712802c88eb896c788a8c94.png',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '10y',
         "content": "Тело персонажа становится сосудом для аватара и персонаж получает 5 стаков Enshrouded.<br/>Продолжительность: 20 сек.<br/>Дополнительный эффект: накладывает на ближайших врагов эффект Hysteria<br/>Эффект Hysteria: противники, попавшие под действие эффекта, не могут действовать по своей воле<br/>Продолжительность: 2 сек.<br/>Может быть использовано только тогда, когда шкала лимит брейка (limit gauge) заполнена.<br/>Время зарядки шкалы: 75 сек.<br/>Не действует на неигровых персонажей и игроков, находящихся в роботах.<br/><br/>※Умение меняется на Communio под действием эффекта Enshrouded.<br/>※Grim Swathe меняется на Lemure's Slice под действием эффекта Enshrouded.<br/>※Infernal Slice Combo меняется на Void Reaping под действием эффекта Enshrouded.",
      },
   };
   FILL_DB_VALUES(db);
   FILL_DB_SKILLS(db);
   FILL_DB_SKILLS_PASSIVE(db);
   FILL_DB_SKILLS_PVP(db);
   FILL_DB_SKILLS_MENU(db);
})();