(() =>{
   let db = {
      "PVE Update": `Последнее обновление: 27/06/2024`,
      "PVP Update": `Последнее обновление: 27/06/2024`,
      // PVE Skill 01
      "PVE Skill 01": {
         "name": 'Riposte',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/8c24d1459dbae096bb8927efb52db5feb9b0d316.png',
         "job_icon": 'RDM',
         "level": '1',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 130. <br/>Навык улучшается до Enchanted Riposte, если запас Black Mana и White Mana 20 или больше.',
      },
      // PVE Skill 02
      "PVE Skill 02": {
         "name": 'Jolt',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/9fc8c455d50ec08c721f4674e7e9015f4700debe.png',
         "job_icon": 'RDM',
         "level": '2',
         "classification": 'Заклинание',
         "cast": '2 сек.',
         "recast": '2.5 сек.',
         "cost": '200 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 170.<br/>Дополнительный эффект: восполняет текущий запас Black Mana и White Mana на 2',
      },
      // PVE Skill 03
      "PVE Skill 03": {
         "name": 'Verthunder',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f5a91b090922e24a43d172f2cdfb85fc4ff9423a.png',
         "job_icon": 'RDM',
         "level": '4',
         "classification": 'Заклинание',
         "cast": '5 сек.',
         "recast": '2.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон молнией с силой атаки 360.<br/>Дополнительный эффект: восполняет запас Black Mana на 6<br/>Дополнительный эффект: 50% шанс получить эффект Verfire Ready<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 04
      "PVE Skill 04": {
         "name": 'Corps-a-corps',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ca149fa59c97f3ce000ba2cdd143dd181a25def6.png',
         "job_icon": 'RDM',
         "level": '6',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '35 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Рывок к цели, наносящий урон с силой атаки 130.<br/>Максимум зарядов: 2<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.',
      },
      // PVE Skill 05
      "PVE Skill 05": {
         "name": 'Veraero',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a774e32d6c268433b5e2c56dc152cae973605e2e.png',
         "job_icon": 'RDM',
         "level": '10',
         "classification": 'Заклинание',
         "cast": '5 сек.',
         "recast": '2.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон ветром с силой атаки 360.<br/>Дополнительный эффект: восполняет запас White Mana на 6<br/>Дополнительный эффект: 50% шанс получить эффект Verstone Ready<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 06
      "PVE Skill 06": {
         "name": 'Scatter',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/adbad46ea7684b2e5914b23c4ec7de0ecb19432d.png',
         "job_icon": 'RDM',
         "level": '15',
         "classification": 'Заклинание',
         "cast": '5 сек.',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 120 по цели и всем ближайшим противникам.<br/>Сила атаки Acceleration: 170<br/>Дополнительный эффект: восполняет текущий запас Black Mana и White Mana на 3',
      },
      // PVE Skill 07
      "PVE Skill 07": {
         "name": 'Verthunder II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e81a0ede20ee59190bd71e6e1e0398449a3d9b54.png',
         "job_icon": 'RDM',
         "level": '18',
         "classification": 'Заклинание',
         "cast": '2 сек.',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон молнией с силой атаки 140 по цели и ближайшим противникам<br/>Дополнительный эффект: восполняет запас Black Mana на 7',
      },
      // PVE Skill 08
      "PVE Skill 08": {
         "name": 'Veraero II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/bd4b649f82039bd9b028dc8bafacef3eb671da79.png',
         "job_icon": 'RDM',
         "level": '22',
         "classification": 'Заклинание',
         "cast": '2 сек.',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон ветром с силой атаки 140 по цели и ближайшим противникам<br/>Дополнительный эффект: восполняет запас White Mana на 7',
      },
      // PVE Skill 09
      "PVE Skill 09": {
         "name": 'Verfire',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ce7efb90e13d0fef394abb8d2e57a09402452890.png',
         "job_icon": 'RDM',
         "level": '26',
         "classification": 'Заклинание',
         "cast": '2 сек.',
         "recast": '2.5 сек.',
         "cost": '200 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон огнем с силой атаки 380.<br/>Дополнительный эффект: восполняет запас Black Mana на 5<br/>Может использоваться только когда эффект Verfire Ready активен.',
      },
      // PVE Skill 10
      "PVE Skill 10": {
         "name": 'Verstone',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c5ddf887a06b23a2ae9426a5a6288b863b92eced.png',
         "job_icon": 'RDM',
         "level": '30',
         "classification": 'Заклинание',
         "cast": '2 сек.',
         "recast": '2.5 сек.',
         "cost": '200 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон землей с силой атаки 380.<br/>Дополнительный эффект: восполняет запас White Mana на 5<br/>Может использоваться только когда эффект Verfire Ready активен.',
      },
      // PVE Skill 11
      "PVE Skill 11": {
         "name": 'Zwerchhau',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/adef75e55602967f0c722896b45d5be518cd9dd4.png',
         "job_icon": 'RDM',
         "level": '35',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 100.<br/>Комбо умение: Riposte или Enchanted Riposte<br/>Сила в комбо: 150<br/>Умение улучшается до Enchanted Zwerchhau если текущий запас Black Mana и White Mana 15 и больше.',
      },
      // PVE Skill 12
      "PVE Skill 12": {
         "name": 'Displacement',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/3a7bcdd99a2d4f40c95c39ce19d97be8ee0a151b.png',
         "job_icon": 'RDM',
         "level": '40',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '35 сек.',
         "cost": '-',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 180.<br/>Дополнительный эффект: прыжок назад на 15 ялмов<br/>Максимум зарядов: 2<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.<br/>Делит время восстановления умений с Engagement.',
      },
      // PVE Skill 13
      "PVE Skill 13": {
         "name": 'Engagement',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/341778a835813d9d96dd39d0a4f67e13b6c09527.png',
         "job_icon": 'RDM',
         "level": '40',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '35 сек.',
         "cost": '-',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 180.<br/>Максимум зарядов: 2<br/>Делит время восстановления умений с Displacement.',
      },
      // PVE Skill 14
      "PVE Skill 14": {
         "name": 'Fleche',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f950d18911258503ab8a8ec2fa28ca3fdb6a8a6d.png',
         "job_icon": 'RDM',
         "level": '45',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '25 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 480.',
      },
      // PVE Skill 15
      "PVE Skill 15": {
         "name": 'Redoublement',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/292f17a2bcaebf7db4560ff8c977f64908db9917.png',
         "job_icon": 'RDM',
         "level": '50',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 100.<br/>Комбо умение: Zwerchhau или Enchanted Zwerchhau<br/>Сила в комбо: 230<br/>Умение улучшается до Enchanted Redoublement если текущий запас Black Mana и White Mana 15 и больше.',
      },
      // PVE Skill 16
      "PVE Skill 16": {
         "name": 'Acceleration',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/831a96d8378a68659074d13e8a1e90e0de2da5a4.png',
         "job_icon": 'RDM',
         "level": '50',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '55 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Гарантирует, что следующее применение умения Verthunder III, Veraero III или Impact будет мгновенным.<br/>Продолжительность: 20 сек.<br/>Дополнительный эффект: увеличивает силу атаки Impact на 50<br/>Дополнительный эффект: гарантирует, что умения Verthunder III и Veraero III активируют эффект Verfire Ready или Verstone Ready<br/>Дополнительный эффект: накладывает эффект Grand Impact Ready<br/>Продолжительность: 30 сек.<br/>Максимум зарядов: 2',
      },
      // PVE Skill 17
      "PVE Skill 17": {
         "name": 'Moulinet',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/fe9877c05ef3a4622f0488b580b6ea36b7446bca.png',
         "job_icon": 'RDM',
         "level": '52',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '8y',
         "radius_img": 'R4',
         "radius": '8y',
         "content": 'Удар, наносящий урон с силой атаки 60 по всем противникам в конусе перед персонажем.<br/>Умение улучшается до Enchanted Moulinet если текущий запас Black Mana и White Mana 20 и больше.',
      },
      // PVE Skill 18
      "PVE Skill 18": {
         "name": 'Vercure',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d23f5785bdb0f0c398a14087753ddcedab6d4e78.png',
         "job_icon": 'RDM',
         "level": '54',
         "classification": 'Заклинание',
         "cast": '2 сек.',
         "recast": '2.5 сек.',
         "cost": '500 MP',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Восстанавливает HP цели.<br/>Сила лечения: 350',
      },
      // PVE Skill 19
      "PVE Skill 19": {
         "name": 'Contre Sixte',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e9183e5932215335efe798ce4d6422d37befaf27.png',
         "job_icon": 'RDM',
         "level": '56',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '35 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '6y',
         "content": 'Удар, наносящий урон с силой атаки 400 по цели и всем ближайшим противникам.',
      },
      // PVE Skill 20
      "PVE Skill 20": {
         "name": 'Embolden',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/85d6955ad939bb051fe8b893c194497b9499d89e.png',
         "job_icon": 'RDM',
         "level": '58',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '30y',
         "content": 'Увеличивает магический урон на 5% и весь наносимый урон ближайшими сопартийцами на 5%.<br/>Продолжительность: 20 сек.<br/>Дополнительный эффект: накладывает эффект Thorned Flourish<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 21
      "PVE Skill 21": {
         "name": 'Manafication',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/fcad96771c4/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5f145a66018e2f197e16b966e30c53bba09e13bd.png',
         "job_icon": 'RDM',
         "level": '60',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '110 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Дает 3 стака Magicked Swordplay, каждый стак позволяет использовать Enchanted Riposte, Enchanted Zwerchhau, Enchanted Redoublement, Enchanted Moulinet, Enchanted Moulinet Deux или Enchanted Moulinet Trois без затрат.<br/>Дополнительный эффект: накладывает 6 стаков эффекта Manafication<br/>Эффект Manafication: увеличивает наносимый магический урон на 5%<br/>Продолжительность: 15 сек.<br/>Накладывает эффект Cineration Ready при использовании 6 стаков Manafication.<br/>Продолжительность: 30 сек.<br/>Все комбо будут сброшены после использования Manafication.<br/>Возможно использовать только в бою.',
      },
      // PVE Skill 22
      "PVE Skill 22": {
         "name": 'Jolt II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e2b3cc05547ba6a37ba5e883f190570d32eabb10.png',
         "job_icon": 'RDM',
         "level": '62',
         "classification": 'Заклинание',
         "cast": '2 сек.',
         "recast": '2.5 сек.',
         "cost": '200 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 280.<br/>Дополнительный эффект: восполняет текущий запас Black Mana and White Mana на 2',
      },
      // PVE Skill 23
      "PVE Skill 23": {
         "name": 'Verraise',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/6be6c45a105e3890f5390c26a2d5532a7e2eea43.png',
         "job_icon": 'RDM',
         "level": '64',
         "classification": 'Заклинание',
         "cast": '10 сек.',
         "recast": '2.5 сек.',
         "cost": '2400 MP',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Воскрешает цель, накладывая эффект слабости (weakeness).',
      },
      // PVE Skill 24
      "PVE Skill 24": {
         "name": 'Impact',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1c5d66100b8539f4dd5779a760ccbc29f5878e6a.png',
         "job_icon": 'RDM',
         "level": '66',
         "classification": 'Заклинание',
         "cast": '5 сек.',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'дар, наносящий нестихийный урон с силой атаки 210 по цели и всем ближайшим противникам.<br/>Сила атаки Acceleration: 260<br/>Дополнительный эффект: восполняет текущий запас Black Mana and White Mana на 3',
      },
      // PVE Skill 25
      "PVE Skill 25": {
         "name": 'Verflare',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d20080ca189b4843d89ac2faab14d42099bd2e4c.png',
         "job_icon": 'RDM',
         "level": '68',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон огнем по цели и всем ближайшим противникам с силой атаки 620 для первого и на 60% меньше для всех остальных.<br/>Дополнительный эффект: восполняет Black Mana на 11<br/>Дополнительный эффект: 20% шанс получить эффект Verfire Ready<br/>Продолжительность: 30 сек.<br/>Шанс получить эффект Verfire Ready повышается до 100%, если White Mana больше чем Black Mana во время использования умения.<br/>Стоимость: 3 Mana Stack<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Verthunder III и Verthunder II меняется на Verflare при соблюдении требований к выполнению.',
      },
      // PVE Skill 26
      "PVE Skill 26": {
         "name": 'Verholy',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/b0bc78e2f74/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/34f4be861c3f40879653fef7fe7039f8df1108c1.png',
         "job_icon": 'RDM',
         "level": '70',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон по цели и всем ближайшим противникам с силой атаки 620 для первого и на 60% меньше для всех остальных.<br/>Дополнительный эффект: восполняет White Mana на 11<br/>Дополнительный эффект: 20% шанс получить эффект Verstone Ready<br/>Продолжительность: 30 сек.<br/>Шанс получить эффект Verfire Ready повышается до 100%, если Black Mana больше чем White Mana во время использования умения.<br/>Стоимость: 3 Mana Stack<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Veraero III и Veraero II меняется на Verholy при соблюдении требований к выполнению.',
      },
      // PVE Skill 27
      "PVE Skill 27": {
         "name": 'Reprise',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5a263708112bc6c8cbada8c40c34e97811874caf.png',
         "job_icon": 'RDM',
         "level": '76',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 100.<br/>Умение улучшается до Enchanted Reprise, если запас Black Mana и White Mana 5 или больше.',
      },
      // PVE Skill 28
      "PVE Skill 28": {
         "name": 'Scorch',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ebe66b332de0465570b50147ee257968cfd77d0e.png',
         "job_icon": 'RDM',
         "level": '80',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон по цели и всем ближайшим противникам с силой атаки 700 для первого и на 60% меньше для всех остальных.<br/>Комбо умение: Verflare или Verholy<br/>Дополнительный эффект: восполняет запас Black Mana и White Mana на 4<br/>Может быть использовано только после успешного приминения Verflare или Verholy в качестве комбо умения.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Jolt III и Impact меняется на Scorch при соблюдении требований к выполнению.',
      },
      // PVE Skill 29
      "PVE Skill 29": {
         "name": 'Verthunder III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/8753ec70302b5e3613d8f95980f6d80d30c8ee9d.png',
         "job_icon": 'RDM',
         "level": '82',
         "classification": 'Заклинание',
         "cast": '5 сек.',
         "recast": '2.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон молнией с силой атаки 420.<br/>Дополнительный эффект: восполняет запас Black Mana на 6<br/>Дополнительный эффект: 50% шанс получить эффект Verfire Ready<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 30
      "PVE Skill 30": {
         "name": 'Veraero III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d9d556c8c08c0704176d7239be8de27e2c1f4aba.png',
         "job_icon": 'RDM',
         "level": '82',
         "classification": 'Заклинание',
         "cast": '5 сек.',
         "recast": '2.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон ветром с силой атаки 420.<br/>Дополнительный эффект: восполняет запас White Mana на 6<br/>Дополнительный эффект: 50% шанс получить эффект Verstone Ready<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 31 NEW
      "PVE Skill 31": {
         "name": 'Jolt III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f3be0e80366bd72a864a87e41eadd964f07a5f57.png',
         "job_icon": 'RDM',
         "level": '84',
         "classification": 'Заклинание',
         "cast": '2 сек.',
         "recast": '2.5 сек.',
         "cost": '200 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 360.<br/>Дополнительный эффект: восполняет текущий запас Black Mana и White Mana на 2',
      },
      // PVE Skill 32
      "PVE Skill 32": {
         "name": 'Magick Barrier',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/76814235b2963003889ec3f3fc8c4857d82d3177.png',
         "job_icon": 'RDM',
         "level": '86',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '30y',
         "content": 'Снижает магический урон, наносимый персонажу и ближайшим сопартийцам на 10%, а также увеличивает количество HP, восстанавливаемое  исцеляющими умениями на 5%.<br/>Продолжительность: 10 сек.',
      },
      // PVE Skill 33
      "PVE Skill 33": {
         "name": 'Resolution',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/3683481bcc4bf11a5c0d8d2b979d3109eb2664f7.png',
         "job_icon": 'RDM',
         "level": '90',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R6',
         "radius": '25y',
         "content": 'Удар, наносящий нестихийный урон по всем ближайшим противникам по прямой линии перед персонажем с силой атаки 800 для первого и на 60% меньше для всех остальных.<br/>Комбо умение: Scorch<br/>Дополнительный эффект: восполняет запас Black Mana и White Mana на 4<br/>Может быть использовано только после успешного приминения Scorch в качестве комбо умения.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Scorch меняется на Resolution при соблюдении требований к выполнению.',
      },
      // PVE Skill 34 NEW
      "PVE Skill 34": {
         "name": 'Vice of Thorns',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/23de2734d998406aa25f526147ebbea7f1012d67.png',
         "job_icon": 'RDM',
         "level": '92',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон по всем ближайшим противникам с силой атаки 700 для первого и на 60% меньше для всех остальных.<br/>Может быть использовано только под действием эффекта Thorned Flourish.',
      },
      // PVE Skill 35 NEW
      "PVE Skill 35": {
         "name": 'Grand Impact',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5be2009c3bc4bd918ee899e0c6edc953571e93a3.png',
         "job_icon": 'RDM',
         "level": '96',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон по цели и всем ближайшим противникам с силой атаки 600 и на 60% меньше для всех остальных.<br/>Дополнительный эффект: восполняет запас Black Mana и White Mana на 3<br/>Может быть использовано только под действием эффекта Grand Impact Ready.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Jolt III и Impact меняется на Grand Impact при соблюдении требований к выполнению.',
      },
      // PVE Skill 36 NEW
      "PVE Skill 36": {
         "name": 'Prefulgence',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f3988ae5cc17fcf0b655c5820f0c25ef2ac72b43.png',
         "job_icon": 'RDM',
         "level": '100',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон по цели и всем ближайшим противникам с силой атаки 900 для первого и на 60% меньше для всех остальных.<br/>Может быть использовано только под действием эффекта Prefulgence Ready.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Manafication меняется на Prefulgence при соблюдении требований к выполнению.',
      },
      // PVE Skill 37
      "PVE Skill 37": {
         "name": 'Enchanted Riposte',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f3b5d72daa982d01b469e4d45a73b184b7056154.png',
         "job_icon": 'RDM',
         "level": '1',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "cost": '-',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 300.<br/>Дополнительный эффект: накладывает эффект Mana Stack<br/>Стоимость: 20 Black Mana шкалы Balance Gauge<br/>Стоимость: 20 White Mana шкалы Balance Gauge<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Riposte меняется на Enchanted Riposte при соблюдении требований к выполнению.',
      },
      // PVE Skill 38
      "PVE Skill 38": {
         "name": 'Enchanted Zwerchhau',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4740dd6eac66424c4d1b236f9002b979f7f993e7.png',
         "job_icon": 'RDM',
         "level": '35',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "cost": '-',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 170.<br/>Комбо умение: Riposte or Enchanted Riposte<br/>Сила в комбо: 360<br/>Дополнительный эффект: накладывает эффект Mana Stack<br/>Стоимость: 15 Black Mana шкалы Balance Gauge<br/>Стоимость: 15 White Mana шкалы Balance Gauge<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Zwerchhau меняется на Enchanted Zwerchhau при соблюдении требований к выполнению.',
      },
      // PVE Skill 39
      "PVE Skill 39": {
         "name": 'Enchanted Redoublement',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/12329935fdf53d176f290194929c91b4f96c5212.png',
         "job_icon": 'RDM',
         "level": '50',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.2 сек.',
         "cost": '-',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 170.<br/>Комбо умение: Enchanted Zwerchhau<br/>Сила в комбо: 540<br/>Дополнительный эффект: накладывает эффект Mana Stack<br/>Стоимость: 15 Black Mana шкалы Balance Gauge<br/>Стоимость: 15 White Mana шкалы Balance Gauge<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Enchanted Zwerchhau меняется на Enchanted Redoublement при соблюдении требований к выполнению.',
      },
      // PVE Skill 40
      "PVE Skill 40": {
         "name": 'Enchanted Moulinet',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/078ff2ecf682fbabebea07caf8631619a223a774.png',
         "job_icon": 'RDM',
         "level": '52',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "cost": '-',
         "range": '8y',
         "radius_img": 'R4',
         "radius": '8y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 130 по всем противникам в конусе перед персонажем.<br/>Дополнительный эффект: накладывает эффект Mana Stack<br/>Стоимость: 20 Black Mana шкалы Balance Gauge<br/>Стоимость: 20 White Mana шкалы Balance Gauge<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Moulinet меняется на Enchanted Moulinet при соблюдении требований к выполнению.',
      },
      // PVE Skill 41 NEW
      "PVE Skill 41": {
         "name": 'Enchanted Moulinet Deux',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e5dfc01b5048f6bef58d504d6e6f633004ad8fc7.png',
         "job_icon": 'RDM',
         "level": '52',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "cost": '-',
         "range": '8y',
         "radius_img": 'R4',
         "radius": '8y',
         "content": 'Удар, наносящий урон по всем противникам в конусе перед персонажем с силой атаки 140.<br/>Комбо умение: Enchanted Moulinet<br/>Дополнительный эффект: накладывает эффект Mana Stack<br/>Стоимость: 15 Black Mana шкалы Balance Gauge<br/>Стоимость: 15 White Mana шкалы Balance Gauge<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Enchanted Moulinet меняется на Enchanted Moulinet Deux при соблюдении требований к выполнению.',
      },
      // PVE Skill 42 NEW
      "PVE Skill 42": {
         "name": 'Enchanted Moulinet Trois',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/0f1ad21893a66c8f4b9253821fee9044ba1b4464.png',
         "job_icon": 'RDM',
         "level": '52',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "cost": '-',
         "range": '8y',
         "radius_img": 'R4',
         "radius": '8y',
         "content": 'Удар, наносящий урон по всем противникам в конусе перед персонажем с силой атаки 150.<br/>Комбо умение: Enchanted Moulinet Deux<br/>Дополнительный эффект: накладывает эффект Mana Stack<br/>Стоимость: 15 Black Mana шкалы Balance Gauge<br/>Стоимость: 15 White Mana шкалы Balance Gauge<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Enchanted Moulinet Deux меняется на Enchanted Moulinet Trois при соблюдении требований к выполнению.',
      },
      // PVE Skill 43
      "PVE Skill 43": {
         "name": 'Enchanted Reprise',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a6e98885e3a5709ef22ba5ea9ad2991f3015752e.png',
         "job_icon": 'RDM',
         "level": '76',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 340.<br/>Стоимость: 5 Black Mana шкалы Balance Gauge<br/>Стоимость: 5 White Mana шкалы Balance Gauge<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // Trait 01
      "Trait 01": {
         "name": 'Dualcast',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ba8e7c2fa1542aff1a448951340a771cea935b14.png',
         "job_icon": 'RDM',
         "level": '1',
         "content": 'Накладывает эффект Dualcast при использовании любого заклинания, имеющего время применения. Когда персонаж находится под эффектом Dualcast, следующее заклинание не будет требовать времени применения. Эффект прекращается при выполнении любого действия, кроме способности. Авто атаки не отменяют эффект.<br/>Продолжительность: 15 сек.',
      },
      // Trait 02
      "Trait 02": {
         "name": 'Maim and Mend',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/688b9e979396925fa8a996968547e39f057ff539.png',
         "job_icon": 'RDM',
         "level": '20',
         "content": 'Увеличивает базовый урон умений и восстановления HP на 10%.',
      },
      // Trait 03
      "Trait 03": {
         "name": 'Maim and Mend II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f0493aff0cf655167be05890774732eebed2b598.png',
         "job_icon": 'RDM',
         "level": '40',
         "content": 'Увеличивает базовый урон умений и восстановления HP на 30%.',
      },
      // Trait 04
      "Trait 04": {
         "name": 'Enhanced Jolt',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b1a374ca735f065a1e74d73de21f2ff0ae9e37d4.png',
         "job_icon": 'RDM',
         "level": '62',
         "content": 'Улучшает умение Jolt до Jolt II. Также повышает силу атаки умений Verthunder и Veraero до 360, и силу атаки умений Verfire и Verstone до 300.',
      },
      // Trait 05
      "Trait 05": {
         "name": 'Scatter Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/25dd9bda53f9b07bde960cd4a2cd17a32e20fce2.png',
         "job_icon": 'RDM',
         "level": '66',
         "content": 'Улучшает умение Scatter до Impact.',
      },
      // Trait 06
      "Trait 06": {
         "name": 'Mana Stack',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5d6d2042423f8017649fa46279afe981ad911ba7.png',
         "job_icon": 'RDM',
         "level": '68',
         "content": 'Добавляет Mana Stack к шкале Balance Gauge при использования  Enchanted Riposte, Enchanted Zwerchhau, Enchanted Redoublement, Enchanted Moulinet, Enchanted Moulinet Deux или Enchanted Moulinet Trois, вплоть до максимума 3.<br/>После получения 3 Mana Stacks Verthunder и Verthunder II улучшаются до Verflare.<br/>После изучения Verholy получение 3 Mana Stacks также улучшает Veraero и Veraero II до Verholy.',
      },
      // Trait 07
      "Trait 07": {
         "name": 'Enhanced Displacement',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d5ae42ee8a96d14ccb2aca8fb77a3dc07870ac98.png',
         "job_icon": 'RDM',
         "level": '72',
         "content": 'Увеличивает силу атаки Displacement и Engagement до 180.',
      },
      // Trait 08
      "Trait 08": {
         "name": 'Red Magic Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/66e611103eb0f8e13a49f0ca1149c7d1cd5059aa.png',
         "job_icon": 'RDM',
         "level": '74',
         "content": 'Снижает время восстановления Contre Sixte до 35 секунд и увеличивает силу Verthunder II и Veraero II до 120.',
      },
      // Trait 09
      "Trait 09": {
         "name": 'Enhanced Manafication',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/8ebee2fe5cc848fb74933058a952ae40ccf70e6c.png',
         "job_icon": 'RDM',
         "level": '78',
         "content": 'Снижает время восстановления Manafication до 110 секунд и добавляет эффект увеличения магического урона на 5%.',
      },
      // Trait 10
      "Trait 10": {
         "name": 'Red Magic Mastery II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/79d78648190b44e68aba9e81a5663b5b1c53823f.png',
         "job_icon": 'RDM',
         "level": '82',
         "content": 'Улучшает умение Verthunder до Verthunder III и Veraero до Veraero III.<br/>После получения 3 Mana Stacks Verthunder III улучшается до Verflare и Veraero III улучшается до Verholy.',
      },
      // Trait 11
      "Trait 11": {
         "name": 'Red Magic Mastery III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ad98a9599086d8643f4d5808e2cabbc50cad1e44.png',
         "job_icon": 'RDM',
         "level": '84',
         "content": 'Улучшает умение Jolt II до Jolt III. Увеличивает силу атаки Enchanted Riposte до 280, Verthunder II до 140, Veraero II до 140, Verfire до 340, Verstone до 340, Enchanted Zwerchhau до 150, Enchanted Redoublement до 130, Impact до 210 и Enchanted Reprise до 340.',
      },
      // Trait 12
      "Trait 12": {
         "name": 'Enhanced Acceleration',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f20258e6dd074997a3856ce6b8744ee3049c6a86.png',
         "job_icon": 'RDM',
         "level": '88',
         "content": 'Позволяет накапливать заряды для последовательного использования Acceleration.<br/>Максимум зарядов: 2',
      },
      // Trait 13
      "Trait 13": {
         "name": 'Enhanced Manafication II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/082650d5e7a3b38c4db5f32824e527281fb91ba1.png',
         "job_icon": 'RDM',
         "level": '90',
         "content": 'Увеличивает максимальное количество стаков Manafication до 6.',
      },
      // Trait 14 NEW
      "Trait 14": {
         "name": 'Enhanced Embolden',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/9fc6fde931036592d442e3d56e3c0d033f463e11.png',
         "job_icon": 'RDM',
         "level": '92',
         "content": 'Накладывает эффект Thorned Flourish при использовании Embolden.<br/>Продолжительность: 30 сек.',
      },
      // Trait 15 NEW
      "Trait 15": {
         "name": 'Enchanted Blade Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/faebcc03aa187f6f45319b41b7336431d1722fc4.png',
         "job_icon": 'RDM',
         "level": '94',
         "content": 'Увеличивает силу атаки Enchanted Riposte до 300, Verfire до 380, Verstone до 380, Enchanted Zwerchhau до 170, Fleche до 480, Enchanted Redoublement до 170, Contre Sixte до 400, Verflare до 620, Verholy до 620, Enchanted Reprise до 380, Scorch до 700, Veraero III до 420, Verthunder III до 420 и Resolution до 800.',
      },
      // Trait 16 NEW
      "Trait 16": {
         "name": 'Enhanced Acceleration II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f88ff137a14d846648c1a350b6927826b0e0c316.png',
         "job_icon": 'RDM',
         "level": '96',
         "content": 'Накладывает эффект Grand Impact Ready при использовании Acceleration.<br/>Продолжительность: 30 сек.<br/>Jolt III и Impact меняются на Grand Impact под действием эффекта Grand Impact Ready.',
      },
      // Trait 17 NEW
      "Trait 17": {
         "name": 'Enhanced Manafication III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/562ae4c055cc5991095f721e986f8ae703ac75f9.png',
         "job_icon": 'RDM',
         "level": '100',
         "content": 'Накладывает эффект Prefulgence Ready при использовании всех стаков Manafication.<br/>Продолжительность: 30 сек.<br/>Manafication меняется на Prefulgence под действием эффекта Prefulgence Ready.',
      },
      // PVP Skill 01
      "PVP Skill 01": {
         "name": 'Verstone',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/9df7186ba12f011456175039cccc827396f24b22.png',
         "classification": 'Заклинание',
         "cast": '1.92 сек.',
         "recast": '2.4 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон землей с силой атаки 5,000.<br/>Дополнительный эффект: накладывает эффект Dualcast, позволяющую мгновенно использовать следующее заклинание<br/>Продолжительность: 10 сек.<br/>Может быть использовано только под действием эффекта White Shift.<br/><br/>※Умение меняется на Dualcast под действием эффекта Veraero III.<br/>※Умение меняется на Verfire под действием эффекта Black Shift.<br/>※Умение меняется на Verthunder III под действием эффектов Black Shift и Dualcast.',
      },
      // PVP Skill 02
      "PVP Skill 02": {
         "name": 'Enchanted Riposte',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/67f481da4b0a277ad6b06432a130adfe4b986d32.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 6,000.<br/>Эффект White Shift: создает вокруг персонажа барьер, поглощающий урон, равный силе лечения 6,000<br/>Продолжительность: 10 сек.<br/>Дополнительный эффект: сила барьера увеличивается на 10%, если на цель наложен эффект Monomachy<br/>Эффект Black Shift: периодический урон<br/>Сила атаки: 3,000<br/>Продолжительность: 6 сек.<br/><br/>※Умение меняется на Enchanted Zwerchhau после использования.',
      },
      // PVP Skill 03
      "PVP Skill 03": {
         "name": 'Resolution',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5aae4c251545f2fc478c40be35966398c7ab9b99.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '25y',
         "radius_img": 'R6',
         "radius": '25y',
         "content": 'Удар, наносящий нестихийный урон по всем противникам по прямой линии перед персонажем с силой атаки 8,000.<br/>Эффект White Shift: безмолвие (silence)<br/>Продолжительность: 2 сек.<br/>Эффект Black Shift: связывание (bind)<br/>Продолжительность: 3 сек.<br/>Этот умение не имеет общего времени восстановления с другими умениями.',
      },
      // PVP Skill 04
      "PVP Skill 04": {
         "name": 'Magick Barrier',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a18eb34f3095e008c14b977841ebd45e02ef04d4.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '25 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '15y',
         "content": 'Снижает урон, получаемый персонажем и ближайшими сопартийцами на 10%, а также увеличивает восстановление HP при использовании лечебных умений на 10%.<br/>Продолжительность: 10 сек.<br/>Может быть выполнено только под действием эффекта White Shift.<br/>Имеет общее время восстановления с умением Frazzle.<br/><br/>※Умение меняется на Frazzle под действием эффекта Black Shift.',
      },
      // PVP Skill 05
      "PVP Skill 05": {
         "name": 'Corps-a-corps',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b524bce7a6b14bd3f524b8c29f5df87cdfc0d955.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Рывок к цели, наносящий урон с силой атаки 4,000.<br/>Дополнительный эффект: накладывает на цель эффект Monomachy<br/>Эффект Monomachy: увеличивает наносимый урон по цели на 10% и снижает получаемый урон от нее на 10%<br/>Продолжительность: 7 сек.<br/>Максимум зарядов: 2<br/>Невозможно использовать, если персонаж находится под эффектами ограничивающими перемещение.',
      },
      // PVP Skill 06
      "PVP Skill 06": {
         "name": 'Displacement',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/447cbba6771ca9884e9fdb197d8bf20dd2b2fa15.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 4,000.<br/>Дополнительный эффект: прыжок назад на 15 ялмов<br/>Дополнительный эффект: накладывает эффект Manafication<br/>Эффект Manafication: увеличивает наносимый урон и силу лечения следующего заклинания на 20%<br/>Продолжительность: 10 сек.<br/>Максимум зарядов: 2<br/>Невозможно использовать, если персонаж находится под эффектами ограничивающими перемещение.',
      },
      // PVP Skill 07
      "PVP Skill 07": {
         "name": 'Black Shift',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ae0ecdc73d81aa25cff5dd887ee3381de4d9328c.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Накладывает эффект Black Shift, изменяющее эффекты нескольких умений.<br/>Можно использовать только под действием эффекта White Shift.<br/><br/>※Умение меняется на White Shift после использования.',
      },
      // PVP Skill 08
      "PVP Skill 08": {
         "name": 'Veraero III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/24a8dde706c9065539f39a69856dd5590e6e2657.png',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.4 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон ветром с силой атаки 5 000.<br/>Можно использовать только под действием эффектов White Shift и Dualcast.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 09
      "PVP Skill 09": {
         "name": 'Verholy',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/07cf43acafca1e04285879b3a5027c5cc7c6d135.png',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.4 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон по цели и всем ближайшим противникам с силой атаки 8,000.<br/>Дополнительный эффект: восстанавливает HP персонажа<br/>Сила лечения: 8,000<br/>Дополнительный эффект: восстанавливает HP сопартийцев, находящихся рядом с целью<br/>Сила лечения: 8,000<br/>Можно использовать только под действием эффектов White Shift и Vermilion Radiance.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 10
      "PVP Skill 10": {
         "name": 'Verfire',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/924e11f407179cd1d2bdedaac9eccbf157425635.png',
         "classification": 'Заклинание',
         "cast": '1.92 сек.',
         "recast": '2.4 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон огнем с силой атаки 5,000.<br/>Дополнительный эффект: накладывает эффект Dualcast, позволяющую мгновенно использовать следующее заклинание<br/>Продолжительность: 10 сек.<br/>Можно использовать только под действием эффекта Black Shift.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 11
      "PVP Skill 11": {
         "name": 'Verthunder III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1878973a204eebd0d777a7f32cf11e03c53405ff.png',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.4 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон молнией с силой атаки 5,000.<br/>Можно использовать только под действием эффектов Black Shift и Dualcast.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 12
      "PVP Skill 12": {
         "name": 'Verflare',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/94fb60c36518f1f3988644ffdcc786c49446eb0d.png',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.4 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон огнем по цели и всем ближайшим противникам с силой атаки 12,000.<br/>Можно использовать только под действием эффектов Black Shift и Vermilion Radiance.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 13
      "PVP Skill 13": {
         "name": 'Enchanted Zwerchhau',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e908bf25ba9fac88edf30da9b4edf9b8bcbf1758.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 7,000.<br/>Комбо умение: Enchanted Riposte<br/>Эффект White Shift : создает барьер вокруг персонажа, поглощающий урон, равный силе лечения 6,000<br/>Продолжительность: 10 сек.<br/>Дополнительный эффект: сила барьера увеличивается на 10%, если на цель наложен эффект Monomachy<br/>Эффект Black Shift: периодический урон<br/>Сила атаки: 3,000<br/>Продолжительность: 6 сек.<br/><br/>※Умение меняется на Enchanted Redoublement после использования.<br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 14
      "PVP Skill 14": {
         "name": 'Enchanted Redoublement',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b2f8944b29325a91ae300010c1fb774e9d53316e.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.4 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 8,000.<br/>Комбо умение: Enchanted Zwerchhau<br/>Дополнительный эффект: накладывает эффект Vermilion Radiance<br/>Продолжительность: 10 сек.<br/>Эффект White Shift: создает барьер вокруг персонажа, поглощающая урон, равный силе лечения 6,000<br/>Продолжительность: 10 сек.<br/>Дополнительный эффект: сила барьера увеличивается на 10%, если на цель наложен эффект Monomachy<br/>Эффект Black Shift: периодический урон<br/>Сила атаки: 3,000<br/>Продолжительность: 6 сек.<br/><br/>※Умение меняется на Verholy под действием эффектов White Shift и Vermilion Radiance.<br/>※Умение меняется на Verflare под действием эффектов Black Shift и Vermilion Radiance.<br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 15
      "PVP Skill 15": {
         "name": 'Frazzle',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1acc1c44ad72be77ee1391495ad6b3a48254d7ba.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '25 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '15y',
         "content": 'Увеличивает получаемый урон ближайших противников на 10%, а также уменьшает HP, восстанавливаемое исцеляющими умениями на 10%.<br/>Продолжительность: 10 сек.<br/>Можно использовать только под действием эффекта Black Shift.<br/>Имеет общее время восстановления с умением Magick Barrier.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 16
      "PVP Skill 16": {
         "name": 'White Shift',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/15220233b94a04dc32fa1b3aafcd4d996e47e47c.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Накладывает эффект White Shift, изменяющее эффекты нескольких умений.<br/>Можно использовать только под действием эффекта Black Shift.<br/>Автоматически активируется при смене класса на красного мага.<br/><br/>※Умение меняется на Black Shift после использования.<br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 17
      "PVP Skill 17": {
         "name": 'Southern Cross',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7c93e62e034c1a0d6cfd0dfc01ed9fa386528e9e.png',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "range": '30y',
         "radius_img": 'R10',
         "radius": '15y',
         "content": 'Накладывает метку в виде большого креста на земле под сопартийцем или противником, восстанавливая HP всем ближайшим сопартийцам и нанося урон противникам<br/>Сила лечения: 8,000<br/>Сила атаки: 8,000<br/>Эффект White Shift: сила лечения увеличивается на 50%<br/>Эффект Black Shift: сила атаки увеличена на 50%<br/>Цели, находящиеся в середине метки, получат двойной эффект от этого действия.<br/>Может быть использовано только тогда, когда шкала лимит брейка (limit gauge) заполнена.<br/>Время зарядки шкалы: 90 сек.',
      },
   };
   FILL_DB_VALUES(db);
   FILL_DB_SKILLS(db);
   FILL_DB_SKILLS_PASSIVE(db);
   FILL_DB_SKILLS_PVP(db);
   FILL_DB_SKILLS_MENU(db);
})();