(() =>{
   let db = {
      "PVE Update": `Последнее обновление: 27/06/2024`,
      "PVP Update": `Последнее обновление: 27/06/2024`,
      // PVE Skill 01
      "PVE Skill 01": {
         "name": 'Hakaze',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/55c0a798d2db426ad407ab0d506fae3afe14cd1d.png',
         "job_icon": 'SAM',
         "level": '1',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 200<br/>Дополнительный эффект: восполняет шкалу Kenki Gauge на 5',
      },
      // PVE Skill 02
      "PVE Skill 02": {
         "name": 'Jinpu',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2cdd1c3fa2b166f8da269d9e3241399d3a37f959.png',
         "job_icon": 'SAM',
         "level": '4',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 160.<br/>Комбо умение: Gyofu<br/>Сила в комбо: 320<br/>Комбо бонус: накладывает Fugetsu<br/>Эффект Fugetsu: увеличивает наносимый урон на 13%<br/>Продолжительность: 40 сек.<br/>Комбо бонус: восполняет шкалу Kenki Gauge на 5',
      },
      // PVE Skill 03
      "PVE Skill 03": {
         "name": 'Third Eye',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/3c97e963e92ae242000e51159d9eb749897d8a68.png',
         "job_icon": 'SAM',
         "level": '6',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Снижает входящий урон от следующей атаки на 10%.<br/>Продолжительность: 4 сек.<br/>Дополнительный эффект: восполняет Kenki Gauge на 10 при получении урона',
      },
      // PVE Skill 04
      "PVE Skill 04": {
         "name": 'Enpi',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b2b75c383779cbd254a8bca3dbd30f2490c1d270.png',
         "job_icon": 'SAM',
         "level": '15',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '20y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Дальний удар, наносящий урон с силой атаки 100.<br/>Бонус силы атаки Enhanced Enpi: 270<br/>Дополнительный эффект: восполняет Kenki Gauge на 10 ',
      },
      // PVE Skill 05
      "PVE Skill 05": {
         "name": 'Shifu',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/64dcd53611773e2f2c981bc01877937b5331df8c.png',
         "job_icon": 'SAM',
         "level": '18',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 160.<br/>Комбо умение: Gyofu<br/>Сила в комбо: 320<br/>Комбо бонус: накладывает Fuka<br/>Эффект Fuka: уменьшает время длительности применения и время восстановления боевых навыков и заклинаний, а также промежуток между авто атаками на 13%.<br/>Продолжительность: 40 сек.<br/>Комбо бонус: восполняет шкалу Kenki Gauge на 5',
      },
      // PVE Skill 06
      "PVE Skill 06": {
         "name": 'Fuga',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5f181040a9d1ef66c6310a307036639fd78ef6c8.png',
         "job_icon": 'SAM',
         "level": '26',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '8y',
         "radius_img": 'R4',
         "radius": '8y',
         "content": 'Удар, наносящий урон с силой атаки 90 по всем противникам в конусе перед персонажем.<br/>Дополнительный эффект: восполняет Kenki Gauge на 5',
      },
      // PVE Skill 07
      "PVE Skill 07": {
         "name": 'Gekko',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/69a82466c03f3531657ce703afb8a399fdd89812.png',
         "job_icon": 'SAM',
         "level": '30',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 180, при выполнении удара в спину цели 230.<br/>Комбо умение: Jinpu<br/>Сила в комбо: 390<br/>Сила в комбо в спину цели: 440<br/>Комбо бонус: восполняет Kenki Gauge на 10<br/>Комбо бонус: активирует Getsu',
      },
      // PVE Skill 08
      "PVE Skill 08": {
         "name": 'Iaijutsu',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/64757011257ac3561af53f09ffb47bd76744803d.png',
         "job_icon": 'SAM',
         "level": '30',
         "classification": 'Боевой навык',
         "cast": '1.3 сек.',
         "recast": '2.5 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Выполняет боевой навык в зависимости от числа Sen сохраненных в Sen Gauge.<br/>1 Sen: Higanbana<br/>2 Sen: Tenka Goken<br/>3 Sen: Midare Setsugekka<br/>Под действием эффекта Tendo, Tenka Goken меняется на Tendo Goken и Midare Setsugekka меняется на Tendo Setsugekka.',
      },
      // PVE Skill 09
      "PVE Skill 09": {
         "name": 'Mangetsu',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/81e6e44a8a26f2355226894a36dea570ce1d6962.png',
         "job_icon": 'SAM',
         "level": '35',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 100 по всем ближайшим противникам.<br/>Комбо умение: Fuko<br/>Сила в комбо: 120<br/>Комбо бонус: накладывает Fugetsu<br/>Эффект Fugetsu: увеличивает урон на 13%<br/>Продолжительность: 40 сек.<br/>Комбо бонус: восполняет Kenki Gauge на 10<br/>Комбо бонус: активирует Getsu',
      },
      // PVE Skill 10
      "PVE Skill 10": {
         "name": 'Kasha',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/8330058e7e147dc2093e838239c2865aea6d6166.png',
         "job_icon": 'SAM',
         "level": '40',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 180, при выполнении удара в бок цели 230.<br/>Комбо эффект: Shifu<br/>Сила в комбо: 390<br/>Сила в комбо в бок цели: 440<br/>Комбо бонус: восполняет Kenki Gauge на 10<br/>Комбо бонус: активирует  Ka',
      },
      // PVE Skill 11
      "PVE Skill 11": {
         "name": 'Oka',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/83caa2b18aa8a589ccdd81b8367452ef73d1e2b2.png',
         "job_icon": 'SAM',
         "level": '45',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 100 по всем ближайшим противникам.<br/>Комбо умение: Fuko<br/>Сила в комбо: 120<br/>Комбо бонус: накладывает Fuka<br/>Эффект Fuka: уменьшает время длительности применения и время восстановления боевых навыков и заклинаний, а также промежуток между авто атаками на 13%<br/>Продолжительность: 40 сек.<br/>Комбо бонус: восполняет Kenki Gauge на 10<br/>Комбо бонус: активирует  Ka',
      },
      // PVE Skill 12
      "PVE Skill 12": {
         "name": 'Yukikaze',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/353a35cad8a1e089d162451dbe5de1fb78f4b0a9.png',
         "job_icon": 'SAM',
         "level": '50',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 180.<br/>Комбо умение: Gyofu<br/>Сила в комбо: 360<br/>Комбо бонус: восполняет Kenki Gauge на 15<br/>Комбо бонус: активирует  Setsu',
      },
      // PVE Skill 13
      "PVE Skill 13": {
         "name": 'Meikyo Shisui',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/13e7fc6c10bb476259ec8d29d086bef49bea509c.png',
         "job_icon": 'SAM',
         "level": '50',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '55 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Позволяет выполнить до трех боевых навыков, требующих комбо эффект без него. Не влияет на Iaijutsu или Ogi Namikiri.<br/>Продолжительность: 20 сек.<br/>Дополнительный эффект: успешное использование Gekko накладывает Fugetsu, а успешное использование Kasha накладывает Fuka.<br/>Дополнительный эффект: накладывает эффект Tsubame-gaeshi Ready<br/>Продолжительность: 30 сек.<br/>Дополнительный эффект: накладывает эффект Tendo<br/>Продолжительность: 30 сек.<br/>Максимум зарядов: 2',
      },
      // PVE Skill 14
      "PVE Skill 14": {
         "name": 'Hissatsu: Shinten',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c57812e667388d676fd1267d87583aa29c2da2ef.png',
         "job_icon": 'SAM',
         "level": '52',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки атаки 250.<br/>Стоимость: 25 Kenki Gauge ',
      },
      // PVE Skill 15
      "PVE Skill 15": {
         "name": 'Hissatsu: Gyoten',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/98f63e44032f5b66bbe9f77ad2882e38b42854b3.png',
         "job_icon": 'SAM',
         "level": '54',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "range": '20y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Рывок к цели, наносящий урон с силой атаки 100.<br/>Стоимость: 10 Kenki Gauge<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.',
      },
      // PVE Skill 16
      "PVE Skill 16": {
         "name": 'Hissatsu: Yaten',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f939f0b2b36012cbc5096f6b64a787a8d5f5ed6a.png',
         "job_icon": 'SAM',
         "level": '56',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 100.<br/>Дополнительный эффект: отскок назад на 10 ялмов<br/>Дополнительный эффект: накладывает Enhanced Enpi<br/>Продолжительность: 15 сек.<br/>Стоимость: 10 Kenki Gauge<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.',
      },
      // PVE Skill 17
      "PVE Skill 17": {
         "name": 'Meditate',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/5c8e5325725/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4b642f7d616d6ca25a2ac0dfb230cb5f953eebd1.png',
         "job_icon": 'SAM',
         "level": '60',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Постепенно восполняет шкалу Kenki Gauge.<br/>Продолжительность: 15 сек.<br/>Дополнительный эффект: накладывает стаки Meditation когда используется в бою, вплоть до 3 стаков<br/>Kenki Gauge не будет восполняться вне битвы.<br/>Эффект спадет при использовании умений или перемещении персонажа (включая разворот в другие стороны).<br/>Прерывает авто атаки при использовании умения.<br/>Активирует время восстановления боевых навыков. Не может использоваться во время восстановления боевых навыков.',
      },
      // PVE Skill 18
      "PVE Skill 18": {
         "name": 'Hissatsu: Kyuten',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b0d5ff90bd65e254949741965c77d50b100b8241.png',
         "job_icon": 'SAM',
         "level": '62',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 120 по всем ближайшим противникам.<br/>Стоимость: 25 Kenki Gauge',
      },
      // PVE Skill 19
      "PVE Skill 19": {
         "name": 'Hagakure',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/afaf9f6273e5d6a275a84ad286c390d7337cd11d.png',
         "job_icon": 'SAM',
         "level": '68',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '5 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Конвертирует Setsu, Getsu и Ka в Kenki. Каждый конвертированный Sen восполняет шкалу Kenki Gauge на 10. Может использоваться под эффектом хотя бы одного из трех Sen.',
      },
      // PVE Skill 20
      "PVE Skill 20": {
         "name": 'Ikishoten',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/9165fbf83411057b22d8d9c2a5e29dd6fd6fce5c.png',
         "job_icon": 'SAM',
         "level": '68',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Восполняет шкалу Kenki Gauge на 50.<br/>Дополнительный эффект: накладывает Ogi Namikiri Ready<br/>Продолжительность: 30 сек.<br/>Дополнительный эффект: накладывает Zanshin Ready<br/>Продолжительность: 30 сек.<br/>Может выполняться только в бою.',
      },
      // PVE Skill 21
      "PVE Skill 21": {
         "name": 'Hissatsu: Guren',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/efa0a96cc36/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a6e4fbc47fbb90b64d6a58495cf991f9aad2548b.png',
         "job_icon": 'SAM',
         "level": '70',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "range": '10y',
         "radius_img": 'R6',
         "radius": '10y',
         "content": 'Удар, наносящий урон по всем противникам по прямой линии перед персонажем с силой атаки 500 для первого и на 25% меньше для остальных.<br/>Стоимость: 25 Kenki Gauge<br/>Имеет общее время восстановления с умением Hissatsu: Senei.',
      },
      // PVE Skill 22
      "PVE Skill 22": {
         "name": 'Hissatsu: Senei',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1812ee8f2135ed92057b767eacbf2469ef0b25ee.png',
         "job_icon": 'SAM',
         "level": '72',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 860.<br/>Стоимость: 25 Kenki Gauge<br/>Имеет общее время восстановления с умением Hissatsu: Guren.',
      },
      // PVE Skill 23
      "PVE Skill 23": {
         "name": 'Tsubame-gaeshi',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2aeabf974ab57ac123bc19cacfcd94c3ad86373a.png',
         "job_icon": 'SAM',
         "level": '76',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Повторяет использованный до этого iaijutsu.<br/>Не может быть использовано для повторения Higanbana.<br/>Может быть использовано только сразу после Iaijutsu, находясь под действием эффекта Tsubame-gaeshi Ready.',
      },
      // PVE Skill 24
      "PVE Skill 24": {
         "name": 'Shoha',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1f8f320806d886a35983a5c411ba95ede40072ce.png',
         "job_icon": 'SAM',
         "level": '80',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '10y',
         "radius_img": 'R6',
         "radius": '10y',
         "content": 'Удар, наносящий нестихийный урон по прямой линии по всем противникам перед персонажем с силой атаки 640 для первого и на 65% меньше для остальных.<br/>Может использоваться после накопления трех стаков Meditation после использования Iaijutsu, Meditate или Ogi Namikiri во время боя.<br/>Эффект Meditation пропадает после использования.',
      },
      // PVE Skill 25 NEW
      "PVE Skill 25": {
         "name": 'Tengetsu',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e19cabdcde1b0f098413243188fac82350642f89.png',
         "job_icon": 'SAM',
         "level": '82',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Уменьшает количество урона, наносимого следующей атакой, на 10%.<br/>Продолжительность: 4 сек.<br/>Дополнительный эффект: накладывает эффект Tengetsu's Foresight и восполняет шкалу Kenki Gauge на 10 при попадании.<br/>Эффект Tengetsu's Foresight: восстанавливает HP по истечении действия эффекта<br/>Продолжительность: 8 сек.<br/>Сила лечения: 500",
      },
      // PVE Skill 26
      "PVE Skill 26": {
         "name": 'Fuko',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/db60b934788a92fdfd9bf4b749c5c7ab80a56d03.png',
         "job_icon": 'SAM',
         "level": '86',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 100 по всем ближайшим противникам.<br/>Стоимость: восполняет Kenki Gauge на 10',
      },
      // PVE Skill 27
      "PVE Skill 27": {
         "name": 'Ogi Namikiri',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/08d676ac5d79d9f433c8ebc11ff39fa40246ae2b.png',
         "job_icon": 'SAM',
         "level": '90',
         "classification": 'Боевой навык',
         "cast": '1.3 сек.',
         "recast": '2.5 сек.',
         "range": '8y',
         "radius_img": 'R4',
         "radius": '8y',
         "content": 'Удар, наносящий критический (critical) урон по всем противникам в конусе перед персонажем с силой атаки 900 для первого и на 75% меньше для остальным.<br/>Наносимый урон увеличивается под действием эффектов, повышающего вероятность критического (critical) урона.<br/>Накладывает стак Meditation, вплоть до 3 стаков.<br/>Можно использовать только под действием эффекта Ogi Namikiri Ready.',
      },
      // PVE Skill 28
      "PVE Skill 28": {
         "name": 'Kaeshi: Namikiri',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/63536deb9e8a888c17e4b367bff095cc0f3c2740.png',
         "job_icon": 'SAM',
         "level": '90',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '8y',
         "radius_img": 'R4',
         "radius": '8y',
         "content": 'Удар, наносящий критический (critical) урон по всем противникам в конусе перед персонажем с силой атаки 900 для первого и на 75% меньше для остальным.<br/>Наносимый урон увеличивается под действием эффектов, повышающего вероятность критического (critical) урона.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Iaijutsu меняется на Kaeshi: Namikiri при соблюдении требований к выполнению.',
      },
      // PVE Skill 29 NEW
      "PVE Skill 29": {
         "name": 'Gyofu',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ddb014de5732830d67f200a551b9e53a5537c3b7.png',
         "job_icon": 'SAM',
         "level": '92',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 240.<br/>Дополнительный эффект: восполняет шкалу Kenki Gauge на 5',
      },
      // PVE Skill 30 NEW
      "PVE Skill 30": {
         "name": 'Zanshin',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4f7a3ffda80a03425ae8a4001c4f4c2412012047.png',
         "job_icon": 'SAM',
         "level": '96',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '8y',
         "radius_img": 'R4',
         "radius": '8y',
         "content": 'Удар, наносящий урон по всем противникам в конусе перед персонажем с силой атаки 900 для первого и на 60% меньше для остальным.<br/>Стоимость: 50 Kenki Gauge<br/>Можно использовать только под действием эффекта Zanshin Ready.',
      },
      // Jyutsu 01
      "Jyutsu 01": {
         "name": 'Higanbana',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/3db719d146f5af6ef728a9d8d093aa26553ce690.png',
         "job_icon": 'SAM',
         "level": '30',
         "classification": 'Боевой навык',
         "cast": '1.3 сек.',
         "recast": '2.5 сек.',
         "range": '6y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 200.<br/>Дополнительный эффект: периодический урон<br/>Сила урона: 50<br/>Продолжительность: 60 сек.<br/>Дополнительный эффект: накладывает стак Meditation, максимум 3<br/>Может быть использовано только после накопления 1 Sen.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Iaijutsu меняется на Higanbana при соблюдении требований к выполнению.',
      },
      // Jyutsu 02
      "Jyutsu 02": {
         "name": 'Tenka Goken',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a1e9553412c34a1614a4f9a1ece32becc2463e15.png',
         "job_icon": 'SAM',
         "level": '40',
         "classification": 'Боевой навык',
         "cast": '1.3 сек.',
         "recast": '2.5 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '8y',
         "content": 'Удар, наносящий урон с силой атаки 300 по всем окружающим противникам.<br/>Дополнительный эффект: накладывает стак Meditation, максимум 3<br/>Может быть использовано только после накопления 2 Sen.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Iaijutsu меняется на Tenka Goken при соблюдении требований к выполнению.',
      },
      // Jyutsu 03
      "Jyutsu 03": {
         "name": 'Midare Setsugekka',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2df83ffd6e49570528cb44af4ad17d777722ab1f.png',
         "job_icon": 'SAM',
         "level": '50',
         "classification": 'Боевой навык',
         "cast": '1.3 сек.',
         "recast": '2.5 сек.',
         "range": '6y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий критический (critical) урон с силой атаки 700.<br/>Наносимый урон увеличивается под действием эффектов, повышающего вероятность критического (critical) урона.<br/>Дополнительный эффект: накладывает стак Meditation, максимум 3<br/>Может быть использовано только после накопления 3 Sen.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Iaijutsu меняется на Midare Setsugekka при соблюдении требований к выполнению.',
      },
      // Jyutsu 04
      "Jyutsu 04": {
         "name": 'Kaeshi: Goken',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4609d44fb480c238ed73e42eed5cd0b722020341.png',
         "job_icon": 'SAM',
         "level": '76',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '8y',
         "content": 'Удар, наносящий урон с силой атаки 300 по всем окружающим противникам.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Iaijutsu меняется на Kaeshi: Goken при соблюдении требований к выполнению.',
      },
      // Jyutsu 05
      "Jyutsu 05": {
         "name": 'Kaeshi: Setsugekka',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/3a733f5ba1130d94fdef4b1e58f7cab9188ded4b.png',
         "job_icon": 'SAM',
         "level": '76',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '6y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий критический (critical) урон с силой атаки 700.<br/>Наносимый урон увеличивается под действием эффектов, повышающего вероятность критического (critical) урона.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Iaijutsu меняется на Kaeshi: Setsugekka при соблюдении требований к выполнению.',
      },
      // Jyutsu 06 NEW
      "Jyutsu 06": {
         "name": 'Tendo Goken',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e2af5b5515a9ffc966a94097a466bd7aaf2376e4.png',
         "job_icon": 'SAM',
         "level": '100',
         "classification": 'Боевой навык',
         "cast": '1.3 сек.',
         "recast": '2.5 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '8y',
         "content": 'Удар, наносящий урон с силой атаки 420 по всем окружающим противникам.<br/>Дополнительный эффект: накладывает стак Meditation, максимум 3<br/>Может быть использовано только под действием эффекта Tendo и после накопления 2 Sen.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Iaijutsu меняется на Tendo Goken при соблюдении требований к выполнению.',
      },
      // Jyutsu 07 NEW
      "Jyutsu 07": {
         "name": 'Tendo Setsugekka',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e4a2a3e87d6208ffe851e7555665b840b1a76f10.png',
         "job_icon": 'SAM',
         "level": '100',
         "classification": 'Боевой навык',
         "cast": '1.3 сек.',
         "recast": '3.2 сек.',
         "range": '6y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий критический (critical) урон с силой атаки 1,020.<br/>Наносимый урон увеличивается под действием эффектов, повышающего вероятность критического (critical) урона.<br/>Дополнительный эффект: накладывает стак Meditation, максимум 3<br/>Может быть использовано только под действием эффекта Tendo и после накопления 3 Sen.<br/>Этот боевой навык не имеет общего время восстановления с другими умениями.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Iaijutsu меняется на Tendo Setsugekka при соблюдении требований к выполнению.',
      },
      // Jyutsu 08 NEW
      "Jyutsu 08": {
         "name": 'Tendo Kaeshi Goken',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/07fe16cdbe1915f02ba048c0f4ce6980f74efdee.png',
         "job_icon": 'SAM',
         "level": '100',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '8y',
         "content": 'Удар, наносящий урон с силой атаки 420 по всем окружающим противникам.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Iaijutsu меняется на Tendo Kaeshi Goken при соблюдении требований к выполнению.',
      },
      // Jyutsu 09 NEW
      "Jyutsu 09": {
         "name": 'Tendo Kaeshi Setsugekka',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/210010f360b4b0d0e9f8362352abf579ea8baad5.png',
         "job_icon": 'SAM',
         "level": '100',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '3.2 сек.',
         "range": '6y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий критический (critical) урон с силой атаки 1,020.<br/>Наносимый урон увеличивается под действием эффектов, повышающего вероятность критического (critical) урона.<br/>Этот боевой навык не имеет общего время восстановления с другими умениями.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Iaijutsu меняется на Tendo Kaeshi Setsugekka при соблюдении требований к выполнению.',
      },
      // Trait 01
      "Trait 01": {
         "name": 'Kenki Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/61100cfbd684bff162dc7c9c39eeaaa3f0d96c26.png',
         "job_icon": 'SAM',
         "level": '52',
         "content": 'Восполняет Kenki Gauge при использовании определенных боевых навыков или при получении урона под эффектом Third Eye.',
      },
      // Trait 02
      "Trait 02": {
         "name": 'Kenki Mastery II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/845bef194008ec4a881c27dd5871ec567eb45d39.png',
         "job_icon": 'SAM',
         "level": '62',
         "content": 'Восполняет Kenki Gauge после использования всех боевых навыков, исключая Iaijutsu.',
      },
      // Trait 03
      "Trait 03": {
         "name": 'Way of the Samurai',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/bc58b07072e258883e9e584c4e45355d092da661.png',
         "job_icon": 'SAM',
         "level": '66',
         "content": 'Увеличивает силу атаки Hakaze до 200, Jinpu до 120 и Shifu до 120.',
      },
      // Trait 04
      "Trait 04": {
         "name": 'Enhanced Iaijutsu',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c54d56abfcd872e0c91d3759851982328da139d2.png',
         "job_icon": 'SAM',
         "level": '74',
         "content": 'Уменьшает время использования Iaijutsu до 1.3 сек.',
      },
      // Trait 05 NEW
      "Trait 05": {
         "name": 'Enhanced Meikyo Shisui',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1651419c5c39dd98ff974b56f6b0a9942a13b473.png',
         "job_icon": 'SAM',
         "level": '76',
         "content": 'Позволяет накапливать заряды для последовательного использования Meikyo Shisui.<br/>Максимум зарядов: 2<br/>Также накладывает эффект Tsubame-gaeshi Ready после использования Meiyo Shisui<br/>Продолжительность: 30 сек.',
      },
      // Trait 06
      "Trait 06": {
         "name": 'Enhanced Fugetsu and Fuka',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/976f373fc969a791206bc0fd6a8f7da24279052d.png',
         "job_icon": 'SAM',
         "level": '78',
         "content": 'Увеличивает урон Fugetsu на 13%, а Fuka уменьшает время длительности применения и время восстановления боевых навыков и заклинаний, а также промежуток между авто атаками на 13%.',
      },
      // Trait 07 NEW
      "Trait 07": {
         "name": 'Third Eye Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/3b709028b6e355c5ae928635159c7201b101d401.png',
         "job_icon": 'SAM',
         "level": '84',
         "content": 'Улучшает умение Third Eye до Tengetsu.',
      },
      // Trait 08
      "Trait 08": {
         "name": 'Way of the Samurai II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/eb2173170fff9f761a656135293703a149717ede.png',
         "job_icon": 'SAM',
         "level": '84',
         "content": 'Увеличивает силу атаки Gekko, Kasha и Yukikaze до 120.',
      },
      // Trait 09
      "Trait 09": {
         "name": 'Fuga Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/424690aa05325ca6f9e0235cec0805bb500aec0a.png',
         "job_icon": 'SAM',
         "level": '86',
         "content": 'Улучшает умение Fuga до Fuko.',
      },
      // Trait 10
      "Trait 10": {
         "name": 'Enhanced Ikishoten',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/0a505b3bd0761c6075c5e0d9564fe6c4a54d8f70.png',
         "job_icon": 'SAM',
         "level": '90',
         "content": 'Накладывает Ogi Namikiri Ready после использования Ikishoten.<br/>Продолжительность: 30 сек.',
      },
      // Trait 11 NEW
      "Trait 11": {
         "name": 'Hakaze Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1035949594b931728b2aa142259f98c75f1e104f.png',
         "job_icon": 'SAM',
         "level": '92',
         "content": 'Улучшает умение Hakaze до Gyofu.',
      },
      // Trait 12 NEW
      "Trait 12": {
         "name": 'Enhanced Hissatsu',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ffe8bda1216028de5c987ce9d6721a1eb8e5dea8.png',
         "job_icon": 'SAM',
         "level": '94',
         "content": 'Уменьшает время восстановления Hissatsu: Guren and Hissatsu: Senei до 60 секунд.',
      },
      // Trait 13 NEW
      "Trait 13": {
         "name": 'Way of the Samurai III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/76ee293b5a8fae7dd16716bc05d79216ef2689a9.png',
         "job_icon": 'SAM',
         "level": '94',
         "content": 'Увеличивает силу атаки Jinpu до 160, Shifu до 160, Enhanced Enpi до 270, Gekko до 180, Higanbana урон с течением времени до 50, Kasha до 180, Yukikaze до 180, Midare Setsugekka до 700, Kaeshi-Setsugekka до 700, Shoha до 640, Ogi Namikiri до 900 и Kaeshi: Namikiri до 900.',
      },
      // Trait 14 NEW
      "Trait 14": {
         "name": 'Enhanced Ikishoten II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b6efd3bb5cbe5bad60fee0cb0e2dc1e44a352ec5.png',
         "job_icon": 'SAM',
         "level": '96',
         "content": 'Накладывает эффект Zanshin Ready после использования Ikishoten.<br/>Продолжительность: 30 сек.',
      },
      // Trait 15 NEW
      "Trait 15": {
         "name": 'Enhanced Meikyo Shisui II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/114c9dbe00b13a2221cad88744b8c10f5ee6a724.png',
         "job_icon": 'SAM',
         "level": '100',
         "content": 'Накладывает эффект Tendo после использования Meikyo Shisui.<br/>Продолжительность: 30 сек.<br/>Tenka Goken меняется на Tendo Goken, а Midare Setsugekka - на Tendo Setsugekka под действием Tendo.',
      },
      // PVP Skill 01
      "PVP Skill 01": {
         "name": 'Yukikaze',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4550282f1053e01184225a9ebebfbd33bbe5cc82.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.2 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 3,000.<br/><br/>※Умение меняется на Hyosetsu под действием эффекта Kaiten.<br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 02
      "PVP Skill 02": {
         "name": 'Gekko',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7e2fec945f14e98f42ab2722c491576d938e630d.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.2 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 4,000.<br/>Комбо умение: Yukikaze или Hyosetsu<br/><br/>※Умение меняется на Mangetsu под действием эффекта Kaiten.<br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 03
      "PVP Skill 03": {
         "name": 'Kasha',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/01a57cd74642c830b68cd1cf56fe16a93e71ef74.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.2 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 5,000.<br/>Комбо умение: Gekko или Mangetsu<br/><br/>※Умение меняется на Oka под действием эффекта Kaiten.<br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 04
      "PVP Skill 04": {
         "name": 'Ogi Namikiri',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2ae0363856a5ee2cf457d107dee97b25d53ae416.png',
         "classification": 'Боевой навык',
         "cast": '1.3 сек.',
         "recast": '20 сек.',
         "range": '8y',
         "radius_img": 'R4',
         "radius": '8y',
         "content": 'Удар, наносящий урон по всем противникам в конусе перед персонажем с силой атаки 8,000.<br/>Сила атаки увеличивается на 50%, если атаковать только одну цель.<br/>Дополнительный эффект: при атаке двух или более целей создает вокруг персонажа барьер, поглощающий урон, равный силе лечения 8,000<br/>Продолжительность: 10 сек.<br/>Этот боевой навык не имеет общего времени восстановления с другими умениями.<br/><br/>При использовании умение меняется на Kaeshi: Namikiri.',
      },
      // PVP Skill 05
      "PVP Skill 05": {
         "name": 'Hissatsu: Soten',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4319cb6547b05b752ade2cd29a192146e77770fb.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "range": '20y',
         "radius_img": 'R6',
         "radius": '0y',
         "content": 'Стремительно прыгает вперед, нанося урон всем противникам на пути с силой атаки 4,000.<br/>Дополнительный эффект: накладывает Kaiten<br/>Продолжительность: 10 сек.<br/>Максимум зарядов: 3<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.<br/><br/>※Yukikaze меняется на Hyosetsu под действием эффекта Kaiten.<br/>※Gekko меняется на Mangetsy под действием эффекта Kaiten.<br/>※Kasha меняется на Oka под действием эффекта Kaiten.',
      },
      // PVP Skill 06
      "PVP Skill 06": {
         "name": 'Hissatsu: Chiten',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2f482255082d1bbb81b74609b8d3f374073e2f30.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '25 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Снижает получаемый урон на 25% и наносит контрудар с силой атаки 2,000 каждый раз, когда персонаж получает урон.<br/>Продолжительность: 5 сек.<br/>Дополнительный эффект: накладывает на цель эффект Kuzushi<br/>Эффект Kuzushi: увеличивает наносимый цели урон на 25%<br/>Продолжительность: 4 сек.',
      },
      // PVP Skill 07
      "PVP Skill 07": {
         "name": 'Mineuchi',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c73a2812a60a1d4905999e4ed74619e7319449b7.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Наносит урон цели, равный 10% от ее текущего HP.<br/>При нанесении урона игнорируется эффект Guard<br/>Наносит урон с силой атаки 4000 по неигровым персонажам и игрокам, находящихся в роботах.<br/>Дополнительный эффект: stun (оглушение)<br/>Продолжительность: 2 сек.',
      },
      // PVP Skill 08
      "PVP Skill 08": {
         "name": 'Meikyo Shisui',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/0e7c1775565b0143c3a89d14f0d700db42893691.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Накладывает Meikyo Shisui и Midare.<br/>Эффект Meikyo Shisui: снимает все статусные негативные эффекты, которые можно снять с помощью Purify<br/>Продолжительность: 3 сек.<br/>Продолжительность Midare: 10 сек.<br/><br/>※Умение меняется на Midare Setsugekka под действием эффекта Midare.',
      },
      // PVP Skill 09
      "PVP Skill 09": {
         "name": 'Hyosetsu',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/79456c6255deea729d1bc1637362c55d9e2ac996.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.2 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 3,000 по всем ближайшим противникам.<br/>Дополнительный эффект: связывание (bind)<br/>Продолжительность: 2 сек.<br/>Можно использовать только под действием эффекта Kaiten.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 10
      "PVP Skill 10": {
         "name": 'Mangetsu',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/3a4302dbe77ba8ab0c294a18ae2ed7ae2122c4df.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.2 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 8,000 по всем ближайшим противникам.<br/>Комбо умение: Yukikaze или Hyosetsu<br/>Можно использовать только под действием эффекта Kaiten.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 11
      "PVP Skill 11": {
         "name": 'Oka',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2177f5db1158be2e88d7bb12c44dee594c64ccbb.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.2 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 5,000 по всем ближайшим противникам.<br/>Комбо умение: Gekko или Mangetsu<br/>Дополнительный эффект: поглощает 100% нанесенного урона в виде HP<br/>Можно использовать только под действием эффекта Kaiten.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 12
      "PVP Skill 12": {
         "name": 'Midare Setsugekka',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e3c037af956f70ba94408aac789a2310bfa5da51.png',
         "classification": 'Боевой навык',
         "cast": '1.3 сек.',
         "recast": '2.2 сек.',
         "range": '8y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 16,000.<br/>Можно использовать только под действием эффекта Midare.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 13
      "PVP Skill 13": {
         "name": 'Kaeshi: Namikiri',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/511537fac5a52af6263ec710e0f44f3bacb27d12.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.2 сек.',
         "range": '8y',
         "radius_img": 'R4',
         "radius": '8y',
         "content": 'Удар, наносящий урон по всем противникам в конусе перед персонажем с силой атаки 8,000.<br/>Сила атаки увеличивается на 50%, если атаковать только одну цель.<br/>Комбо умение: Ogi Namikiri<br/>Дополнительный эффект: при атаке двух или более целей создает вокруг персонажа барьер, поглощающий урон, равный силе лечения 8000<br/>Продолжительность: 10 сек.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 14
      "PVP Skill 14": {
         "name": 'Zantetsuken',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ff8b2867c7cbf972efb8da7deaf7a5c4f48d60cb.png',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "range": '20y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Стремительно прыгает вперед, нанося урон по цели и всем ближайшим противникам с силой атаки 24,000.<br/>Если цель находится под эффектом Kuzushi, то умение наносит урон, равный 100% ее максимального HP.<br/>При нанесении урона игнорируется эффекты Guard.<br/>Дополнительный эффект Kuzushi не действует на неигровых персонажей, игроков под действием Guard или находящихся в роботах.<br/>Может быть использовано только тогда, когда шкала лимит брейка (limit gauge) заполнена.<br/>Время зарядки шкалы: 120 сек.<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.',
      },
   };
   FILL_DB_VALUES(db);
   FILL_DB_SKILLS(db);
   FILL_DB_SKILLS_PASSIVE(db);
   FILL_DB_SKILLS_PVP(db);
   FILL_DB_SKILLS_MENU(db);
})();