(() =>{
   let db = {
      "PVE Update": `Последнее обновление: 27/06/2024`,
      "PVP Update": `Последнее обновление: 27/06/2024`,
      // PVE Skill 01
      "PVE Skill 01": {
         "name": 'Ruin',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1c74fa1688f3d89d6f5b972ce384df15f62e35d1.png',
         "job_icon": 'SCH',
         "level": '1',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 150.',
      },
      // PVE Skill 02
      "PVE Skill 02": {
         "name": 'Bio',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/93f61adcffc6644730a017347d91805359b52bdb.png',
         "job_icon": 'SCH',
         "level": '2',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Периодический нестихийный урон.<br/>Сила атаки: 20<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 03 
      "PVE Skill 03": {
         "name": 'Physick',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e51f309947cde0c36f3a0cd815ca01e268928eb6.png',
         "job_icon": 'SCH',
         "level": '4',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Восстанавливает HP цели.<br/>Сила лечения: 450',
      },
      // PVE Skill 04
      "PVE Skill 04": {
         "name": 'Summon Eos',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7e5c03b72c4e181034da8121d6f2bdf2f1aa2a60.png',
         "job_icon": 'SCH',
         "level": '4',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '200 MP',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Призывает фею Eos, которая будет сражаться на стороне персонажа.<br/>Фея со статусом Guard автоматически накладывает эффект Embrance на сопартийцев, которые получают урон.',
      },
      // PVE Skill 05
      "PVE Skill 05": {
         "name": 'Resurrection',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/9e61ea15caf1f7c0e4b44943dcbee0178e61a9fd.png',
         "job_icon": 'ACN',
         "level": '12',
         "classification": 'Заклинание',
         "cast": '8 сек.',
         "recast": '2.5 сек.',
         "cost": '2400 MP',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Воскрешает цель, накладывая эффект слабости (weakeness).',
      },
      // PVE Skill 06
      "PVE Skill 06": {
         "name": 'Whispering Dawn',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/161dc95f27e69fb5bd4caecfdeab022e3560193d.png',
         "job_icon": 'SCH',
         "level": '20',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Приказывает фее использовать умение Whispering Dawn. Если призвана Seraph, приказывает ей использовать Angel's Whisper.<br/>Эффект Whispering Dawn/Angel's Whisper: постепенно восстанавливает HP ближайших сопартийцев<br/>Сила лечения: 80<br/>Продолжительность: 21 сек.",
      },
      // PVE Skill 07
      "PVE Skill 07": {
         "name": 'Bio II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ea0a5e685172203ac73332f7e1690a5a89b25590.png',
         "job_icon": 'SCH',
         "level": '26',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Периодический нестихийный урон.<br/>Сила атаки: 40<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 08
      "PVE Skill 08": {
         "name": 'Adloquium',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/2f077612950/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/07beea4eb1cc3f24533d045db5b694c939f3a3ac.png',
         "job_icon": 'SCH',
         "level": '30',
         "classification": 'Заклинание',
         "cast": '2 сек.',
         "recast": '2.5 сек.',
         "cost": '1000 MP',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Восстанавливает HP цели.<br/>Сила лечения: 300<br/>Дополнительный эффект: накладывает на цель эффект Galvanize, который предотвращает получение урона, равного 180% от количества восстановленных HP. При критическом восстановлении HP также накладывает эффект Catalyze, который предотвращает получение урона, равного 180% от количества восстановленных HP<br/>Продолжительность: 30 сек.<br/>Эффект не складывается с некоторыми эффектами барьеров сейджа.',
      },
      // PVE Skill 09
      "PVE Skill 09": {
         "name": 'Succor',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/3982b226cea/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/59ca7d9f2002ba3176f070a023bcfd8fa2129fb9.png',
         "job_icon": 'SCH',
         "level": '35',
         "classification": 'Заклинание',
         "cast": '2 сек.',
         "recast": '2.5 сек.',
         "cost": '1000 MP',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '15y',
         "content": 'Восстанавливает HP персонажа и всех ближайших сопартийцев.<br/>Сила лечения: 200<br/>Дополнительный эффект: создает магический барьер, который предотвращает получение урона, равного 160% от количества восстановленных HP<br/>Продолжительность: 30 сек.<br/>Эффект не складывается с некоторыми эффектами барьеров сейджа.',
      },
      // PVE Skill 10
      "PVE Skill 10": {
         "name": 'Ruin II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d6875ae1008a9e4b2d04562cff42646752e919c5.png',
         "job_icon": 'SCH',
         "level": '38',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 220.',
      },
      // PVE Skill 11
      "PVE Skill 11": {
         "name": 'Fey Illumination',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/6ed1ace8e31760fa3b042e6d27dac669668196b0.png',
         "job_icon": 'SCH',
         "level": '40',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Приказывает фее использовать умение Fey Illumination. Если призвана Seraph, приказывает ей использовать Seraphic Illumination.<br/>Эффект Fey Illumination/Seraphic Illumination: увеличивает эффективность магии лечения всех ближайших сопартийцев на 10% и снижает получаемый ближайшими сопартийцами магический урон на 5%.<br/>Продолжительность: 20 сек.<br/>Эффект не складывается с эффектом Seraphic Illumination.',
      },
      // PVE Skill 12
      "PVE Skill 12": {
         "name": 'Aetherflow',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/175631d8db5550a7b74a9bc811c3781e083e393e.png',
         "job_icon": 'SCH',
         "level": '45',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Восстанавливает 20% от максимума MP.<br/>Дополнительный эффект: Aetherflow III<br/>Может использоваться только в бою.',
      },
      // PVE Skill 13
      "PVE Skill 13": {
         "name": 'Energy Drain',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/92ea9227a8a09c62eb53852e2c26c0d6763a35c2.png',
         "job_icon": 'SCH',
         "level": '45',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 100.<br/>Дополнительный эффект: поглощает часть нанесенного урона в виде HP<br/>Дополнительный эффект: восполняет шкалу Faerie Gauge на 10<br/>Стоимость: 1 Aetherflow Gauge',
      },
      // PVE Skill 14
      "PVE Skill 14": {
         "name": 'Lustrate',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/c27e36893ce/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a9adc8943d1d8402366c869416b7a9d5ef7fcf07.png',
         "job_icon": 'SCH',
         "level": '45',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "cost": '-',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Восстанавливает HP цели.<br/>Сила лечения: 600<br/>Дополнительный эффект: восполняет шкалу Faerie Gauge на 10<br/>Стоимость: 1 Aetherflow Gauge',
      },
      // PVE Skill 15
      "PVE Skill 15": {
         "name": 'Art of War',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a414b67652d67ff6707276156d1ce275f188ef07.png',
         "job_icon": 'SCH',
         "level": '46',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 165 по всем окружающим противникам.',
      },
      // PVE Skill 16
      "PVE Skill 16": {
         "name": 'Sacred Soil',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/0479212014e/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4c47bdf94dc6c3dcd9b303cfa42a08a5cfd13629.png',
         "job_icon": 'SCH',
         "level": '50',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '30 сек.',
         "cost": '-',
         "range": '30y',
         "radius_img": 'R2',
         "radius": '15y',
         "content": 'В указанном месте создает область, в которой сопартийцы будут получать только 90% от входящего урона.<br/>Продолжительность: 15 сек.<br/>Дополнительный эффект: периодическое лечение (regen)<br/>Сила лечения: 100<br/>Дополнительный эффект: восполняет шкалу Faerie Gauge на 10<br/>Стоимость: 1 Aetherflow Gauge',
      },
      // PVE Skill 17
      "PVE Skill 17": {
         "name": 'IndomitСпособность',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/983121f3ab5/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7f80a5bd016eab7200c55dd8d1d6afb07361a0ca.png',
         "job_icon": 'SCH',
         "level": '52',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '30 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '15y',
         "content": 'Восстанавливает HP персонажа и всех ближайших сопартийцев.<br/>Сила лечения: 400<br/>Дополнительный эффект: восполняет шкалу Faerie Gauge на 10<br/>Стоимость: 1 Aetherflow Gauge',
      },
      // PVE Skill 18
      "PVE Skill 18": {
         "name": 'Broil',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/e7491bf50a9/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7203f797d2c3dd4148a8cb5fe510c1cfd1ac46a8.png',
         "job_icon": 'SCH',
         "level": '54',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 220.',
      },
      // PVE Skill 19
      "PVE Skill 19": {
         "name": 'Deployment Tactics',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/d97b37c19da/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/307e3a65fff1e38b28235509dd392323642d6965.png',
         "job_icon": 'SCH',
         "level": '56',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '90 сек.',
         "cost": '-',
         "range": '30y',
         "radius_img": 'R2',
         "radius": '30y',
         "content": 'Распространяет эффект Galvanize, наложенный персонажем на себя или на сопартийца, на всех ближайших сопартийцев.<br/>Продолжительность: имеет общее время восстановления с оригинальным эффектом<br/>Умение не будет иметь эффекта, если изначальная цель не находится под действием Galvanize.',
      },
      // PVE Skill 20
      "PVE Skill 20": {
         "name": 'Emergency Tactics',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/8d033a705ce/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/fbfaa6c46fac537aec9d2903ec64d4f64fc54557.png',
         "job_icon": 'SCH',
         "level": '58',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Преобразует следующие эффекты Galvanize и Catalyze в восстановление HP, равное количеству сниженного урона, предназначенного для барьера.<br/>Продолжительность: 15 сек.',
      },
      // PVE Skill 21
      "PVE Skill 21": {
         "name": 'Dissipation',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/51612260b5d/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/fffbdbce557a09ee3a50f541fac07d432bfc7c89.png',
         "job_icon": 'SCH',
         "level": '60',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '180 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Отзывает фею с поля битвы, давая максимум стаков Aetherflow. Также увеличивает эффективность магии лечения на 20%.<br/>Продолжительность: 30 сек.<br/>Отозванная фея вернется, как только закончится эффект умения.<br/>Умение Summon Eos не может быть использовано, пока персонаж находится под действием эффекта Dissipation.<br/>Может использоваться только когда фея призвана и персонаж находится в бою.',
      },
      // PVE Skill 22
      "PVE Skill 22": {
         "name": 'Excogitation',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b46ada85c48a81940953f46eaaba05f1c2f5cfdd.png',
         "job_icon": 'SCH',
         "level": '64',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '45 сек.',
         "cost": '-',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Накладывает на персонажа или сопартийца эффект Excogitation, который восстанавливает HP в момент, когда запас HP падает ниже 50% или заканчивается время действия эффекта.<br/>Сила лечения: 800<br/>Продолжительность: 45 сек.<br/>Дополнительный эффект: восполняет Faerie Gauge на 10<br/>Стоимость: 1 Aetherflow Gauge',
      },
      // PVE Skill 23
      "PVE Skill 23": {
         "name": 'Broil II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d8d8172feffed42f80d335bb7bedb14cc90fbd56.png',
         "job_icon": 'SCH',
         "level": '64',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 240.',
      },
      // PVE Skill 24
      "PVE Skill 24": {
         "name": 'Chain Stratagem',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2f5f538d79932e3bfb3bd5c72af6f13987aa3e6d.png',
         "job_icon": 'SCH',
         "level": '66',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Увеличивает шанс получения целью критического (critical) удара на 10%.<br/>Продолжительность: 15 сек.<br/>Дополнительный эффект: накладывает эффект Impact Imminent<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 25
      "PVE Skill 25": {
         "name": 'Aetherpact',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/7dfe6b513d8/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/eb866b142bd93d46ffa7809e1092aefc48f48f3c.png',
         "job_icon": 'SCH',
         "level": '70',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '3 сек.',
         "cost": '-',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Приказывает фее использовать Fey Union на выбранного сопартийца. Умение отменяется при повторном использовании.<br/>Стоимость: 10 Faerie Gauge<br/>Эффект Union Effect: постепенно восстанавливает HP сопартийца, на которого фея использовала Fey Union<br/>Сила лечения: 300<br/>Шкала Faerie Gauge расходуется по 10, пока восстанавливается HP. Эффект Fey Union завершается при использовании других умений феи или когда сопартиец находится за пределами 30 ялмов от феи.<br/>Шкала Faerie Gauge восполняется, если фея или Seraph призваны и успешно применяют умение Aetherflow в бою.',
      },
      // PVE Skill 26
      "PVE Skill 26": {
         "name": 'Dissolve Union',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/10602136009d5a92a005f0bd127a1a9ec8c1691a.png',
         "job_icon": 'SCH',
         "level": '70',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Отменяет эффект Fey Union.',
      },
      // PVE Skill 27
      "PVE Skill 27": {
         "name": 'Biolysis',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e77ebe8644e35de5bc2d67a4c8365d6d726c9ca4.png',
         "job_icon": 'SCH',
         "level": '72',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Периодический нестихийный урон.<br/>Сила атаки: 75<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 28
      "PVE Skill 28": {
         "name": 'Broil III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1f85b58d71471a33c2d35db849b20a681bfd5b56.png',
         "job_icon": 'SCH',
         "level": '72',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 255.',
      },
      // PVE Skill 29
      "PVE Skill 29": {
         "name": 'Recitation',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b1be794db381c20399faf7dec80b7f64eaba2e61.png',
         "job_icon": 'SCH',
         "level": '74',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Позволяет выполнять Adloquium, Concitation, IndomitСпособность или Excogitation без использование ресурсов, а также с гарантированным критическим эффектом восстановления HP.<br/>Продолжительность: 15 сек.',
      },
      // PVE Skill 30
      "PVE Skill 30": {
         "name": 'Fey Blessing',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e37b65935298898f61fd4b12a293998ba1258be5.png',
         "job_icon": 'SCH',
         "level": '76',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Приказывает фее использовать Fey Blessing.<br/>Эффект Fey Blessing: восстанавливает HP всем ближайшим сопартийцам<br/>Сила лечения: 320',
      },
      // PVE Skill 31
      "PVE Skill 31": {
         "name": 'Summon Seraph',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ff070d67e4c75ed8bb06de1f577979e8c69c8ad1.png',
         "job_icon": 'SCH',
         "level": '80',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Призывает фею Seraph, которая будет сражаться на стороне персонажа. Фея со статусом Guard автоматически накладывает эффект Seraphic Veil на сопартийцев, которые получают урон.<br/>Нельзя призвать Seraph, если другой питомец не был призван. Призванный питомец покинет поле боя на время призыва Seraph и вернется после.<br/>Продолжительность: 22 сек.',
      },
      // PVE Skill 32
      "PVE Skill 32": {
         "name": 'Consolation',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/86ce58393104f45f36ef15d9d358a684c4013df4.png',
         "job_icon": 'SCH',
         "level": '80',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '30 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Приказывает Seraph использовать Consolation.<br/>Эффект Consolation: восстанавливает HP всех ближайших сопартийцев<br/>Сила лечения: 250<br/>Дополнительный эффект: создает магический барьер, который поглощает получаемый урон, равный восстановленному HP<br/>Продолжительность: 30 сек.<br/>Максимум зарядов: 2',
      },
      // PVE Skill 33
      "PVE Skill 33": {
         "name": 'Broil IV',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ec2463dfb6a287aaf59d57acf7620690fb92606e.png',
         "job_icon": 'SCH',
         "level": '82',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 310.',
      },
      // PVE Skill 34
      "PVE Skill 34": {
         "name": 'Art of War II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ec9b2021f0cbe6165173334f9081ce3be52c92d2.png',
         "job_icon": 'SCH',
         "level": '82',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 180 по всем окружающим противникам.',
      },
      // PVE Skill 35
      "PVE Skill 35": {
         "name": 'Protraction',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4960cc6d3b31acfe657bfbdca97021bc546aada0.png',
         "job_icon": 'SCH',
         "level": '86',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "cost": '-',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Увеличивает максимальный запас HP персонажа или сопартийца на 10% и восстанавливает увеличенное количество.<br/>Дополнительный эффект: увеличивает силу лечебных умений на 10%<br/>Продолжительность: 10 сек.',
      },
      // PVE Skill 36
      "PVE Skill 36": {
         "name": 'Expedient',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b9eb7f8aed74850abe24b753549fc676af9db2c8.png',
         "job_icon": 'SCH',
         "level": '90',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '30y',
         "content": 'Накладывает Expedience и Desperate Measures на всех ближайших сопартийцев.<br/>Эффект Expedience: увеличивает скорость передвижения<br/>Продолжительность: 10 сек.<br/>Эффект Desperate Measures: снижает получаемый урон на 10%<br/>Продолжительность: 20 сек.',
      },
      // PVE Skill 37 NEW
      "PVE Skill 37": {
         "name": 'Baneful Impaction',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/16ca1e2b66efb797ca63394b5f856ab89a709acf.png',
         "job_icon": 'SCH',
         "level": '92',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Наносит по цели и всем окружающим противникам периодический нестихийный урон.<br/>Сила атаки: 140<br/>Продолжительность: 15 сек.<br/>Можно использовать только под действием эффекта Impact Imminent.',
      },
      // PVE Skill 38 NEW
      "PVE Skill 38": {
         "name": 'Concitation',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f124b01882a45f5befe10fa82964fc7fb7895e8c.png',
         "job_icon": 'SCH',
         "level": '96',
         "classification": 'Заклинание',
         "cast": '2 сек.',
         "recast": '2.5 сек.',
         "cost": '1000 MP',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '15y',
         "content": 'Восстанавливает HP персонажа и всех ближайших сопартийцев.<br/>Сила лечения: 200<br/>Дополнительный эффект: создает магический барьер, который предотвращает получение урона, равного 180% от количества восстановленных HP.<br/>Продолжительность: 30 сек.<br/>Эффект не работает вместе с некоторыми эффектами барьеров сейджа.',
      },
      // PVE Skill 39 NEW
      "PVE Skill 39": {
         "name": 'Seraphism',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/3660e0317ed2aba78b7cfdc526dd174efa94d88d.png',
         "job_icon": 'SCH',
         "level": '100',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '180 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Постепенно восстанавливает HP персонажа и всех ближайших сопартийцев в радиусе 50 ялмов.<br/>Сила лечения: 100<br/>Дополнительный эффект: заменяет Adloquium на Manifestation и Concitation на Accession<br/>Дополнительный эффект: сбрасывает время повторного применения Emergency Tactics и уменьшает его повторное применение до 1 сек.<br/>Продолжительность: 15 сек.<br/>Эффект не складывается с эффектом Dissipation.<br/>Может использоваться только когда фея призвана и персонаж находится в бою.',
      },
      // PVE Skill 40 NEW
      "PVE Skill 40": {
         "name": 'Manifestation',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7244131eba68b8042f1461bf4100deaebe2a7c0d.png',
         "job_icon": 'SCH',
         "level": '100',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '1000 MP',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Восстанавливает HP цели.<br/>Сила лечения: 360<br/>Дополнительный эффект: накладывает на цель эффект Galvanize, который предотвращает получение урона, равного 180% от количества восстановленных HP. При критическом восстановлении HP также накладывает эффект Catalyze, который предотвращает получение урона, равного 180% от количества восстановленных HP. <br/>Продолжительность: 30 сек.<br/>Эффект не работает вместе с некоторыми эффектами барьеров сейджа.<br/>Можно использовать только под действием эффекта Seraphism.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Adloquium меняется на Manifestation при соблюдении требований к выполнению.',
      },
      // PVE Skill 41 NEW
      "PVE Skill 41": {
         "name": 'Accession',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c859b1042c024b57c646316f1e0e93ff5e5f90fb.png',
         "job_icon": 'SCH',
         "level": '100',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '1000 MP',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '15y',
         "content": 'Восстанавливает HP персонажа и всех ближайших сопартийцев.<br/>Сила лечения: 240<br/>Дополнительный эффект: создает магический барьер, который предотвращает получение урона, равного 180% от количества восстановленных HP.<br/>Продолжительность: 30 сек.<br/>Эффект не работает вместе с некоторыми эффектами барьеров сейджа.<br/>Можно использовать только под действием эффекта Seraphism.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Concitation меняется на Accession при соблюдении требований к выполнению.',
      },
      // Pet Actions 01
      "Pet Actions 01": {
         "name": 'Embrace',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d674990026a72270d2b697fb082a11876075d580.png',
         "job_icon": 'SCH',
         "level": '1',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '3 сек.',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Восстанавливает HP цели.<br/>Сила лечения: 180<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // Pet Actions 02
      "Pet Actions 02": {
         "name": 'Whispering Dawn',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2b4f6def5e70800aa4fee24c630e0e1c1fb238a7.png',
         "job_icon": 'SCH',
         "level": '20',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '-',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '15y',
         "content": 'Постепенно восстанавливает HP персонажа и всех ближайших сопартийцев.<br/>Сила лечения: 80<br/>Продолжительность: 21 сек.<br/><br/>※Это умение нельзя поместить на хотбар',
      },
      // Pet Actions 03
      "Pet Actions 03": {
         "name": 'Fey Illumination',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/23bfb94bb82e70982c73fafd94771c0d522bc326.png',
         "job_icon": 'SCH',
         "level": '40',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '-',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '30y',
         "content": 'Увеличивает эффективность магии лечения всех ближайших сопартийцев на 10% и снижает получаемый ближайшими сопартийцами магический урон на 5%.<br/>Продолжительность: 20 сек.<br/>Эффект не складывается с Seraphic Illumination.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // Pet Actions 04
      "Pet Actions 04": {
         "name": 'Fey Union',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2289de5779836f1b6905349f5031b2421bc9fd01.png',
         "job_icon": 'SCH',
         "level": '70',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '-',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Постепенно восстанавливает HP сопартийца, к которому фея привязана с помощью Fey Union.<br/>Сила лечения: 300<br/>Шкала Faerie Gauge тратится, в то время как восстанавливается HP. Эффект Fey Union спадает, когда фея использует другие умения. Цель умения должна быть не более чем в 30 ялмах.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // Pet Actions 05
      "Pet Actions 05": {
         "name": 'Fey Blessing',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7e8ec62242991c3169dad8acbd2663bbc806ba70.png',
         "job_icon": 'SCH',
         "level": '76',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '-',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '20y',
         "content": 'Восстанавливает HP всех ближайших сопартийцев.<br/>Сила лечения: 320<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // Pet Actions 06
      "Pet Actions 06": {
         "name": 'Seraphic Veil',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/07f1ba0fbda8b1b69078795da3932089e055e10d.png',
         "job_icon": 'SCH',
         "level": '80',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '3 сек.',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Восстанавливает HP цели.<br/>Сила лечения: 180<br/>Дополнительный эффект: создает магический барьер, который поглощает получаемый урон, равный восстановленному HP<br/>Продолжительность: 30 сек.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // Pet Actions 07
      "Pet Actions 07": {
         "name": "Angel's Whisper",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c6732641fcefad97152fbf3fbefa0a4a1d3a5114.png',
         "job_icon": 'SCH',
         "level": '80',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '-',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '15y',
         "content": 'Постепенно восстанавливает HP всех ближайших сопартийцев.<br/>Сила лечения: 80<br/>Продолжительность: 21 сек.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // Pet Actions 08
      "Pet Actions 08": {
         "name": 'Seraphic Illumination',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f52540afc77b83926b4b31d0c3caacd9147e7af6.png',
         "job_icon": 'SCH',
         "level": '80',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '-',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '30y',
         "content": 'Увеличивает эффективность магии лечения всех ближайших сопартийцев на 10% и снижает получаемый магический урон ближайшими сопартийцами на 5%.<br/>Продолжительность: 20 сек.<br/>Эффект не складывается с эффектом Fey Illumination.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // Pet Actions 09
      "Pet Actions 09": {
         "name": 'Consolation',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/49e61f876fbd6dccbebcf0e5d2f979f2472df3f5.png',
         "job_icon": 'SCH',
         "level": '80',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '-',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '30y',
         "content": 'Восстанавливает HP всех ближайших сопартийцев.<br/>Сила лечения: 250<br/>Дополнительный эффект: создает магический барьер, который поглощает получаемый урон, равный восстановленному HP<br/>Продолжительность: 30 сек.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // Pet Actions (Commands)
      "Away": `Приказ питомцу покинуть поле боя.`,
      "Heel": `Приказ питомцу следовать за персонажем.`,
      "Place": `Приказ питомцу переместиться в указанную область.`,
      "Stay": `Приказ питомцу находиться на месте.`,
      "Guard": `Приказ питомцу не атаковать, пока персонаж не атакует.`,
      "Steady": `Приказ питомцу не атаковать до тех пор, пока ему напрямую не приказано.`,
      // Trait 01
      "Trait 01": {
         "name": 'Maim and Mend',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/688b9e979396925fa8a996968547e39f057ff539.png',
         "job_icon": 'ACN',
         "level": '20',
         "content": 'Увеличивает базовый урон умений и восстановления HP на 10%.<br/>Также увеличивает базовый урон и восстановление HP питомца на 10%.',
      },
      // Trait 02
      "Trait 02": {
         "name": 'Corruption Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/fd4ddaac3d4898d0689365d5038649a6e0beb2f5.png',
         "job_icon": 'SCH',
         "level": '26',
         "content": 'Улучшает умение Bio до Bio II.',
      },
      // Trait 03
      "Trait 03": {
         "name": 'Maim and Mend II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f0493aff0cf655167be05890774732eebed2b598.png',
         "job_icon": 'ACN',
         "level": '40',
         "content": 'Увеличивает базовый урон умений и восстановления HP на 30%.<br/>Также увеличивает базовый урон и восстановление HP питомца на 30%.',
      },
      // Trait 04
      "Trait 04": {
         "name": 'Broil Mastery',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/e7491bf50a9/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1ef0bbff5fb269b52268453973e2b7fa93f67781.png',
         "job_icon": 'SCH',
         "level": '54',
         "content": 'Улучшает умение Ruin до Broil и увеличивает силу атаки Ruin II до 160 и Art of War до 165.',
      },
      // Trait 05
      "Trait 05": {
         "name": 'Broil Mastery II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/36b142f4c46cc7055a73a4a440e4dc84f36d2292.png',
         "job_icon": 'SCH',
         "level": '64',
         "content": 'Улучшает умение Broil до Broil II и увеличивает силу атаки Ruin II до 180.',
      },
      // Trait 06
      "Trait 06": {
         "name": 'Corruption Mastery II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ff3a29ed186d5e46a9a2abbb5a84d771b75de7d0.png',
         "job_icon": 'SCH',
         "level": '72',
         "content": 'Улучшает умение Bio II до Biolysis.',
      },
      // Trait 07
      "Trait 07": {
         "name": 'Broil Mastery III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c9a4609b0f6fee0a67c7a77da9c65dc0131c0e71.png',
         "job_icon": 'SCH',
         "level": '72',
         "content": 'Улучшает умение Broil II до Broil III и увеличивает силу атаки Ruin II до 200.',
      },
      // Trait 08
      "Trait 08": {
         "name": 'Enhanced Sacred Soil',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d4ca0ba1f12bb4295af4b02e6cf5c14b1662478c.png',
         "job_icon": 'SCH',
         "level": '78',
         "content": 'Наделяет дополнительным эффектом Sacred Soil, который периодически восстанавливает HP.',
      },
      // Trait 09
      "Trait 09": {
         "name": 'Broil Mastery IV',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/eb3e1565b48bbfe93ed55ba61fec2a20634eb6c4.png',
         "job_icon": 'SCH',
         "level": '82',
         "content": 'Улучшает Broil III до Broil IV и увеличивает силу атаки Ruin II до 220.',
      },
      // Trait 10
      "Trait 10": {
         "name": 'Art of War Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2f128fa215622f4f48891b6f590a043b84916c85.png',
         "job_icon": 'SCH',
         "level": '82',
         "content": 'Улучшает умение Art of War до Art of War II.',
      },
      // Trait 11
      "Trait 11": {
         "name": 'Enhanced Healing Magic',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a24e5cd23307348ea0119062908b5153b2b84ca2.png',
         "job_icon": 'SCH',
         "level": '85',
         "content": 'Увеличивает силу исцеляющих умений Physick до 450, Embrace до 180 и Seraphic Veil до 180.<br/>Увеличивает прочность барьеров умений Adloquium до 180% от восстановленного HP и Succor до 160% от восстановленного HP.',
      },
      // Trait 12
      "Trait 12": {
         "name": 'Enhanced Deployment Tactics',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/588edc8bc960ee211bf98b7c7a7d4c475b8aa12e.png',
         "job_icon": 'SCH',
         "level": '88',
         "content": 'Уменьшает время восстановления умения Deployment Tactics до 90 сек.',
      },
      // Trait 13 NEW
      "Trait 13": {
         "name": 'Enhanced Chain Stratagem',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d7db48ae39f61343dfe40dca1213dfc7cafc7cac.png',
         "job_icon": 'SCH',
         "level": '92',
         "content": 'Накладывает эффект Impact Imminent при использовании Chain Strategem.<br/>Продолжительность: 30 сек.',
      },
      // Trait 14 NEW
      "Trait 14": {
         "name": "Tactician's Mastery",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/faebcc03aa187f6f45319b41b7336431d1722fc4.png',
         "job_icon": 'SCH',
         "level": '94',
         "content": 'Увеличивает силу атаки Biolysis, наносящего урон с течением времени, до 75 и Broil IV до 310.',
      },
      // Trait 15 NEW
      "Trait 15": {
         "name": 'Succor Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4da1e7f4705cf4f9818dfa7d28dc35814f7b6291.png',
         "job_icon": 'SCH',
         "level": '96',
         "content": 'Улучшает умение Succor до Concitation.',
      },
      // Trait 16 NEW
      "Trait 16": {
         "name": 'Enhanced Recitation',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/3dab3b88f599e0456c01548bf94c8bd9895ee004.png',
         "job_icon": 'SCH',
         "level": '98',
         "content": 'Сокращает время восстановления Recitation до 60 секунд.',
      },
      // PVP Skill 01
      "PVP Skill 01": {
         "name": 'Broil IV',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f6608e86b2f0526d4f9fd593eac7cb7e8a674668.png',
         "classification": 'Заклинание',
         "cast": '1.44 сек.',
         "recast": '2.4 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 5,000.',
      },
      // PVP Skill 02
      "PVP Skill 02": {
         "name": 'Adloquium',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/22a3932c3e8625b941a6d65c7bb1985e2244abe7.png',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Восстанавливает HP цели.<br/>Сила лечения: 3,000<br/>Дополнительный эффект: накладывает на цель Galvanize и Catalyze<br/>Эффект Galvanize: поглощающий урон равный силе лечения 6,000<br/>Продолжительность: 15 сек.<br/>Сила барьера увеличивается на 50%, когда персонаж находится под действием Recitation.<br/>Эффект Catalyze: увеличивает наносимый урон на 8%<br/>Продолжительность: 15 сек.<br/>Максимум зарядов: 2<br/>Этот умение не имеет общего времени восстановления с другими умениями.',
      },
      // PVP Skill 03
      "PVP Skill 03": {
         "name": 'Biolysis',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f1a089378baca67848f466998eaf675ca65b241f.png',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Накладывает на цель Biolysis and Biolytic.<br/>Эффект Biolysis: периодический урон<br/>Сила атаки: 3,000<br/>Продолжительность: 15 сек.<br/>Сила атаки увеличивается на 50%, когда персонаж находится под действием Recitation.<br/>Эффект Biolytic: снижает наносимый целью урон на 8%<br/>Продолжительность: 15 сек.<br/>Этот умение не имеет общего времени восстановления с другими умениями.',
      },
      // PVP Skill 04
      "PVP Skill 04": {
         "name": 'Deployment Tactics',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ba157dccbbb4761461ca40b5e03c2a882498cdf3.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '30y',
         "radius_img": 'R2',
         "radius": '15y',
         "content": 'Распространяет эффект Galvanize, примененный персонажем на себя или на сопартийца, на всех ближайших сопартийцев.<br/>При выборе противника распространяет эффекты Biolysis and Biolytic по всем окружающим противникам.<br/>Продолжительность: время, оставшееся от первоначального эффекта<br/>Не действует на неигровых персонажей, игроков под действием Guard или находящихся в роботах.<br/>Максимум зарядов: 2',
      },
      // PVP Skill 05
      "PVP Skill 05": {
         "name": 'Mummification',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/00aa2e44a8489b7640717e48cdf0097f6fb2bca0.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '8y',
         "radius_img": 'R4',
         "radius": '8y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 6,000 по всем противникам в конусе перед персонажем.<br/>Дополнительный эффект: уменьшает количество HP, восстанавливаемых целью умениями лечения, на 25%<br/>Продолжительность: 10 сек.',
      },
      // PVP Skill 06
      "PVP Skill 06": {
         "name": 'Expedient',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5f98fdab5e9b3c01f61588afd6f60ceeb8fc7966.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '30 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '15y',
         "content": 'Накладывает Expedience и Desperate Measures на персонажа и всех ближайших сопартийцев.<br/>Эффект Expedience: увеличивает скорость передвижения на 25%<br/>Продолжительность: 10 сек.<br/>Эффект Desperate Measures: снижает получаемый урон на 10%<br/>Продолжительность: 10 сек.<br/>Дополнительный эффект: накладывает эффект Recitation<br/>Эффект Recitation: увеличивает силу умений Galvanize, Biolysis и Biolytic<br/>Продолжительность: 15 сек.',
      },
      // PVP Skill 07
      "PVP Skill 07": {
         "name": 'Consolation',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/fcb5a5bb525f6e87cb54b03c28dee34f62bc2cbb.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Приказывает Seraph использовать Consolation.<br/>Эффект Consolation: восстанавливает HP всех ближайших сопартийцев<br/>Сила лечения: 4,000<br/>Дополнительный эффект: создаёт магический барьер, который поглощает получаемый урон, равный силе лечения 4,000<br/>Продолжительность: 10 сек.<br/>Можно использовать только во время призыва Seraph.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 08
      "PVP Skill 08": {
         "name": 'Seraphic Veil',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/fe17c3c2cb39842c9bfe50d5839d2b6a93075ef9.png',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Восстанавливает HP цели.<br/>Сила лечения: 4,000<br/>Дополнительный эффект: создаёт магический барьер, который поглощает получаемый урон, равный равный силе лечения 4,000<br/>Продолжительность: 10 сек.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 09
      "PVP Skill 09": {
         "name": 'Consolation',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7a5471b9fcc2f37dee57e8705f450297f8ed876a.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '20y',
         "content": 'Восстанавливает HP всех ближайших сопартийцев.<br/>Сила лечения: 4,000<br/>Дополнительный эффект: создаёт магический барьер, который поглощает получаемый урон, равный силе лечения 4,000.<br/>Продолжительность: 10 сек.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 10
      "PVP Skill 10": {
         "name": 'Summon Seraph',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/614407d07c71d678c0f13c555dfb338d69fbf9e7.png',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "range": '30y',
         "radius_img": 'R2',
         "radius": '10y',
         "content": 'Призывает фею Seraph для сражения в указанную область.<br/>Сразу после вызова Seraph использует Seraph Flight.<br/>Автоматически накладывает Seraphic Veil на сопартийцев, получающих урон.<br/>Дополнительный эффект: накладывает эффект Recitation<br/>Эффект Recitation: увеличивает силу умений Galvanize, Biolysis и Biolytic<br/>Продолжительность: 15 сек.<br/>Может быть использовано только тогда, когда шкала лимит брейка (limit gauge) заполнена.<br/>Время зарядки шкалы: 90 сек.<br/><br/>※Умением меняется на Consolation после использования.',
      },
      // PVP Skill 11
      "PVP Skill 11": {
         "name": 'Seraph Flight',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4718502b9fd4f9ed2848fb3cbcb42015f7d70440.png',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '10y',
         "content": 'Накладывает Seraph Flight и Excogitation на всех ближайших сопартийцев.<br/>Эффект Seraph Flight: обнуляет следующий статусный эффект, который может быть снят Purify<br/>Продолжительность: 20 сек.<br/>Эффект Excogitation: восстанавливает HP, когда оно падает ниже 50% или по истечении срока действия эффекта<br/>Сила лечения: 8,000<br/>Продолжительность: 20 сек.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
   };
   FILL_DB_VALUES(db);
   FILL_DB_SKILLS(db);
   FILL_DB_SKILLS_PASSIVE(db);
   FILL_DB_SKILLS_PVP(db);
   FILL_DB_SKILLS_MENU(db);
})();