(() =>{
   let db = {
      "PVE Update": `Последнее обновление: 27/06/2024`,
      "PVP Update": `Последнее обновление: 27/06/2024`,
      // PVE Skill 01
      "PVE Skill 01": {
         "name": 'Ruin',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1c74fa1688f3d89d6f5b972ce384df15f62e35d1.png',
         "job_icon": 'ACN',
         "level": '1',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 240.',
      },
      // PVE Skill 02
      "PVE Skill 02": {
         "name": 'Summon Carbuncle',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/14a64b174c103f36179809458245dc5e4f4fe0a6.png',
         "job_icon": 'ACN',
         "level": '2',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Призыв питомца Carbuncle, который будет сражаться на стороне персонажа.',
      },
      // PVE Skill 03
      "PVE Skill 03": {
         "name": 'Radiant Aegis',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a116b861109158ee5db8e36cf922fae8f923e7d5.png',
         "job_icon": 'ACN',
         "level": '2',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Приказывает Carbuncle использовать умение Radiant Aegis.<br/>Эффект Radiant Aegis: создает барьер вокруг персонажа, поглощающий урон в размере 20% от максимального HP<br/>Продолжительность: 30 сек.<br/>Максимум зарядов: 2<br/>Можно использовать только когда Carbuncle призван.',
      },
      // PVE Skill 04
      "PVE Skill 04": {
         "name": 'Physick',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e51f309947cde0c36f3a0cd815ca01e268928eb6.png',
         "job_icon": 'ACN',
         "level": '4',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Восстанавливает HP цели.<br/>Сила лечения: 400',
      },
      // PVE Skill 05
      "PVE Skill 05": {
         "name": 'Aethercharge',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ad9a8a02fa446a43dc54439c8ac1d04dad1384b2.png',
         "job_icon": 'ACN',
         "level": '6',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Накладывает Aethercharge, увеличивающий силу заклинаний Ruin, Ruin II и Ruin III на 50, а Outburst - на 20.<br/>Продолжительность: 15 сек.<br/>Дополнительный эффект: накладывает эффект Ruby Arcanum, Topaz Arcanum и Emerald Arcanum<br/>Можно использовать только в бою и когда Carbuncle призван.',
      },
      // PVE Skill 06
      "PVE Skill 06": {
         "name": 'Summon Ruby',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/23ce1df0ac3aa5df6aa4b22cdf2369ff364cabc0.png',
         "job_icon": 'ACN',
         "level": '6',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Призывает Ruby Carbuncle и приказывает ему использовать умение Glittering Ruby.<br/>Эффект Glittering Ruby: бросается на цель и наносит урон огнем с силой атаки 400<br/>Дополнительный эффект: накладывает 2 стака эффекта Fire Attunement<br/>Эффект Fire Attunement: умения Gemshine и Precious Brilliance получают свойства стихии огня<br/>Продолжительность: 30 сек.<br/>Может быть использовано только под действием эффекта Ruby Arcanum и когда Carbuncle призван.<br/>Текущий питомец покинет поле боя, пока призван Ruby Carbuncle, и вернется, как только закончится призыв.',
      },
      // PVE Skill 07
      "PVE Skill 07": {
         "name": 'Gemshine',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b1b0a655e18e0c446a0774ef264f010a8766db7f.png',
         "job_icon": 'ACN',
         "level": '6',
         "classification": 'Заклинание',
         "cast": '2.5 сек.',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Использует энергию текущей активной стихии для атаки противника.<br/>Эффект Fire Attunement: наносит урон огнем по одной цели<br/>Эффект Earth Attunement: наносит урон землей по одной цели<br/>Эффект Wind Attunement: наносит урон ветром по одной цели',
      },
      // PVE Skill 08
      "PVE Skill 08": {
         "name": 'Ruby Ruin',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1c74fa1688f3d89d6f5b972ce384df15f62e35d1.png',
         "job_icon": 'ACN',
         "level": '6',
         "classification": 'Заклинание',
         "cast": '2.8 сек.',
         "recast": '3 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон огнем с силой атаки 340.<br/>Стоимость: 1 Fire Attunement <br/>Это умение не имеет общего времени восстановления с другими умениями. После выполнения время повторного применения этого умения будет применено ко всем боевым навыкам и магическим умениям.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 09
      "PVE Skill 09": {
         "name": 'Fester',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b2df31cca5d00be7bba89943c76b799ae82aba8d.png',
         "job_icon": 'ACN',
         "level": '10',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 340.<br/>Стоимость: 1 Aetherflow Gauge',
      },
      // PVE Skill 10
      "PVE Skill 10": {
         "name": 'Energy Drain',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/92ea9227a8a09c62eb53852e2c26c0d6763a35c2.png',
         "job_icon": 'ACN',
         "level": '10',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 200.<br/>Дополнительный эффект: накладывается эффект Aetherflow II<br/>Дополнительный эффект: накладывается эффект Further Ruin<br/>Продолжительность: 60 сек.<br/>Имеет общее время восстановления с умением Energy Siphon.',
      },
      // PVE Skill 11
      "PVE Skill 11": {
         "name": 'Resurrection',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/9e61ea15caf1f7c0e4b44943dcbee0178e61a9fd.png',
         "job_icon": 'ACN',
         "level": '12',
         "classification": 'Заклинание',
         "cast": '8 сек.',
         "recast": '2.5 сек.',
         "cost": '2400 MP',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Воскрешает цель, накладывая эффект слабости (weakeness).',
      },
      // PVE Skill 12
      "PVE Skill 12": {
         "name": 'Summon Topaz',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/c6975b0e58d/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/45345cb4f108a07c372f8a355b26c13661d51887.png',
         "job_icon": 'ACN',
         "level": '15',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Призывает Topaz Carbuncle и приказывает ему использовать умение Glittering Topaz.<br/>Эффект Glittering Topaz: бросается на цель и наносит урон землей с силой атаки 400<br/>Дополнительный эффект: накладывает 4 стака эффекта Earth Attunement<br/>Эффект Earth Attunement: умения Gemshine and Precious Brilliance получают свойства стихии земли<br/>Продолжительность: 30 сек.<br/>Может быть использовано только под действием эффекта Topaz Arcanum и когда Carbuncle призван.<br/>Текущий питомец покинет поле боя, пока призван Topaz Carbuncle, и вернется, как только закончится призыв.',
      },
      // PVE Skill 13
      "PVE Skill 13": {
         "name": 'Topaz Ruin',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1c74fa1688f3d89d6f5b972ce384df15f62e35d1.png',
         "job_icon": 'ACN',
         "level": '15',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон землей с силой атаки 240.<br/>Стоимость: 1 Earth Attunement<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 14
      "PVE Skill 14": {
         "name": 'Summon Emerald',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d9d328ec1a7b30579dd56ad69fad33981e197f70.png',
         "job_icon": 'ACN',
         "level": '22',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Призывает Emerald Carbuncle и приказывает ему использовать умение Glittering Emerald.<br/>Эффект Glittering Topaz: бросается на цель и наносит урон ветром с силой атаки 400<br/>Дополнительный эффект: накладывает 4 стака эффекта Wind Attunement<br/>Эффект Wind Attunement: умения Gemshine and Precious Brilliance получают свойства стихии ветра<br/>Продолжительность: 30 сек.<br/>Может быть использовано только под действием эффекта Emerald Arcanum и когда Carbuncle призван.<br/>Текущий питомец покинет поле боя, пока призван Emerald Carbuncle, и вернется, как только закончится призыв.',
      },
      // PVE Skill 15
      "PVE Skill 15": {
         "name": 'Emerald Ruin',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1c74fa1688f3d89d6f5b972ce384df15f62e35d1.png',
         "job_icon": 'ACN',
         "level": '22',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон ветром с силой атаки 160.<br/>Стоимость: 1 Wind Attunement<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 16
      "PVE Skill 16": {
         "name": 'Outburst',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/aa5a6e6d676d222c70ac9c001132276cd401a140.png',
         "job_icon": 'ACN',
         "level": '26',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 100 по цели и всем ближайшим противникам.',
      },
      // PVE Skill 17
      "PVE Skill 17": {
         "name": 'Precious Brilliance',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1fa3119e51a423fedea3e3a238497548d0c64960.png',
         "job_icon": 'ACN',
         "level": '26',
         "classification": 'Заклинание',
         "cast": '2.5 сек.',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Использует текущей активной стихии для атаки нескольких противников.<br/>Эффект Fire Attunement: наносит урон огнем по цели и всем ближайшим противникам<br/>Эффект Earth Attunement: наносит урон землей по цели и всем ближайшим противникам<br/>Эффект Wind Attunement: наносит урон ветром по цели и всем ближайшим противникам',
      },
      // PVE Skill 18
      "PVE Skill 18": {
         "name": 'Ruby Outburst',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/aa5a6e6d676d222c70ac9c001132276cd401a140.png',
         "job_icon": 'ACN',
         "level": '26',
         "classification": 'Заклинание',
         "cast": '2.8 сек.',
         "recast": '3 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон огнем с силой атаки 160 по цели и всем ближайшим противникам.<br/>Стоимость: 1 Fire Attunement<br/>Это умение не имеет общего времени восстановления с другими умениями. После выполнения время повторного применения этого умения будет применено ко всем боевым навыкам и магическим умениям.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 19
      "PVE Skill 19": {
         "name": 'Topaz Outburst',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/aa5a6e6d676d222c70ac9c001132276cd401a140.png',
         "job_icon": 'ACN',
         "level": '26',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'дар, наносящий урон землей с силой атаки 110 по цели и всем ближайшим противникам.<br/>Стоимость: 1 Earth Attunement<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 20
      "PVE Skill 20": {
         "name": 'Emerald Outburst',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/aa5a6e6d676d222c70ac9c001132276cd401a140.png',
         "job_icon": 'ACN',
         "level": '26',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон ветром с силой атаки 70 по цели и всем ближайшим противникам.<br/>Стоимость: 1 Wind Attunement<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 21
      "PVE Skill 21": {
         "name": 'Ruin II',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/45ea45aff3a/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d6875ae1008a9e4b2d04562cff42646752e919c5.png',
         "job_icon": 'ACN',
         "level": '30',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 270.',
      },
      // PVE Skill 22
      "PVE Skill 22": {
         "name": 'Summon Ifrit',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/4bb5af1e8a9/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5e826d0c09e4894638df5676fc15863cce8d5182.png',
         "job_icon": 'SMN',
         "level": '30',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Призывает Ifrit-Egi и приказывает ему использовать умение Inferno.<br/>Эффект Inferno: бросается вперед и наносит урон огнем всем противникам в конусе 5 ялмов перед существом с силой атаки 600 для первого и на 60% меньше для всех остальных<br/>Дополнительный эффект: накладывает 2 стака Fire Attunement<br/>Эффект Fire Attunement: Gemshine и Precious Brilliance  получают свойства стихии огня<br/>Продолжительность: 30 сек.<br/>Дополнительный эффект: накладывает Ifrit's Favor<br/>Эффект Ifrit's Favor заканчивается при использовании определенных умений призывателя.<br/>Может быть использовано только под действием эффекта Ruby Arcanum и когда Carbuncle призван.<br/>Текущий питомец покинет поле боя, пока призван Ifrit-Egi, и вернется, как только закончится призыв.",
      },
      // PVE Skill 23
      "PVE Skill 23": {
         "name": 'Ruby Ruin II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d6875ae1008a9e4b2d04562cff42646752e919c5.png',
         "job_icon": 'ACN',
         "level": '30',
         "classification": 'Заклинание',
         "cast": '2.8 сек.',
         "recast": '3 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон огнем с силой атаки 380.<br/>Стоимость: 1 Fire Attunement<br/>Это умение не имеет общего времени восстановления с другими умениями. После использования время повторного применения этого умения будет применено ко всем боевым навыкам и магическим умениям.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 24
      "PVE Skill 24": {
         "name": 'Topaz Ruin II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d6875ae1008a9e4b2d04562cff42646752e919c5.png',
         "job_icon": 'ACN',
         "level": '30',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон землей с силой атаки 270.<br/>Стоимость: 1 Earth Attunement<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 25
      "PVE Skill 25": {
         "name": 'Emerald Ruin II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d6875ae1008a9e4b2d04562cff42646752e919c5.png',
         "job_icon": 'ACN',
         "level": '30',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон ветром с силой атаки 170.<br/>Стоимость: 1 Wind Attunement <br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 26
      "PVE Skill 26": {
         "name": 'Summon Titan',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/46cfc4f4ead/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/0e63c4fe037c46bb8fcb3b1402319d0cf1084711.png',
         "job_icon": 'SMN',
         "level": '35',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Призывает Titan-Egi и приказывает ему использовать умение Earthen Fury.<br/>Эффект Earthen Fury: бросается вперед и наносит урон землем всем противникам в радусе 5 ялмов с силой атаки 600 для первого и на 60% меньше для всех остальных<br/>Дополнительный эффект: накладывает 2 стака Earth Attunement<br/>Эффект Earth Attunement: Gemshine и Precious Brilliance  получают свойства стихии земли<br/>Продолжительность: 30 сек.<br/>Может быть использовано только под действием эффекта Topaz Arcanum и когда Carbuncle призван.<br/>Текущий питомец покинет поле боя, пока призван Titan-Egi, и вернется, как только закончится призыв.',
      },
      // PVE Skill 27
      "PVE Skill 27": {
         "name": 'Painflare',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/722e85adea5/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/0d06f6fcf4a18fc6dcf2e084098a5acecf958f28.png',
         "job_icon": 'SMN',
         "level": '40',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 150 по цели и всем ближайшим противникам.<br/>Стоимость: 1 Aetherflow Gauge',
      },
      // PVE Skill 28
      "PVE Skill 28": {
         "name": 'Summon Garuda',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/20d0b7fc492/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f0d45cc564da364190b10ea26b9978147b3813fd.png',
         "job_icon": 'SMN',
         "level": '45',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Призывает Garuda-Egi  и приказывает ему использовать умение Aerial Blast.<br/>Эффект Aerial Blast: наносит урон ветром по цели и всем противникам в радиусе 5 ялмов с силой атаки 600 для первого и на 60% меньше для всех остальных<br/>Дополнительный эффект: накладывает 4 стака Wind Attunement<br/>Эффект Wind Attunement: Gemshine и Precious Brilliance получают свойства стихии ветра<br/>Продолжительность: 30 сек.<br/>Дополнительный эффект: накладывает эффект Garuda's Favor<br/>Эффект Garuda's Favor заканчивается при использовании определенных умений призывателя.<br/>Может быть использовано только под действием эффекта Emerald Arcanum и когда Carbuncle призван.<br/>Текущий питомец покинет поле боя, пока призван Garuda-Egi, и вернется, как только закончится призыв.",
      },
      // PVE Skill 29
      "PVE Skill 29": {
         "name": 'Energy Siphon',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/7beee5ac856/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/9a6ba0bc2e8f682c23f8c2d9241a2ed4bf6a637c.png',
         "job_icon": 'SMN',
         "level": '52',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 100 по цели и всем ближайшим противникам.<br/>Дополнительный эффект: накладывается эффект Aetherflow II<br/>Additional Effect: накладывается эффект Further Ruin<br/>Продолжительность: 60 сек.<br/>Имеет общее время восстановления с умением Energy Drain.',
      },
      // PVE Skill 30
      "PVE Skill 30": {
         "name": 'Ruin III',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/c2839ee8c3d/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5d2d65267abd378e60f7f9e832ee92be084ff6d7.png',
         "job_icon": 'SMN',
         "level": '54',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 360.',
      },
      // PVE Skill 31
      "PVE Skill 31": {
         "name": 'Ruby Ruin III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5d2d65267abd378e60f7f9e832ee92be084ff6d7.png',
         "job_icon": 'SMN',
         "level": '54',
         "classification": 'Заклинание',
         "cast": '2.8 сек.',
         "recast": '3 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон огнем с силой атаки 410<br/>Стоимость: 1 Fire Attunement<br/>Это умение не имеет общего времени восстановления с другими умениями. После выполнения время повторного применения этого умения будет применено ко всем боевым навыкам и магическим умениям.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 32
      "PVE Skill 32": {
         "name": 'Topaz Ruin III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5d2d65267abd378e60f7f9e832ee92be084ff6d7.png',
         "job_icon": 'SMN',
         "level": '54',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон землей с силой атаки 300.<br/>Стоимость: 1 Earth Attunement<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 33
      "PVE Skill 33": {
         "name": 'Emerald Ruin III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5d2d65267abd378e60f7f9e832ee92be084ff6d7.png',
         "job_icon": 'SMN',
         "level": '54',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон ветром с силой атаки 180.<br/>Стоимость: 1 Wind Attunement <br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 34
      "PVE Skill 34": {
         "name": 'Dreadwyrm Trance',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/565ec60b81e/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/629a0b7a52fe0aad68cf3d0a7a0d40ab0d9c45bf.png',
         "job_icon": 'SMN',
         "level": '58',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Персонаж входит в Dreadwyrm Trance.<br/>Продолжительность: 15 сек.<br/>Дополнительный эффект: изменяет Ruin III на Astral Impulse и Outburst на Astral Flare<br/>Дополнительный эффект: дает Ruby Arcanum, Topaz Arcanum и Emerald Arcanum<br/>Можно использовать только в бою и когда Carbuncle призван.<br/>Это умение не имеет общего времени восстановления с другими умениями. ',
      },
      // PVE Skill 35
      "PVE Skill 35": {
         "name": 'Astral Impulse',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2ba7ab41cd2f8dac96ba0c89426eebff963d6be0.png',
         "job_icon": 'SMN',
         "level": '58',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 500.<br/>Может быть использовано только под действием эффекта Dreadwyrm Trance.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Ruin III меняется на Astral Impulse при соблюдении требований к выполнению.',
      },
      // PVE Skill 36
      "PVE Skill 36": {
         "name": 'Astral Flare',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/41380367e3ff56dfc723ac049dbcacd00ac5c6f8.png',
         "job_icon": 'SMN',
         "level": '58',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 180 по цели и всем ближайшим противникам.<br/>Может быть использовано только под действием эффекта Dreadwyrm Trance.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Tri-disaster меняется на Astral Flare при соблюдении требований к выполнению.',
      },
      // PVE Skill 37
      "PVE Skill 37": {
         "name": 'Astral Flow',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/fad79bc76d6/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/3fd44c9091d6888f7b3b3ee449d3f71d94d9b05a.png',
         "job_icon": 'SMN',
         "level": '60',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Направьте энергию активного транса или элементальной благосклонности на выполнение одного из нескольких умений.<br/>Эффект Dreadwyrm Trance: умение меняется на Deathflare<br/>Эффект Lightwyrm Trance : умение меняется на Sunflare<br/>Эффект Firebird Trance: умение меняется на Rekindle<br/>Эффект Ifrit's Favor: умение меняется на Crimson Cyclone<br/>Эффект Titan's Favor: умение меняется на Mountain Buster<br/>Эффект Garuda's Favor: умение меняется на Slipstream",
      },
      // PVE Skill 38
      "PVE Skill 38": {
         "name": 'Deathflare',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/710d60dfcdf5a59cb192084786c7c37bff62fb99.png',
         "job_icon": 'SMN',
         "level": '60',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон по цели и всем ближайшим противникам с силой атаки 500 для первого и на 60% меньше для всех остальных.<br/>Может быть использовано только под действием эффекта Dreadwyrm Trance.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Astral Flow меняется на Deathflare при соблюдении требований к выполнению.',
      },
      // PVE Skill 39
      "PVE Skill 39": {
         "name": 'Ruin IV',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/84226db4cce94d2c2c686af2c6fca01dfc6a63f9.png',
         "job_icon": 'SMN',
         "level": '62',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон по цели и всем ближайшим противникам с силой атаки 490 для первого и на 60% меньше для всех остальных.<br/>Может быть использовано только под действием эффекта Further Ruin.',
      },
      // PVE Skill 40
      "PVE Skill 40": {
         "name": 'Searing Light',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/6c4b1ae3c69201feb415963f374cd3449a4ad7db.png',
         "job_icon": 'SMN',
         "level": '66',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '30y',
         "content": "Увеличивает наносимый урон персонажем и ближайшими сопартийцами на 5%.<br/>Длительность: 20 сек.<br/>Дополнительный эффект: накладывает эффект Ruby's Glimmer<br/>Длительность: 30 сек.",
      },
      // PVE Skill 41
      "PVE Skill 41": {
         "name": 'Summon Bahamut',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/a1074a175f6/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2e961ffd2e67115c99ad1b4863fc29d5064c4fe9.png',
         "job_icon": 'SMN',
         "level": '70',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Персонаж входит в Dreadwyrm Trance и вызывает Demi-Bahamut.<br/>После вызова Demi-Bahamut автоматически использует Wyrmwave к целям, которые атакует персонаж.<br/>Увеличивает уровень угрозы персонажа при вызове Demi-Bahamut.<br/>Продолжительность: 15 сек.<br/>Дополнительный эффект: изменяет Ruin III на Astral Impulse и Tri-disaster на Astral Flare<br/>Дополнительный эффект: дает Ruby Arcanum, Topaz Arcanum, and Emerald Arcanum<br/>Можно использовать только в бою и когда Carbuncle призван.<br/>Это умение не имеет общего времени восстановления с другими умениями.',
      },
      // PVE Skill 42
      "PVE Skill 42": {
         "name": 'Wyrmwave',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d2234447db9cad86e7f87d6af71b7088e5fee400.png',
         "job_icon": 'SMN',
         "level": '70',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "cost": '-',
         "range": '50y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 150.<br/>Можно использовать только во время призыва Demi-Bahamut.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 43
      "PVE Skill 43": {
         "name": 'Enkindle Bahamut',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/cbf72c7579e45d4a64a7232be3fa7d38a34b703f.png',
         "job_icon": 'SMN',
         "level": '70',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'риказывает Demi-Bahamut использовать Akh Morn.<br/>Эффект Akh Morn: удар, наносящий нестихийный урон по цели и всем ближайшим противникам с силой атаки 1,300 для первого и на 60% меньше для всех остальных.',
      },
      // PVE Skill 44
      "PVE Skill 44": {
         "name": 'Akh Morn',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/bdea704b3466837dbf634ca8fa4b21e80cddf833.png',
         "job_icon": 'SMN',
         "level": '70',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '-',
         "cost": '-',
         "range": '50y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон по цели и всем ближайшим противникам с силой атаки 1,300 для первого и на 60% меньше для всех остальных.<br/>Можно использовать только во время призыва Demi-Bahamut.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 45
      "PVE Skill 45": {
         "name": 'Ruby Rite',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/3c739e3604ba2d045b691a46c0dbef1a658951f3.png',
         "job_icon": 'SMN',
         "level": '72',
         "classification": 'Заклинание',
         "cast": '2.8 сек.',
         "recast": '3 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон огнем с силой атаки 540.<br/>Стоимость: 1 Fire Attunement<br/>Это умение не имеет общего времени восстановления с другими умениями.<br/>После выполнения время повторного применения этого умения будет применено ко всем боевым навыкам и магическим умениям.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Gemshine меняется на Ruby Rite при соблюдении требований к выполнению.',
      },
      // PVE Skill 46
      "PVE Skill 46": {
         "name": 'Topaz Rite',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4c4900529cf628e2f3fda4134c996741f8b465c3.png',
         "job_icon": 'SMN',
         "level": '72',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Удар, наносящий урон землей с силой атаки 340.<br/>Дополнительный эффект: накладывает эффект Titan's Favor<br/>Эффект Titan's Favor заканчивается при использовании определенных умений призывателя.<br/>Стоимость: 1 Earth Attunement<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Gemshine меняется на Topaz Rite при соблюдении требований к выполнению.",
      },
      // PVE Skill 47
      "PVE Skill 47": {
         "name": 'Emerald Rite',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/87c16672ddea00204d4c0489b5417166cdb2546a.png',
         "job_icon": 'SMN',
         "level": '72',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон ветром с силой атаки 240.<br/>Стоимость: 1 Wind Attunement<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Gemshine меняется на Emerald Rite при соблюдении требований к выполнению.',
      },
      // PVE Skill 48
      "PVE Skill 48": {
         "name": 'Tri-disaster',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/20e1e40922c159401231154ab0cc94c789b1f58f.png',
         "job_icon": 'SMN',
         "level": '74',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 120 по цели и всем ближайшим противникам.',
      },
      // PVE Skill 49
      "PVE Skill 49": {
         "name": 'Ruby Disaster',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/20e1e40922c159401231154ab0cc94c789b1f58f.png',
         "job_icon": 'SMN',
         "level": '74',
         "classification": 'Заклинание',
         "cast": '2.8 сек.',
         "recast": '3 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон огнем с силой атаки 190 по цели и всем ближайшим противникам.<br/>Стоимость: 1 Fire Attunement<br/>Это умение не имеет общего времени восстановления с другими умениями. После выполнения время повторного применения этого умения будет применено ко всем боевым навыкам и магическим умениям.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 50
      "PVE Skill 50": {
         "name": 'Topaz Disaster',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/20e1e40922c159401231154ab0cc94c789b1f58f.png',
         "job_icon": 'SMN',
         "level": '74',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон землей с силой атаки 130 по цели и всем ближайшим противникам.<br/>Стоимость: 1 Earth Attunement<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 51
      "PVE Skill 51": {
         "name": 'Emerald Disaster',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/20e1e40922c159401231154ab0cc94c789b1f58f.png',
         "job_icon": 'SMN',
         "level": '74',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон ветром с силой атаки 90 по цели и всем ближайшим противникам.<br/>Стоимость: 1 Wind Attunement <br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 52
      "PVE Skill 52": {
         "name": 'Summon Phoenix',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e38e769e9f268f4dcc345b25d310cd53d10d4795.png',
         "job_icon": 'SMN',
         "level": '80',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Персонаж входит в Firebird Trance и вызывает Demi-Phoenix, который в момент своего появления использует Everlasting Flight.<br/>После вызова Demi-Phoenix автоматически использует Scarlet Flame к целям, которые атакует персонаж.<br/>Увеличивает уровень угрозы персонажа при вызове Demi-Phoenix.<br/>Продолжительность: 15 сек.<br/>Дополнительный эффект: изменяет Ruin III на Fountain of Fire и Tri-disaster на Brand of Purgatory<br/>Дополнительный эффект: дает Ruby Arcanum, Topaz Arcanum и Emerald Arcanum<br/>Можно использовать только в бою и когда Carbuncle призван.<br/>Это умение не имеет общего времени восстановления с другими умениями.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Summon Bahamut меняется на Summon Phoenix при соблюдении требований к выполнению.',
      },
      // PVE Skill 53
      "PVE Skill 53": {
         "name": 'Fountain of Fire',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1b50beab981774f701d16ac61674bfc01747f38b.png',
         "job_icon": 'SMN',
         "level": '80',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон огнем с силой атаки 580.<br/>Может быть использовано только под действием эффекта Firebird Trance.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Ruin III меняется на Fountain of Fire при соблюдении требований к выполнению.',
      },
      // PVE Skill 54
      "PVE Skill 54": {
         "name": 'Brand of Purgatory',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/daebb0133d31dbdcc989ecf9fd04ef3acf040cba.png',
         "job_icon": 'SMN',
         "level": '80',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '8y',
         "content": 'Удар, наносящий урон огнем с силой атаки 240 по цели и всем ближайшим противникам.<br/>Может быть использовано только под действием эффекта Firebird Trance.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Tri-disaster меняется на Brand of Purgatory при соблюдении требований к выполнению.',
      },
      // PVE Skill 55
      "PVE Skill 55": {
         "name": 'Rekindle',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/6b2befa4d39ad77fa8992d934bd796e836eed13f.png',
         "job_icon": 'SMN',
         "level": '80',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "cost": '-',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Восстанавливает HP персонажа или выбранному сопартийцу.<br/>Сила лечения: 400<br/>Дополнительный эффект: накладывает на цель Rekindle<br/>Продолжительность: 30 сек.<br/>Эффект Rekindle: периодическое лечение, когда HP падает ниже 75% или по истечении срока действия эффекта<br/>Сила лечения: 200<br/>Продолжительность: 15 сек.<br/>Может быть использовано только под действием эффекта Firebird Trance.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Astral Flow меняется на Rekindle при соблюдении требований к выполнению.',
      },
      // PVE Skill 56
      "PVE Skill 56": {
         "name": 'Enkindle Phoenix',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/596917791c140eef84754e4488df04bfb7aabf87.png',
         "job_icon": 'SMN',
         "level": '80',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Приказывает Demi-Phoenix использовать Revelation.<br/>Эффект Revelation: удар, наносящий урон огнем по цели и всем ближайшим противникам с силой атаки 1 300 для первого и на 60% меньше для всех остальных<br/>Умение заменяет Enkindle Bahamut, пока призван Demi-Phoenix.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Enkindle Bahamut меняется на Enkindle Phoenix при соблюдении требований к выполнению.',
      },
      // PVE Skill 57
      "PVE Skill 57": {
         "name": 'Everlasting Flight',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/47555a1b908cba86b377560667afa40e8471b69a.png',
         "job_icon": 'SMN',
         "level": '80',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '-',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '15y',
         "content": 'Постепенно восстанавливает HP персонажа и всех ближайших сопартийцев.<br/>Сила лечения: 100<br/>Продолжительность: 21 сек.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 58
      "PVE Skill 58": {
         "name": 'Scarlet Flame',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/865ff61841e27dc0ede5742b0109c45b672c2ef2.png',
         "job_icon": 'SMN',
         "level": '80',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "cost": '-',
         "range": '50y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон огнем с силой атаки 150.<br/>Можно использовать только во время призыва Demi-Phoenix.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 59
      "PVE Skill 59": {
         "name": 'Revelation',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/9358e80cfda84c41bef60f05c6f66218842a6f74.png',
         "job_icon": 'SMN',
         "level": '80',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '-',
         "cost": '-',
         "range": '50y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон огнем по цели и всем ближайшим противникам с силой атаки 1,300 для первого и на 60% меньше для всех остальных.<br/>Можно использовать только во время призыва Demi-Phoenix.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 60
      "PVE Skill 60": {
         "name": 'Ruby Catastrophe',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/aff103d032034722b3a4063ad749eb2bb85793aa.png',
         "job_icon": 'SMN',
         "level": '82',
         "classification": 'Заклинание',
         "cast": '2.8 сек.',
         "recast": '3 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон огнем с силой атаки 210 по цели и всем ближайшим противникам.<br/>Стоимость: 1 Fire Attunement<br/>Это умение не имеет общего времени восстановления с другими умениями.<br/>После выполнения время повторного применения этого умения будет применено ко всем боевым навыкам и магическим умениям.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Precious Brilliance меняется на Ruby Catastrophe при соблюдении требований к выполнению.',
      },
      // PVE Skill 61
      "PVE Skill 61": {
         "name": 'Topaz Catastrophe',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/8f6bc648e6b39fcdfdb5d747cc28ea98dd65b441.png',
         "job_icon": 'SMN',
         "level": '82',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": "Удар, наносящий урон землей с силой атаки 140 по цели и всем ближайшим противникам.<br/>Стоимость: 1 Earth Attunement<br/>Дополнительный эффект: накладывает эффект Titan's Favor<br/>Эффект Titan's Favor заканчивается при использовании определенных умений призывателя.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Precious Brilliance меняется на Topaz Catastrophe при соблюдении требований к выполнению",
      },
      // PVE Skill 62
      "PVE Skill 62": {
         "name": 'Emerald Catastrophe',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/876d6589f594c3f74d7d2834d297f18da7809199.png',
         "job_icon": 'SMN',
         "level": '82',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон ветром с силой атаки 100 по цели и всем ближайшим противникам.<br/>Стоимость: 1 Wind Attunement<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Precious Brilliance меняется на Emerald Catastrophe при соблюдении требований к выполнению.',
      },
      // PVE Skill 63
      "PVE Skill 63": {
         "name": 'Crimson Cyclone',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7ec3b0243e57959d38e7bcbfaaab4fe0bbf8972b.png',
         "job_icon": 'SMN',
         "level": '86',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": "Рывок вперед и удар, наносящий урон огнем по цели и всем ближайшим противникам с силой атаки 490 для первого и на 65% меньше для всех остальных.<br/>Может быть использовано только под действием эффекта Ifrit's Favor.<br/>Невозможно использовать, если персонаж находится под эффектами ограничивающими перемещение.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Astral Flow меняется на Crimson Cyclone при соблюдении требований к выполнению.",
      },
      // PVE Skill 64
      "PVE Skill 64": {
         "name": 'Crimson Strike',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a63bb4e29d20c938e1b68ea0dc0ab64c3a8a9fdf.png',
         "job_icon": 'SMN',
         "level": '86',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '3y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон огнем по цели и всем ближайшим противникам с силой атаки 490 для первого и на 65% меньше для всех остальных.<br/>Комбо умение: Crimson Cyclone<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Crimson Cyclone меняется на Crimson Strike при соблюдении требований к выполнению.',
      },
      // PVE Skill 65
      "PVE Skill 65": {
         "name": 'Mountain Buster',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/735d3aabed75539866193ca97b356367f818821f.png',
         "job_icon": 'SMN',
         "level": '86',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": "Удар, наносящий урон огнем по цели и всем ближайшим противникам с силой атаки 160 для первого и на 70% меньше для всех остальных.<br/>Может быть использовано только под действием эффекта Titan's Favor.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Astral Flow меняется на Mountain Buster при соблюдении требований к выполнению.",
      },
      // PVE Skill 66
      "PVE Skill 66": {
         "name": 'Slipstream',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/6a54b05a1f6bd144d28149045f1f9cc61f86daf3.png',
         "job_icon": 'SMN',
         "level": '86',
         "classification": 'Заклинание',
         "cast": '3 сек.',
         "recast": '3.5 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": "Удар, наносящий урон ветром по цели и всем ближайшим противникам с силой атаки 490 для первого и на 65% меньше для всех остальных.<br/>Дополнительный эффект: создает ураган вокруг цели, наносящий урон всем противникам, попавшим в него<br/>Сила атаки: 30<br/>Продолжительность: 15 сек.<br/>Может быть использовано только под действием эффекта Garuda's Favor.<br/>Это умение не имеет общего времени восстановления с другими умениями.<br/>После выполнения время повторного применения этого умения будет применено ко всем боевым навыкам и магическим умениям.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Astral Flow меняется на Slipstream при соблюдении требований к выполнению.",
      },
      // PVE Skill 67
      "PVE Skill 67": {
         "name": 'Summon Ifrit II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e49b3a55b75a637cb0e6e794d588b2ba4886c742.png',
         "job_icon": 'SMN',
         "level": '90',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Призывает Ruby Ifrit и приказывает ему использовать умение Inferno.<br/>Эффект Inferno: бросается вперед и наносит урон огнем по цели и всем противникам в радиусе 5 ялмов с силой атаки 800 для первого и на 60% меньше для всех остальных<br/>Дополнительный эффект: накладывает 2 стака Fire Attunement<br/>Эффект Fire Attunement: Gemshine и Precious Brilliance  получают свойства стихии огня<br/>Продолжительность: 30 сек.<br/>Дополнительный эффект: накладывает Ifrit's Favor<br/>Эффект Ifrit's Favor заканчивается при использовании определенных умений призывателя.<br/>Может быть использовано только под действием эффекта Ruby Arcanum и когда Carbuncle призван.<br/>Текущий питомец покинет поле боя, пока призван Ruby Ifrit и вернется, как только закончится призыв.",
      },
      // PVE Skill 68
      "PVE Skill 68": {
         "name": 'Summon Titan II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d5e3edcb915673621b1ccb51774abf494eba6b5e.png',
         "job_icon": 'SMN',
         "level": '90',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Призывает Topaz Titan и приказывает ему использовать умение Earthen Fury.<br/>Эффект Inferno: бросается вперед и наносит урон землей по цели и всем противникам в радиусе 5 ялмов с силой атаки 800 для первого и на 60% меньше для всех остальных<br/>Дополнительный эффект: накладывает 4 стака Earth Attunement<br/>Эффект Earth Attunement: Gemshine и Precious Brilliance  получают свойства стихии земли<br/>Продолжительность: 30 сек.<br/>Может быть использовано только под действием эффекта Topaz Arcanum и когда Carbuncle призван.<br/>Текущий питомец покинет поле боя, пока призван Topaz Titan, и вернется, как только закончится призыв.',
      },
      // PVE Skill 69
      "PVE Skill 69": {
         "name": 'Summon Garuda II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f25f4c81570c889872295e4ba99496ee6bf3fc89.png',
         "job_icon": 'SMN',
         "level": '90',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Призывает Emerald Garuda и приказывает ему использовать умение Aerial Blast.<br/>Эффект Aerial Blast: наносит урон ветром по цели и всем противникам в радиусе 5 ялмов с силой атаки 800 для первого и на 60% меньше для всех остальных<br/>Дополнительный эффект: накладывает 4 стака Wind Attunement<br/>Эффект Wind Attunement: Gemshine и Precious Brilliance получают свойства стихии ветра<br/>Продолжительность: 30 сек.<br/>Дополнительный эффект: накладывает эффект Garuda's Favor<br/>Эффект Garuda's Favor заканчивается при использовании определенных умений призывателя.<br/>Может быть использовано только под действием эффекта Emerald Arcanum и когда Carbuncle призван.<br/>Текущий питомец покинет поле боя, пока призван Emerald Garuda, и вернется, как только закончится призыв.",
      },
      // PVE Skill 70 NEW
      "PVE Skill 70": {
         "name": 'Necrotize',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f224b169e6f0f4b35b361e5c6666293e09a1f0ac.png',
         "job_icon": 'SMN',
         "level": '92',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 420.<br/>Стоимость: 1 Aetherflow Gauge',
      },
      // PVE Skill 71 NEW
      "PVE Skill 71": {
         "name": 'Searing Flash',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b1edfc3a4d1b47e1df840e26e0969529070fed58.png',
         "job_icon": 'SMN',
         "level": '96',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": "Удар, наносящий нестихийный урон с силой атаки 600 по цели и всем ближайшим противникам.<br/>Может быть использовано только под действием эффекта Ruby's Glimmer.",
      },
      // PVE Skill 72 NEW
      "PVE Skill 72": {
         "name": 'Lux Solaris',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/38e51b1e903bd0b7bc685ec95c2ac105779bbc8c.png',
         "job_icon": 'SMN',
         "level": '100',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '15y',
         "content": 'Восстанавливает HP персонажа и всех ближайших сопартийцев.<br/>Сила лечения: 500<br/>Может быть использовано только под действием эффекта Refulgent Lux.',
      },
      // PVE Skill 73 NEW
      "PVE Skill 73": {
         "name": 'Summon Solar Bahamut',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/8b65e3df95387470664286d1e2a0f71dd29b8f77.png',
         "job_icon": 'SMN',
         "level": '100',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Персонаж входит в Lightwyrm Trance и вызывает Solar Bahamut.<br/>После вызова Solar Bahamut автоматически использует Luxwave к целям, которые атакует персонаж.<br/>Увеличивает уровень угрозы персонажа при вызове Solar Bahamut.<br/>Продолжительность: 15 сек.<br/>Дополнительный эффект: накладывает эффект Refulgent Lux<br/>Продолжительность: 30 сек.<br/>Дополнительный эффект: изменяет Ruin III на Umbral Impulse и Tri-disaster на Umbral Flare<br/>Дополнительный эффект: дает Ruby Arcanum, Topaz Arcanum, and Emerald Arcanum<br/>Можно использовать только в бою и когда Carbuncle призван.<br/>Это умение не имеет общего времени восстановления с другими умениями.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Summon Bahamut меняется на Summon Solar Bahamut при соблюдении требований к выполнению.',
      },
      // PVE Skill 74 NEW
      "PVE Skill 74": {
         "name": 'Umbral Impulse',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/097755a6dc321ca146451fbb0e5c42dca4d9dd02.png',
         "job_icon": 'SMN',
         "level": '100',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон огнем с силой атаки 600.<br/>Может быть использовано только под действием эффекта Lightwyrm Trance.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Ruin III меняется на Umbral Impulse при соблюдении требований к выполнению.',
      },
      // PVE Skill 75 NEW
      "PVE Skill 75": {
         "name": 'Umbral Flare',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e20b0b341a670598c6af9548925d4da35c2e4365.png',
         "job_icon": 'SMN',
         "level": '100',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '8y',
         "content": 'Удар, наносящий урон огнем с силой атаки 280 по цели и всем ближайшим противникам.<br/>Может быть использовано только под действием эффекта Lightwyrm Trance.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Tri-disaster меняется на Umbral Flare при соблюдении требований к выполнению.',
      },
      // PVE Skill 76 NEW
      "PVE Skill 76": {
         "name": 'Sunflare',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ea98821592c274277d2472f4eb33e014c66a751f.png',
         "job_icon": 'SMN',
         "level": '100',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон по цели и всем ближайшим противникам с силой атаки 600 для первого и на 60% меньше для всех остальных.<br/>Может быть использовано только под действием эффекта Lightwyrm Trance.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Astral Flow меняется на Sunflare при соблюдении требований к выполнению.',
      },
      // PVE Skill 77 NEW
      "PVE Skill 77": {
         "name": 'Enkindle Solar Bahamut',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4deaaa9815c4b1bd5fc52e76019d9192342568b9.png',
         "job_icon": 'SMN',
         "level": '100',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Приказывает Solar Bahamut использовать Exodus.<br/>Эффект Exodus: удар, наносящий нестихийный урон по цели и всем ближайшим противникам с силой атаки 1,400 для первого и на 60% меньше для всех остальных<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Enkindle Bahamut меняется на Enkindle Solar Bahamut при соблюдении требований к выполнению.',
      },
      // PVE Skill 78 NEW
      "PVE Skill 78": {
         "name": 'Luxwave',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7ea77f0af91e55be0b619e4dc72e20c5ba56f516.png',
         "job_icon": 'SMN',
         "level": '100',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '1.5 сек.',
         "cost": '-',
         "range": '50y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 160.<br/>Можно использовать только во время призыва Solar Bahamut.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVE Skill 79 NEW
      "PVE Skill 79": {
         "name": 'Exodus',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/97f91c1009d19698ee6e2e3272b974a4c0dd62ff.png',
         "job_icon": 'SMN',
         "level": '100',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '-',
         "cost": '-',
         "range": '50y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон по цели и всем ближайшим противникам с силой атаки 1,400 для первого и на 60% меньше для всех остальных.<br/>Можно использовать только во время призыва Solar Bahamut.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // Pet Action
      "Pet Action": {
         "name": 'Radiant Aegis',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/926e42e9a30e357e4214c95427cd1dd1592974c5.png',
         "job_icon": 'ACN',
         "level": '2',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '-',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Создает барьер вокруг персонажа, поглощающий урон в размере 20% от максимального HP.<br/>Продолжительность: 30 сек.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // Pet Actions (Commands)
      "Away": 'Приказ питомцу покинуть поле боя.',
      "Heel": 'Приказ питомцу следовать за персонажем.',
      "Place": 'Приказ питомцу переместиться в указанную область.',
      "Stay": 'Приказ питомцу находиться на месте.',
      "Guard": 'Приказ питомцу не атаковать, пока ваш персонаж не атакует.<',
      "Steady": 'Приказ питомцу не атаковать до тех пор, пока вы напрямую ему не прикажете.',
      // Trait 01
      "Trait 01": {
         "name": 'Enhanced Aethercharge',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/c6975b0e58d/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/0d5f1b0f41d84fb376bb973d3d453f1ed48a9ca2.png',
         "job_icon": 'ACN',
         "level": '15',
         "content": 'Накладывает эффекты Ruby Arcanum и Topaz Arcanum при использовании Aethercharge.',
      },
      // Trait 02
      "Trait 02": {
         "name": 'Maim and Mend',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/688b9e979396925fa8a996968547e39f057ff539.png',
         "job_icon": 'ACN',
         "level": '20',
         "content": 'Увеличивает базовый урон от умений и восстановление HP на 10%. Также увеличивает базовый урон и восстановление HP питомца на 10%.',
      },
      // Trait 03
      "Trait 03": {
         "name": 'Enhanced Aethercharge II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/df55a50ece90bf55a6df3e1029d3c6ee481527fb.png',
         "job_icon": 'ACN',
         "level": '22',
         "content": 'Накладывает эффект Ruby Arcanum, Topaz Arcanum и Emerald Arcanum после использования Aethercharge.',
      },
      // Trait 04
      "Trait 04": {
         "name": 'Ruin Mastery',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/45ea45aff3a/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c168e6c62a3af11ff0e563c27ebe4ce647be6fd3.png',
         "job_icon": 'ACN',
         "level": '30',
         "content": 'Улучшает умение Ruin до Ruin II.',
      },
      // Trait 05
      "Trait 05": {
         "name": 'Ruby Summoning Mastery',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/4bb5af1e8a9/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ab4d285d509b54780c84520c65ce899550edb7ba.png',
         "job_icon": 'SMN',
         "level": '30',
         "content": 'Улучшает Summon Ruby до Summon Ifrit.',
      },
      // Trait 06
      "Trait 06": {
         "name": 'Topaz Summoning Mastery',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/46cfc4f4ead/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5352a72c327a0d3f663cf4dd75dfec7cc6dbd8bc.png',
         "job_icon": 'SMN',
         "level": '35',
         "content": 'Улучшает Summon Topaz до Summon Titan.',
      },
      // Trait 07
      "Trait 07": {
         "name": 'Maim and Mend II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f0493aff0cf655167be05890774732eebed2b598.png',
         "job_icon": 'ACN',
         "level": '40',
         "content": 'Увеличивает базовый урон от умений и восстановление HP на 30%. Также увеличивает базовый урон и восстановление HP питомца на 30%.',
      },
      // Trait 08
      "Trait 08": {
         "name": 'Emerald Summoning Mastery',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/20d0b7fc492/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f4f08c3219769e18eb45db731619e58bff42c137.png',
         "job_icon": 'SMN',
         "level": '45',
         "content": 'Улучшает Summon Emerald до Summon Garuda.',
      },
      // Trait 09
      "Trait 09": {
         "name": 'Enkindle',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/7fcd8e13916/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e9c0aec5b67359dfa8fcd1b5cdd72000d94705b6.png',
         "job_icon": 'SMN',
         "level": '50',
         "content": "Усиливает основную атаку призываемых существ, улучшая Ifrit-Egi's Burning Strike до Inferno, Titan-Egi's Rock Buster до Earthen Fury и Garuda-Egi's Aerial Slash до Aerial Blast.",
      },
      // Trait 10
      "Trait 10": {
         "name": 'Ruin Mastery II',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/c2839ee8c3d/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/922e9f98625dbd32de2731c34566f15d168d987d.png',
         "job_icon": 'SMN',
         "level": '54',
         "content": 'Улучшает умение Ruin II до Ruin III.',
      },
      // Trait 11
      "Trait 11": {
         "name": 'Aethercharge Mastery',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/565ec60b81e/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/8b4a2b42cc234681fc17f9c6896ee86fe590077a.png',
         "job_icon": 'SMN',
         "level": '58',
         "content": 'Улучшает умение Aethercharge до Dreadwyrm Trance.',
      },
      // Trait 12
      "Trait 12": {
         "name": 'Enhanced Energy Siphon',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/53ddce372333beca80631fa8666b8c55f2d1828e.png',
         "job_icon": 'SMN',
         "level": '62',
         "content": 'Накладывает эффект Further Ruin после использования Energy Drain или Energy Siphon.',
      },
      // Trait 13
      "Trait 13": {
         "name": 'Enhanced Dreadwyrm Trance',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/a1074a175f6/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/8eed8e90cb9b2303b53bca1d58495492b16a5b6f.png',
         "job_icon": 'SMN',
         "level": '70',
         "content": 'Улучшает умение Dreadwyrm Trance до Summon Bahamut.',
      },
      // Trait 14
      "Trait 14": {
         "name": 'Ruin Mastery III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/878a70f208dc7cc5bd6adbbfa406c94cb4703203.png',
         "job_icon": 'SMN',
         "level": '72',
         "content": 'Усиливает Gemshine в соответствии с текущей активной стихией.<br/>Улучшение Fire Attunement: Ruby Rite<br/>Улучшение Earth Attunement: Topaz Rite<br/>Улучшение Wind Attunement: Emerald Rite',
      },
      // Trait 15
      "Trait 15": {
         "name": 'Outburst Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4a041cbfab769ce247b1e8845cb9f766eb435a89.png',
         "job_icon": 'SMN',
         "level": '74',
         "content": 'Улучшает умение Outburst до Tri-disaster.',
      },
      // Trait 16
      "Trait 16": {
         "name": 'Enhanced Summon Bahamut',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/8b01009ce2128991d557d23ac60c016fa5f77a68.png',
         "job_icon": 'SMN',
         "level": '80',
         "content": 'Улучшает Summon Bahamut до Summon Phoenix, когда Demi-Bahamut возвращается после призыва.',
      },
      // Trait 17
      "Trait 17": {
         "name": 'Outburst Mastery II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/cb628fc19fa6edbd36ec1c3f10ae2c511a574873.png',
         "job_icon": 'SMN',
         "level": '82',
         "content": 'Усиливает Precious Brilliance в соответствии с текущей активной стихией.<br/>Улучшение Fire Attunement: Ruby Catastrophe<br/>Улучшение Earth Attunement: Topaz Catastrophe<br/>Улучшение Wind Attunement: Emerald Catastrophe',
      },
      // Trait 18
      "Trait 18": {
         "name": 'Ruin Mastery IV',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d74d04bc18a9d70697cc89b5172335a2a8efd55f.png',
         "job_icon": 'SMN',
         "level": '84',
         "content": 'Увеличивает силу атаки Ruin III до 310, Ruby Rite до 510, Topaz Rite до 330 и Emerald Rite до 230.',
      },
      // Trait 19
      "Trait 19": {
         "name": 'Elemental Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/416d78494cf0fff59953835015c798594957d3fa.png',
         "job_icon": 'SMN',
         "level": '86',
         "content": "Накладывает Ifrit's Favor после использования Summon Ifrit, Titan's Favor после использования Topaz Rite или Topaz Catastrophe и Garuda's Favor после использования Summon Garuda.<br/>Усиливает Astral Flow в соответствии с благосклонностью на персонаже.<br/>Улучшение Ifrit's Favor: Crimson Cyclone<br/>Улучшение Titan's Favor: Mountain Buster<br/>Улучшение Garuda's Favor: Slipstream",
      },
      // Trait 20
      "Trait 20": {
         "name": 'Enhanced Radiant Aegis',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e7fa7ae2aa1f0c0fc8ee4623545a07e592a62e75.png',
         "job_icon": 'SMN',
         "level": '88',
         "content": 'Позволяет накапливать заряды для последовательного использования Radiant Aegis.<br/>Максимум зарядов: 2',
      },
      // Trait 21
      "Trait 21": {
         "name": 'Enkindle II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e9ffce052261a486d77cc418e7a220293b8d0d35.png',
         "job_icon": 'SMN',
         "level": '90',
         "content": 'Улучшает Summon Ifrit до Summon Ifrit II, Summon Titan до Summon Titan II и Summon Garuda до Summon Garuda II.',
      },
      // Trait 22 NEW
      "Trait 22": {
         "name": 'Enhanced Fester',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/53facd8b25710db47632a36af5234c873d2e0fb9.png',
         "job_icon": 'SMN',
         "level": '92',
         "content": 'Улучшает умение Fester до Necrotize.',
      },
      // Trait 23 NEW
      "Trait 23": {
         "name": 'Arcane Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/faebcc03aa187f6f45319b41b7336431d1722fc4.png',
         "job_icon": 'SMN',
         "level": '94',
         "content": 'Увеличивает силу атаки Ruin II до 360, Astral Impulse до 500, Ruin IV до 490, Ruby Rite до 540, Topaz Rite до 340, Emerald Rite до 240, Fountain of Fire до 580, Crimson Strike до 490, Crimson Cyclone до 490, Mountain Buster до 160, Slipstream до 490, Inferno до 800, Earthen Fury до 800 и Aerial Blast до 800.',
      },
      // Trait 24 NEW
      "Trait 24": {
         "name": 'Enhanced Searing Light',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/449b3c71c516f6bef021c30b88e2fa442cfb8b6b.png',
         "job_icon": 'SMN',
         "level": '96',
         "content": "Накладывает эффект Ruby's Glimmer после использования Searing Light.",
      },
      // Trait 25 NEW
      "Trait 25": {
         "name": 'Enhanced Summon Bahamut II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/6a8260bfa47331ec8f85dd4a445b793acdcbc468.png',
         "job_icon": 'SMN',
         "level": '100',
         "content": 'Позволяет вызывать Solar Bahamut в дополнение к Demi-Phoenix и Demi-Bahamut.',
      },
      // PVP Skill 01
      "PVP Skill 01": {
         "name": 'Ruin III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/38c2df65f188c9a5f9a3ad26343f8d835f309628.png',
         "classification": 'Заклинание',
         "cast": '1.44 сек.',
         "recast": '2.4 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 5,000.<br/><br/>※Умение меняется на Astral Impulse под действием эффекта Dreadwyrm Trance.<br/>※Умение меняется на Fountain of Fire под действием эффекта Firebird Trance.',
      },
      // PVP Skill 02
      "PVP Skill 02": {
         "name": 'Crimson Cyclone',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/79fa50e276f79eda778dfce164dc19481e609e30.png',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Рывок вперед и удар, наносящий урон огнем по цели и всем ближайшим противникам с силой атаки 8,000.<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.<br/>Это умение не имеет общего времени восстановления с другими умениями.<br/><br/>※Умение меняется на Crimson Strike после использования.',
      },
      // PVP Skill 03
      "PVP Skill 03": {
         "name": 'Slipstream',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ce754803ec26e9785e32a9650cffcfc65c56409e.png',
         "classification": 'Заклинание',
         "cast": '1.92 сек.',
         "recast": '30 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '10y',
         "content": 'Удар, наносящий урон ветром с силой атаки 8,000 по цели и всем ближайшим противникам.<br/>Дополнительный эффект: создает Slipstream вокруг цели, наносящий урон всем противникам, попавшим в него..<br/>Противники, находящиеся в радиусе 5 ялмов от центра бури не получают урона.<br/>Сила атаки: 4,000<br/>Дополнительный эффект: увеличивает скорость передвижения сопартийцев, находящихся в Slipstream, на 25%<br/>Продолжительность: 10 сек.<br/>Это умение не имеет общего времени восстановления с другими умениями.',
      },
      // PVP Skill 04
      "PVP Skill 04": {
         "name": 'Radiant Aegis',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b85eed363cf03ccdd2ddb535f391e2578dc27f61.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'оздает барьер вокруг персонажа или выбранного сопартийца, снижающий получаемый урон на 20% и поглощающий урон, равный силе лечения 10,000.<br/>Продолжительность: 10 сек.',
      },
      // PVP Skill 05
      "PVP Skill 05": {
         "name": 'Mountain Buster',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4fc71ae248e50adc69b9c80b00442de765b93d4b.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон землей с силой атаки 4,000 по цели и всем ближайшим противникам.<br/>Дополнительный эффект: накладывает на первую цель эффект связывание (bind), а на все остальные цели - тяжесть (heavy) +75%<br/>Продолжительность: 3 сек.<br/>Дополнительный эффект: притягивает остальные цели к первой',
      },
      // PVP Skill 06
      "PVP Skill 06": {
         "name": 'Fester',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a3ee44589112e6e3be04096f2b468bf6c6cb44bc.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 4,000.<br/>Сила атаки увеличивается по мере уменьшения HP цели, вплоть до 8,000, и достигает максимального значения, когда у цели остается 50% HP или меньше.<br/>Максимум зарядов: 2',
      },
      // PVP Skill 07
      "PVP Skill 07": {
         "name": 'Astral Impulse',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a4f03f56fc241517b2f1d3b66f44968caf83d6f7.png',
         "classification": 'Заклинание',
         "cast": '1.44 сек.',
         "recast": '2.4 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 7,500.<br/>Может быть использовано только под действием эффекта Dreadwyrm Trance.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 08
      "PVP Skill 08": {
         "name": 'Fountain of Fire',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/38e05864b47b78020da96fc263981869c4b6a5c9.png',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.4 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон огнем с силой атаки 5,000.<br/>Может быть использовано только под действием эффекта Firebird Trance.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 09
      "PVP Skill 09": {
         "name": 'Crimson Strike',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/20b52c9ffc91356c6aceaaf9752e942df7bceffb.png',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон огнем с силой атаки 12000 по цели и всем ближайшим противникам.<br/>Комбо умение: Crimson Cyclone<br/>Дополнительный эффект: отталкивает противников на 5 ялмов от первой цели<br/>Это умение не имеет общего времени восстановления с другими умениями. <br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 10
      "PVP Skill 10": {
         "name": 'Enkindle Bahamut',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/527ed62ae9f390bfc9ca7280f99d4d44a5d6d623.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Приказывает Demi-Bahamut использовать Akh Morn.<br/>Эффект Akh Morn: удар, наносящий нестихийный урон с силой атаки 12,000 по цели и всем ближайшим противникам.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 11
      "PVP Skill 11": {
         "name": 'Wyrmwave',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/486ac3f0e00283c10de5009a26b0cc90c3c424d4.png',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 6,000.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 12
      "PVP Skill 12": {
         "name": 'Akh Morn',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/527ed62ae9f390bfc9ca7280f99d4d44a5d6d623.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '100y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 12,000 по цели и всем ближайшим противникам.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 13
      "PVP Skill 13": {
         "name": 'Enkindle Phoenix',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f372829c6195b29b0bc550a544a39e1307e859b6.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Приказывает Demi-Phoenix использовать Revelation.<br/>Эффект Revelation: удар, наносящий нестихийный урон с силой атаки 6000 по цели и всем ближайшим противникам<br/>Дополнительный эффект: периодический урон<br/>Сила атаки: 3,000<br/>Продолжительность: 15 сек.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 14
      "PVP Skill 14": {
         "name": 'Scarlet Flame',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/3b078c7a3180375e47a20012da7ca10c5ca364ef.png',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон огнем с силой атаки 4,000.<br/>Дополнительный эффект: снижает наносимый целью урон на 50%<br/>Продолжительность: 5 сек.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 15
      "PVP Skill 15": {
         "name": 'Revelation',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7b2d75cdeffd1d00b2e2088f9073b3d02f7da5e1.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '100y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 6,000 по цели и всем ближайшим противникам.<br/>Дополнительный эффект: периодический урон<br/>Сила атаки: 3,000<br/>Продолжительность: 15 сек.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 16
      "PVP Skill 16": {
         "name": 'Summon Bahamut',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7ef1dd621306bd909533ec27e89d0c1dc00da182.png',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "range": '30y',
         "radius_img": 'R2',
         "radius": '15y',
         "content": 'Персонаж входит в Dreadwyrm Trance и вызывает Demi-Bahamut на выбранное место.<br/>Продолжительность: 20 сек.<br/>После призыва Demi-Bahamut применит Megaflare, а затем автоматически использует Wyrmwave, отдавая предпочтение целям с наименьшим количеством HP в радиусе 30 ялмов.<br/>Может быть использовано только тогда, когда шкала лимит брейка (limit gauge) заполнена.<br/>Время зарядки шкалы: 90 сек.<br/><br/>※Умение меняется на Enkindle Bahamut после использования.<br/>※Ruin III меняется на Astral Impulse после использования под эффектом Dreadwyrm Trance.',
      },
      // PVP Skill 17
      "PVP Skill 17": {
         "name": 'Megaflare',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2a26548300186f20cfb000ecd2e279e952b0daf7.png',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '15y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 18000 по всем ближайшим противникам.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 18
      "PVP Skill 18": {
         "name": 'Summon Phoenix',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/43a7121c604b4da78f2a9d4110cc2a85bc6c6425.png',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "range": '30y',
         "radius_img": 'R2',
         "radius": '15y',
         "content": 'Персонаж входит в Firebird Trance и вызывает Demi-Phoenix на выбранное место.<br/>Продолжительность: 20 сек.<br/>После призыва Demi-Phoenix применит Everlasting Flight, а затем автоматически использует Scarlet Flame, выбирая ближайшую цель в радиусе 30 ялмов.<br/>Может быть использовано только тогда, когда шкала лимит брейка (limit gauge) заполнена.<br/>Время зарядки шкалы: 90 сек.<br/><br/>※Умение меняется на Enkindle Phoenix после использования.<br/>※Ruin III меняется на Fountain of Fire после использования под эффектом Firebird Trance.',
      },
      // PVP Skill 19
      "PVP Skill 19": {
         "name": 'Everlasting Flight',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/790d6bfaf5e0b6360d2a39c760e66f1b92ba4b46.png',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '15y',
         "content": 'Постепенно восстанавливает HP персонажа и всех ближайших сопартийцев.<br/>Сила лечения: 4,000<br/>Продолжительность: 15 сек.<br/>Дополнительный эффект: восстанавливает HP, когда оно падает ниже 25% или по истечении срока действия эффекта<br/>Сила лечения: 12,000<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
   };
   FILL_DB_VALUES(db);
   FILL_DB_SKILLS(db);
   FILL_DB_SKILLS_PASSIVE(db);
   FILL_DB_SKILLS_PVP(db);
   FILL_DB_SKILLS_MENU(db);
})();