(() =>{
   let db = {
      "PVE Update": `Последнее обновление: 28/06/2024`,
      "PVP Update": `Последнее обновление: 28/06/2024`,
      // PVE Skill 01
      "PVE Skill 01": {
         "name": 'Steel Fangs',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4c17f1a64284635f1483f205f9aea15be9bd1a16.png',
         "job_icon": 'VPR',
         "level": '1',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 200.',
      },
      // PVE Skill 02
      "PVE Skill 02": {
         "name": "Hunter's Sting",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/3b2aea9fa0be73f01aeb45b7eff15fd344776af0.png',
         "job_icon": 'VPR',
         "level": '5',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Удар, наносящий урон с силой атаки 260.<br/>Дополнительный эффект: накладывает эффект Hunter's Instinct<br/>Эффект Hunter's Instinct: увеличивает наносимый урон на 10%<br/>Продолжительность: 40 сек.<br/>Может быть использовано только после успешного применения Steel Fangs или Dread Fangs.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Steel Fangs меняется на Hunter's Sting при соблюдении требований к выполнению.",
      },
      // PVE Skill 03
      "PVE Skill 03": {
         "name": 'Dread Fangs',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/0763edc3238365b4076dba5d28b8f5c68be1d3de.png',
         "job_icon": 'VPR',
         "level": '10',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 140.<br/>Дополнительный эффект: накладывает на цель Noxious Gnash<br/>Эффект Noxious Gnash: увеличивает наносимый цели урон на 10%<br/>Продолжительность: 20 сек.<br/>Увеличивает продолжительность умения Noxious Gnash на 20 сек., вплоть до 40 сек.',
      },
      // PVE Skill 04
      "PVE Skill 04": {
         "name": 'Writhing Snap',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/251a98740164ae526be0e23bf9477abb8e28fe94.png',
         "job_icon": 'VPR',
         "level": '15',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '20y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Дальний удар, наносящий урон с силой атаки 200.',
      },
      // PVE Skill 05
      "PVE Skill 05": {
         "name": "Swiftskin's Sting",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/75a4621d0d002a4b18c59acfdfb097424ff88a5b.png',
         "job_icon": 'VPR',
         "level": '20',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Удар, наносящий урон с силой атаки 260.<br/>Дополнительный эффект: накладывает эффект Swiftscaled<br/>Эффект Swiftscaled: сокращает время применения и восстановления боевых навыков, заклинаний и авто атак на 15%<br/>Продолжительность: 40 сек.<br/>Может быть использовано только после успешного применения Steel Fangs или Dread Fangs.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Dread Fangs меняется на Swiftskin's Sting при соблюдении требований к выполнению.",
      },
      // PVE Skill 06
      "PVE Skill 06": {
         "name": 'Steel Maw',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/8b9f63b988cfb7be43914b31ff5551ee41c99ffa.png',
         "job_icon": 'VPR',
         "level": '25',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 100 по всем окружающим противникам.',
      },
      // PVE Skill 07
      "PVE Skill 07": {
         "name": 'Flanksting Strike',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/05bf152b3b5ac3ed319b5cdcbbdca1db4006cd96.png',
         "job_icon": 'VPR',
         "level": '30',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Удар, наносящий урон с силой атаки 300, при выполнении удара в бок цели 360.<br/>Под действием эффекта Flankstung Venom сила атаки увеличивается на 100.<br/>Дополнительный эффект: накладывает эффект Hindstung Venom<br/>Эффект Hindstung Venom: увеличивает силу Hindsting Strike на 100<br/>Продолжительность: 40 сек.<br/>Эффект не стакается с другими эффектами яда вайпера.<br/>Восполняет ресурс шкалы Serpent Offerings на 10<br/>Может быть использовано только после успешного применения Hunter's Sting.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Hunter's Sting меняется на Flanksting Strike при соблюдении требований к выполнению.",
      },
      // PVE Skill 08
      "PVE Skill 08": {
         "name": 'Flanksbane Fang',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/24777f7ac5f5169f3ebf6b656d7cedf54d57e9a6.png',
         "job_icon": 'VPR',
         "level": '30',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Удар, наносящий урон с силой атаки 300, при выполнении удара в бок цели 360.<br/>Под действием эффекта Flanksbane Venom сила атаки увеличивается на 100.<br/>Дополнительный эффект: накладывает эффект Hindsbane Venom<br/>Эффект Hindsbane Venom: увеличивает силу Hindsbane Fang на 100<br/>Продолжительность: 40 сек.<br/>Эффект не стакается с другими эффектами яда вайпера.<br/>Восполняет ресурс шкалы Serpent Offerings на 10<br/>Может быть использовано только после успешного применения Hunter's Sting.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Swiftskin's Sting меняется на Flanksbane Fang при соблюдении требований к выполнению.",
      },
      // PVE Skill 09
      "PVE Skill 09": {
         "name": 'Hindsting Strike',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c0524362f22ecb3fe78015685d2385c1cfbbe811.png',
         "job_icon": 'VPR',
         "level": '30',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Удар, наносящий урон с силой атаки 300, при выполнении удара в спину цели 350.<br/>Под действием эффекта Hindstung Venom сила атаки увеличивается на 100.<br/>Дополнительный эффект: накладывает эффект Flanksbane Venom<br/>Эффект Flanksbane Venom: увеличивает силу Flanksbane Fang на 100<br/>Продолжительность: 40 сек.<br/>Эффект не стакается с другими эффектами яда вайпера.<br/>Восполняет ресурс шкалы Serpent Offerings на 10<br/>Может быть использовано только после успешного применения Swiftskin's Sting.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Hunter's Sting меняется на Hindsting Strike при соблюдении требований к выполнению.",
      },
      // PVE Skill 10
      "PVE Skill 10": {
         "name": 'Hindsbane Fang',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2ca132552615abcd4f962ec2b32eb8b0ef6ccd50.png',
         "job_icon": 'VPR',
         "level": '30',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Удар, наносящий урон с силой атаки 300, при выполнении удара в спину цели 360.<br/>Под действием эффекта Flanksbane Venom сила атаки увеличивается на 100.<br/>Дополнительный эффект: накладывает эффект Flankstung Venom<br/>Эффект Flankstung Venom: увеличивает силу Flanksting Strike на 100<br/>Продолжительность: 40 сек.<br/>Эффект не стакается с другими эффектами яда вайпера.<br/>Восполняет ресурс шкалы Serpent Offerings на 10<br/>Может быть использовано только после успешного применения Swiftskin's Sting.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Swiftskin's Sting меняется на Hindsting Strike при соблюдении требований к выполнению.",
      },
      // PVE Skill 11
      "PVE Skill 11": {
         "name": 'Dread Maw',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d5b0fd312dbb29775aba54246dc487805eb045e7.png',
         "job_icon": 'VPR',
         "level": '35',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 80 по всем окружающим противникам.<br/>Дополнительный эффект: накладывает на цель эффект Noxious Gnash<br/>Эффект Noxious Gnash: увеличивает наносимый цели урон на 10%<br/>Продолжительность: 20 сек.<br/>Увеличивает продолжительность умения Noxious Gnash на 20 сек., вплоть до 40 сек.',
      },
      // PVE Skill 12
      "PVE Skill 12": {
         "name": 'Slither',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7ebdd1c17d9bfe7e52641396ee2c0ff944aea319.png',
         "job_icon": 'VPR',
         "level": '40',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '30 сек.',
         "range": '20y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Рывок к выбранному противнику или сопартийцу.<br/>Максимум стаков: 3<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.',
      },
      // PVE Skill 13
      "PVE Skill 13": {
         "name": "Hunter's Bite",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2117aa184918197d460d34352b715a239d27af1d.png',
         "job_icon": 'VPR',
         "level": '40',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": "Удар, наносящий урон с силой атаки 120 по всем окружающим противникам.<br/>Дополнительный эффект: накладывает эффект Hunter's Instinct<br/>Эффект Noxious Gnash: увеличивает наносимый цели урон на 10%<br/>Продолжительность: 40 сек.<br/>Может быть использовано только после успешного применения Steel Maw или Dread Maw.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Steel Maw меняется на Hunter's Bite при соблюдении требований к выполнению.",
      },
      // PVE Skill 14
      "PVE Skill 14": {
         "name": "Swiftskin's Bite",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c45c309beb82894d97fdb3a01afe3673cc1ec5b0.png',
         "job_icon": 'VPR',
         "level": '45',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": "Удар, наносящий урон с силой атаки 120 по всем окружающим противникам.<br/>Дополнительный эффект: накладывает эффект Swiftscaled<br/>Эффект Swiftscaled: сокращает время применения и восстановления боевых навыков, заклинаний и авто атак на 15%<br/>Продолжительность: 40 сек.<br/>Может быть использовано только после успешного применения Steel Maw или Dread Maw.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Steel Maw меняется на Swiftskin's Bite при соблюдении требований к выполнению.",
      },
      // PVE Skill 15
      "PVE Skill 15": {
         "name": 'Jagged Maw',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a7c0917ef2eebad0e74ffceccb472348016fcb79.png',
         "job_icon": 'VPR',
         "level": '50',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": "Удар, наносящий урон с силой атаки 140 по всем окружающим противникам.<br/>Под действием эффекта Grimhunter's Venom сила атаки увеличивается на 20.<br/>Дополнительный эффект: накладывает эффект Grimskin's Venom<br/>Эффект Grimskin's Venom: увеличивает силу атаки Bloodied Maw на 20<br/>Продолжительность: 40 сек.<br/>Эффект не стакается с другими эффектами яда вайпера.<br/>Доволнительный эффект: восполняет ресурс шкалы Serpent Offerings на 10<br/>Может быть использовано только после успешного применения Hunter's Bite или Swiftskin's Bite.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Hunter's Bite меняется на Jagged Maw при соблюдении требований к выполнению.",
      },
      // PVE Skill 16
      "PVE Skill 16": {
         "name": 'Bloodied Maw',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/6715225127c0d7b81affb5d8cbdbb81dbaac8744.png',
         "job_icon": 'VPR',
         "level": '50',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": "Удар, наносящий урон с силой атаки 140 по всем окружающим противникам.<br/>Под действием эффекта Grimskin's Venom сила атаки увеличивается на 20.<br/>Дополнительный эффект: накладывает эффект Grimhunter's Venom<br/>Эффект Grimhunter's Venom: увеличивает силу атаки Jagged Maw  на 20<br/>Продолжительность: 40 сек.<br/>Эффект не стакается с другими эффектами яда вайпера.<br/>Доволнительный эффект: восполняет ресурс шкалы Serpent Offerings на 10<br/>Может быть использовано только после успешного применения Hunter's Bite или Swiftskin's Bite.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Swiftskin's Bite меняется на Bloodied Maw при соблюдении требований к выполнению.",
      },
      // PVE Skill 17
      "PVE Skill 17": {
         "name": "Serpent's Tail",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/462326b75ba66828eb96e0f2d64ef7542daccf38.png',
         "job_icon": 'VPR',
         "level": '55',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Удар, наносящий урон с силой атаки 140 по всем окружающим противникам.<br/>Под действием эффекта Grimskin's Venom сила атаки увеличивается на 20.<br/>Дополнительный эффект: накладывает эффект Grimhunter's Venom<br/>Эффект Grimhunter's Venom: увеличивает силу атаки Jagged Maw на 20<br/>Продолжительность: 40 сек.<br/>Эффект не стакается с другими эффектами яда вайпера.<br/>Доволнительный эффект: восполняет ресурс шкалы Serpent Offerings на 10<br/>Может быть использовано только после успешного применения Hunter's Bite или Swiftskin's Bite.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Swiftskin's Bite меняется на Bloodied Maw при соблюдении требований к выполнению.",
      },
      // PVE Skill 18
      "PVE Skill 18": {
         "name": 'Death Rattle',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/42670e7db3e339182d5d65c29f7acee4319d5360.png',
         "job_icon": 'VPR',
         "level": '55',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Удар, наносящий урон с силой атаки 250.<br/>Может быть использовано только после успешного применения Flanksting Strike, Flanksbane Fang, Hindsting Strike или Hindsbane Fang.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Serpent's Tail меняется на Death Rattle при соблюдении требований к выполнению.",
      },
      // PVE Skill 19
      "PVE Skill 19": {
         "name": 'Last Lash',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/6931cd1152c69f96360689e0e61a8c6cabfafe46.png',
         "job_icon": 'VPR',
         "level": '60',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": "Удар, наносящий урон с силой атаки 100 по всем окружающим противникам.<br/>Может быть использовано только после успешного применения Jagged Maw или Bloodied Maw.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Serpent's Tail меняется на Last Lash при соблюдении требований к выполнению.",
      },
      // PVE Skill 20
      "PVE Skill 20": {
         "name": 'Dreadwinder',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7958ea7095b37de74593fd6d1426d74177e46536.png',
         "job_icon": 'VPR',
         "level": '65',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '40 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 450.<br/>Дополнительный эффект: накладывает на цель Noxious Gnash<br/>Эффект Noxious Gnash: увеличивает наносимый цели урон на 10%<br/>Продолжительность: 20 сек.<br/>Увеличивает продолжительность умения Noxious Gnash на 20 сек., вплоть до 40 сек.<br/>Дает Rattling Coil, максимум 3<br/>Максимальное количество зарядов: 2<br/>Имеет общее время восстановления с умением Pit of Dread.',
      },
      // PVE Skill 21
      "PVE Skill 21": {
         "name": "Hunter's Coil",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a9a91ec0b652e92408c4211e510ffca14d7498cd.png',
         "job_icon": 'VPR',
         "level": '65',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '3 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Удар, наносящий урон с силой атаки 500, при выполнении удара в бок цели 550.<br/>Дополнительный эффект: накладывает эффект Hunter's Instinct<br/>Эффект Hunter's Instinct: увеличивает наносимый урон на 10%<br/>Продолжительность: 40 сек.<br/>Дополнительный эффект: накладывает эффект Hunter's Venom<br/>Эффект Hunter's Venom: увеличивает силу атаки Twinfang Bite на 50<br/>Продолжительность: 30 сек.<br/>Дополнительный эффект: восполняет ресурс шкалы Serpent Offerings на 5<br/>При успешном выполнении этого умения Twinfang меняется на Twinfang Bite и Twinblood меняется на Twinblood Bite.<br/>Эти умения могут быть использованы в общей сложности два раза, после последовательного Hunter's Coil.<br/>Может быть использовано только после Dreadwinder или Swiftskin's Coil.<br/>Этот боевой навык не имеет общего время восстановления с другими умениями.",
      },
      // PVE Skill 22
      "PVE Skill 22": {
         "name": "Swiftskin's Coil",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2ff8a8c9e5710f229b6d3dc3e19ea40c7908cb50.png',
         "job_icon": 'VPR',
         "level": '65',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '3 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Удар, наносящий урон с силой атаки 500, при выполнении удара в спину цели 550.<br/>Дополнительный эффект: накладывает эффект Swiftscaled<br/>Эффект Swiftscaled: сокращает время применения и восстановления боевых навыков, заклинаний и авто атак на 15%<br/>Продолжительность: 40 сек.<br/>Дополнительный эффект: накладывает эффект Swiftskin's Venom<br/>Эффект Swiftskin's Venom: увеличивает силу атаки Twinblood Bite на 50<br/>Продолжительность: 30 сек.<br/>Дополнительный эффект: восполняет ресурс шкалы Serpent Offerings на 5<br/>При успешном выполнении этого умения Twinfang меняется на Twinfang Bite и Twinblood меняется на Twinblood Bite.<br/>Эти умения могут быть использованы в общей сложности два раза, после последовательного Hunter's Coil.<br/>Может быть использовано только после Dreadwinder или Swiftskin's Coil.<br/>Этот боевой навык не имеет общего время восстановления с другими умениями.",
      },
      // PVE Skill 23
      "PVE Skill 23": {
         "name": 'Pit of Dread',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/13c9698f33d48e95d53bb67e7eef68bfff122e14.png',
         "job_icon": 'VPR',
         "level": '70',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '40 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 200 по всем окружающим противникам.<br/>Дополнительный эффект: накладывает на цель эффект Noxious Gnash<br/>Эффект Noxious Gnash: увеличивает наносимый цели урон на 10%<br/>Продолжительность: 20 сек.<br/>Увеличивает продолжительность умения Noxious Gnash на 20 сек., вплоть до 40 сек.<br/>Дает Rattling Coil, максимум 3<br/>Максимальное количество зарядов: 2<br/>Имеет общее время восстановления с умением Dreadwinder.',
      },
      // PVE Skill 24
      "PVE Skill 24": {
         "name": "Hunter's Den",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d807e8e444e8cb313a14e04f5c4d9f3af91b9706.png',
         "job_icon": 'VPR',
         "level": '70',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '3 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": "Удар, наносящий урон с силой атаки 250 по всем окружающим противникам.<br/>Дополнительный эффект: накладывает эффект Hunter's Instinct<br/>Эффект Noxious Gnash: увеличивает наносимый цели урон на 10%<br/>Продолжительность: 40 сек.<br/>Дополнительный эффект: накладывает эффект Fellhunter's Venom<br/>Эффект Fellhunter's Venom: увеличивает силу атаки Twinfang Thresh на 30<br/>Продолжительность: 30 сек.<br/>Дополнительный эффект: восполняет ресурс шкалы Serpent Offerings на 5<br/>При успешном выполнении этого умения Twinfang меняется на Twinfang Thresh и Twinblood меняется на Twinblood Thresh.<br/>Эти умения могут быть использованы в общей сложности два раза, после последовательного Hunter's Coil.<br/>Может быть использовано только после Pit of Dread или Swiftskin's Den.<br/>Этот боевой навык не имеет общего время восстановления с другими умениями.",
      },
      // PVE Skill 25
      "PVE Skill 25": {
         "name": "Swiftskin's Den",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2425fc375286fe6776b09f0db2f020faec679bfd.png',
         "job_icon": 'VPR',
         "level": '70',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '3 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": "Удар, наносящий урон с силой атаки 250 по всем окружающим противникам.<br/>Дополнительный эффект: накладывает эффект Swiftscaled<br/>Эффект Swiftscaled: сокращает время применения и восстановления боевых навыков, заклинаний и авто атак на 15%<br/>Продолжительность: 40 сек.<br/>Дополнительный эффект: накладывает эффект Fellskin's Venom<br/>Эффект Fellskin's Venom: увеличивает силу атаки Twinblood Thresh на 30<br/>Продолжительность: 30 сек.<br/>Дополнительный эффект: восполняет ресурс шкалы Serpent Offerings на 5<br/>При успешном выполнении этого умения Twinfang меняется на Twinfang Thresh и Twinblood меняется на Twinblood Thresh.<br/>Эти умения могут быть использованы в общей сложности два раза, после последовательного Swiftskin's Den.<br/>Может быть использовано только после Pit of Dread или Hunter's Den.<br/>Этот боевой навык не имеет общего время восстановления с другими умениями.",
      },
      // PVE Skill 26
      "PVE Skill 26": {
         "name": 'Twinfang',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c0a3ce4ca4284759ef6ac5592b351f6985fe4edd.png',
         "job_icon": 'VPR',
         "level": '75',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Меняется на Twinfang Bite, Twinfang Thresh или Uncoiled Twinfang при соблюдении требований к выполнению.',
      },
      // PVE Skill 27
      "PVE Skill 27": {
         "name": 'Twinblood',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/0093aca28c0a2877e6fb631b24af1d0b77c46f92.png',
         "job_icon": 'VPR',
         "level": '75',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Меняется на Twinblood Bite, Twinblood Thresh или Uncoiled Twinblood при соблюдении требований к выполнению.',
      },
      // PVE Skill 28
      "PVE Skill 28": {
         "name": 'Twinfang Bite',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7f157bebbaa01d92600ee604fbce64f969730966.png',
         "job_icon": 'VPR',
         "level": '75',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Удар, наносящий урон с силой атаки 100.<br/>Сила атаки Hunter's Venom: 150<br/>Дополнительный эффект: дает Swiftskin's Venom, когда выполняется после Hunter's Coil<br/>Продолжительность: 30 сек.<br/>Может быть использовано только после успешного применения Hunter's Coil или Swiftskin's Coil.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Twinfang меняется на Twinfang Bite при соблюдении требований к выполнению.",
      },
      // PVE Skill 29
      "PVE Skill 29": {
         "name": 'Twinblood Bite',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d2e6fe2cd7f5e0ac0170f7aeb78639533e4f7cc7.png',
         "job_icon": 'VPR',
         "level": '75',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Удар, наносящий урон с силой атаки 100.<br/>Сила атаки Swiftskin's Venom: 150<br/>Дополнительный эффект: дает Hunter's Venom, когда выполняется после Swiftskin's Coil<br/>Продолжительность: 30 сек.<br/>Может быть использовано только после успешного применения Hunter's Coil или Swiftskin's Coil.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Twinblood меняется на Twinblood Bite при соблюдении требований к выполнению.",
      },
      // PVE Skill 30
      "PVE Skill 30": {
         "name": 'Twinfang Thresh',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/94a94c69ef3f58b4b0601e1f04fdef144ad2830f.png',
         "job_icon": 'VPR',
         "level": '80',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": "Удар, наносящий урон с силой атаки 50 по всем окружающим противникам.<br/>Сила атаки Fellhunter's Venom: 80<br/>Дополнительный эффект: дает Fellskin's Venom, когда выполняется после Hunter's Den<br/>Продолжительность: 30 сек.<br/>Может быть использовано только после успешного применения Hunter's Coil или Swiftskin's Den.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Twinfang меняется на Twinfang Thresh при соблюдении требований к выполнению.",
      },
      // PVE Skill 31
      "PVE Skill 31": {
         "name": 'Twinblood Thresh',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/29c3f69d1f38de7049262c99da58d8ff8ba8607d.png',
         "job_icon": 'VPR',
         "level": '80',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": "Удар, наносящий урон с силой атаки 50 по всем окружающим противникам.<br/>Сила атаки Fellskin's Venom: 80<br/>Дополнительный эффект: дает Fellhunter's Venom, когда выполняется после Swiftskin's Den<br/>Продолжительность: 30 сек.<br/>Может быть использовано только после успешного применения Hunter's Den или Swiftskin's Den.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Twinblood меняется на Twinblood Thresh при соблюдении требований к выполнению.",
      },
      // PVE Skill 32
      "PVE Skill 32": {
         "name": 'Uncoiled Fury',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/9b1b65c7abae88ab3c5ba775a7eda8e6afccf3b2.png',
         "job_icon": 'VPR',
         "level": '82',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '3.5 сек.',
         "range": '20y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 600 для первого противника и на 50% меньше для остальных.<br/>Дополнительный эффект: накладывает Poised for Twinfang<br/>Эффект Poised for Twinfang: увеличивает силу атаки Uncoiled Twinfang на 50<br/>Продолжительность: 60 сек.<br/>Стоимость Rattling Coil: 1<br/>Этот боевой навык не имеет общего время восстановления с другими умениями.',
      },
      // PVE Skill 33
      "PVE Skill 33": {
         "name": "Serpent's Ire",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/07ad6a7df65952f604f164eb4ac1cb99238dd871.png',
         "job_icon": 'VPR',
         "level": '86',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Дает Rattling Coil.<br/>Дает Ready to Reawaken<br/>Продолжительность: 30 сек.<br/>Может выполняться только в бою.',
      },
      // PVE Skill 34
      "PVE Skill 34": {
         "name": 'Reawaken',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/747eae977c8adbe87254c934e1e890fc54a85b50.png',
         "job_icon": 'VPR',
         "level": '90',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.2 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 700 для первого противника и на 60% меньше для остальных.<br/>Дополнительный эффект: дает 5 стаков Anguine Tribute<br/>Продолжительность: 30 сек.<br/>Стоимость: 50 Serpent Offerings Gauge',
      },
      // PVE Skill 35
      "PVE Skill 35": {
         "name": 'First Generation',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/0669ed905da6f1885333d21619a678cf6b382a72.png',
         "job_icon": 'VPR',
         "level": '90',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '3y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 400 для первого противника и на 60% меньше для остальных.<br/>Сила атаки увеличивается до 600, когда выполняется после Reawaken.<br/>Стоимость Anguine Tribute: 1<br/>Этот боевой навык не имеет общего время восстановления с другими умениями.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Steel Fangs и Steel Maw меняется на First Generation при соблюдении требований к выполнению.',
      },
      // PVE Skill 36
      "PVE Skill 36": {
         "name": 'Second Generation',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/0c534882c858afef2cee59ccf78664dac5f5d28e.png',
         "job_icon": 'VPR',
         "level": '90',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '3y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 400 для первого противника и на 60% меньше для остальных.<br/>Сила атаки увеличивается до 600, когда выполняется после First Generation.<br/>Стоимость Anguine Tribute: 1<br/>Этот боевой навык не имеет общего время восстановления с другими умениями.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Dread Fangs и Dread Maw меняется на Second Generation при соблюдении требований к выполнению.',
      },
      // PVE Skill 37
      "PVE Skill 37": {
         "name": 'Third Generation',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/bac0b9c0fc9068b083e47d645b2db52d8888ae7e.png',
         "job_icon": 'VPR',
         "level": '90',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '3y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": "Удар, наносящий урон с силой атаки 400 для первого противника и на 60% меньше для остальных.<br/>Сила атаки увеличивается до 600, когда выполняется после Second Generation.<br/>Стоимость Anguine Tribute: 1<br/>Этот боевой навык не имеет общего время восстановления с другими умениями.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Hunter's Coil и Hunter's Den меняется на Third Generation при соблюдении требований к выполнению.",
      },
      // PVE Skill 38
      "PVE Skill 38": {
         "name": 'Fourth Generation',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/718f70f8e5f985309a09171ba83bcf34fba0cbf9.png',
         "job_icon": 'VPR',
         "level": '90',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '3y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": "Удар, наносящий урон с силой атаки 400 для первого противника и на 60% меньше для остальных.<br/>Сила атаки увеличивается до 600, когда выполняется после Third Generation.<br/>Стоимость Anguine Tribute: 1<br/>Этот боевой навык не имеет общего время восстановления с другими умениями.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Swiftskin's Coil и Swiftskin's Den меняется на Fourth Generation при соблюдении требований к выполнению.",
      },
      // PVE Skill 39
      "PVE Skill 39": {
         "name": 'Uncoiled Twinfang',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/fb4eb443e7d759b2e6e01ead35aa6b6dd73abf4c.png',
         "job_icon": 'VPR',
         "level": '92',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '20y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 100 для первого противника и на 50% меньше для остальных.<br/>Сила атаки Poised for Twinfang: 150<br/>Дополнительный эффект: накладывает эффект Poised for Twinblood<br/>Эффект Poised for Twinblood: увеличивает силу Uncoiled Twinblood на 50<br/>Продолжительность: 60 сек.<br/>Может быть использовано только после Uncoiled Fury.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Twinfang меняется на Uncoiled Twinfang при соблюдении требований к выполнению.',
      },
      // PVE Skill 40
      "PVE Skill 40": {
         "name": 'Uncoiled Twinblood',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/eb4f394f15241c1820a674ba2f671d005ab431cf.png',
         "job_icon": 'VPR',
         "level": '92',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '20y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 100 для первого противника и на 50% меньше для остальных.<br/>Сила атаки Poised for Twinblood: 150<br/>Может быть использовано только после Uncoiled Fury.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Twinblood меняется на Uncoiled Twinblood при соблюдении требований к выполнению.',
      },
      // PVE Skill 41
      "PVE Skill 41": {
         "name": 'Ouroboros',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/9c66e4147b2a5467f541734d3aedc5e0f1522b07.png',
         "job_icon": 'VPR',
         "level": '96',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '3 сек.',
         "range": '3y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 1,050 для первого противника и на 60% меньше для остальных.<br/>Эффект Reawakened пропадает после использования.<br/>Требуется как минимум один стак Anguine Tribute.<br/>Этот боевой навык не имеет общего время восстановления с другими умениями.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Reawaken меняется на Ouroboros при соблюдении требований к выполнению.',
      },
      // PVE Skill 42
      "PVE Skill 42": {
         "name": 'First Legacy',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a7750d692ef417ce934373dab4f71214ca5d6676.png',
         "job_icon": 'VPR',
         "level": '100',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '3y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": "Удар, наносящий урон с силой атаки 250 для первого противника и на 60% меньше для остальных.<br/>Может быть использовано только после First Generation.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Serpent's Tail меняется на First Legacy при соблюдении требований к выполнению.",
      },
      // PVE Skill 43
      "PVE Skill 43": {
         "name": 'Second Legacy',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/845aa0a62b6afed88ac65e36b63ec0e171526aa4.png',
         "job_icon": 'VPR',
         "level": '100',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '3y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": "Удар, наносящий урон с силой атаки 250 для первого противника и на 60% меньше для остальных.<br/>Может быть использовано только после Second Generation.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Serpent's Tail меняется на Second Generation при соблюдении требований к выполнению.",
      },
      // PVE Skill 44
      "PVE Skill 44": {
         "name": 'Third Legacy',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/6fbd15532cd7c980e0f5c55b40d641d64c849b17.png',
         "job_icon": 'VPR',
         "level": '100',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '3y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": "Удар, наносящий урон с силой атаки 250 для первого противника и на 60% меньше для остальных.<br/>Может быть использовано только после Third Generation.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Serpent's Tail меняется на Third Generation при соблюдении требований к выполнению.",
      },
      // PVE Skill 45
      "PVE Skill 45": {
         "name": 'Fourth Legacy',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/479c9e0777b6a210f15ef8215c2bac81c1c5ffb0.png',
         "job_icon": 'VPR',
         "level": '100',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '3y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": "Удар, наносящий урон с силой атаки 250 для первого противника и на 60% меньше для остальных.<br/>Может быть использовано только после Fourth Generation.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Serpent's Tail меняется на Fourth Generation при соблюдении требований к выполнению.",
      },
      // Trait 01
      "Trait 01": {
         "name": "Viper's Fangs",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/9e14a796df9b3cae3544d8cb2d1854bc672ad210.png',
         "job_icon": 'VPR',
         "level": '55',
         "content": 'Позволяет использовать Death Rattle. Может быть использовано только после успешного завершения комбо с Flanksting Strike, Flankbane Fang, Hindsting Strike или Hindsbane Fang.',
      },
      // Trait 02
      "Trait 02": {
         "name": "Viper's Maw",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/09630c297ad9fe64beeca174d41e2cf8c8ed559d.png',
         "job_icon": 'VPR',
         "level": '60',
         "content": 'Позволяет использовать Last Lash. Может быть использовано только после успешного завершения комбо с Jagged Maw или Bloodied Maw. ',
      },
      // Trait 03
      "Trait 03": {
         "name": 'Melee Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/bc58b07072e258883e9e584c4e45355d092da661.png',
         "job_icon": 'VPR',
         "level": '74',
         "content": "Увеличивает силу атаки умениям Steel Fangs до 200, Dread Fangs до 140, Hunter's Sting до 260 и Swiftskin's Sting до 260.",
      },
      // Trait 04
      "Trait 04": {
         "name": "Viper's Bite",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4b105f04e744d6a65f6ed28c75a79ec5f0151a49.png',
         "job_icon": 'VPR',
         "level": '75',
         "content": "Позволяет использовать Two Fang Bite и Twin Blood Bite.<br/>Может быть использовано только после успешного завершения комбо с Hunter's Coil или Swiftskin's Coil.",
      },
      // Trait 05
      "Trait 05": {
         "name": "Viper's Thresh",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2122a2b003b6dd72cc260a13a93f22097ebe07af.png',
         "job_icon": 'VPR',
         "level": '80',
         "content": "Позволяет использовать Twin Fang Thresh и Twinblood Thresh.<br/>Может быть использовано только после успешного завершения комбо с Hunter's Den или Swiftskin's Den.",
      },
      // Trait 06
      "Trait 06": {
         "name": "Viper's Rattle",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5e6639d21fbec398ad534ae0c2fe19b5f3001b4b.png',
         "job_icon": 'VPR',
         "level": '82',
         "content": 'Дает Rattling Coil при успешном использовании Dreadwinder или Pit of Dread.',
      },
      // Trait 07
      "Trait 07": {
         "name": 'Enhanced Slither',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1e60ee225ffece4266216964ac996c1466a8b858.png',
         "job_icon": 'VPR',
         "level": '84',
         "content": 'Добавляет третий заряд для умения Slither.',
      },
      // Trait 08
      "Trait 08": {
         "name": 'Melee Mastery II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b60557edca3b093463f0f0c0c04dc3895855e9f8.png',
         "job_icon": 'VPR',
         "level": '84',
         "content": 'Увеличивает силу атаки умениям Flanksting Strike до 300, Flanksbane Fang до 300, Hindsting Strike до 300 и Hindsbane Fang до 300.',
      },
      // Trait 09
      "Trait 09": {
         "name": "Enhanced Viper's Rattle",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5a6e704cdb935de113fa46e137907d9a816e5194.png',
         "job_icon": 'VPR',
         "level": '88',
         "content": "Позволяет накапливать третий Rattling Coil.",
      },
      // Trait 10
      "Trait 10": {
         "name": "Serpent's Lineage",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/026131d5e2c5bb1aab3bb492c7329cc791cc8c39.png',
         "job_icon": 'VPR',
         "level": '90',
         "content": "Позволяет восполнять шкалу Serpent Offerings Gauge при выполнении определенных умений.<br/>Кроме того, добавляет дополнительный эффект к Serpent's Ire, который дает Ready to Reawaken.<br/>Продолжительность: 30 сек.",
      },
      // Trait 11
      "Trait 11": {
         "name": 'Uncoiled Fangs',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1fd453ec378516f7b77ff959e7c0714be8f82c1e.png',
         "job_icon": 'VPR',
         "level": '92',
         "content": 'Позволяет выполнить Uncoiled Twinfang или Uncoiled Twin Blood после выполнения Uncoiled Fury.',
      },
      // Trait 12
      "Trait 12": {
         "name": "Enhanced Serpent's Lineage",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/940beb1eff18a213456848f7d19318112040ea6e.png',
         "job_icon": 'VPR',
         "level": '96',
         "content": 'Позволяет накапливать пять Anguine Tribute в шкале Serpent Offerings.<br/>Кроме того, позволяет использовать Ouroboros, находясь под действием эффекта  Reawakened. ',
      },
      // Trait 13
      "Trait 13": {
         "name": "Serpent's Legacy",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f06c1aae31dc1d1324391254870d3b0b0a1402ea.png',
         "job_icon": 'VPR',
         "level": '100',
         "content": 'Позволяет выполнить First Legacy после First Generation, Second Legacy после Second Generation, Third Legacy после Third Generation и Fourth Legacy после Fourth Generation.',
      },
      // PVP Skill 01
      "PVP Skill 01": {
         "name": 'Steel Fangs',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/15337c3d71d35597218e0409e01081633652d23f.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.4 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 3,000.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 02
      "PVP Skill 02": {
         "name": "Hunter's Sting",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/dfeba44b89c0d27641837c677bb18ff423b34d40.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.4 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Удар, наносящий урон с силой атаки 4,000.<br/>Комбо умение: Steel Fangs<br/>Дополнительный эффект: накладывает эффект Hunter's Instinct<br/>Эффект Hunter's Instinct: увеличивает наносимый урон на 10%<br/>Продолжительность: 15 сек.<br/>Увеличивает продолжительность умения Hunter's Instinct на 15 сек., вплоть до 30 сек.<br/><br/>※Это умение нельзя поместить на хотбар.",
      },
      // PVP Skill 03
      "PVP Skill 03": {
         "name": 'Barbarous Bite',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a0c368a4f7ebb14a8cea1d1a344e0fc916081a3f.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.4 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Удар, наносящий урон с силой атаки 5,000.<br/>Комбо умение: Hunter's Sting<br/><br/>※Это умение нельзя поместить на хотбар.",
      },
      // PVP Skill 04
      "PVP Skill 04": {
         "name": 'Piercing Fangs',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e59eb58734d7a36986f811450ec692e626655bec.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.4 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 3,000.<br/>Комбо умение: Barbarous Bite<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 05
      "PVP Skill 05": {
         "name": "Swiftskin's Sting",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ad647f94d46f0cb3284648c436fa967aadf989a1.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.4 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 4,000.<br/>Комбо умение: Piercing Fangs<br/>Дополнительный эффект: накладывает эффект Swiftscaled<br/>Эффект Swiftscaled: уменьшает время восстановления боевых навыков на 20%<br/>Продолжительность: 15 сек.<br/>Увеличивает продолжительность умения Swiftscaled на 15 сек., вплоть до 30 сек.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 06
      "PVP Skill 06": {
         "name": 'Ravenous Bite',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/9df032ccdca8feaf3e7288acfd2dd3fdb68def20.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.4 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Удар, наносящий урон с силой атаки 5,000.<br/>Комбо умение: Swiftskin's Sting<br/><br/>※Это умение нельзя поместить на хотбар.",
      },
      // PVP Skill 07
      "PVP Skill 07": {
         "name": "Hunter's Snap",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1a805b094cbbf2d8cba34910f919e4ed395a2786.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Удар, наносящий урон с силой атаки 8,000.<br/>Дополнительный эффект: накладывает эффект Hunter's Instinct<br/>Эффект Hunter's Instinct: увеличивает наносимый урон на 10%<br/>Продолжительность: 15 сек.<br/>Увеличивает продолжительность умения Hunter's Instinct на 15 сек., вплоть до 30 сек.<br/>Максимум зарядов: 2<br/>Этот умение не имеет общего время восстановления с другими умениями.<br/><br/>※Умение меняется на Swiftskin's Coil после использования.",
      },
      // PVP Skill 08
      "PVP Skill 08": {
         "name": 'Uncoiled Fury',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c9bf1d09821271fbe0d0fa58a70b9460eb72680c.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '20y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 8,000 по цели и всем окружающим противникам.<br/>Сила атаки увеличивается на 50%, если атаковать только одну цель.<br/>Этот боевой навык не имеет общего время восстановления с другими умениями.',
      },
      // PVP Skill 09
      "PVP Skill 09": {
         "name": "Serpent's Tail",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c6b4fc449bc125b8df51956cd02b4721cd94e742.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Меняется на Death Rattle, Twinfang Bite, Twinblood Bite, Uncoiled Twinfang, First Legacy, Second Legacy, Third Legacy или Fourth Legacy при соблюдении требований к выполнению.',
      },
      // PVP Skill 10
      "PVP Skill 10": {
         "name": 'Slither',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1558fe95bce595ce0219cc4d24631d922c72bb81.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '20y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Рывок к выбранному противнику или сопартийцу.<br/>Дополнительный эффект: накладывает эффект Slither<br/>Эффект Slither: увеличивает урон, наносимый следующим боевым навыком, на 25%<br/>Продолжительность: 10 сек.<br/>Максимум стаков: 3<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.',
      },
      // PVP Skill 11
      "PVP Skill 11": {
         "name": 'Snake Scales',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e07af133f3aa974349eba0f4a938631964728177.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '30 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Накладывает эффект Hardened Scales, меняя Snake Scales на Backlash.<br/>Эффект Hardened Scales: снижает получаемый урон на 50% и дает иммунитет к эффектам оглушения (stun), сна (sleep), связывания (bind), тяжести (heavy), полу сна (half-asleep), безмолвия (silence), сна (sleep) и глубокой заморозки (deep freeze), а также к отбрасывающим и притягивающим эффектам.<br/>Продолжительность: 4 сек.<br/>Дополнительный эффект: накладывает на персонажа эффект Armored Scales, создающий барьер, предотвращающий получение урона, эквивалентного исцелению силой 6,000<br/>Продолжительность: 4 сек.<br/>Накладывает эффект Snake's Bane, когда барьер полностью поглощен.<br/>Если выждать 4 сек. или использовать умение Backlash, находясь под действием эффекта Hardened Scales, то атака с силой атаки 6,000 нанесет урон всем врагам в радиусе 5 ялмов.<br/>Дальность действия увеличивается на 15 ялмов, а сила атаки удваивается для врагов в радиусе 5 ялмов, находящихся под действием эффекта Snake's Bane.<br/>Невозможно двигаться под действием эффекта Hardened Scales.",
      },
      // PVP Skill 12
      "PVP Skill 12": {
         "name": 'Rattling Coil',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/147f8d74ae9ae599fa971b0ab6080a4690220c4f.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Сбрасывает время повторного использования умений Uncoiled Fury и Snake Scales.<br/>Время восстановления уменьшается на 10 сек. после убийства или получения ассиста.',
      },
      // PVP Skill 13
      "PVP Skill 13": {
         "name": "Swiftskin's Coil",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1842fa2852ed84e6b56cf7385caabd23312e47de.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.88 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Удар, наносящий урон с силой атаки 8,000.<br/>Комбо умение: Hunter's Snap<br/>Дополнительный эффект: накладывает эффект Swiftscaled<br/>Эффект Swiftscaled: уменьшает время восстановления боевых навыков на 20%.<br/>Продолжительность: 15 сек.<br/>Увеличивает продолжительность умения Swiftscaled на 15 сек., вплоть до 30 сек.<br/><br/>※Это умение нельзя поместить на хотбар.",
      },
      // PVP Skill 14
      "PVP Skill 14": {
         "name": 'First Generation',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/8f5e873cc3e905162527647b1156f0ae740b442e.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '1.92 сек.',
         "range": '5y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 5,000 по цели и всем окружающим противникам.<br/>Комбо умение: World-swallower<br/>Может быть использовано только под действием эффекта Reawakened.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 15
      "PVP Skill 15": {
         "name": 'Second Generation',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/af774179732ea48f9ce9c21b0e2a7f35d58330df.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '1.92 сек.',
         "range": '5y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 5,000 по цели и всем окружающим противникам.<br/>Комбо умение: First Generation<br/>Может быть использовано только под действием эффекта Reawakened.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 16
      "PVP Skill 16": {
         "name": 'Third Generation',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/6b755b35b9d30313dbae0a1bc153fe714668b790.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '1.92 сек.',
         "range": '5y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 5,000 по цели и всем окружающим противникам.<br/>Комбо умение: Second Generation<br/>Может быть использовано только под действием эффекта Reawakened.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 17
      "PVP Skill 17": {
         "name": 'Fourth Generation',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e71fea55bada906d1f752bdcb7f1cda184978532.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '1.92 сек.',
         "range": '5y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 5,000 по цели и всем окружающим противникам.<br/>Комбо умение: Third Generation<br/>Может быть использовано только под действием эффекта Reawakened.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 18
      "PVP Skill 18": {
         "name": 'Ouroboros',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e7971a6b1359d5fb936f931f07f362247061077c.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.88 сек.',
         "range": '5y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": "Удар, наносящий урон с силой атаки 10,000 по цели и всем окружающим противникам.<br/>Дополнительный эффект: увеличивает продолжительность эффектов Hunter's Instinct и Swiftscaled на 15 сек., вплоть до 30 сек.<br/>Может быть использовано только под действием эффекта Reawakened. Эффект пропадает после использования.<br/><br/>※Это умение нельзя поместить на хотбар.",
      },
      // PVP Skill 19
      "PVP Skill 19": {
         "name": 'Death Rattle',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/071377e0e1e3711012d7e0db2dc7b84b74ca9714.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 3,000.<br/>Игнорирует эффект Guard при нанесении урона.<br/>Дополнительный эффект: добавляет 3 секунды к накоплению шкалы лимит брейка (limit gauge).<br/>Может быть использовано только после успешного применения Barbarous Bite или Ravenous Bite.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 20
      "PVP Skill 20": {
         "name": 'Twinfang Bite',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e87afcce9e10bc1bf6fabb5db22d3e5644af2688.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Удар, наносящий урон с силой атаки 3,000.<br/>Игнорирует эффект Guard при нанесении урона.<br/>Дополнительный эффект: добавляет 3 секунды к накоплению шкалы лимит брейка (limit gauge).<br/>Может быть использовано только после успешного применения Hunter's Snap.<br/><br/>※Это умение нельзя поместить на хотбар.",
      },
      // PVP Skill 21
      "PVP Skill 21": {
         "name": 'Twinblood Bite',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/6bbb676b91db09777535491b7c2bbd236b693dcb.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": "Удар, наносящий урон с силой атаки 3,000.<br/>Игнорирует эффект Guard при нанесении урона.<br/>Дополнительный эффект: добавляет 3 секунды к накоплению шкалы лимит брейка (limit gauge).<br/>Может быть использовано только после успешного применения Swiftskin's Coil.<br/><br/>※Это умение нельзя поместить на хотбар.",
      },
      // PVP Skill 22
      "PVP Skill 22": {
         "name": 'Uncoiled Twinfang',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/da71d25a9c4ec075ee870a2ad5434f54d5ec141d.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '20y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 3,000 по цели и всем окружающим противникам.<br/>Игнорирует эффект Guard при нанесении урона.<br/>Дополнительный эффект: добавляет 3 секунды к накоплению шкалы лимит брейка (limit gauge).<br/>Может быть использовано только после успешного применения Uncoiled Fury.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 23
      "PVP Skill 23": {
         "name": 'First Legacy',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/3eded561d986ef0d88cbddc58a1203bd13392e12.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '5y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 3,000 по цели и всем окружающим противникам.<br/>Дополнительный эффект: добавляет 3 секунды к накоплению шкалы лимит брейка (limit gauge).<br/>Может быть использовано только после успешного применения First Generation.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 24
      "PVP Skill 24": {
         "name": 'Second Legacy',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/754ccf3d14880402121e03e9d6406fb938558a7b.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '5y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 3,000 по цели и всем окружающим противникам.<br/>Дополнительный эффект: добавляет 3 секунды к накоплению шкалы лимит брейка (limit gauge).<br/>Может быть использовано только после успешного применения Second Generation.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 25
      "PVP Skill 25": {
         "name": 'Third Legacy',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/9ab5ad729ec0e3b515a72f1f15dcdc64b159decd.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '5y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 3,000 по цели и всем окружающим противникам.<br/>Дополнительный эффект: добавляет 3 секунды к накоплению шкалы лимит брейка (limit gauge).<br/>Может быть использовано только после успешного применения Third Generation.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 26
      "PVP Skill 26": {
         "name": 'Fourth Legacy',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/609221c5f7e2ab86304dcc9db03fef237f414985.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '5y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 3,000 по цели и всем окружающим противникам.<br/>Дополнительный эффект: добавляет 3 секунды к накоплению шкалы лимит брейка (limit gauge).<br/>Может быть использовано только после успешного применения Fourth Generation.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 27
      "PVP Skill 27": {
         "name": 'Backlash',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/6c01119dc0bdb81236252001d0c655ad929feed1.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '5y',
         "content": "Удар, наносящий урон с силой атаки 6,000 по всем окружающим противникам.<br/>Дополнительный эффект: поглощает 50% нанесенного урона в виде HP<br/>Дальность действия увеличивается на 15 ялмов, а сила атаки удваивается для врагов в радиусе 5 ялмов, находящихся под действием эффекта Snake's Bane.<br/>Эффекты Hardened Scales и Snake's Bane исчезают после использования.<br/>Может быть использовано только под действием эффекта Hardened Scales.<br/><br/>※Это умение нельзя поместить на хотбар.",
      },
      // PVP Skill 28 LB
      "PVP Skill 28": {
         "name": 'World-swallower',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ed95dc742df4e9795e7c0a72e18eb72d0d00293a.png',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "range": '20y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": "Удар, наносящий урон в прыжке по цели и всем противникам поблизости с силой атаки 10,000.<br/>Дополнительный эффект: накладывает эффект Reawakened<br/>Продолжительность: 20 сек.<br/>Дополнительный эффект: поражает цель эффектом Noxious Gnash<br/>Эффект Noxious Gnash: увеличивает наносимый цели урон на 20%<br/>Продолжительность: 10 сек.<br/>Дополнительный эффект: тяжесть (heavy) +75%<br/>Продолжительность: 5 сек.<br/>Может быть выполнено только тогда, когда шкала лимит брейка (limit gauge) заполнена.<br/>Время зарядки шкалы: 90 сек.<br/><br/>※Dual Fang Combo меняется на First Generation под действием эффекта Reawakened.<br/>※ Hunter's Snap меняется на Ouroboros под действием эффекта Reawakened.",
      },
   };
   FILL_DB_VALUES(db);
   FILL_DB_SKILLS(db);
   FILL_DB_SKILLS_PASSIVE(db);
   FILL_DB_SKILLS_PVP(db);
   FILL_DB_SKILLS_MENU(db);
})();