(() =>{
   let db = {
      "PVE Update": `Последнее обновление: 27/06/2024`,
      "PVP Update": `Последнее обновление: 27/06/2024`,
      // PVE Skill 01
      "PVE Skill 01": {
         "name": 'Heavy Swing',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7a622f61949998a4bca402f5be90c0417bb02ac1.png',
         "job_icon": 'MRD',
         "level": '1',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 220.',
      },
      // PVE Skill 02
      "PVE Skill 02": {
         "name": 'Maim',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/39dae45d3a3309357462861dac9bb9b159030ea8.png',
         "job_icon": 'MRD',
         "level": '4',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 190.<br/>Комбо умение: Heavy Swing<br/>Сила в комбо: 340<br/>Комбо бонус: восполняет ресурс шкалы Beast Gauge на 10',
      },
      // PVE Skill 03
      "PVE Skill 03": {
         "name": 'Berserk',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c5a2c3896b62318a88ea9e48159ff7efd0962be1.png',
         "job_icon": 'MRD',
         "level": '6',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Накладывает 3 стака Berserk, боевые навыки под данным эффектом гарантированно наносят критический (critical) и прямой (direct) урон.<br/>Наносимый урон увеличивается под действием эффектов, повышающих вероятность критического (critical) и прямого (direct) урона.<br/>Продолжительность: 15 сек.<br/>Дополнительный эффект: увеличивает продолжительность эффекта Surging Tempest на 10 сек., вплоть до 60 сек.',
      },
      // PVE Skill 04
      "PVE Skill 04": {
         "name": 'Overpower',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/335c367406c5d952f11b8fd2dadaabb89e1cecbc.png',
         "job_icon": 'MRD',
         "level": '10',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 110 по всем окружающим противникам.',
      },
      // PVE Skill 05
      "PVE Skill 05": {
         "name": 'Defiance',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e6cc16e225417ce3c68cde5eb28df034f349d25d.png',
         "job_icon": 'MRD',
         "level": '10',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '2 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Танковая стойка. Значительно повышает генерацию уровня угрозы.<br/>Эффект спадает при повторном использовании.',
      },
      // PVE Skill 06
      "PVE Skill 06": {
         "name": 'Release Defiance',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1965311bb3fb720ba65258cb8f427bb986fa36c4.png',
         "job_icon": 'MRD',
         "level": '10',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Отменяет эффект Defiance.',
      },
      // PVE Skill 07
      "PVE Skill 07": {
         "name": 'Tomahawk',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/1b82df7a839/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/de42e4febcf54cf4af3189f9d2adfa4ca5975c25.png',
         "job_icon": 'MRD',
         "level": '15',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '20y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Дальний удар, наносящий урон с силой атаки 150.<br/>Дополнительный эффект: повышает уровень угрозы',
      },
      // PVE Skill 08
      "PVE Skill 08": {
         "name": "Storm's Path",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/14d9c5aa40a8f86aa13890aa9bedc9f6579ed289.png',
         "job_icon": 'MRD',
         "level": '26',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 200.<br/>Комбо умение: Maim<br/>Сила в комбо: 480<br/>Комбо бонус эффекта: восстанавливает HP персонажа<br/>Сила лечения: 250<br/>Комбо бонус: восполняет ресурс шкалы Beast Gauge на 20',
      },
      // PVE Skill 09
      "PVE Skill 09": {
         "name": 'Thrill of Battle',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/c082bce15bb/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/9412945d8b5a61fbb118907bd33046110ff83434.png',
         "job_icon": 'MRD',
         "level": '30',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '90 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Увеличивает максимальное количество HP на 20% и восстанавливает такое же количество при применении умения.<br/>Дополнительный эффект: увеличивает эффект получаемого исцеления на 20%<br/>Продолжительность: 10 сек.',
      },
      // PVE Skill 10
      "PVE Skill 10": {
         "name": 'Inner Beast',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/0a4aa18f8ce/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c72ea7de2c06ad8a03bc55598297aba5bf00b0b6.png',
         "job_icon": 'WAR',
         "level": '35',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 330.<br/>Стоимость: 50 Beast Gauge',
      },
      // PVE Skill 11
      "PVE Skill 11": {
         "name": 'Vengeance',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/72a939d0010304553c5b88fae576f5a25f453e10.png',
         "job_icon": 'MRD',
         "level": '38',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Снижает получаемый урон на 30% и наносит урон с силой 55 каждый раз, когда персонаж получаете физический урон.<br/>Продолжительность: 15 сек.',
      },
      // PVE Skill 12
      "PVE Skill 12": {
         "name": 'Mythril Tempest',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/9d79c446b7f/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b9efeaf988763dc594fc2497b603cfda4253064f.png',
         "job_icon": 'WAR',
         "level": '40',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 100 по всем окружающим противникам.<br/>Комбо умение: Overpower<br/>Сила в комбо: 140<br/>Комбо бонус: накладывает эффект Surging Tempest, увеличивая наносимый урон на 10%<br/>Продолжительность: 30 сек.<br/>Увеличивает продолжительность эффекта Surging Tempest на 30 сек., вплоть до 60 сек.<br/>Комбо бонус: восполняет ресурс шкалы Beast Gauge на 20',
      },
      // PVE Skill 13
      "PVE Skill 13": {
         "name": 'Holmgang',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/91b5673b1dfb08c80d7b8fc2bdc936f46906317f.png',
         "job_icon": 'MRD',
         "level": '42',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '240 сек.',
         "range": '6y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Под действием эффекта Holmgang не позволяет большинству атак опустить HP персонажа ниже 1.<br/>Продолжительность: 10 сек.<br/>Останавливает передвижение выбранной цели цепями.',
      },
      // PVE Skill 14
      "PVE Skill 14": {
         "name": 'Steel Cyclone',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/f9ca807f2c9/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/caee561eee94d7ecc27ac396982ebe39df5c6893.png',
         "job_icon": 'WAR',
         "level": '45',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 160 по всем окружающим противникам.<br/>Стоимость: 50 Beast Gauge',
      },
      // PVE Skill 15
      "PVE Skill 15": {
         "name": "Storm's Eye",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/05faebea82787675c2331bb4ddb7778b70ab53f0.png',
         "job_icon": 'MRD',
         "level": '50',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 200.<br/>Комбо умение: Maim<br/>Сила в комбо: 480<br/>Комбо бонус: накладывает эффект Surging Tempest, увеличивающий наносимый урон на 10%<br/>Продолжительность: 30 сек.<br/>Увеличивает продолжительность эффекта Surging Tempest на 30 сек., вплоть до 60 секунд.<br/>Комбо бонус: восполняет ресурс шкалы Beast Gauge на 10',
      },
      // PVE Skill 16
      "PVE Skill 16": {
         "name": 'Infuriate',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/3bf7d4d27ba/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ecd32b95358ef9b2756b005daef73afdde9fab80.png',
         "job_icon": 'WAR',
         "level": '50',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Восполняет ресурс шкалы Beast Gauge на 50.<br/>Дополнительный эффект: накладывает эффект Nascent Chaos<br/>Продолжительность: 30 сек.<br/>Nascent Chaos Effect: когда шкала Beast Gauge равна 50 или больше, Decimate меняется на Chaotic Cyclone и Fell Cleave на Inner Chaos<br/>Максимум зарядов: 2<br/>Может быть использовано только в бою.',
      },
      // PVE Skill 17
      "PVE Skill 17": {
         "name": 'Fell Cleave',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/3a541cff74e/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5d146522a8fc94788d96043b93034176eab59a10.png',
         "job_icon": 'WAR',
         "level": '54',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 580.<br/>Стоимость: 50 Beast Gauge<br/><br/>※Умение меняется на Inner Chaos под действием эффекта Nascent Chaos.',
      },
      // PVE Skill 18
      "PVE Skill 18": {
         "name": 'Raw Intuition',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/4e064a2888d/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1d9a63cc19bbec0e2f99d192040c26e306e2e675.png',
         "job_icon": 'WAR',
         "level": '56',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '25 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Снижает получаемый урон на 10%.<br/>Продолжительность: 6 сек.<br/>Дополнительный эффект: восстанавливает HP при каждом успешном попадании боевым навыком<br/>Сила лечения: 400<br/>Имеет общее время восстановления с умением Nascent Flash.',
      },
      // PVE Skill 19
      "PVE Skill 19": {
         "name": 'Equilibrium',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/447e54738f5/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b549a16dfa8cbde55ec19b81bad325c5480d98e2.png',
         "job_icon": 'WAR',
         "level": '58',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Восстанавливает HP персонажа.<br/>Сила лечения: 1,200<br/>Дополнительный эффект: постепенно восстанавливает HP<br/>Сила лечения: 200<br/>Продолжительность: 15 сек.',
      },
      // PVE Skill 20
      "PVE Skill 20": {
         "name": 'Decimate',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/6079bd110a1/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f4fdd09a56a0b83a0cbe11a83f706dc0fb6781f5.png',
         "job_icon": 'WAR',
         "level": '60',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 180 по всем окружающим противникам.<br/>Стоимость: 50 Beast Gauge<br/><br/>※Умение меняется на Chaotic Cyclone под действием эффекта Nascent Chaos.',
      },
      // PVE Skill 21
      "PVE Skill 21": {
         "name": 'Onslaught',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d0a1dad0fa6c8294ceb31b6879c765a02498e3fb.png',
         "job_icon": 'WAR',
         "level": '62',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '30 сек.',
         "range": '20y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Рывок к цели, наносящий урон с силой атаки 150.<br/>Максимум зарядов: 3<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.',
      },
      // PVE Skill 22
      "PVE Skill 22": {
         "name": 'Upheaval',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ba0b3b08d9b2ef02636e06148bc739680390fdd3.png',
         "job_icon": 'WAR',
         "level": '64',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '30 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 400.<br/>Имеет общее время восстановления с умением Orogeny.',
      },
      // PVE Skill 23
      "PVE Skill 23": {
         "name": 'Shake It Off',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f71e2c46512c1e937c0ff316be668d853869c637.png',
         "job_icon": 'WAR',
         "level": '68',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '90 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '30y',
         "content": 'Создает барьер вокруг персонажа и всех ближайших саппортийцев, который поглощает получаемый урон в количестве 15% от максимального HP цели.<br/>Снимает эффекты Thrill of Battle, Damnation и Bloodwhetting, увеличивая прочность барьера на 2% за каждый снятый эффект.<br/>Продолжительность: 30 сек.<br/>Дополнительный эффект: постепенно восстанавливает HP<br/>Сила лечения: 100<br/>Продолжительность: 15 сек.<br/>Дополнительный эффект: восстанавливает HP цели<br/>Сила лечения: 300',
      },
      // PVE Skill 24
      "PVE Skill 24": {
         "name": 'Inner Release',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/02aed005346/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/809168ffb23f67e3d4b720b3caa4a0a1773fea4c.png',
         "job_icon": 'WAR',
         "level": '70',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Накладывает 3 заряда эффекта Inner Release, каждый из которых позволяет использовать Fell Cleave или Decimate без затрат и гарантирует нанесение критического (critical) и прямого (direct) урона.<br/>Наносимый урон увеличивается под действием эффектов, повышающего вероятность критического (critical) и прямого (direct) урона.<br/>Дополнительный эффект: накладывает эффект Inner Strength<br/>Эффект Inner Strength: на время действия умения дает иммунитет к эффектам оглушения (stun), сна (sleep), связывания (bind), тяжести (heavy), также защищает от большинства эффектов отталкивания и притягивания на время действия умения<br/>Продолжительность: 15 сек.<br/>Дополнительный эффект: увеличивает продолжительность эффекта Surging Tempest на 10 сек., вплоть до 60 сек.<br/>Дополнительный эффект: накладывает эффект Primal Rend Ready<br/>Продолжительность: 30 сек.<br/>Дополнительный эффект: при успешном использовании Fell Cleave или Decimate дает стак Burgeoning Fury, максимум 3<br/>При максимальном количестве стаков эффект трансформируется в Wrathful, заменяющий Inner Release на Primal Wrath.',
      },
      // PVE Skill 25
      "PVE Skill 25": {
         "name": 'Chaotic Cyclone',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a5ea711252d08de0f9fd2e65313690c19b9f8773.png',
         "job_icon": 'WAR',
         "level": '72',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий критический (critical) прямой (direct) урон с силой атаки 300 по всем окружающим противникам.<br/>Наносимый урон увеличивается под действием эффектов, повышающего вероятность критического (critical) и прямого (direct) урона.<br/>Дополнительный эффект: снижает время восстановления умения Infuriate на 5 сек.<br/>Стоимость: 50 Beast Gauge<br/>Умение может быть использовано только под действием эффекта Nascent Chaos. Эффект пропадает после использования.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Decimate меняется на Chaotic Cyclone при соблюдении требований к выполнению.',
      },
      // PVE Skill 26
      "PVE Skill 26": {
         "name": 'Nascent Flash',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/0a4356e3696cea8f2c8cea9be200e773da6c7caa.png',
         "job_icon": 'WAR',
         "level": '76',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '25 сек.',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Накладывает эффект Nascent Flash на персонажа и эффект Nascent Glint на выбранного сопартийца.<br/>Эффект Nascent Flash: восстанавливает HP персонажа при каждом попадании боевого навыка<br/>Сила лечения: 400<br/>Эффект Nascent Glint: восстанавливает HP в размере 100% от количества, восстановленного под эффектом Nascent Flash, и снижает получаемый урон на 10%<br/>Продолжительность: 8 сек.<br/>Дополнительный эффект: накладывает на выбранного сопартийца эффект Stem the Flow, снижая получаемый урон на 10%<br/>Продолжительность: 4 сек.<br/>Дополнительный эффект: накладывает на выбранного сопартийца эффект Stem the Tide, предотвращая получение урона, равному силой лечения 400<br/>Продолжительность: 20 сек.<br/>Имеет общее время восстановления с умением Bloodwhetting.',
      },
      // PVE Skill 27
      "PVE Skill 27": {
         "name": 'Inner Chaos',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/70a629706b7fa0dc566d988dbf32da064d0c3458.png',
         "job_icon": 'WAR',
         "level": '80',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '3y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий критический (critical) и прямой (direct) урон с силой атаки 660.<br/>Наносимый урон увеличивается под действием эффектов, повышающего вероятность критического (critical) и прямого (direct) урона.<br/>Дополнительный эффект: снижает время восстановления умения Infuriate на 5 сек.<br/>Стоимость: 50 Beast Gauge<br/>Умение может быть использовано только под действием эффекта Nascent Chaos. Эффект пропадает после использования.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Fell Cleave меняется на Inner Chaos при соблюдении требований к выполнению.',
      },
      // PVE Skill 28
      "PVE Skill 28": {
         "name": 'Bloodwhetting',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/439c677f7cd4da8e9be9b92245865d2eb1ebceca.png',
         "job_icon": 'WAR',
         "level": '82',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '25 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Уменьшает получаемый урон на 10%.<br/>Продолжительность: 8 сек.<br/>Дополнительный эффект: восстанавливает HP персонажа при каждом попадании боевого навыка<br/>Сила лечения: 400<br/>Дополнительные эффекты: накладывает эффект Stem the Flow<br/>Эффект Stem the Flow: снижает получаемый урон на 10%<br/>Продолжительность: 4 сек.<br/>Дополнительный эффект: накладывает эффект Stem the Tide<br/>Эффект Stem the Tide: создает вокруг персонажа барьер, поглощающий урон, равный силе лечения 400<br/>Продолжительность: 20 сек.<br/>Имеет общее время восстановления с умением Nascent Flash.',
      },
      // PVE Skill 29
      "PVE Skill 29": {
         "name": 'Orogeny',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a746763655d8eb64a4f2577f4a19d445866aa8e5.png',
         "job_icon": 'WAR',
         "level": '86',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '30 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 150 по всем окружающим противникам.<br/>Имеет общее время восстановления с умением Upheaval.',
      },
      // PVE Skill 30
      "PVE Skill 30": {
         "name": 'Primal Rend',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e6ccdb7bd1a86153af07f02f06583113ac86c8eb.png',
         "job_icon": 'WAR',
         "level": '90',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "range": '20y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Прыжок к цели, наносящий критический (critical) и прямой (direct) урон по цели и по всем окружающим противникам с силой атаки 700 по первому и на 70% по всем оставшимся.<br/>Наносимый урон увеличивается под действием эффектов, повышающего вероятность критического (critical) и прямого (direct) урона.<br/>Дополнительный эффект: накладывает эффект Primal Ruination Ready<br/>Продолжительность: 30 сек.<br/>Возможно использовать только под действием эффекта Primal Rend Ready, наложенного Inner Release.<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.',
      },
      // PVE Skill 31 NEW
      "PVE Skill 31": {
         "name": 'Damnation',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a4f5302a169e6ee5667e03976e7455aacc394604.png',
         "job_icon": 'WAR',
         "level": '92',
         "classification": 'Ability',
         "cast": 'Instant',
         "recast": '120 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Уменьшает получаемый урон на 40% и наносит атаку с силой 55 каждый раз, когда персонаж получает физический урон.<br/>Продолжительность: 15 сек.<br/>Дополнительный эффект: накладывает эффект Primeval Impulse по истечении срока действия эффекта<br/>Эффект Salvation: эффект периодического восстановления<br/>Сила лечения: 400<br/>Продолжительность: 15 сек.',
      },
      // PVE Skill 32 NEW
      "PVE Skill 32": {
         "name": 'Primal Wrath',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e9e68562064da9f0787632d983da080105fc2389.png',
         "job_icon": 'WAR',
         "level": '96',
         "classification": 'Ability',
         "cast": 'Instant',
         "recast": '1 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон по всем окружающим противникам с силой атаки 700 по первому и на 70% по всем оставшимся.<br/>Может быть использован только под действием эффекта Wrathful.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Inner Release меняется на  Primal Wrath при соблюдении требований к выполнению.',
      },
      // PVE Skill 33 NEW
      "PVE Skill 33": {
         "name": 'Primal Ruination',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/5eb4d961217f31467ecf479d45f89767f5f9c0d7.png',
         "job_icon": 'WAR',
         "level": '100',
         "classification": 'Weaponskill',
         "cast": 'Instant',
         "recast": '2.5 сек.',
         "range": '3y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий критический (critical) прямой (direct) урон по цели и по всем окружающим противникам с силой атаки 740 по первому и на 70% по всем оставшимся.<br/>Наносимый урон увеличивается под действием эффектов, повышающего вероятность критического (critical) и прямого (direct) урона.<br/>Возможно использовать только под действием эффекта Primal Ruination Ready.<br/><br/>※Это умение нельзя поместить на хотбар.<br/>※Primal Rend меняется на Primal Ruination при соблюдении требований к выполнению.',
      },
      // Trait 01
      "Trait 01": {
         "name": 'Tank Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b6414caac03c831ec90c34e501e444031d44003c.png',
         "job_icon": 'MRD',
         "level": '1',
         "content": 'Снижает получаемый урон на 20%. Также персонаж получает бонус к максимальному количеству HP в зависимости от значения выносливости (vitality) и бонус к урону в зависимости от значения силы (strength).',
      },
      // Trait 02
      "Trait 02": {
         "name": 'The Beast Within',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/0a4aa18f8ce/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1d10b3734c0ac46bf83e4b6dadeb2776fcbab0be.png',
         "job_icon": 'WAR',
         "level": '35',
         "content": `Восполняет ресурс шкалы Beast Gauge при использовании умения Maim или Storm's Path в комбо.`,
      },
      // Trait 03
      "Trait 03": {
         "name": 'Inner Beast Mastery',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/3a541cff74e/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/0348d86d64f3ad4c3903ee9eff727f49929d05c8.png',
         "job_icon": 'WAR',
         "level": '54',
         "content": 'Улучшает умение Inner Beast до Fell Cleave.',
      },
      // Trait 04
      "Trait 04": {
         "name": 'Steel Cyclone Mastery',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/6079bd110a1/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2ac33bbd12953a4d539f46bf5118f8e4529ca698.png',
         "job_icon": 'WAR',
         "level": '60',
         "content": 'Улучшает умение Steel Cyclone до Decimate.',
      },
      // Trait 05
      "Trait 05": {
         "name": 'Enhanced Infuriate',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1a5dae6cb0b5d7b7158bfa730936a4bac168de52.png',
         "job_icon": 'WAR',
         "level": '66',
         "content": 'Уменьшает время восстановления умения Infuriate на 5 секунд после использования Fell Cleave или Decimate по большинству целей.',
      },
      // Trait 06
      "Trait 06": {
         "name": 'Berserk Mastery',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/02aed005346/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c31fbc72ed1bf1ab02e77a17a42cd6f2327df8e2.png',
         "job_icon": 'WAR',
         "level": '70',
         "content": 'Улучшает умение Berserk до Inner Release.',
      },
      // Trait 07
      "Trait 07": {
         "name": 'Nascent Chaos',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/825adb90166b2a7a0b9ccc5f399392d895337565.png',
         "job_icon": 'WAR',
         "level": '72',
         "content": 'Infuriate накладывает эффект Nascent Chaos, улучшая Decimate до Chaotic Cyclone, когад шкала Beast Gauge равна 50 или выше. При достижении 80 уровня, эффект Nascent Chaos улучшает Fell Cleave до Inner Chaos.<br/>Продолжительность: 30 сек.',
      },
      // Trait 08
      "Trait 08": {
         "name": 'Mastering the Beast',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/840b30e9758509963bad58c3f9bee151efab466d.png',
         "job_icon": 'WAR',
         "level": '74',
         "content": 'Накапливает Beast Gauge при использовании Mythril Tempest в комбо.',
      },
      // Trait 09
      "Trait 09": {
         "name": 'Enhanced Shake It Off',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/57bdf03782fbb632a57f9eeae29c7b7a995f2392.png',
         "job_icon": 'WAR',
         "level": '76',
         "content": 'Добавляет эффект лечения к умению Shake It Off.<br/>Сила лечения: 300',
      },
      // Trait 10
      "Trait 10": {
         "name": 'Enhanced Thrill of Battle',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/52be11902b062536721be4257c7d5bcb35f8bc57.png',
         "job_icon": 'WAR',
         "level": '78',
         "content": 'Добавляет к умению Thrill of Battle эффект, увеличивающий количество восстанавливаемого HP на 20%.',
      },
      // Trait 11
      "Trait 11": {
         "name": 'Raw Intuition Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1244d605cbfb73e04b30ff6d51e918a069a4da83.png',
         "job_icon": 'WAR',
         "level": '82',
         "content": 'Улучшает умение Raw Intuition до Bloodwhetting.',
      },
      // Trait 12
      "Trait 12": {
         "name": 'Enhanced Nascent Flash',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/dad6571de24248dac73a723d1a9359f95dca8a99.png',
         "job_icon": 'WAR',
         "level": '82',
         "content": 'Увеличивает продолжительность действий эффекта Nascent Flash и эффекта Nascent Glint до 8 секунд.<br/>Накладывает на цель эффект Stem the Flow, снижающий получаемый урон на 10%.<br/>Продолжительность: 4 сек.<br/>Накладывает на цель Stem the Tide, предотвращая получение урона, равное силе лечения 400.<br/>Продолжительность: 20 сек.',
      },
      // Trait 13
      "Trait 13": {
         "name": 'Enhanced Equilibrium',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/492bd21d22da975f17ad7a993a71f36bc201a32f.png',
         "job_icon": 'WAR',
         "level": '84',
         "content": 'Накладывает на персонажа эффект периодического восстановления HP.<br/>Сила лечения: 200<br/>Продолжительность: 15 сек.',
      },
      // Trait 14
      "Trait 14": {
         "name": 'Melee Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/bc58b07072e258883e9e584c4e45355d092da661.png',
         "job_icon": 'WAR',
         "level": '84',
         "content": `Увеличивает силу атаки Heavy Swing до 200, Maim до 150, Storm's Path до 160 и Storm's Eye до 160.`,
      },
      // Trait 15
      "Trait 15": {
         "name": 'Enhanced Onslaught',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/9e25aa37d3494d7045013593b3af7793616dc6d7.png',
         "job_icon": 'WAR',
         "level": '88',
         "content": 'Добавляет третий заряд для умения Onslaught.',
      },
      // Trait 16 NEW
      "Trait 16": {
         "name": 'Vengeance Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/560fe59ae6180b6e09d564c3ed9b04247280a82f.png',
         "job_icon": 'WAR',
         "level": '92',
         "content": 'Улучшает умение Vengeance до Damnation.',
      },
      // Trait 17 NEW
      "Trait 17": {
         "name": 'Melee Mastery II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b60557edca3b093463f0f0c0c04dc3895855e9f8.png',
         "job_icon": 'WAR',
         "level": '94',
         "content": "Увеличивает силу атаки умениям Heavy Swing до 220, Maim до 190, Storm's Path до 200, Storm's Eye до 200 и Fell Cleave до 580.",
      },
      // Trait 18 NEW
      "Trait 18": {
         "name": 'Enhanced Inner Release',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/58c4546dabdcda9d3e09834f0660b863d77842ec.png',
         "job_icon": 'WAR',
         "level": '96',
         "content": 'Дает стак Burgeoning Fury после использования Fell Cleave или Decimate, находясь под эффектом Inner Release.<br/>Продолжительность: 30 сек.<br/>Максимум стаков: 3<br/>При максимальном количестве стаков эффект трансформируется в Wrathful, заменяющий Inner Release на Primal Wrath.',
      },
      // Trait 19 NEW
      "Trait 19": {
         "name": 'Enhanced Primal Rend',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f6f313152cbf847258f0d7a0a1a5d0d2d40914ca.png',
         "job_icon": 'WAR',
         "level": '100',
         "content": 'Накладывает эффект Primal Ruination Ready после использования Primal Rend.<br/>Продолжительность: 30 сек.',
      },
      // PVP Skill 01
      "PVP Skill 01": {
         "name": 'Heavy Swing',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/620b56980ee1b82942bf0b05b356663531ab13b0.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.4 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 3,000.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 02
      "PVP Skill 02": {
         "name": 'Maim',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/da21ae7d5c8b75f6b24205cd2f263d53c0fc3c17.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.4 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 4,000.<br/>Комбо умение: Heavy Swing<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 03
      "PVP Skill 03": {
         "name": "Storm's Path",
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/9ade61d55ebe1ced213ac5f2e18217d1a8cf3efc.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.4 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 5,000.<br/>Комбо умение: Maim<br/>Дополнительный эффект: поглощает 100% нанесенного урона в виде HP<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 04
      "PVP Skill 04": {
         "name": 'Primal Rend',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7dcf0639ab9919a5e4a6e94597813727101b5711.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '20y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон в прыжке по цели и всем противникам поблизости с силой атаки 8,000.<br/>Сила атаки Inner Release: 16,000<br/>Дополнительный эффект: оглушение (stun)<br/>Продолжительность: 2 сек.<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.<br/>Этот боевой навык не имеет общего время восстановления с другими умениями.',
      },
      // PVP Skill 05
      "PVP Skill 05": {
         "name": 'Onslaught',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/90e5bf247f1527c6f9b417b79014131b75657aa8.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "range": '20y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Рывок к цели, наносящий урон с силой атаки 500.<br/>Сила атаки увеличивается до 5,000, когда значение HP близко к максимальному.<br/>Расходует 10% текущего HP при использовании.<br/>Дополнительный эффект: увеличивает урон получаемый целью на 10%<br/>Продолжительность: 10 сек.<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.',
      },
      // PVP Skill 06
      "PVP Skill 06": {
         "name": 'Orogeny',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/0c1021aeac66c93d12f000d6c469ebde0fad356d.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 1,000 по всем окружающим противникам.<br/>Сила атаки увеличивается до 10,000, когда значение HP близко к максимальному.<br/>Расходует 10% текущего HP при использовании.<br/>Дополнительный эффект: снижает наносимый целью урон на 10%<br/>Продолжительность: 10 сек.',
      },
      // PVP Skill 07
      "PVP Skill 07": {
         "name": 'Blota',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c0a4d063fb602de6211f217192680b05d2d64698.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '10y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Мгновенно притягивает цель к персонажу.<br/>Дополнительный эффект: тяжесть (heavy) +75%<br/>Продолжительность: 3 сек.',
      },
      // PVP Skill 08
      "PVP Skill 08": {
         "name": 'Bloodwhetting',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/791304fb065ed36949c9ae74ae1a6a8b8e649948.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Накладывает эффекты Bloodwhetting, Stem the Tide и Nascent Chaos.<br/>Эффект Bloodwhetting: восстанавливает HP в размере 100% от наносимого урона<br/>Продолжительность: 10 сек.<br/>Эффект Stem the Tide: создает вокруг персонажа барьер, поглощающий урон, в размере 10% от максимального HP персонажа<br/>Продолжительность: 10 сек.<br/>Эффект Nascent Chaos: Bloodwhetting меняется на Chaotic Cyclone<br/>Продолжительность: 10 сек.',
      },
      // PVP Skill 09
      "PVP Skill 09": {
         "name": 'Fell Cleave',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2d0f3dd8777837d2ca5c617eac4cac2950ebec44.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.4 сек.',
         "range": '5y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон с силой атаки 12,000.<br/>Может быть использовано только под действием эффекта Inner Release.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 10
      "PVP Skill 10": {
         "name": 'Chaotic Cyclone',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/9eece9bd72707dba5fc6c4deae34d27f47b3312a.png',
         "classification": 'Боевой навык',
         "cast": 'Мгновенная',
         "recast": '2.4 сек.',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий урон с силой атаки 8, 000 по всем окружающим противникам.<br/>Сила атаки Inner Release: 16,000<br/>Может быть использовано только под действием эффекта Nascent Chaos.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 11
      "PVP Skill 11": {
         "name": 'Primal Scream',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/6bcfcb1fa456db189719af5c6e06d82f24c40191.png',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "range": '12y',
         "radius_img": 'R4',
         "radius": '12y',
         "content": `Персонаж издает кровавый крик в конусе перед собой, лишая противников возможности использовать Guard.<br/>Продолжительность: 15 сек.<br/>Дополнительный эффект: накладывает эффекты Inner Release и Thrill of Battle<br/>Эффект Inner Release: увеличивает силу атаки Primal Rend и Chaotic Cyclone, повышает скорость передвижения на 25% и дает иммунитет к эффектам оглушения (stun), сна (sleep), связывания (bind), тяжести (heavy), полу сна (half-sleep), сна (sleep) и глубокой заморозки (deep freeze), а также к отбрасывающим и притягивающим эффектам<br/>Продолжительность: 15 сек.<br/>Невозможно использовать Guard, находясь под действием эффекта Inner Release<br/>Эффект Thrill of Battle: увеличивает максимальное количество HP на 20% и восстанавливает их в том же количестве<br/>Продолжительность: 30 сек.<br/>Может быть использовано только тогда, когда шкала лимит брейка (limit gauge) заполнена.<br/>Время зарядки шкалы: 90 сек.<br/><br/>※Combo Storm's Path меняется на Fell Cleave под действием эффекта Inner Release.`,
      },
   };
   FILL_DB_VALUES(db);
   FILL_DB_SKILLS(db);
   FILL_DB_SKILLS_PASSIVE(db);
   FILL_DB_SKILLS_PVP(db);
   FILL_DB_SKILLS_MENU(db);
})();