(() =>{
   let db = {
      "PVE Update": `Последнее обновление: 27/06/2024`,
      "PVP Update": `Последнее обновление: 27/06/2024`,
      // PVE Skill 01
      "PVE Skill 01": {
         "name": 'Stone',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/002aa233f5d570b0e27d55ce38b57a6b06b7cc69.png',
         "job_icon": 'CNJ',
         "level": '1',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '200 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон землей с силой атаки 140.',
      },
      // PVE Skill 02
      "PVE Skill 02": {
         "name": 'Cure',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a2d0e0ed56915f523e8a7326bbdd09eff0534eda.png',
         "job_icon": 'CNJ',
         "level": '2',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Восстанавливает HP цели.<br/>Сила лечения: 500<br/>Дополнительный эффект: шанс 15%, что следующее применение Cure II не потребует MP<br/>Продолжительность: 15 сек.',
      },
      // PVE Skill 03
      "PVE Skill 03": {
         "name": 'Aero',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/78107cd063a81b78b99eb7cb5da15f2bec403c70.png',
         "job_icon": 'CNJ',
         "level": '4',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '200 MP',
         "range": '20y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон ветром с силой атаки 50.<br/>Дополнительный эффект: периодический урон ветром<br/>Сила атаки: 30<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 04
      "PVE Skill 04": {
         "name": 'Medica',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/6c5fd075bab7c063aef743a1de5e36958354b42b.png',
         "job_icon": 'CNJ',
         "level": '10',
         "classification": 'Заклинание',
         "cast": '2 сек.',
         "recast": '2.5 сек.',
         "cost": '900 MP',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '15y',
         "content": 'Восстанавливает HP персонажа и всех ближайших сопартийцев.<br/>Сила лечения: 400',
      },
      // PVE Skill 05
      "PVE Skill 05": {
         "name": 'Raise',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/34bdc3ad370b701a106f32daa68e73055ab72331.png',
         "job_icon": 'CNJ',
         "level": '12',
         "classification": 'Заклинание',
         "cast": '8 сек.',
         "recast": '2.5 сек.',
         "cost": '2400 MP',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Воскрешает цель, накладывая эффект слабости (weakeness).',
      },
      // PVE Skill 06
      "PVE Skill 06": {
         "name": 'Stone II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ce8e52e199a7d9e548537bc77197f4d7965dea58.png',
         "job_icon": 'CNJ',
         "level": '18',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '200 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон землей с силой атаки 190.',
      },
      // PVE Skill 07
      "PVE Skill 07": {
         "name": 'Cure II',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/a02c1c29571/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a70a8e3dcb347c11047f00945f9435687f21f06d.png',
         "job_icon": 'CNJ',
         "level": '30',
         "classification": 'Заклинание',
         "cast": '2 сек.',
         "recast": '2.5 сек.',
         "cost": '1000 MP',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Восстанавливает HP цели.<br/>Сила лечения: 800',
      },
      // PVE Skill 08
      "PVE Skill 08": {
         "name": 'Presence of Mind',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/e3eba90aefc/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7be14bf07b21fa5c78cd7f7891279704da6cadb9.png',
         "job_icon": 'WHM',
         "level": '30',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Снижает время выполнения и время восстановления заклинаний, а также задержку между авто атаками на 20%.<br/>Продолжительность: 15 сек.<br/>Дополнительный эффект: накладывает 3 стака эффекта Sacred Sight<br/>Продолжительность: 30 сек',
      },
      // PVE Skill 09
      "PVE Skill 09": {
         "name": 'Regen',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/309e3e7e609/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/53bb0b4fc881c4c06d64c915864968cced6c6201.png',
         "job_icon": 'WHM',
         "level": '35',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Накладывает на цель эффект периодического лечения.<br/>Сила лечения: 250<br/>Продолжительность: 18 сек.',
      },
      // PVE Skill 10
      "PVE Skill 10": {
         "name": 'Cure III',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/8891efb6fde/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/33c3597ee1004e364a6331f732f077666e798acd.png',
         "job_icon": 'WHM',
         "level": '40',
         "classification": 'Заклинание',
         "cast": '2 сек.',
         "recast": '2.5 сек.',
         "cost": '1500 MP',
         "range": '30y',
         "radius_img": 'R2',
         "radius": '10y',
         "content": 'Восстанавливает HP цели и всех ближайших сопартийцев вокруг.<br/>Сила лечения: 600',
      },
      // PVE Skill 11 NEW
      "PVE Skill 11": {
         "name": 'Aetherial Shift',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/d69b1e0884f3f4edac543210cd9b42d74c2b3f25.png',
         "job_icon": 'WHM',
         "level": '40',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Быстрый рывок на 15 ялмов вперед.<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.',
      },
      // PVE Skill 12
      "PVE Skill 12": {
         "name": 'Holy',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/20e64bc5c59/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/bb161bfc68766590d81cb1f7d6049711c949039b.png',
         "job_icon": 'WHM',
         "level": '45',
         "classification": 'Заклинание',
         "cast": '2.5 сек.',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '8y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 140 по всем окружающим противникам.<br/>Дополнительный эффект: оглушение (stun)<br/>Продолжительность: 4 сек.',
      },
      // PVE Skill 13
      "PVE Skill 13": {
         "name": 'Aero II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7e4202353c63451702e9944dc93551a18951efcf.png',
         "job_icon": 'CNJ',
         "level": '46',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '200 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон ветром с силой атаки 50.<br/>Дополнительный эффект: периодический урон ветром<br/>Сила атаки: 50<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 14
      "PVE Skill 14": {
         "name": 'Medica II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/530234ed64e2b5b5aaacf978a90d87932734272f.png',
         "job_icon": 'CNJ',
         "level": '50',
         "classification": 'Заклинание',
         "cast": '2 сек.',
         "recast": '2.5 сек.',
         "cost": '1000 MP',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '20y',
         "content": 'Восстанавливает HP персонажа и всех ближайших сопартийцев.<br/>Сила лечения: 250<br/>Дополнительный эффект: эффект периодического лечения (regen).<br/>Сила лечения: 150<br/>Продолжительность: 15 сек.',
      },
      // PVE Skill 15
      "PVE Skill 15": {
         "name": 'Benediction',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/6ea2ad6309a/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/44e09756739b6b8924b82471572e7103ac5ca1fb.png',
         "job_icon": 'WHM',
         "level": '50',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '180 сек.',
         "cost": '-',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Полностью восстанавливает HP цели.',
      },
      // PVE Skill 16
      "PVE Skill 16": {
         "name": 'Afflatus Solace',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a9c7b172b8c82aaa311a578fe3b42f5f30266e93.png',
         "job_icon": 'WHM',
         "level": '52',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Восстанавливает HP цели.<br/>Сила лечения: 800<br/>Дополнительный эффект: накапливает Blood Lily<br/>Стоимость: 1 Lily Healing Gauge',
      },
      // PVE Skill 17
      "PVE Skill 17": {
         "name": 'Asylum',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/a8b01c03e71/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/cf3242dc922e88211cb5b2c4aa67f9ae79fb88fb.png',
         "job_icon": 'WHM',
         "level": '52',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '90 сек.',
         "cost": '-',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '15y',
         "content": 'Создает в указанной области купол целителя, восстанавливащий HP персонажу и сопартийцам, находящимся внутри.<br/>Сила лечения: 100<br/>Продолжительность: 24 сек.<br/>Дополнительный эффект: увеличивает силу лечебных умений, применнёных на всех сопартийцев в области действия, на 10%',
      },
      // PVE Skill 18
      "PVE Skill 18": {
         "name": 'Stone III',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/0c34c7f08e8/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f38006e73efc8e122777b9c23097a4c40bc9c9c4.png',
         "job_icon": 'WHM',
         "level": '54',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '300 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон землей с силой атаки 220.',
      },
      // PVE Skill 19
      "PVE Skill 19": {
         "name": 'Assize',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/cbcd1cda8ca/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4c9f83b599b37adfa6597ea7e884331cac170a12.png',
         "job_icon": 'WHM',
         "level": '56',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '40 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '15y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 400 по всем окружающим противникам.<br/>Дополнительный эффект: восстанавливает HP персонажа и всех ближайших сопартийцев<br/>Сила лечения: 400<br/>Дополнительный эффект: восстанавливает 5% от максимума MP персонажа',
      },
      // PVE Skill 20
      "PVE Skill 20": {
         "name": 'Thin Air',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/96be5e383ec/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/539a73220a23fd185c17bed962b140bf7b4673d2.png',
         "job_icon": 'WHM',
         "level": '58',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Следующее умение не потребует затрат MP.<br/>Продолжительность: 12 сек.<br/>Максимум зарядов: 2',
      },
      // PVE Skill 21
      "PVE Skill 21": {
         "name": 'Tetragrammaton',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/3aeddb8e685/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/6e00b907b75a6906045955d68cf68af66ba6aa9e.png',
         "job_icon": 'WHM',
         "level": '60',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "cost": '-',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Восстанавливает HP цели.<br/>Сила лечения: 700<br/>Максимум зарядов: 2',
      },
      // PVE Skill 22
      "PVE Skill 22": {
         "name": 'Stone IV',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/33eacc1401b5fe03a2dd54e317cd60ccbb912c44.png',
         "job_icon": 'WHM',
         "level": '64',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий урон землей с силой атаки 260.',
      },
      // PVE Skill 23
      "PVE Skill 23": {
         "name": 'Divine Benison',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/065d9df35159a3bc53d59984a18b35581b442a73.png',
         "job_icon": 'WHM',
         "level": '66',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '30 сек.',
         "cost": '-',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Создает барьер вокруг персонажа или сопартийца, поглощающий урон, равный силе лечения 500.<br/>Продолжительность: 15 сек.<br/>Максимум зарядов: 2',
      },
      // PVE Skill 24
      "PVE Skill 24": {
         "name": 'Plenary Indulgence',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/83f6c053e16/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2144617daa9bac9ea7bc1f063a9e0cd033fcd363.png',
         "job_icon": 'WHM',
         "level": '70',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '20y',
         "content": 'Накладывает эффект Confession на персонажа и всех ближайших сопартийцев.<br/>Сопартийцы, находящиеся под действием эффекта Confession, получают дополнительное восстановлении HP с помощью Medica, Medica III, Cure III или Afflatus Rapture.<br/>Сила лечения: 200',
      },
      // PVE Skill 25
      "PVE Skill 25": {
         "name": 'Dia',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/de737874f0025d808d0bddac1d4156fec9464d00.png',
         "job_icon": 'WHM',
         "level": '72',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 70.<br/>Дополнительный эффект: нестихийный периодический урон<br/>Сила атаки: 70<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 26
      "PVE Skill 26": {
         "name": 'Glare',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/c1f9bdbca11c2c7944e3e95cf7599a6a3849e5a2.png',
         "job_icon": 'WHM',
         "level": '72',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 290.',
      },
      // PVE Skill 27
      "PVE Skill 27": {
         "name": 'Afflatus Misery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/e01507664cb997891de06ec522b71619279969bc.png',
         "job_icon": 'WHM',
         "level": '74',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон по цели и по всем окружающим противникам с силой атаки 1,320 для первого и на 50% меньше для всех остальных.<br/>Может использоваться только когда Blood Lily полностью расцвела.',
      },
      // PVE Skill 28
      "PVE Skill 28": {
         "name": 'Afflatus Rapture',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/9582c5aa6ffa9abf82db6140916020235a003a20.png',
         "job_icon": 'WHM',
         "level": '76',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '20y',
         "content": 'Восстанавливает HP персонажа и всех ближайших сопартийцев.<br/>Сила лечения: 400<br/>Дополнительный эффект: накапливает Blood Lily<br/>Стоимость: 1 Lily Healing Gauge',
      },
      // PVE Skill 29
      "PVE Skill 29": {
         "name": 'Temperance',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/78e099cba536b64fe978d05487c51b28a66f29df.png',
         "job_icon": 'WHM',
         "level": '80',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '120 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Увеличивает эффективность магии лечения на 20%, также снижает получаемый урон персонажем и сопартийцами в радиусе 50 ялмов на 10%.<br/>Продолжительность: 20 сек.<br/>Дополнительный эффект: накладывает эффект Divine Grace<br/>Продолжительность: 30 сек.',
      },
      // PVE Skill 30
      "PVE Skill 30": {
         "name": 'Glare III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/dfafd20ceefae82548deba9511d3d765c4535b3a.png',
         "job_icon": 'WHM',
         "level": '82',
         "classification": 'Заклинание',
         "cast": '1.5 сек.',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 330.',
      },
      // PVE Skill 31
      "PVE Skill 31": {
         "name": 'Holy III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/eceb9103dbf8066a8b6c8bce2e84df7552f1a074.png',
         "job_icon": 'WHM',
         "level": '82',
         "classification": 'Заклинание',
         "cast": '2.5 сек.',
         "recast": '2.5 сек.',
         "cost": '400 MP',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '8y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 150 по всем окружающим противникам.<br/>Дополнительный эффект: оглушение (stun)<br/>Продолжительность: 4 сек.',
      },
      // PVE Skill 32
      "PVE Skill 32": {
         "name": 'Aquaveil',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f87f8e18282665458cc9c358ff1a2b8a78833491.png',
         "job_icon": 'WHM',
         "level": '86',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '60 сек.',
         "cost": '-',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Снижает получаемый урон персонажем или сопартийцем урон на 15%.<br/>Продолжительность: 8 сек.',
      },
      // PVE Skill 33
      "PVE Skill 33": {
         "name": 'Liturgy of the Bell',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4d31a93f520e700ac70ab1604bdb6811f124ebb4.png',
         "job_icon": 'WHM',
         "level": '90',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '180 сек.',
         "cost": '-',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Помещает исцеляющий цветок в указанное место и дает персонажу 5 стаков Liturgy of the Bell.<br/>Продолжительность: 20 сек.<br/>Когда персонаж получает урон, 1 стак Liturgy of the Bell расходуется, чтобы исцелить себя и всех сопартийцев в радиусе 20 ялмов.<br/>Сила лечения: 400<br/>Эффект этого умения срабатывает не чаще одного раза в секунду.<br/>По окончанию времени действия умения или при использовании его второй раз все оставшиеся стаки Liturgy of the Bell будет использованы для дополнительного восстановления HP.<br/>Сила лечения: 200 за каждый оставшийся стак Liturgy of the Bell<br/>Этот умение не имеет общего время восстановления с другими умениями.',
      },
      // PVE Skill 34 NEW
      "PVE Skill 34": {
         "name": 'Glare IV',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/8114a12aa7d10fbe87b9edfe0fc6257adec7a06f.png',
         "job_icon": 'WHM',
         "level": '92',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.5 сек.',
         "cost": '-',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон по цели и по всем окружающим противникам с силой атаки 640 для первого и на 40% меньше для всех остальных.<br/Может быть использовано только при активном эффекте Sacred Sight.',
      },
      // PVE Skill 35 NEW
      "PVE Skill 35": {
         "name": 'Medica III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/afd378388b20cba91d3988c04efeff1256eae7b3.png',
         "job_icon": 'WHM',
         "level": '96',
         "classification": 'Заклинание',
         "cast": '2 сек.',
         "recast": '2.5 сек.',
         "cost": '1000 MP',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '20y',
         "content": 'Восстанавливает HP персонажа и всех ближайших сопартийцев.<br/>Сила лечения: 250<br/>Дополнительный эффект: эффект периодического лечения (Regen).<br/>Сила лечения: 175<br/>Продолжительность: 15 сек.',
      },
      // PVE Skill 36 NEW
      "PVE Skill 36": {
         "name": 'Divine Caress',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/94e9cc4b561ab6fca2c4a92cdbb2c86cd7825df9.png',
         "job_icon": 'WHM',
         "level": '100',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '1 сек.',
         "cost": '-',
         "range": '0y',
         "radius_img": 'R2',
         "radius": '15y',
         "content": 'Создает вокруг персонажа и всех ближайших сопартийцев барьер, поглощающий урон, эквивалентный исцелению с силой 400.<br/>Продолжительность: 10 сек.<br/>Накладывает эффект периодического лечения (Regen) после того, как эффект барьера исчезает.<br/>Сила лечения: 200<br/>Продолжительность: 15 сек.<br/>Может быть использовано только при активном эффекте Divine Grace.',
      },
      // Trait 01
      "Trait 01": {
         "name": 'Stone Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/ec59af21d4783ec07af93ded5382036016d67ade.png',
         "job_icon": 'CNJ',
         "level": '18',
         "content": 'Улучшает умение Stone до Stone II.',
      },
      // Trait 02
      "Trait 02": {
         "name": 'Maim and Mend',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/688b9e979396925fa8a996968547e39f057ff539.png',
         "job_icon": 'CNJ',
         "level": '20',
         "content": 'Увеличивает базовый урон умений и восстановления HP на 10%.',
      },
      // Trait 03
      "Trait 03": {
         "name": 'Freecure',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a3a57f7b7aa0de5e6da5e5696661ad29a4888e7f.png',
         "job_icon": 'CNJ',
         "level": '32',
         "content": 'Дает 15% шанс, что после использования Cure, стоимость следующего Cure II будет равна 0 MP.<br/>Продолжительность: 15 сек.',
      },
      // Trait 04
      "Trait 04": {
         "name": 'Maim and Mend II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/f0493aff0cf655167be05890774732eebed2b598.png',
         "job_icon": 'CNJ',
         "level": '40',
         "content": 'Увеличивает базовый урон умений и восстановления HP на 30%.',
      },
      // Trait 05
      "Trait 05": {
         "name": 'Aero Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/bfb73b26584ff1beea3c051df995efb2057f9746.png',
         "job_icon": 'CNJ',
         "level": '46',
         "content": 'Улучшает умение Aero до Aero II.',
      },
      // Trait 06
      "Trait 06": {
         "name": 'Secret of the Lily',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/a8b01c03e71/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/9d84d98cec3b373c4d288036197345815b0079a5.png',
         "job_icon": 'WHM',
         "level": '52',
         "content": 'Добавляет Lily на Healing Gauge персонажа каждые 20 секунд при нахождении в бою. Максимум 3 Lily.',
      },
      // Trait 07
      "Trait 07": {
         "name": 'Stone Mastery II',
         "eorzeadb": 'https://eu.finalfantasyxiv.com/lodestone/playguide/db/quest/0c34c7f08e8/',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7700f3365453c8581b17b771446e0ceb253d2482.png',
         "job_icon": 'WHM',
         "level": '54',
         "content": 'Улучшает умение Stone II до Stone III.',
      },
      // Trait 08
      "Trait 08": {
         "name": 'Stone Mastery III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/0dece0a812fe1229b768f235340926de1be3a4d9.png',
         "job_icon": 'WHM',
         "level": '64',
         "content": 'Улучшает умение Stone III до Stone IV.',
      },
      // Trait 09
      "Trait 09": {
         "name": 'Aero Mastery II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7f5083e44cab6be3c440d2db89c35be3242d340d.png',
         "job_icon": 'WHM',
         "level": '72',
         "content": 'Улучшает умение Aero II до Dia.',
      },
      // Trait 10
      "Trait 10": {
         "name": 'Stone Mastery IV',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/092e5ba991784873f9b5f9a92db364956029657a.png',
         "job_icon": 'WHM',
         "level": '72',
         "content": 'Улучшает умение Stone IV до Glare.',
      },
      // Trait 11
      "Trait 11": {
         "name": 'Transcendent Afflatus',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/df2fd48f77f5355c6ddc3580504abf58b9aa69ea.png',
         "job_icon": 'WHM',
         "level": '74',
         "content": 'Добавляет Blood Lily к Healing Gauge, которая расцветает после трех применений Afflatus Solace или Afflatus Rapture.',
      },
      // Trait 12
      "Trait 12": {
         "name": 'Enhanced Asylum',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/b340f8eedf09a0058e1a6d74bf129a6c0cfff5d1.png',
         "job_icon": 'WHM',
         "level": '78',
         "content": 'Добавляет дополнительный эффект умению Asylum, увеличивающий силу умений восстанавливающих HP на 10%.',
      },
      // Trait 13
      "Trait 13": {
         "name": 'Glare Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/4a78ef89a46bfc230651382c1326ea848696bf4f.png',
         "job_icon": 'WHM',
         "level": '82',
         "content": 'Улучшает умение Glare to Glare III.',
      },
      // Trait 14
      "Trait 14": {
         "name": 'Holy Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/8754d08e1d361478839e1a220369134a71a28d0a.png',
         "job_icon": 'WHM',
         "level": '82',
         "content": 'Улучшает умение Holy да Holy III.',
      },
      // Trait 15
      "Trait 15": {
         "name": 'Enhanced Healing Magic',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/a24e5cd23307348ea0119062908b5153b2b84ca2.png',
         "job_icon": 'WHM',
         "level": '85',
         "content": 'Увеличивает силу исцеляющих умений Cure до 500, Medica до 400, Cure II до 800, Regen до 250, Cure III до 600, Medica II до 250, эффект периодического лечения Medica II (regen) до 150, Afflatus Solace до 800 и Afflatus Rapture до 400.',
      },
      // Trait 16
      "Trait 16": {
         "name": 'Enhanced Divine Benison',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/70956bb631d282deba1787b5497f70b9540eeaa5.png',
         "job_icon": 'WHM',
         "level": '88',
         "content": 'Позволяет накапливать заряды для последовательного использования Divine Benison.<br/>Максимум зарядов: 2',
      },
      // Trait 17 NEW
      "Trait 17": {
         "name": 'Enhanced Presence of Mind',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/522d1367f418f9d9ab9497cb7aac3fd75d75ef16.png',
         "job_icon": 'WHM',
         "level": '92',
         "content": 'Presence of Mind дает 3 стака эффекта Sacred Sight после использования.<br/>Продолжительность: 30 сек.',
      },
      // Trait 18 NEW
      "Trait 18": {
         "name": 'White Magic Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/faebcc03aa187f6f45319b41b7336431d1722fc4.png',
         "job_icon": 'WHM',
         "level": '94',
         "content": 'Увеличивает силу атаки умениям Dia и его урон с течением времени до 70, Afflatus Misery до 1,320 и Glare III до 330.',
      },
      // Trait 19 NEW
      "Trait 19": {
         "name": 'Medica Mastery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/6e19d26c224d8df136427dc9d65b2b8adcda20d7.png',
         "job_icon": 'WHM',
         "level": '96',
         "content": 'Улучшает умение Medica II до Medica III.',
      },
      // Trait 20 NEW
      "Trait 20": {
         "name": 'Enhanced Tetragrammaton',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/2c8d74105960fc4db1162f4bfc05b258cc43adb0.png',
         "job_icon": 'WHM',
         "level": '98',
         "content": 'Позволяет накапливать заряды для последовательного использования Tetragrammaton.<br/>Максимум зарядов: 2',
      },
      // Trait 21 NEW
      "Trait 21": {
         "name": 'Enhanced Temperance',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1617b594d0846dfcbc4a7c258e89bdc2fb10c168.png',
         "job_icon": 'WHM',
         "level": '100',
         "content": 'Temperance накладывает эффект Divine Grace после использования.<br/>Продолжительность: 30 сек.',
      },
      // PVP Skill 01
      "PVP Skill 01": {
         "name": 'Glare III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/889b00ef7b55083b462b1dc589add79e07e87379.png',
         "classification": 'Заклинание',
         "cast": '1.44 сек.',
         "recast": '2.4 сек.',
         "range": '25y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Удар, наносящий нестихийный урон с силой атаки 5,000.',
      },
      // PVP Skill 02
      "PVP Skill 02": {
         "name": 'Cure II',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/7e7fd985e01134a3f7a76bda607c5cb1a36b3f7c.png',
         "classification": 'Заклинание',
         "cast": '1.44 сек.',
         "recast": '15 сек.',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Восстанавливает HP цели.<br/>Сила лечения: 12,000<br/>Максимум стаков: 2<br/>Этот умение не имеет общего времени восстановления с другими умениями.<br/><br/>※Умение меняется на Cure III под действием эффекта Cure III Ready.',
      },
      // PVP Skill 03
      "PVP Skill 03": {
         "name": 'Afflatus Misery',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/67c045d9c3c41f736c36022272cefd8c0980f19f.png',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '15 сек.',
         "range": '25y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Удар, наносящий нестихийный урон по цели и по всем окружающим противникам с силой атаки 12,000.<br/>Этот умение не имеет общего времени восстановления с другими умениями.',
      },
      // PVP Skill 04
      "PVP Skill 04": {
         "name": 'Aquaveil',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/db63ef3d2573abbcb89237b70189beb66d9f08c1.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '30y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Создает барьер вокруг персонажа или сопартийца, поглощающий урон, равный лечению с силой 8,000.<br/>Продолжительность: 10 сек.<br/>Дополнительный эффект: снимает один статусный эффект, который может быть снят Purify<br/>Сила барьера удваивается, если данное умение успешно снимает статусный эффект.',
      },
      // PVP Skill 05
      "PVP Skill 05": {
         "name": 'Miracle of Nature',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/1245aecd31eaf0821a81907c6664946404770339.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '45 сек.',
         "range": '10y',
         "radius_img": 'R1',
         "radius": '0y',
         "content": 'Насильно превращает цель в крошечное существо, лишая ее возможности использовать умения.<br/>Продолжительность: 2 сек.<br/>Не действует на неигровых персонажей, игроков под действием Guard или находящихся в роботах.',
      },
      // PVP Skill 06
      "PVP Skill 06": {
         "name": 'Seraph Strike',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/8f0999ae68bff865ab683d7f1059024d126b013e.png',
         "classification": 'Способность',
         "cast": 'Мгновенная',
         "recast": '20 сек.',
         "range": '20y',
         "radius_img": 'R2',
         "radius": '10y',
         "content": 'Прыжок на цель, наносящий нестихийный урон с силой атаки 8,000 по цели и по всем окружающим противникам.<br/>Дополнительный эффект: накладывает эффект Protect на персонажа и всех окружающих сопартийцев<br/>Эффект Protect: снижает получаемый урон на 10%<br/>Продолжительность: 10 сек.<br/>Дополнительный эффект: накладывает эффект Cure III Ready<br/>Продолжительность: 10 сек.<br/>Невозможно использовать, если персонаж находится под эффектами, ограничивающими перемещение.<br/><br/>※Умение Cure II меняется на Cure III под действием эффекта Cure III Ready.',
      },
      // PVP Skill 07
      "PVP Skill 07": {
         "name": 'Cure III',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/3c4b6cbc3b8ae09ebf0dc3c69c16594e211cdfe6.png',
         "classification": 'Заклинание',
         "cast": 'Мгновенная',
         "recast": '2.4 сек.',
         "range": '30y',
         "radius_img": 'R2',
         "radius": '5y',
         "content": 'Восстанавливает HP персонажа и всех ближайших сопартийцев.<br/>Сила лечения: 16000<br/>Может быть использовано только под действием эффекта Cure III Ready.<br/><br/>※Это умение нельзя поместить на хотбар.',
      },
      // PVP Skill 08
      "PVP Skill 08": {
         "name": 'Afflatus Purgation',
         "skill_icon": 'https://lds-img.finalfantasyxiv.com/d/885443eeb029d7cbca537be10edca5eb6c920401.png',
         "cast": 'Мгновенная',
         "recast": '10 сек.',
         "range": '40y',
         "radius_img": 'R6',
         "radius": '40y',
         "content": 'Удар, наносящий нестихийный урон по всем противникам по прямой линии перед персонажем с силой атаки 18,000.<br/>Дополнительный эффект: оглушение (stun)<br/>Продолжительность: 2 сек.<br/>Дополнительный эффект: накладывает эффект Temperance<br/>Эффект Temperance: увеличивает наносимый урон и силу лечения на 10%, а также накладывает эффект периодического лечения (regen) на персонажа и всех ближайших сопартийцев в радиусе 30 ялмов<br/>Сила лечения: 3,000<br/>Продолжительность: 15 сек.<br/>Может быть использовано только тогда, когда шкала лимит брейка (limit gauge) заполнена.<br/>Время зарядки шкалы: 60 сек.',
      },
   };
   FILL_DB_VALUES(db);
   FILL_DB_SKILLS(db);
   FILL_DB_SKILLS_PASSIVE(db);
   FILL_DB_SKILLS_PVP(db);
   FILL_DB_SKILLS_MENU(db);
})();